// ═══════════════════════════════════════════
// FOOD DATABASE — Extracted from HistaTrack
// ═══════════════════════════════════════════
const FOOD_DB = [
  // ══════ PROTÉINES — Viandes ══════
  {name:"Poulet frais",cat:"Protéines",score:0,level:"Faible",tip:"Mieux toléré si très frais et vite réfrigéré"},
  {name:"Dinde fraîche",cat:"Protéines",score:0,level:"Faible",tip:"Comme les viandes fraîches non maturées"},
  {name:"Boeuf frais",cat:"Protéines",score:0,level:"Faible",tip:"Plutôt faible si très frais, non maturé"},
  {name:"Agneau frais",cat:"Protéines",score:0,level:"Faible",tip:"Plutôt faible si très frais"},
  {name:"Porc frais",cat:"Protéines",score:0,level:"Faible",tip:"OK si très frais, attention à la transformation"},
  {name:"Veau frais",cat:"Protéines",score:0,level:"Faible",tip:"Viande jeune, généralement bien tolérée si fraîche"},
  {name:"Canard frais",cat:"Protéines",score:1,level:"Modéré",tip:"Plus gras, tolérance variable"},
  {name:"Lapin frais",cat:"Protéines",score:0,level:"Faible",tip:"Viande maigre généralement bien tolérée"},
  {name:"Viande hachée maison",cat:"Protéines",score:1,level:"Modéré",tip:"Dépend beaucoup de la fraîcheur, s'altère vite"},
  {name:"Viande maturée / rassise",cat:"Protéines",score:3,level:"Très élevé",tip:"La maturation augmente fortement l'histamine"},
  {name:"Oeufs",cat:"Protéines",score:1,level:"Modéré",tip:"Tolérance variable selon les personnes"},
  {name:"Blanc d'oeuf",cat:"Protéines",score:0,level:"Faible",tip:"Mieux toléré que l'oeuf entier pour certains"},
  {name:"Tofu frais",cat:"Protéines",score:1,level:"Modéré",tip:"Soja = libérateur d'histamine, variable selon individu"},
  {name:"Tempeh",cat:"Protéines",score:3,level:"Très élevé",tip:"Soja fermenté, risque élevé"},
  // ══════ PROTÉINES — Poissons ══════
  {name:"Poisson très frais",cat:"Poissons",score:1,level:"Modéré",tip:"Dépend de la fraîcheur et chaîne du froid"},
  {name:"Cabillaud frais",cat:"Poissons",score:1,level:"Modéré",tip:"OK si très frais, poisson blanc plutôt bien toléré"},
  {name:"Colin frais",cat:"Poissons",score:1,level:"Modéré",tip:"Poisson blanc, attention à la fraîcheur"},
  {name:"Sole fraîche",cat:"Poissons",score:1,level:"Modéré",tip:"Poisson plat, généralement mieux toléré frais"},
  {name:"Truite fraîche",cat:"Poissons",score:1,level:"Modéré",tip:"OK si très fraîche, chaîne du froid cruciale"},
  {name:"Saumon frais",cat:"Poissons",score:1,level:"Modéré",tip:"Fraîcheur absolument critique pour le saumon"},
  {name:"Thon frais",cat:"Poissons",score:2,level:"Élevé",tip:"Le thon accumule vite de l'histamine, même frais"},
  {name:"Sardines fraîches",cat:"Poissons",score:2,level:"Élevé",tip:"Se dégrade vite, cuisson immédiate recommandée"},
  {name:"Thon en conserve",cat:"Poissons",score:3,level:"Très élevé",tip:"Poisson conservé = risque histamine élevé"},
  {name:"Sardines en conserve",cat:"Poissons",score:3,level:"Très élevé",tip:"Conserve de poisson = risque élevé"},
  {name:"Maquereaux en conserve",cat:"Poissons",score:3,level:"Très élevé",tip:"Poisson gras conservé, histamine très élevée"},
  {name:"Saumon fumé",cat:"Poissons",score:3,level:"Très élevé",tip:"Fumé/transformé souvent mal toléré"},
  {name:"Hareng fumé / mariné",cat:"Poissons",score:3,level:"Très élevé",tip:"Fumé/mariné = accumulation d'histamine"},
  {name:"Anchois",cat:"Poissons",score:3,level:"Très élevé",tip:"Saumure et maturation = très riche en histamine"},
  {name:"Surimi",cat:"Poissons",score:2,level:"Élevé",tip:"Transformé, additifs, qualité variable"},
  {name:"Fruits de mer",cat:"Poissons",score:3,level:"Très élevé",tip:"Crevettes, moules, huîtres : déclencheurs fréquents"},
  {name:"Crevettes fraîches",cat:"Poissons",score:2,level:"Élevé",tip:"Libérateur d'histamine même si fraîches"},
  {name:"Moules",cat:"Poissons",score:3,level:"Très élevé",tip:"Coquillages souvent très problématiques"},
  // ══════ FÉCULENTS & CÉRÉALES ══════
  {name:"Riz",cat:"Féculents",score:0,level:"Faible",tip:"Base simple des régimes pauvres en histamine"},
  {name:"Riz complet",cat:"Féculents",score:0,level:"Faible",tip:"Aussi bien toléré que le riz blanc"},
  {name:"Quinoa",cat:"Féculents",score:0,level:"Faible",tip:"Graine souvent compatible"},
  {name:"Pommes de terre",cat:"Féculents",score:0,level:"Faible",tip:"Base simple souvent utilisée"},
  {name:"Patate douce",cat:"Féculents",score:0,level:"Faible",tip:"Souvent bien tolérée"},
  {name:"Pâtes nature",cat:"Féculents",score:0,level:"Faible",tip:"Faible si nature et sans sauces déclenchantes"},
  {name:"Pâtes complètes",cat:"Féculents",score:0,level:"Faible",tip:"Aussi bien tolérées que les pâtes blanches"},
  {name:"Semoule / couscous",cat:"Féculents",score:0,level:"Faible",tip:"Blé dur nature, généralement bien toléré"},
  {name:"Boulgour",cat:"Féculents",score:0,level:"Faible",tip:"Blé concassé, souvent bien toléré"},
  {name:"Maïs / polenta",cat:"Féculents",score:0,level:"Faible",tip:"Généralement bien toléré"},
  {name:"Galettes de riz",cat:"Féculents",score:0,level:"Faible",tip:"Snack simple souvent bien toléré"},
  {name:"Avoine / flocons",cat:"Féculents",score:0,level:"Faible",tip:"Bien toléré nature, sans ajouts"},
  {name:"Sarrasin",cat:"Féculents",score:0,level:"Faible",tip:"Sans gluten, généralement compatible"},
  {name:"Millet",cat:"Féculents",score:0,level:"Faible",tip:"Céréale ancienne bien tolérée"},
  {name:"Tapioca / manioc",cat:"Féculents",score:0,level:"Faible",tip:"Fécule neutre, très bien tolérée"},
  {name:"Pain frais simple",cat:"Féculents",score:1,level:"Modéré",tip:"Variable selon ingrédients/levure/fermentation"},
  {name:"Pain au levain",cat:"Féculents",score:2,level:"Élevé",tip:"Fermentation longue = plus de risque"},
  {name:"Pâte à pizza nature",cat:"Féculents",score:1,level:"Modéré",tip:"Variable selon fermentation, hors garnitures"},
  {name:"Farine (blé, riz, maïs)",cat:"Féculents",score:0,level:"Faible",tip:"Farines nature sans additifs OK"},
  {name:"Crackers / biscottes",cat:"Féculents",score:1,level:"Modéré",tip:"Vérifier ingrédients, levure, conservateurs"},
  // ══════ LÉGUMES ══════
  {name:"Courgette",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien tolérée"},
  {name:"Carotte",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien tolérée"},
  {name:"Concombre",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien toléré"},
  {name:"Laitue",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien tolérée"},
  {name:"Mâche",cat:"Légumes",score:0,level:"Faible",tip:"Salade douce, bien tolérée"},
  {name:"Roquette",cat:"Légumes",score:0,level:"Faible",tip:"Généralement bien tolérée"},
  {name:"Brocoli",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien toléré"},
  {name:"Chou-fleur",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien toléré"},
  {name:"Chou vert / blanc",cat:"Légumes",score:0,level:"Faible",tip:"OK frais, pas fermenté"},
  {name:"Chou rouge",cat:"Légumes",score:0,level:"Faible",tip:"OK frais et cuit"},
  {name:"Choux de Bruxelles",cat:"Légumes",score:0,level:"Faible",tip:"Généralement bien tolérés"},
  {name:"Haricots verts",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien tolérés"},
  {name:"Petits pois",cat:"Légumes",score:0,level:"Faible",tip:"Frais ou surgelés, bien tolérés"},
  {name:"Asperges",cat:"Légumes",score:0,level:"Faible",tip:"Généralement bien tolérées"},
  {name:"Fenouil",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien toléré, peut aider la digestion"},
  {name:"Céleri",cat:"Légumes",score:0,level:"Faible",tip:"Généralement bien toléré"},
  {name:"Poireau",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien toléré"},
  {name:"Navet",cat:"Légumes",score:0,level:"Faible",tip:"Légume racine bien toléré"},
  {name:"Panais",cat:"Légumes",score:0,level:"Faible",tip:"Légume racine doux, bien toléré"},
  {name:"Radis",cat:"Légumes",score:0,level:"Faible",tip:"Généralement bien toléré"},
  {name:"Betterave",cat:"Légumes",score:0,level:"Faible",tip:"Généralement bien tolérée fraîche"},
  {name:"Courge / butternut",cat:"Légumes",score:0,level:"Faible",tip:"Courges généralement bien tolérées"},
  {name:"Potiron / potimarron",cat:"Légumes",score:0,level:"Faible",tip:"Bien toléré, saveur douce"},
  {name:"Endive",cat:"Légumes",score:0,level:"Faible",tip:"Souvent bien tolérée"},
  {name:"Artichaut",cat:"Légumes",score:0,level:"Faible",tip:"Généralement bien toléré"},
  {name:"Oignon",cat:"Légumes",score:0,level:"Faible",tip:"Bien toléré, contient de la quercétine (anti-histamine naturel)"},
  {name:"Ail",cat:"Légumes",score:0,level:"Faible",tip:"Bien toléré, propriétés anti-inflammatoires"},
  {name:"Échalote",cat:"Légumes",score:0,level:"Faible",tip:"Comme l'oignon, généralement bien tolérée"},
  {name:"Poivron",cat:"Légumes",score:1,level:"Modéré",tip:"Tolérance variable, certains le tolèrent bien"},
  {name:"Champignons",cat:"Légumes",score:1,level:"Modéré",tip:"Tolérance variable, attention à la fraîcheur"},
  {name:"Tomate",cat:"Légumes",score:2,level:"Élevé",tip:"Souvent classée parmi les aliments problématiques"},
  {name:"Tomate cuite / sauce",cat:"Légumes",score:3,level:"Très élevé",tip:"La cuisson et transformation augmentent le risque"},
  {name:"Aubergine",cat:"Légumes",score:2,level:"Élevé",tip:"Souvent problématique en régime pauvre en histamine"},
  {name:"Avocat",cat:"Légumes",score:2,level:"Élevé",tip:"Tolérance variable, classé à risque"},
  {name:"Épinards",cat:"Légumes",score:3,level:"Très élevé",tip:"Souvent fortement déconseillés"},
  {name:"Choucroute",cat:"Légumes",score:3,level:"Très élevé",tip:"Fermenté = fort risque"},
  {name:"Olives",cat:"Légumes",score:2,level:"Élevé",tip:"Souvent fermentées/marinées, risque modéré à élevé"},
  {name:"Cornichons",cat:"Légumes",score:3,level:"Très élevé",tip:"Fermentés dans le vinaigre"},
  // ══════ LÉGUMINEUSES ══════
  {name:"Lentilles",cat:"Légumineuses",score:1,level:"Modéré",tip:"Tolérance variable, certains les tolèrent bien"},
  {name:"Pois chiches",cat:"Légumineuses",score:1,level:"Modéré",tip:"Tolérance variable, mieux tolérés frais"},
  {name:"Haricots blancs",cat:"Légumineuses",score:1,level:"Modéré",tip:"Légumineuse à tester individuellement"},
  {name:"Haricots rouges",cat:"Légumineuses",score:1,level:"Modéré",tip:"Légumineuse à tester individuellement"},
  {name:"Pois cassés",cat:"Légumineuses",score:1,level:"Modéré",tip:"Généralement assez bien toléré"},
  {name:"Fèves",cat:"Légumineuses",score:1,level:"Modéré",tip:"Tolérance variable"},
  {name:"Edamame",cat:"Légumineuses",score:1,level:"Modéré",tip:"Soja jeune, mieux toléré que le soja transformé"},
  {name:"Houmous",cat:"Légumineuses",score:2,level:"Élevé",tip:"Pois chiches + citron + souvent vinaigre"},
  // ══════ FRUITS ══════
  {name:"Pomme",cat:"Fruits",score:0,level:"Faible",tip:"Fruit de base souvent bien toléré"},
  {name:"Poire",cat:"Fruits",score:0,level:"Faible",tip:"Fruit de base souvent bien toléré"},
  {name:"Myrtilles",cat:"Fruits",score:0,level:"Faible",tip:"Souvent bien tolérées"},
  {name:"Raisin",cat:"Fruits",score:0,level:"Faible",tip:"Souvent bien toléré frais"},
  {name:"Mangue",cat:"Fruits",score:0,level:"Faible",tip:"Souvent bien tolérée"},
  {name:"Pastèque",cat:"Fruits",score:0,level:"Faible",tip:"Souvent bien tolérée"},
  {name:"Melon",cat:"Fruits",score:0,level:"Faible",tip:"Généralement bien toléré"},
  {name:"Cerise",cat:"Fruits",score:0,level:"Faible",tip:"Souvent bien tolérée, propriétés anti-inflammatoires"},
  {name:"Figue fraîche",cat:"Fruits",score:0,level:"Faible",tip:"OK fraîche, attention séchée"},
  {name:"Litchi",cat:"Fruits",score:0,level:"Faible",tip:"Généralement bien toléré"},
  {name:"Noix de coco",cat:"Fruits",score:0,level:"Faible",tip:"Chair et lait de coco bien tolérés"},
  {name:"Pêche",cat:"Fruits",score:0,level:"Faible",tip:"Généralement bien tolérée fraîche"},
  {name:"Abricot",cat:"Fruits",score:0,level:"Faible",tip:"Bien toléré frais"},
  {name:"Nectarine",cat:"Fruits",score:0,level:"Faible",tip:"Bien tolérée fraîche"},
  {name:"Prune",cat:"Fruits",score:0,level:"Faible",tip:"OK fraîche, pruneaux plus risqués"},
  {name:"Grenade",cat:"Fruits",score:0,level:"Faible",tip:"Généralement bien tolérée"},
  {name:"Kiwi",cat:"Fruits",score:1,level:"Modéré",tip:"Tolérance variable, à tester individuellement"},
  {name:"Ananas",cat:"Fruits",score:2,level:"Élevé",tip:"Libérateur d'histamine fréquent"},
  {name:"Banane",cat:"Fruits",score:2,level:"Élevé",tip:"Souvent listée parmi les aliments à surveiller"},
  {name:"Banane très mûre",cat:"Fruits",score:3,level:"Très élevé",tip:"Plus elle mûrit, plus l'histamine augmente"},
  {name:"Fraise",cat:"Fruits",score:2,level:"Élevé",tip:"Libérateur d'histamine fréquent"},
  {name:"Framboise",cat:"Fruits",score:1,level:"Modéré",tip:"Moins problématique que la fraise, à tester"},
  {name:"Orange",cat:"Fruits",score:2,level:"Élevé",tip:"Agrume, souvent à surveiller"},
  {name:"Citron",cat:"Fruits",score:2,level:"Élevé",tip:"Agrume, mais parfois mieux toléré que l'orange"},
  {name:"Pamplemousse",cat:"Fruits",score:2,level:"Élevé",tip:"Agrume à surveiller"},
  {name:"Mandarine / clémentine",cat:"Fruits",score:2,level:"Élevé",tip:"Agrume, risque modéré à élevé"},
  {name:"Papaye",cat:"Fruits",score:2,level:"Élevé",tip:"Libérateur d'histamine pour certains"},
  {name:"Fruits secs (dattes, raisins...)",cat:"Fruits",score:2,level:"Élevé",tip:"Le séchage concentre et augmente l'histamine"},
  {name:"Pruneaux",cat:"Fruits",score:2,level:"Élevé",tip:"Fruits séchés = risque plus élevé"},
  // ══════ PRODUITS LAITIERS ══════
  {name:"Lait frais",cat:"Produits laitiers",score:0,level:"Faible",tip:"Frais et pasteurisé, généralement bien toléré"},
  {name:"Lait UHT",cat:"Produits laitiers",score:0,level:"Faible",tip:"Longue conservation mais peu de risque histamine"},
  {name:"Beurre",cat:"Produits laitiers",score:0,level:"Faible",tip:"Matière grasse pure, généralement bien tolérée"},
  {name:"Crème fraîche",cat:"Produits laitiers",score:1,level:"Modéré",tip:"Légère fermentation, tolérance variable"},
  {name:"Fromage frais / cottage",cat:"Produits laitiers",score:0,level:"Faible",tip:"Non affiné, généralement bien toléré"},
  {name:"Ricotta",cat:"Produits laitiers",score:0,level:"Faible",tip:"Fromage frais non affiné"},
  {name:"Mascarpone",cat:"Produits laitiers",score:0,level:"Faible",tip:"Crémeux non affiné, bien toléré"},
  {name:"Mozzarella fraîche",cat:"Produits laitiers",score:1,level:"Modéré",tip:"Moins maturée, tolérance variable"},
  {name:"Feta",cat:"Produits laitiers",score:2,level:"Élevé",tip:"Saumure et affinage léger, à surveiller"},
  {name:"Chèvre frais",cat:"Produits laitiers",score:1,level:"Modéré",tip:"Mieux toléré que les fromages affinés"},
  {name:"Chèvre affiné",cat:"Produits laitiers",score:2,level:"Élevé",tip:"L'affinage augmente l'histamine"},
  {name:"Yaourt",cat:"Produits laitiers",score:2,level:"Élevé",tip:"Produit fermenté, souvent mal toléré"},
  {name:"Kéfir",cat:"Produits laitiers",score:2,level:"Élevé",tip:"Fermenté, mêmes risques que le yaourt"},
  {name:"Emmental",cat:"Produits laitiers",score:2,level:"Élevé",tip:"Semi-affiné, risque modéré à élevé"},
  {name:"Gruyère",cat:"Produits laitiers",score:3,level:"Très élevé",tip:"Fromage affiné = risque élevé"},
  {name:"Comté",cat:"Produits laitiers",score:3,level:"Très élevé",tip:"Longue maturation = histamine élevée"},
  {name:"Parmesan",cat:"Produits laitiers",score:3,level:"Très élevé",tip:"Fromage très affiné = risque très élevé"},
  {name:"Cheddar",cat:"Produits laitiers",score:3,level:"Très élevé",tip:"Fromage affiné = risque élevé"},
  {name:"Roquefort / bleu",cat:"Produits laitiers",score:3,level:"Très élevé",tip:"Moisissure + affinage = très élevé"},
  {name:"Camembert / Brie",cat:"Produits laitiers",score:3,level:"Très élevé",tip:"Croûte fleurie et affinage = risque élevé"},
  {name:"Raclette",cat:"Produits laitiers",score:2,level:"Élevé",tip:"Semi-affiné, risque modéré"},
  // ══════ ÉPICES & HERBES ══════
  {name:"Sel",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Aucun risque histamine"},
  {name:"Poivre noir",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Généralement bien toléré en quantité normale"},
  {name:"Curcuma",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Anti-inflammatoire, souvent recommandé dans le SAMA"},
  {name:"Gingembre frais",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Propriétés anti-inflammatoires, souvent bien toléré"},
  {name:"Basilic frais",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe fraîche bien tolérée"},
  {name:"Persil frais",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe fraîche bien tolérée"},
  {name:"Ciboulette",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe fraîche bien tolérée"},
  {name:"Menthe fraîche",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe fraîche bien tolérée"},
  {name:"Coriandre fraîche",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe fraîche bien tolérée"},
  {name:"Aneth frais",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe fraîche bien tolérée"},
  {name:"Romarin",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe aromatique bien tolérée"},
  {name:"Thym",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe aromatique bien tolérée"},
  {name:"Origan",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Généralement bien toléré"},
  {name:"Laurier",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Feuille aromatique sans risque"},
  {name:"Sauge",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe aromatique bien tolérée"},
  {name:"Estragon",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Herbe fine bien tolérée"},
  {name:"Cumin",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Épice généralement bien tolérée"},
  {name:"Coriandre moulue",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Épice douce bien tolérée"},
  {name:"Cardamome",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Épice douce, pas de risque connu"},
  {name:"Safran",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Épice rare, aucun risque histamine connu"},
  {name:"Vanille",cat:"Épices & Herbes",score:0,level:"Faible",tip:"Pas de risque histamine"},
  {name:"Cannelle",cat:"Épices & Herbes",score:1,level:"Modéré",tip:"Libérateur d'histamine pour certains, à tester"},
  {name:"Noix de muscade",cat:"Épices & Herbes",score:1,level:"Modéré",tip:"En petite quantité OK, sensibilité variable"},
  {name:"Paprika doux",cat:"Épices & Herbes",score:1,level:"Modéré",tip:"Piment séché, tolérance variable"},
  {name:"Curry (mélange)",cat:"Épices & Herbes",score:1,level:"Modéré",tip:"Mélange variable, peut contenir des épices à risque"},
  {name:"Clou de girofle",cat:"Épices & Herbes",score:0,level:"Faible",tip:"En petite quantité, pas de risque connu"},
  {name:"Piment / chili",cat:"Épices & Herbes",score:2,level:"Élevé",tip:"Peut déclencher une libération de médiateurs"},
  {name:"Piment de Cayenne",cat:"Épices & Herbes",score:2,level:"Élevé",tip:"Fort, peut provoquer une libération d'histamine"},
  {name:"Harissa",cat:"Épices & Herbes",score:2,level:"Élevé",tip:"Piment + souvent vinaigre, double risque"},
  {name:"Ras el hanout",cat:"Épices & Herbes",score:1,level:"Modéré",tip:"Mélange complexe, vérifier la composition"},
  // ══════ NOIX & GRAINES ══════
  {name:"Amandes",cat:"Noix & Graines",score:0,level:"Faible",tip:"Généralement bien tolérées"},
  {name:"Graines de courge",cat:"Noix & Graines",score:0,level:"Faible",tip:"Souvent bien tolérées"},
  {name:"Graines de tournesol",cat:"Noix & Graines",score:0,level:"Faible",tip:"Souvent bien tolérées"},
  {name:"Graines de sésame",cat:"Noix & Graines",score:0,level:"Faible",tip:"Généralement bien tolérées"},
  {name:"Graines de lin",cat:"Noix & Graines",score:0,level:"Faible",tip:"Oméga-3, généralement bien tolérées"},
  {name:"Graines de chia",cat:"Noix & Graines",score:0,level:"Faible",tip:"Généralement bien tolérées"},
  {name:"Noix de cajou",cat:"Noix & Graines",score:1,level:"Modéré",tip:"Tolérance variable selon les individus"},
  {name:"Noisettes",cat:"Noix & Graines",score:1,level:"Modéré",tip:"Tolérance variable"},
  {name:"Pistaches",cat:"Noix & Graines",score:1,level:"Modéré",tip:"À tester individuellement"},
  {name:"Noix",cat:"Noix & Graines",score:2,level:"Élevé",tip:"Souvent citée comme libérateur d'histamine"},
  {name:"Cacahuètes / arachides",cat:"Noix & Graines",score:2,level:"Élevé",tip:"Libérateur d'histamine fréquent"},
  {name:"Noix du Brésil",cat:"Noix & Graines",score:1,level:"Modéré",tip:"Tolérance variable, riche en sélénium"},
  {name:"Pignons de pin",cat:"Noix & Graines",score:0,level:"Faible",tip:"Généralement bien tolérés"},
  // ══════ CONDIMENTS & SAUCES ══════
  {name:"Moutarde",cat:"Condiments",score:2,level:"Élevé",tip:"Souvent fermentée et/ou avec vinaigre"},
  {name:"Ketchup",cat:"Condiments",score:3,level:"Très élevé",tip:"Tomate + produit transformé + vinaigre"},
  {name:"Sauce soja",cat:"Condiments",score:3,level:"Très élevé",tip:"Produit fermenté"},
  {name:"Vinaigre",cat:"Condiments",score:3,level:"Très élevé",tip:"Fermenté, souvent déconseillé"},
  {name:"Vinaigre de cidre",cat:"Condiments",score:2,level:"Élevé",tip:"Fermenté mais parfois mieux toléré que le vinaigre de vin"},
  {name:"Vinaigre balsamique",cat:"Condiments",score:3,level:"Très élevé",tip:"Fermentation longue et concentrée"},
  {name:"Mayonnaise",cat:"Condiments",score:2,level:"Élevé",tip:"Variable selon ingrédients (vinaigre, moutarde)"},
  {name:"Pesto",cat:"Condiments",score:2,level:"Élevé",tip:"Noix de pin + parmesan + souvent transformation"},
  {name:"Sauce tomate",cat:"Condiments",score:3,level:"Très élevé",tip:"Tomate cuite + souvent vinaigre"},
  {name:"Sauce worcestershire",cat:"Condiments",score:3,level:"Très élevé",tip:"Très fermentée, anchois, vinaigre"},
  {name:"Sauce barbecue",cat:"Condiments",score:3,level:"Très élevé",tip:"Tomate + vinaigre + sucre transformé"},
  {name:"Sauce teriyaki",cat:"Condiments",score:3,level:"Très élevé",tip:"Soja fermenté + mirin"},
  {name:"Nuoc-mâm / sauce poisson",cat:"Condiments",score:3,level:"Très élevé",tip:"Poisson fermenté, très riche en histamine"},
  {name:"Tahini",cat:"Condiments",score:0,level:"Faible",tip:"Purée de sésame, généralement bien tolérée"},
  {name:"Purée d'amande",cat:"Condiments",score:0,level:"Faible",tip:"Oléagineux broyé, généralement bien toléré"},
  // ══════ MATIÈRES GRASSES ══════
  {name:"Huile d'olive",cat:"Matières grasses",score:0,level:"Faible",tip:"Généralement bien tolérée"},
  {name:"Huile de colza",cat:"Matières grasses",score:0,level:"Faible",tip:"Neutre, bien tolérée"},
  {name:"Huile de coco",cat:"Matières grasses",score:0,level:"Faible",tip:"Bien tolérée, saveur douce"},
  {name:"Huile de tournesol",cat:"Matières grasses",score:0,level:"Faible",tip:"Neutre, bien tolérée"},
  {name:"Huile de lin",cat:"Matières grasses",score:0,level:"Faible",tip:"Riche en oméga-3, à consommer crue"},
  {name:"Ghee (beurre clarifié)",cat:"Matières grasses",score:0,level:"Faible",tip:"Souvent très bien toléré, pas de protéines laitières"},
  // ══════ SUCRÉS ══════
  {name:"Sucre blanc",cat:"Sucrés",score:0,level:"Faible",tip:"Pas de risque histamine direct"},
  {name:"Sucre roux / cassonade",cat:"Sucrés",score:0,level:"Faible",tip:"Pas de risque histamine direct"},
  {name:"Miel",cat:"Sucrés",score:0,level:"Faible",tip:"Généralement bien toléré, choisir pur"},
  {name:"Sirop d'érable",cat:"Sucrés",score:0,level:"Faible",tip:"Pas de risque histamine connu"},
  {name:"Sirop d'agave",cat:"Sucrés",score:0,level:"Faible",tip:"Alternative sucrante sans risque"},
  {name:"Confiture maison",cat:"Sucrés",score:1,level:"Modéré",tip:"Dépend du fruit utilisé et de la cuisson"},
  {name:"Chocolat noir",cat:"Sucrés",score:3,level:"Très élevé",tip:"Cacao = déclencheur fréquent d'histamine"},
  {name:"Chocolat au lait",cat:"Sucrés",score:3,level:"Très élevé",tip:"Cacao + lait, double risque potentiel"},
  {name:"Cacao en poudre",cat:"Sucrés",score:3,level:"Très élevé",tip:"Riche en amines biogènes"},
  {name:"Pâte à tartiner (Nutella...)",cat:"Sucrés",score:3,level:"Très élevé",tip:"Cacao + noisettes + transformation industrielle"},
  // ══════ BOISSONS ══════
  {name:"Eau",cat:"Boissons",score:0,level:"Faible",tip:"Sans risque histamine"},
  {name:"Eau gazeuse",cat:"Boissons",score:0,level:"Faible",tip:"Sans risque histamine"},
  {name:"Tisane (camomille, tilleul)",cat:"Boissons",score:0,level:"Faible",tip:"Infusions non fermentées, généralement OK"},
  {name:"Tisane de gingembre",cat:"Boissons",score:0,level:"Faible",tip:"Anti-inflammatoire, souvent recommandée"},
  {name:"Tisane de menthe",cat:"Boissons",score:0,level:"Faible",tip:"Souvent bien tolérée"},
  {name:"Rooibos",cat:"Boissons",score:0,level:"Faible",tip:"Non fermenté (ou peu), bon substitut au thé"},
  {name:"Lait végétal (riz, avoine)",cat:"Boissons",score:0,level:"Faible",tip:"Sans fermentation, généralement bien toléré"},
  {name:"Lait de coco",cat:"Boissons",score:0,level:"Faible",tip:"Bien toléré, alternative crémeuse"},
  {name:"Lait d'amande",cat:"Boissons",score:0,level:"Faible",tip:"Bien toléré si sans additifs"},
  {name:"Café",cat:"Boissons",score:1,level:"Modéré",tip:"Peut aggraver chez certaines personnes"},
  {name:"Thé noir",cat:"Boissons",score:1,level:"Modéré",tip:"À surveiller individuellement"},
  {name:"Thé vert",cat:"Boissons",score:1,level:"Modéré",tip:"Moins fermenté que le noir, mais à tester"},
  {name:"Jus d'orange",cat:"Boissons",score:2,level:"Élevé",tip:"Agrume + souvent pasteurisé/stocké"},
  {name:"Jus de tomate",cat:"Boissons",score:3,level:"Très élevé",tip:"Tomate transformée, risque élevé"},
  {name:"Smoothie aux fruits rouges",cat:"Boissons",score:2,level:"Élevé",tip:"Dépend des fruits, fraises = risque"},
  {name:"Vin rouge",cat:"Boissons",score:3,level:"Très élevé",tip:"Classique déclencheur, riche en amines"},
  {name:"Vin blanc",cat:"Boissons",score:2,level:"Élevé",tip:"Moins d'histamine que le rouge mais reste fermenté"},
  {name:"Bière",cat:"Boissons",score:3,level:"Très élevé",tip:"Fermentée, souvent mal tolérée"},
  {name:"Champagne / prosecco",cat:"Boissons",score:3,level:"Très élevé",tip:"Double fermentation, risque élevé"},
  {name:"Spiritueux (vodka, gin)",cat:"Boissons",score:1,level:"Modéré",tip:"Distillés = moins d'histamine que le vin, mais l'alcool inhibe la DAO"},
  {name:"Kombucha",cat:"Boissons",score:3,level:"Très élevé",tip:"Thé fermenté, risque très élevé"},
  // ══════ CHARCUTERIES & TRANSFORMÉS ══════
  {name:"Jambon",cat:"Charcuteries",score:3,level:"Très élevé",tip:"Viande transformée/affinée"},
  {name:"Jambon cuit (blanc)",cat:"Charcuteries",score:2,level:"Élevé",tip:"Moins affiné que le jambon sec, mais transformé"},
  {name:"Jambon sec / cru",cat:"Charcuteries",score:3,level:"Très élevé",tip:"Longue maturation = très riche en histamine"},
  {name:"Salami",cat:"Charcuteries",score:3,level:"Très élevé",tip:"Charcuterie fermentée/affinée"},
  {name:"Saucisson sec",cat:"Charcuteries",score:3,level:"Très élevé",tip:"Fermenté et maturé, très élevé en histamine"},
  {name:"Chorizo",cat:"Charcuteries",score:3,level:"Très élevé",tip:"Fermenté/affiné + épices"},
  {name:"Bacon",cat:"Charcuteries",score:3,level:"Très élevé",tip:"Produit transformé souvent mal toléré"},
  {name:"Saucisse fraîche",cat:"Charcuteries",score:1,level:"Modéré",tip:"Moins risqué si fraîche, vérifier ingrédients"},
  {name:"Pâté / terrine",cat:"Charcuteries",score:3,level:"Très élevé",tip:"Transformation + conservation = risque élevé"},
  {name:"Lardons",cat:"Charcuteries",score:2,level:"Élevé",tip:"Transformés, souvent fumés, à surveiller"},
  // ══════ FERMENTÉS ══════
  {name:"Kimchi",cat:"Fermentés",score:3,level:"Très élevé",tip:"Fermenté, très riche en histamine"},
  {name:"Miso",cat:"Fermentés",score:3,level:"Très élevé",tip:"Soja fermenté longue durée"},
  {name:"Natto",cat:"Fermentés",score:3,level:"Très élevé",tip:"Soja fermenté, très riche en amines"},
  {name:"Levure alimentaire",cat:"Fermentés",score:2,level:"Élevé",tip:"Peut déclencher des réactions chez certains"},
  {name:"Levure de bière",cat:"Fermentés",score:3,level:"Très élevé",tip:"Fermentée, souvent mal tolérée"},
  // ══════ CONTEXTE ══════
  {name:"Restes réfrigérés >24h",cat:"Contexte",score:3,level:"Très élevé",tip:"Même un aliment faible peut devenir problématique"},
  {name:"Plat industriel",cat:"Contexte",score:2,level:"Élevé",tip:"Risque lié aux additifs, conservation"},
  {name:"Plat réchauffé",cat:"Contexte",score:2,level:"Élevé",tip:"Le réchauffage n'élimine pas l'histamine accumulée"}
];

const SYMPTOM_CATEGORIES = [
  {id:"digestif", label:"Digestif", emoji:"\u{1FAC4}"},
  {id:"peau", label:"Peau", emoji:"\u{1F534}"},
  {id:"neuro", label:"Neuro", emoji:"\u{1F9E0}"},
  {id:"respOrl", label:"Resp/ORL", emoji:"\u{1F443}"},
  {id:"cardio", label:"Cardio", emoji:"\u{1F493}"},
  {id:"autres", label:"Autres", emoji:"\u{1F4CB}"}
];

// Pantry staples - always considered available for recipe matching
const PANTRY_STAPLES = ["Sel", "Poivre noir", "Eau", "Huile d'olive", "Sucre blanc"];
