const RECIPES_BATCH_7 = [
  {
    id: "fr-pot-au-feu-classique",
    name: "Pot-au-Feu Classique Adapté",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Bœuf frais (gîte ou plat de côtes)", qty: 800, unit: "g", optional: false },
      { food: "Os à moelle frais", qty: 2, unit: "pièces", optional: true },
      { food: "Carottes", qty: 4, unit: "pièces", optional: false },
      { food: "Poireaux", qty: 3, unit: "pièces", optional: false },
      { food: "Navets", qty: 2, unit: "pièces", optional: false },
      { food: "Céleri-rave", qty: 0.5, unit: "pièce", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Clous de girofle", qty: 3, unit: "pièces", optional: false },
      { food: "Bouquet garni (thym, laurier, persil frais)", qty: 1, unit: "bouquet", optional: false },
      { food: "Pommes de terre", qty: 4, unit: "pièces", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir fraîchement moulu", qty: 1, unit: "pincée", optional: false },
      { food: "Gros sel", qty: 1, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Plonger le bœuf dans une grande marmite d'eau froide. Porter à ébullition et écumer soigneusement pendant 10 minutes pour obtenir un bouillon limpide.",
      "Éplucher l'oignon et le piquer avec les clous de girofle. Ajouter l'oignon piqué, le bouquet garni, le gros sel et les os à moelle dans la marmite.",
      "Réduire le feu et laisser mijoter à frémissement pendant 1h30.",
      "Éplucher et tailler les carottes en tronçons, les poireaux en sections de 5 cm, les navets en quartiers et le céleri-rave en morceaux grossiers.",
      "Ajouter les légumes dans le bouillon (sauf les pommes de terre) et poursuivre la cuisson 45 minutes.",
      "Éplucher les pommes de terre, les ajouter et cuire encore 25 minutes jusqu'à ce qu'elles soient tendres.",
      "Rectifier l'assaisonnement en sel et poivre. Retirer le bouquet garni.",
      "Servir le bœuf découpé avec les légumes et un peu de bouillon chaud. Proposer le gros sel séparément."
    ],
    nutrition: { calories: 520, protein: 45, carbs: 35, fat: 18, fiber: 6 },
    tips: "Adaptation histamine du classique français : aucun vin ni vinaigre n'est utilisé. Le bouillon naturel de bœuf remplace tout apport acide. Utiliser uniquement de la viande fraîche achetée le jour même.",
    isCustom: false
  },
  {
    id: "fr-blanquette-veau",
    name: "Blanquette de Veau à l'Ancienne",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 90,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Veau frais (épaule ou tendron)", qty: 800, unit: "g", optional: false },
      { food: "Carottes", qty: 3, unit: "pièces", optional: false },
      { food: "Oignons", qty: 2, unit: "pièces", optional: false },
      { food: "Champignons de Paris frais", qty: 200, unit: "g", optional: false },
      { food: "Beurre frais", qty: 60, unit: "g", optional: false },
      { food: "Farine", qty: 40, unit: "g", optional: false },
      { food: "Crème fraîche épaisse très fraîche", qty: 200, unit: "ml", optional: false },
      { food: "Jaunes d'œufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Bouquet garni (thym, laurier, persil frais)", qty: 1, unit: "bouquet", optional: false },
      { food: "Clous de girofle", qty: 2, unit: "pièces", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc fraîchement moulu", qty: 1, unit: "pincée", optional: false },
      { food: "Cerfeuil frais", qty: 1, unit: "bouquet", optional: false }
    ],
    steps: [
      "Couper le veau en morceaux de 5 cm. Mettre dans une casserole, couvrir d'eau froide, porter à ébullition et blanchir 3 minutes. Égoutter et rincer.",
      "Remettre le veau dans la casserole avec les carottes pelées et coupées en rondelles, les oignons piqués de clous de girofle et le bouquet garni. Couvrir d'eau froide et saler légèrement.",
      "Porter à frémissement et cuire doucement 1 heure à couvert.",
      "Nettoyer les champignons et les poêler rapidement dans 20 g de beurre. Réserver.",
      "Préparer le roux : faire fondre le reste du beurre dans une casserole, ajouter la farine et cuire 2 minutes en remuant. Ajouter progressivement 500 ml du bouillon de cuisson chaud en fouettant pour éviter les grumeaux.",
      "Mijoter cette sauce 10 minutes. Hors du feu, incorporer la crème fraîche et les jaunes d'œufs battus ensemble.",
      "Ajouter le veau égoutté et les champignons dans la sauce. Réchauffer sans faire bouillir.",
      "Rectifier l'assaisonnement et parsemer de cerfeuil frais ciselé avant de servir avec du riz blanc."
    ],
    nutrition: { calories: 560, protein: 42, carbs: 18, fat: 34, fiber: 3 },
    tips: "Le secret de la blanquette : ne jamais faire bouillir la sauce après l'ajout des jaunes d'œufs pour éviter qu'elle ne tourne. Le cerfeuil frais apporte la note herbacée traditionnelle sans recourir à la moutarde.",
    isCustom: false
  },
  {
    id: "fr-fricassee-poulet-creme",
    name: "Fricassée de Poulet à la Crème et aux Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 50,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Poulet frais entier découpé", qty: 1.2, unit: "kg", optional: false },
      { food: "Beurre frais", qty: 50, unit: "g", optional: false },
      { food: "Échalotes", qty: 3, unit: "pièces", optional: false },
      { food: "Champignons de Paris frais", qty: 200, unit: "g", optional: false },
      { food: "Bouillon de poulet maison", qty: 300, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 200, unit: "ml", optional: false },
      { food: "Estragon frais", qty: 3, unit: "branches", optional: false },
      { food: "Cerfeuil frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Persil plat frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Farine", qty: 20, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc fraîchement moulu", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Saler et poivrer les morceaux de poulet. Dans une cocotte, faire fondre le beurre à feu moyen. Y dorer les morceaux de poulet sur toutes les faces pendant 8 minutes. Retirer et réserver.",
      "Dans la même cocotte, faire revenir les échalotes ciselées finement jusqu'à ce qu'elles soient translucides.",
      "Saupourdrer de farine, mélanger et cuire 2 minutes à feu doux.",
      "Verser progressivement le bouillon de poulet chaud en fouettant. Ajouter l'estragon frais.",
      "Remettre les morceaux de poulet dans la cocotte. Couvrir et mijoter 30 minutes à feu doux.",
      "Nettoyer les champignons et les ajouter. Poursuivre la cuisson 10 minutes.",
      "Retirer le poulet. Incorporer la crème fraîche dans la sauce et faire réduire 5 minutes à feu vif.",
      "Remettre le poulet dans la sauce. Parsemer de cerfeuil et persil frais ciselés avant de servir."
    ],
    nutrition: { calories: 490, protein: 38, carbs: 12, fat: 30, fiber: 2 },
    tips: "L'estragon est l'herbe emblématique de la fricassée française. Utiliser uniquement de l'estragon frais car l'estragon séché perd ses arômes. Le bouillon maison remplace avantageusement le vin blanc.",
    isCustom: false
  },
  {
    id: "fr-navarin-agneau-printanier",
    name: "Navarin d'Agneau Printanier",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 90,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Épaule d'agneau fraîche désossée", qty: 700, unit: "g", optional: false },
      { food: "Carottes nouvelles", qty: 8, unit: "pièces", optional: false },
      { food: "Navets nouveaux", qty: 6, unit: "pièces", optional: false },
      { food: "Petits pois frais écossés", qty: 200, unit: "g", optional: false },
      { food: "Haricots verts fins", qty: 150, unit: "g", optional: false },
      { food: "Pommes de terre grenaille", qty: 12, unit: "pièces", optional: false },
      { food: "Oignons nouveaux", qty: 1, unit: "botte", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Bouquet garni (thym, laurier, persil)", qty: 1, unit: "bouquet", optional: false },
      { food: "Beurre frais", qty: 40, unit: "g", optional: false },
      { food: "Farine", qty: 30, unit: "g", optional: false },
      { food: "Bouillon de veau maison", qty: 500, unit: "ml", optional: false },
      { food: "Persil plat frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper l'agneau en morceaux réguliers de 4 cm. Saler et poivrer.",
      "Dans une cocotte en fonte, faire fondre le beurre et dorer les morceaux d'agneau sur toutes les faces. Retirer et réserver.",
      "Faire revenir les oignons nouveaux émincés dans la même cocotte. Singer (saupoudrer de farine) et cuire 2 minutes.",
      "Verser le bouillon de veau chaud, ajouter les gousses d'ail entières et le bouquet garni. Remettre l'agneau.",
      "Porter à frémissement, couvrir et cuire 30 minutes.",
      "Ajouter les carottes, les navets et les pommes de terre grenaille. Poursuivre 30 minutes.",
      "Ajouter les haricots verts et les petits pois. Cuire encore 15 minutes.",
      "Retirer le bouquet garni. Rectifier l'assaisonnement. Parsemer de persil plat frais haché avant de servir."
    ],
    nutrition: { calories: 510, protein: 36, carbs: 40, fat: 20, fiber: 8 },
    tips: "Le navarin printanier est un symbole de la cuisine de printemps en France. Sans tomate ni vin, les légumes de saison apportent toute la saveur du plat. Choisir une épaule fraîche du jour.",
    isCustom: false
  },
  {
    id: "fr-boeuf-bourguignon-adapte",
    name: "Bœuf Mijoté aux Herbes (Façon Bourguignon)",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Bœuf frais (paleron ou joue)", qty: 800, unit: "g", optional: false },
      { food: "Carottes", qty: 3, unit: "pièces", optional: false },
      { food: "Oignons", qty: 2, unit: "pièces", optional: false },
      { food: "Champignons de Paris frais", qty: 250, unit: "g", optional: false },
      { food: "Petits oignons grelots frais", qty: 200, unit: "g", optional: false },
      { food: "Beurre frais", qty: 50, unit: "g", optional: false },
      { food: "Farine", qty: 30, unit: "g", optional: false },
      { food: "Bouillon de bœuf maison", qty: 500, unit: "ml", optional: false },
      { food: "Jus de pomme non pasteurisé dilué", qty: 100, unit: "ml", optional: false },
      { food: "Thym frais", qty: 4, unit: "branches", optional: false },
      { food: "Laurier frais", qty: 2, unit: "feuilles", optional: false },
      { food: "Persil plat frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir fraîchement moulu", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper le bœuf en cubes de 4 cm. Saler et poivrer. Dans une cocotte en fonte, faire fondre le beurre à feu vif et dorer les morceaux par petites quantités. Réserver.",
      "Dans la même cocotte, faire revenir les oignons émincés et les carottes en rondelles jusqu'à légère coloration.",
      "Remettre le bœuf, singer de farine et mélanger. Cuire 2 minutes à feu moyen.",
      "Verser le bouillon de bœuf chaud et le jus de pomme dilué. Ajouter l'ail écrasé, le thym et le laurier.",
      "Porter à frémissement, couvrir hermétiquement et enfourner à 160°C pendant 2h30.",
      "30 minutes avant la fin, faire dorer les petits oignons grelots dans le beurre. Ajouter les champignons nettoyés et coupés en quatre. Incorporer au bœuf.",
      "Vérifier la tendreté de la viande : elle doit s'effeuiller. Rectifier l'assaisonnement.",
      "Parsemer de persil frais haché et servir avec des pommes de terre vapeur ou une purée maison."
    ],
    nutrition: { calories: 580, protein: 48, carbs: 20, fat: 28, fiber: 4 },
    tips: "Le jus de pomme dilué apporte une légère douceur qui remplace le vin rouge sans acidité. La cuisson longue au four garantit une viande fondante. Ne jamais utiliser de lardons fumés dans cette version.",
    isCustom: false
  },
  {
    id: "bistro-veau-marengo-adapte",
    name: "Veau Marengo Adapté aux Herbes Fraîches",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 70,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Veau frais (épaule)", qty: 700, unit: "g", optional: false },
      { food: "Champignons de Paris frais", qty: 250, unit: "g", optional: false },
      { food: "Petits oignons grelots frais", qty: 150, unit: "g", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 50, unit: "g", optional: false },
      { food: "Huile d'olive fraîche", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Farine", qty: 25, unit: "g", optional: false },
      { food: "Bouillon de veau maison", qty: 400, unit: "ml", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Thym frais", qty: 3, unit: "branches", optional: false },
      { food: "Laurier frais", qty: 2, unit: "feuilles", optional: false },
      { food: "Persil plat frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Estragon frais", qty: 2, unit: "branches", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper le veau en morceaux de 5 cm. Saler, poivrer et fariner légèrement.",
      "Dans une cocotte, chauffer le beurre et l'huile d'olive. Dorer le veau sur toutes les faces. Retirer et réserver.",
      "Faire revenir les oignons grelots entiers jusqu'à coloration dorée. Ajouter les carottes en rondelles et l'ail haché.",
      "Verser le bouillon de veau chaud. Ajouter le thym, le laurier et l'estragon. Remettre le veau.",
      "Couvrir et mijoter à feu doux pendant 45 minutes.",
      "Ajouter les champignons nettoyés et coupés en quartiers. Poursuivre 15 minutes.",
      "Retirer les herbes. La sauce doit être légèrement nappante ; si nécessaire, la faire réduire à découvert quelques minutes.",
      "Parsemer de persil frais et d'estragon ciselés. Servir avec du riz pilaf ou des tagliatelles fraîches."
    ],
    nutrition: { calories: 480, protein: 40, carbs: 16, fat: 26, fiber: 3 },
    tips: "Le veau Marengo traditionnel contient des tomates. Cette adaptation utilise uniquement le bouillon maison pour une sauce légère et parfumée. L'estragon frais est indispensable pour l'authenticité du plat.",
    isCustom: false
  },
  {
    id: "fr-veloute-poireaux-pommes-de-terre",
    name: "Velouté de Poireaux et Pommes de Terre",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poireaux", qty: 4, unit: "pièces", optional: false },
      { food: "Pommes de terre farineuses", qty: 400, unit: "g", optional: false },
      { food: "Beurre frais", qty: 40, unit: "g", optional: false },
      { food: "Bouillon de poulet maison", qty: 800, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 150, unit: "ml", optional: false },
      { food: "Ciboulette fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc fraîchement moulu", qty: 1, unit: "pincée", optional: false },
      { food: "Noix de muscade fraîche râpée", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Nettoyer les poireaux soigneusement et les émincer en fines rondelles, en gardant la partie verte tendre.",
      "Dans une grande casserole, faire fondre le beurre à feu doux. Y faire suer les poireaux pendant 10 minutes sans les colorer, en remuant régulièrement.",
      "Éplucher les pommes de terre et les couper en dés. Les ajouter aux poireaux.",
      "Verser le bouillon de poulet chaud. Saler, poivrer et ajouter la muscade. Porter à ébullition puis réduire le feu.",
      "Couvrir et cuire 25 minutes jusqu'à ce que les pommes de terre soient bien tendres.",
      "Mixer finement à l'aide d'un mixeur plongeant jusqu'à obtenir un velouté lisse et onctueux.",
      "Incorporer la crème fraîche en fouettant doucement. Réchauffer sans faire bouillir. Rectifier l'assaisonnement.",
      "Servir dans des bols chauds garnis de ciboulette fraîche ciselée et d'une noisette de beurre."
    ],
    nutrition: { calories: 280, protein: 8, carbs: 32, fat: 14, fiber: 4 },
    tips: "Ce velouté est la base de la vichyssoise. Pour une version froide estivale, laisser refroidir complètement et réfrigérer 2 heures avant de servir. Ne jamais utiliser de crème aigre ou de yaourt.",
    isCustom: false
  },
  {
    id: "fr-vichyssoise-classique",
    name: "Vichyssoise Froide aux Fines Herbes",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blancs de poireaux", qty: 5, unit: "pièces", optional: false },
      { food: "Pommes de terre à chair farineuse", qty: 500, unit: "g", optional: false },
      { food: "Beurre frais", qty: 50, unit: "g", optional: false },
      { food: "Bouillon de poulet maison très clair", qty: 900, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 200, unit: "ml", optional: false },
      { food: "Ciboulette fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel fin", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc fraîchement moulu", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Nettoyer et émincer finement les blancs de poireaux. Éplucher et couper les pommes de terre en dés réguliers.",
      "Dans une casserole à fond épais, faire fondre le beurre à feu doux. Faire suer les poireaux 8 minutes sans coloration.",
      "Ajouter les pommes de terre, verser le bouillon et porter à ébullition. Saler légèrement.",
      "Réduire le feu, couvrir et laisser mijoter 25 minutes à feu doux.",
      "Mixer très finement puis passer au tamis fin pour obtenir une texture parfaitement lisse.",
      "Incorporer la crème fraîche froide en fouettant. Rectifier l'assaisonnement en sel et poivre blanc.",
      "Laisser refroidir à température ambiante puis réfrigérer au minimum 3 heures.",
      "Servir dans des assiettes creuses bien froides, garni de ciboulette fraîche abondamment ciselée."
    ],
    nutrition: { calories: 260, protein: 6, carbs: 30, fat: 12, fiber: 3 },
    tips: "La vichyssoise doit être servie très froide pour révéler ses arômes délicats. Préparer la veille pour un meilleur résultat. Le passage au tamis est indispensable pour obtenir une texture digne d'un grand restaurant.",
    isCustom: false
  },
  {
    id: "fr-veloute-asperges",
    name: "Velouté d'Asperges Blanches à la Crème",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Asperges blanches fraîches", qty: 800, unit: "g", optional: false },
      { food: "Beurre frais", qty: 40, unit: "g", optional: false },
      { food: "Échalote", qty: 1, unit: "pièce", optional: false },
      { food: "Bouillon de légumes maison", qty: 700, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 150, unit: "ml", optional: false },
      { food: "Farine", qty: 20, unit: "g", optional: false },
      { food: "Cerfeuil frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Éplucher les asperges avec un économe en partant de la pointe vers la base. Couper les extrémités dures.",
      "Réserver quelques pointes d'asperges pour la décoration. Couper le reste en tronçons.",
      "Faire fondre le beurre dans une casserole. Y faire suer l'échalote ciselée 3 minutes. Ajouter la farine et cuire 1 minute.",
      "Verser le bouillon chaud progressivement en fouettant. Ajouter les tronçons d'asperges.",
      "Porter à ébullition, réduire le feu et cuire à couvert 20 minutes.",
      "Pendant ce temps, cuire les pointes réservées dans de l'eau bouillante salée pendant 5 minutes. Égoutter et réserver.",
      "Mixer le velouté finement et passer au chinois. Incorporer la crème fraîche.",
      "Réchauffer doucement, rectifier l'assaisonnement. Servir avec les pointes d'asperges et le cerfeuil frais."
    ],
    nutrition: { calories: 210, protein: 7, carbs: 18, fat: 12, fiber: 4 },
    tips: "La saison des asperges blanches s'étend d'avril à juin. Hors saison, utiliser des asperges surgelées de qualité, mais le résultat sera moins raffiné. Ne jamais utiliser de conserves d'asperges, trop riches en histamine.",
    isCustom: false
  },
  {
    id: "fr-soupe-fenouil-poisson",
    name: "Soupe de Fenouil et Sole Fraîche",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Bulbes de fenouil frais", qty: 2, unit: "pièces", optional: false },
      { food: "Filets de sole frais", qty: 300, unit: "g", optional: false },
      { food: "Pommes de terre", qty: 2, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 30, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Bouillon de légumes maison", qty: 800, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 100, unit: "ml", optional: false },
      { food: "Aneth frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Réserver les frondes de fenouil pour la décoration. Émincer les bulbes et les tiges tendres.",
      "Faire fondre le beurre dans une grande casserole. Y faire suer l'oignon émincé et le fenouil 8 minutes.",
      "Ajouter les pommes de terre épluchées et coupées en dés. Verser le bouillon chaud. Saler.",
      "Cuire 20 minutes jusqu'à ce que les légumes soient tendres. Mixer et passer au chinois.",
      "Incorporer la crème fraîche. Réchauffer doucement.",
      "Couper les filets de sole en morceaux réguliers. Les pocher délicatement dans la soupe frémissante pendant 3 minutes.",
      "Rectifier l'assaisonnement. Servir immédiatement garni d'aneth frais et de frondes de fenouil.",
    ],
    nutrition: { calories: 240, protein: 18, carbs: 20, fat: 10, fiber: 5 },
    tips: "La sole doit être achetée le matin même et pochée à la dernière minute pour rester nacrée et fondante. Le fenouil frais apporte une note anisée délicate typique de la cuisine du littoral français.",
    isCustom: false
  },
  {
    id: "fr-consomme-volaille-royale",
    name: "Consommé de Volaille à la Royale",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 120,
    servings: 4,
    difficulty: "difficile",
    histamineScore: 1,
    ingredients: [
      { food: "Carcasse de poulet frais", qty: 1, unit: "pièce", optional: false },
      { food: "Blanc de poulet frais", qty: 200, unit: "g", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Poireau", qty: 1, unit: "pièce", optional: false },
      { food: "Céleri branche", qty: 2, unit: "branches", optional: false },
      { food: "Bouquet garni (thym, laurier, persil)", qty: 1, unit: "bouquet", optional: false },
      { food: "Œufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Lait entier frais", qty: 100, unit: "ml", optional: false },
      { food: "Cerfeuil frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préparer le bouillon : mettre la carcasse dans une grande casserole d'eau froide avec les légumes et le bouquet garni. Porter à ébullition, écumer, puis mijoter 1h30 à feu doux.",
      "Filtrer le bouillon au chinois fin. Laisser refroidir et dégraisser.",
      "Préparer la royale : battre les œufs entiers avec le lait. Saler légèrement. Verser dans un petit moule beurré.",
      "Cuire la royale au bain-marie à 160°C pendant 20 minutes jusqu'à ce qu'elle soit ferme.",
      "Laisser refroidir la royale, la démouler et la couper en petits cubes ou losanges.",
      "Réchauffer le consommé limpide. Rectifier l'assaisonnement.",
      "Disposer les cubes de royale dans des assiettes creuses chaudes. Verser le consommé bouillant dessus.",
      "Garnir de cerfeuil frais et servir immédiatement."
    ],
    nutrition: { calories: 180, protein: 22, carbs: 6, fat: 7, fiber: 1 },
    tips: "Le consommé est la quintessence de la grande cuisine française. La royale est une garniture d'œuf cuit au bain-marie d'une extrême délicatesse. Ce plat convient parfaitement comme entrée de dîner soigné.",
    isCustom: false
  },
  {
    id: "fr-sole-meuniere-adaptee",
    name: "Sole Meunière au Beurre Noisette et Persil",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Soles fraîches entières habillées", qty: 2, unit: "pièces (400g chacune)", optional: false },
      { food: "Beurre frais", qty: 80, unit: "g", optional: false },
      { food: "Farine", qty: 40, unit: "g", optional: false },
      { food: "Persil plat frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel fin", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc fraîchement moulu", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Rincer les soles à l'eau froide et les sécher soigneusement avec du papier absorbant. Saler et poivrer des deux côtés.",
      "Fariner légèrement les soles en tapotant pour éliminer l'excès de farine.",
      "Dans une grande poêle, faire fondre 40 g de beurre jusqu'à ce qu'il soit mousseux. Faire cuire les soles côté peau foncée en premier, 4 à 5 minutes.",
      "Retourner délicatement les soles et poursuivre la cuisson 4 minutes. Les soles doivent être dorées et la chair nacrée.",
      "Retirer les soles et les poser sur les assiettes de service chaudes.",
      "Dans la même poêle, ajouter le reste du beurre et le laisser chauffer jusqu'à obtenir une couleur noisette dorée.",
      "Ajouter immédiatement le persil frais haché et verser le beurre noisette sur les soles.",
      "Servir sans attendre. Accompagner de pommes vapeur ou de riz blanc."
    ],
    nutrition: { calories: 420, protein: 38, carbs: 14, fat: 24, fiber: 1 },
    tips: "La sole meunière traditionnelle utilise un filet de citron. Cette version s'en passe et laisse la qualité du beurre noisette et du poisson frais s'exprimer. La sole doit être achetée vivante ou très fraîche du matin.",
    isCustom: false
  },
  {
    id: "fr-bar-papillote-herbes",
    name: "Bar en Papillote aux Herbes de Jardin",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Bar (loup de mer) frais entier", qty: 600, unit: "g", optional: false },
      { food: "Fenouil frais", qty: 1, unit: "bulbe", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 30, unit: "g", optional: false },
      { food: "Thym frais", qty: 3, unit: "branches", optional: false },
      { food: "Romarin frais", qty: 1, unit: "branche", optional: false },
      { food: "Laurier frais", qty: 2, unit: "feuilles", optional: false },
      { food: "Estragon frais", qty: 2, unit: "branches", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 200°C. Écailler et vider le bar si ce n'est pas fait, rincer et sécher.",
      "Inciser le poisson de chaque côté à 3 reprises. Glisser des herbes fraîches dans les incisions.",
      "Émincer finement le fenouil et tailler les carottes en julienne.",
      "Disposer les légumes au centre d'une grande feuille de papier cuisson. Poser le bar dessus.",
      "Farcir l'intérieur du poisson avec le thym, le romarin, le laurier, l'estragon et l'ail écrasé.",
      "Déposer des noisettes de beurre sur et autour du poisson. Saler et poivrer généreusement.",
      "Refermer hermétiquement la papillote. Enfourner 18 à 20 minutes selon la taille du poisson.",
      "Ouvrir la papillote à table pour libérer les arômes. Servir avec du riz ou des légumes vapeur."
    ],
    nutrition: { calories: 380, protein: 42, carbs: 10, fat: 18, fiber: 4 },
    tips: "La papillote préserve tous les arômes et la jutosité du bar. Vérifier la cuisson en pressant légèrement la chair : elle doit s'effeuiller facilement. Le bar est un poisson à très faible teneur en histamine quand il est très frais.",
    isCustom: false
  },
  {
    id: "fr-turbot-beurre-blanc",
    name: "Filets de Turbot au Beurre Blanc aux Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "difficile",
    histamineScore: 0,
    ingredients: [
      { food: "Filets de turbot frais", qty: 400, unit: "g", optional: false },
      { food: "Beurre frais très froid", qty: 150, unit: "g", optional: false },
      { food: "Échalotes", qty: 3, unit: "pièces", optional: false },
      { food: "Bouillon de légumes maison", qty: 100, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 50, unit: "ml", optional: false },
      { food: "Ciboulette fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Cerfeuil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préparer le beurre blanc : émincer finement les échalotes et les faire réduire dans le bouillon de légumes jusqu'à quasi-sèchement.",
      "Ajouter la crème fraîche et réduire de moitié à feu moyen.",
      "Hors du feu, incorporer le beurre très froid coupé en dés, morceau par morceau, en fouettant vigoureusement. La sauce doit être onctueuse et nacrée.",
      "Ajouter la ciboulette ciselée. Saler et poivrer. Maintenir au chaud au bain-marie en fouettant.",
      "Saler et poivrer les filets de turbot. Les cuire à la vapeur ou à la poêle dans 20 g de beurre, 3 minutes de chaque côté.",
      "Dresser les filets sur des assiettes chaudes. Napper généreusement de beurre blanc.",
      "Décorer de cerfeuil frais et servir immédiatement."
    ],
    nutrition: { calories: 460, protein: 35, carbs: 4, fat: 34, fiber: 0 },
    tips: "Le beurre blanc est une sauce emblématique de la cuisine de la Loire. Sans vinaigre ni citron, le bouillon maison apporte l'acidité nécessaire à l'émulsion. La clé : le beurre doit être très froid et incorporé hors du feu.",
    isCustom: false
  },
  {
    id: "fr-raie-beurre-noisette-capres",
    name: "Aile de Raie au Beurre Noisette et Câpres Fraîches",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 18,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Ailes de raie fraîches", qty: 500, unit: "g", optional: false },
      { food: "Beurre frais", qty: 80, unit: "g", optional: false },
      { food: "Câpres fraîches au sel (rincées)", qty: 30, unit: "g", optional: true },
      { food: "Persil plat frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false },
      { food: "Court-bouillon maison (eau, carotte, laurier, thym)", qty: 1, unit: "litre", optional: false }
    ],
    steps: [
      "Préparer le court-bouillon : faire bouillir l'eau avec une carotte, le laurier et le thym pendant 15 minutes. Saler.",
      "Pocher les ailes de raie dans le court-bouillon frémissant (pas bouillant) pendant 10 à 12 minutes.",
      "Égoutter délicatement les ailes. Les déposer sur des assiettes chaudes.",
      "Retirer la peau gélatineuse si elle est encore présente.",
      "Dans une poêle propre, faire chauffer le beurre jusqu'à obtenir une couleur noisette dorée (attention à ne pas le brûler).",
      "Ajouter les câpres rincées et le persil frais haché. Faire revenir 30 secondes.",
      "Verser immédiatement sur la raie. Servir sans attendre avec des pommes vapeur."
    ],
    nutrition: { calories: 350, protein: 36, carbs: 2, fat: 22, fiber: 0 },
    tips: "La raie doit être pochée et non frite pour rester tendre. Si les câpres au sel sont interdites (elles peuvent contenir un peu de vinaigre dans certaines préparations), les omettre tout simplement. La raie est naturellement riche en oméga-3.",
    isCustom: false
  },
  {
    id: "fr-gratin-dauphinois-adapte",
    name: "Gratin Dauphinois à la Crème Fraîche",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 75,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Pommes de terre à chair ferme", qty: 1, unit: "kg", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 400, unit: "ml", optional: false },
      { food: "Lait entier frais", qty: 200, unit: "ml", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Beurre frais", qty: 20, unit: "g", optional: false },
      { food: "Noix de muscade fraîche râpée", qty: 1, unit: "pincée", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false },
      { food: "Thym frais", qty: 2, unit: "branches", optional: true }
    ],
    steps: [
      "Préchauffer le four à 160°C. Frotter le plat à gratin avec les gousses d'ail coupées en deux, puis le beurrer généreusement.",
      "Éplucher et laver les pommes de terre. Les couper en tranches très fines et régulières de 2 mm au couteau ou mandoline.",
      "Ne pas rincer les tranches pour préserver l'amidon qui liera le gratin.",
      "Dans une casserole, porter à frémissement la crème et le lait avec la muscade râpée, le sel, le poivre et les gousses d'ail émincées.",
      "Disposer les tranches de pommes de terre en couches régulières dans le plat beurré. Verser le mélange crème-lait chaud dessus.",
      "La crème doit presque affleurer le niveau des pommes de terre. Parsemer de thym frais si désiré.",
      "Enfourner 1h15 jusqu'à ce que le dessus soit gratiné doré et les pommes de terre fondantes.",
      "Laisser reposer 10 minutes avant de servir."
    ],
    nutrition: { calories: 420, protein: 7, carbs: 45, fat: 24, fiber: 4 },
    tips: "Le vrai gratin dauphinois ne contient ni fromage ni œufs. C'est la crème et l'amidon des pommes de terre qui créent sa texture incomparable. Utiliser uniquement de la crème fraîche très fraîche du jour.",
    isCustom: false
  },
  {
    id: "fr-gratin-courgettes-ricotta",
    name: "Gratin de Courgettes à la Ricotta et au Basilic",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Courgettes fraîches", qty: 800, unit: "g", optional: false },
      { food: "Ricotta fraîche", qty: 250, unit: "g", optional: false },
      { food: "Œufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 100, unit: "ml", optional: false },
      { food: "Basilic frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Ciboulette fraîche", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Beurre frais", qty: 20, unit: "g", optional: false },
      { food: "Chapelure fraîche (pain rassis maison)", qty: 40, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C. Beurrer un plat à gratin.",
      "Laver et couper les courgettes en rondelles de 5 mm. Les faire dégorger 20 minutes avec un peu de sel, puis les éponger.",
      "Dans un bol, mélanger la ricotta, les œufs battus, la crème, le basilic ciselé et la ciboulette. Saler, poivrer et muscader.",
      "Faire revenir les courgettes dans le beurre restant 5 minutes à feu vif pour les colorer légèrement.",
      "Disposer les courgettes en couches dans le plat à gratin. Verser la préparation à la ricotta entre les couches.",
      "Terminer par une couche de courgettes. Saupoudrer de chapelure fraîche et de quelques noisettes de beurre.",
      "Enfourner 35 à 40 minutes jusqu'à ce que le dessus soit bien doré.",
      "Laisser reposer 5 minutes. Décorer de feuilles de basilic frais avant de servir."
    ],
    nutrition: { calories: 290, protein: 14, carbs: 18, fat: 18, fiber: 3 },
    tips: "Ce gratin remplace les gratins au fromage âgé. La ricotta fraîche apporte la même onctuosité sans risque histaminique. Faire la chapelure soi-même avec du pain blanc du jour séché au four.",
    isCustom: false
  },
  {
    id: "fr-gratin-fenouil-creme",
    name: "Tian de Fenouil Braisé à la Crème",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Bulbes de fenouil frais", qty: 4, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 40, unit: "g", optional: false },
      { food: "Bouillon de légumes maison", qty: 200, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 150, unit: "ml", optional: false },
      { food: "Thym frais", qty: 2, unit: "branches", optional: false },
      { food: "Laurier frais", qty: 1, unit: "feuille", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C. Nettoyer les fenouils, retirer les tiges dures et couper chaque bulbe en quartiers.",
      "Dans une cocotte allant au four, faire fondre le beurre. Y faire dorer les quartiers de fenouil sur toutes les faces.",
      "Saler et poivrer. Ajouter le thym, le laurier et le bouillon de légumes.",
      "Couvrir la cocotte et enfourner 25 minutes.",
      "Retirer le couvercle, verser la crème fraîche et poursuivre la cuisson à découvert 15 à 20 minutes.",
      "Le fenouil doit être fondant et légèrement caramélisé, la sauce crémeuse et réduite.",
      "Retirer les herbes. Servir directement dans la cocotte avec du poisson ou de la volaille."
    ],
    nutrition: { calories: 180, protein: 3, carbs: 12, fat: 14, fiber: 5 },
    tips: "Le fenouil braisé est un accompagnement raffiné souvent servi avec le poisson. Sa saveur anisée s'adoucit à la cuisson. Ce plat peut se préparer à l'avance et se réchauffer doucement.",
    isCustom: false
  },
  {
    id: "fr-tian-provencal-adapte",
    name: "Tian Provençal de Légumes d'Été",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Courgettes fraîches", qty: 3, unit: "pièces", optional: false },
      { food: "Pommes de terre", qty: 3, unit: "pièces", optional: false },
      { food: "Oignons", qty: 2, unit: "pièces", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Huile d'olive fraîche", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Thym frais", qty: 4, unit: "branches", optional: false },
      { food: "Romarin frais", qty: 2, unit: "branches", optional: false },
      { food: "Laurier frais", qty: 2, unit: "feuilles", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false },
      { food: "Bouillon de légumes maison", qty: 100, unit: "ml", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C. Huiler généreusement un grand plat à gratin.",
      "Éplucher et émincer finement les oignons et l'ail. Les faire revenir dans 2 c. à soupe d'huile d'olive jusqu'à ce qu'ils soient fondants. Les étaler au fond du plat.",
      "Couper les courgettes et les pommes de terre épluchées en rondelles de 5 mm d'épaisseur.",
      "Disposer les rondelles en les intercalant (courgette, pomme de terre) debout en rangées serrées dans le plat.",
      "Glisser les herbes fraîches entre les légumes. Verser le bouillon.",
      "Arroser du reste d'huile d'olive. Saler et poivrer généreusement.",
      "Couvrir de papier aluminium et enfourner 30 minutes. Retirer le papier et poursuivre 30 minutes jusqu'à légère coloration.",
      "Servir chaud ou à température ambiante. Les arômes sont encore meilleurs réchauffés le lendemain."
    ],
    nutrition: { calories: 220, protein: 4, carbs: 30, fat: 10, fiber: 5 },
    tips: "Le tian provençal traditionnel contient des tomates. Cette version sans tomates laisse les courgettes et pommes de terre exprimer leurs saveurs naturelles. Le secret : les légumes doivent être taillés à la même épaisseur.",
    isCustom: false
  },
  {
    id: "fr-quiche-lorraine-adaptee",
    name: "Quiche Lorraine au Poulet Frais (Sans Lardons)",
    category: "plat",
    mealType: ["dejeuner"],
    prepTime: 25,
    cookTime: 45,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte brisée maison (farine, beurre, eau, sel)", qty: 200, unit: "g de farine", optional: false },
      { food: "Blancs de poulet frais", qty: 200, unit: "g", optional: false },
      { food: "Œufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse très fraîche", qty: 200, unit: "ml", optional: false },
      { food: "Lait entier frais", qty: 100, unit: "ml", optional: false },
      { food: "Beurre frais", qty: 100, unit: "g", optional: false },
      { food: "Échalote", qty: 1, unit: "pièce", optional: false },
      { food: "Ciboulette fraîche", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préparer la pâte brisée : sabler 200 g de farine avec 100 g de beurre froid en dés, ajouter une pincée de sel et 50 ml d'eau froide. Pétrir rapidement, former une boule et réfrigérer 30 minutes.",
      "Préchauffer le four à 180°C. Étaler la pâte et foncer un moule à tarte. Piquer le fond. Cuire à blanc 10 minutes avec des billes.",
      "Couper le poulet en petits dés. Les faire revenir dans une noisette de beurre avec l'échalote ciselée pendant 5 minutes. Assaisonner.",
      "Préparer l'appareil : battre les œufs avec la crème et le lait. Saler, poivrer, muscader.",
      "Répartir le poulet et la ciboulette ciselée sur le fond de tarte précuit.",
      "Verser l'appareil à quiche par-dessus.",
      "Enfourner 35 à 40 minutes jusqu'à ce que la quiche soit dorée et l'appareil bien pris.",
      "Laisser tiédir 10 minutes avant de démouler et de servir avec une salade verte."
    ],
    nutrition: { calories: 420, protein: 22, carbs: 28, fat: 26, fiber: 1 },
    tips: "La quiche Lorraine traditionnelle utilise des lardons fumés, interdits en alimentation pauvre en histamine. Le poulet frais est une excellente alternative qui apporte la même richesse protéique sans risque.",
    isCustom: false
  },
  {
    id: "fr-tarte-poireaux-chevre",
    name: "Tarte Fine aux Poireaux et Chèvre Frais",
    category: "plat",
    mealType: ["dejeuner"],
    prepTime: 20,
    cookTime: 35,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte feuilletée maison ou du boucher", qty: 1, unit: "rouleau", optional: false },
      { food: "Poireaux", qty: 4, unit: "pièces", optional: false },
      { food: "Chèvre frais (bûche fraîche très jeune)", qty: 150, unit: "g", optional: false },
      { food: "Beurre frais", qty: 30, unit: "g", optional: false },
      { food: "Crème fraîche épaisse très fraîche", qty: 150, unit: "ml", optional: false },
      { food: "Œufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Ciboulette fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Thym frais", qty: 2, unit: "branches", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 190°C. Étaler la pâte feuilletée sur une plaque. Réfrigérer 15 minutes.",
      "Nettoyer les poireaux et les émincer finement. Les faire fondre dans le beurre à feu doux pendant 15 minutes jusqu'à ce qu'ils soient fondants. Saler et poivrer.",
      "Dans un bol, mélanger la crème fraîche et les œufs. Ajouter la ciboulette ciselée. Saler légèrement.",
      "Piquer la pâte et y étaler les poireaux fondus en laissant un bord de 2 cm.",
      "Verser l'appareil crème-œufs sur les poireaux.",
      "Émietter le chèvre frais par-dessus. Parsemer de feuilles de thym frais.",
      "Rabattre les bords de la pâte et les dorer à l'œuf.",
      "Enfourner 30 à 35 minutes jusqu'à ce que la tarte soit bien dorée. Servir tiède."
    ],
    nutrition: { calories: 390, protein: 12, carbs: 32, fat: 24, fiber: 3 },
    tips: "Utiliser uniquement du chèvre frais du jour (buche très jeune et blanche, non affinée). Le chèvre frais ne génère pas d'histamine contrairement aux chèvres affinés ou secs.",
    isCustom: false
  },
  {
    id: "fr-flamiche-aux-poireaux",
    name: "Flamiche Picarde aux Poireaux",
    category: "plat",
    mealType: ["dejeuner"],
    prepTime: 30,
    cookTime: 40,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte brisée maison", qty: 300, unit: "g de farine", optional: false },
      { food: "Beurre frais", qty: 150, unit: "g", optional: false },
      { food: "Poireaux", qty: 6, unit: "pièces", optional: false },
      { food: "Œufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse très fraîche", qty: 250, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préparer la pâte brisée. Diviser en deux. Étaler une moitié et foncer un moule beurré. Réfrigérer.",
      "Nettoyer et émincer finement les poireaux (blanc et vert tendre). Les faire fondre dans 50 g de beurre à feu très doux, à couvert, pendant 20 minutes. Laisser refroidir.",
      "Battre les œufs avec la crème fraîche. Saler, poivrer, muscader. Incorporer les poireaux.",
      "Préchauffer le four à 200°C.",
      "Verser la garniture sur le fond de pâte.",
      "Étaler la seconde moitié de pâte par-dessus. Souder les bords soigneusement en les chiquetant.",
      "Dorer à l'œuf, faire une cheminée au centre. Enfourner 35 à 40 minutes.",
      "Servir chaud ou tiède, découpée en parts généreuses."
    ],
    nutrition: { calories: 440, protein: 10, carbs: 38, fat: 28, fiber: 4 },
    tips: "La flamiche est une spécialité de la Picardie et de la Bourgogne. Cette tourte aux poireaux est différente de la quiche car elle est entièrement couverte de pâte. Elle se congèle très bien une fois cuite.",
    isCustom: false
  },
  {
    id: "fr-tarte-oignon-alsacienne",
    name: "Tarte à l'Oignon Alsacienne (Zwiebelkuchen)",
    category: "plat",
    mealType: ["dejeuner"],
    prepTime: 25,
    cookTime: 50,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte brisée ou levée maison", qty: 250, unit: "g de farine", optional: false },
      { food: "Oignons", qty: 800, unit: "g", optional: false },
      { food: "Beurre frais", qty: 60, unit: "g", optional: false },
      { food: "Œufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse très fraîche", qty: 200, unit: "ml", optional: false },
      { food: "Lait entier frais", qty: 50, unit: "ml", optional: false },
      { food: "Ciboulette fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Thym frais", qty: 2, unit: "branches", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préparer la pâte et la réfrigérer 30 minutes. Préchauffer le four à 180°C.",
      "Éplucher et émincer finement les oignons. Les faire fondre à feu très doux dans le beurre pendant 30 minutes, jusqu'à ce qu'ils soient fondants et légèrement caramélisés. Laisser refroidir.",
      "Foncer le moule à tarte avec la pâte. Piquer le fond. Cuire à blanc 10 minutes.",
      "Battre les œufs avec la crème et le lait. Incorporer la ciboulette et le thym. Saler, poivrer, muscader.",
      "Mélanger les oignons confits avec l'appareil à quiche.",
      "Verser la préparation sur le fond de tarte précuit.",
      "Enfourner 35 à 40 minutes. La tarte doit être dorée et l'appareil ferme.",
      "Servir tiède en entrée ou en plat principal avec une salade de mâche."
    ],
    nutrition: { calories: 380, protein: 9, carbs: 36, fat: 22, fiber: 4 },
    tips: "La cuisson très douce des oignons est la clé de ce plat. Ils doivent fondre et se caraméliser légèrement sans colorer. Cette tarte est idéale pour les repas d'automne et d'hiver.",
    isCustom: false
  },
  {
    id: "fr-poulet-roti-classique",
    name: "Poulet Rôti Classique au Beurre d'Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 75,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poulet frais entier fermier", qty: 1.5, unit: "kg", optional: false },
      { food: "Beurre frais", qty: 80, unit: "g", optional: false },
      { food: "Ail", qty: 4, unit: "gousses", optional: false },
      { food: "Thym frais", qty: 4, unit: "branches", optional: false },
      { food: "Romarin frais", qty: 2, unit: "branches", optional: false },
      { food: "Estragon frais", qty: 3, unit: "branches", optional: false },
      { food: "Laurier frais", qty: 2, unit: "feuilles", optional: false },
      { food: "Sel fin", qty: 2, unit: "c. à café", optional: false },
      { food: "Poivre noir fraîchement moulu", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Sortir le poulet du réfrigérateur 30 minutes avant la cuisson. Préchauffer le four à 220°C.",
      "Préparer le beurre d'herbes : mélanger le beurre ramolli avec les herbes fraîches ciselées finement (thym, romarin, estragon). Saler et poivrer.",
      "Glisser délicatement le beurre aux herbes sous la peau du poulet au niveau des poitrines et des cuisses, sans déchirer la peau.",
      "Farcir la cavité avec les gousses d'ail non pelées et les herbes restantes.",
      "Enduire l'extérieur du poulet avec le beurre aux herbes restant. Saler et poivrer généreusement.",
      "Disposer le poulet dans un plat et enfourner 15 minutes à 220°C pour dorer la peau.",
      "Réduire à 180°C et poursuivre la cuisson 60 minutes en arrosant toutes les 15 minutes avec les jus de cuisson.",
      "Vérifier la cuisson : le jus doit être clair quand on pique la cuisse. Laisser reposer 10 minutes avant de découper."
    ],
    nutrition: { calories: 460, protein: 42, carbs: 2, fat: 30, fiber: 0 },
    tips: "Le secret du poulet rôti parfait : le beurre sous la peau maintient la chair moelleuse et la fait parfumer de l'intérieur. Le repos après cuisson est indispensable pour que les jus se redistribuent.",
    isCustom: false
  },
  {
    id: "fr-canard-pommes-thym",
    name: "Magret de Canard aux Pommes et Thym",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Magrets de canard frais", qty: 2, unit: "pièces", optional: false },
      { food: "Pommes (golden ou reinette)", qty: 3, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 30, unit: "g", optional: false },
      { food: "Bouillon de volaille maison", qty: 100, unit: "ml", optional: false },
      { food: "Thym frais", qty: 4, unit: "branches", optional: false },
      { food: "Laurier frais", qty: 2, unit: "feuilles", optional: false },
      { food: "Miel d'acacia", qty: 1, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir fraîchement moulu", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Quadriller le gras des magrets au couteau sans atteindre la chair. Saler et poivrer généreusement.",
      "Déposer les magrets côté gras dans une poêle froide. Cuire à feu moyen 10 minutes jusqu'à ce que le gras soit fondu et bien doré.",
      "Retourner et cuire côté chair 5 à 6 minutes pour une cuisson rosée.",
      "Retirer les magrets, couvrir d'une feuille d'aluminium et laisser reposer 5 minutes.",
      "Dans la même poêle, retirer l'excès de graisse. Faire sauter les pommes épluchées et coupées en quartiers avec le beurre et les feuilles de thym.",
      "Ajouter le miel si désiré et laisser caraméliser légèrement. Verser le bouillon et réduire à glace.",
      "Trancher les magrets en biais. Dresser avec les pommes caramélisées et la sauce.",
      "Garnir de brins de thym frais."
    ],
    nutrition: { calories: 540, protein: 36, carbs: 22, fat: 32, fiber: 3 },
    tips: "Le canard à l'orange traditionnel est interdit (agrumes). Les pommes créent une association classique avec le canard tout aussi raffinée. La cuisson rosée est recommandée pour le magret.",
    isCustom: false
  },
  {
    id: "fr-poulet-estragon-creme",
    name: "Poulet à l'Estragon en Cocotte",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 55,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Poulet frais entier découpé en 8 morceaux", qty: 1.2, unit: "kg", optional: false },
      { food: "Beurre frais", qty: 50, unit: "g", optional: false },
      { food: "Échalotes", qty: 4, unit: "pièces", optional: false },
      { food: "Estragon frais", qty: 1, unit: "botte généreuse", optional: false },
      { food: "Bouillon de poulet maison", qty: 250, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 200, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Saler et poivrer les morceaux de poulet. Dans une cocotte en fonte, faire fondre le beurre à feu moyen-vif.",
      "Dorer les morceaux de poulet sur toutes les faces, environ 10 minutes. Retirer et réserver.",
      "Dans la même cocotte, faire revenir les échalotes ciselées finement jusqu'à ce qu'elles soient translucides.",
      "Hacher la moitié de l'estragon et l'ajouter aux échalotes. Verser le bouillon de poulet.",
      "Remettre les morceaux de poulet. Couvrir et cuire à feu doux 40 minutes.",
      "Retirer les morceaux de poulet. Verser la crème fraîche dans la cocotte et faire réduire la sauce 5 minutes.",
      "Remettre le poulet dans la sauce. Ajouter le reste de l'estragon frais ciselé.",
      "Servir immédiatement avec des tagliatelles fraîches ou un riz pilaf."
    ],
    nutrition: { calories: 470, protein: 40, carbs: 6, fat: 30, fiber: 1 },
    tips: "L'estragon frais est l'herbe aromatique par excellence de la cuisine classique française. Il ne peut pas être remplacé par de l'estragon séché qui a perdu ses huiles essentielles.",
    isCustom: false
  },
  {
    id: "fr-creme-brulee-vanille",
    name: "Crème Brûlée à la Vanille Bourbon",
    category: "dessert",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 45,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Crème fraîche liquide entière très fraîche", qty: 500, unit: "ml", optional: false },
      { food: "Jaunes d'œufs frais", qty: 5, unit: "pièces", optional: false },
      { food: "Sucre en poudre", qty: 80, unit: "g", optional: false },
      { food: "Gousses de vanille de Bourbon", qty: 2, unit: "pièces", optional: false },
      { food: "Cassonade", qty: 4, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Préchauffer le four à 150°C. Fendre les gousses de vanille en deux et gratter les graines.",
      "Porter la crème à frémissement avec les gousses et les graines de vanille. Retirer du feu et laisser infuser 15 minutes.",
      "Dans un saladier, battre les jaunes d'œufs avec le sucre jusqu'à ce que le mélange blanchisse légèrement.",
      "Retirer les gousses de vanille. Verser la crème chaude progressivement sur les jaunes en fouettant doucement pour éviter de les cuire.",
      "Filtrer l'appareil au chinois fin. Écumer les bulles de surface.",
      "Verser dans 4 ramequins. Déposer dans un bain-marie (plat avec de l'eau chaude) et enfourner 40 à 45 minutes.",
      "Les crèmes doivent être légèrement tremblotantes au centre. Réfrigérer au moins 3 heures.",
      "Au moment de servir, saupoudrer de cassonade et caraméliser au chalumeau. Servir immédiatement."
    ],
    nutrition: { calories: 480, protein: 8, carbs: 28, fat: 38, fiber: 0 },
    tips: "La crème brûlée est l'un des desserts français les plus adaptés à l'alimentation pauvre en histamine. La vanille naturelle est tolérée. Ne jamais utiliser d'extrait de vanille avec de l'alcool.",
    isCustom: false
  },
  {
    id: "fr-flan-patissier-classique",
    name: "Flan Pâtissier Parisien à la Vanille",
    category: "dessert",
    mealType: ["dejeuner"],
    prepTime: 25,
    cookTime: 50,
    servings: 8,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte brisée maison", qty: 200, unit: "g de farine", optional: false },
      { food: "Lait entier frais", qty: 750, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 200, unit: "ml", optional: false },
      { food: "Œufs frais entiers", qty: 3, unit: "pièces", optional: false },
      { food: "Jaunes d'œufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Sucre en poudre", qty: 150, unit: "g", optional: false },
      { food: "Maïzena (fécule de maïs)", qty: 60, unit: "g", optional: false },
      { food: "Gousse de vanille", qty: 1, unit: "pièce", optional: false },
      { food: "Beurre frais", qty: 30, unit: "g", optional: false }
    ],
    steps: [
      "Foncer un moule à manqué de 22 cm avec la pâte brisée. Réfrigérer.",
      "Porter le lait et la crème à frémissement avec la gousse de vanille fendue et grattée. Laisser infuser 10 minutes.",
      "Fouetter les œufs entiers, les jaunes et le sucre. Ajouter la maïzena et mélanger.",
      "Verser le lait chaud (sans la gousse) progressivement sur le mélange œufs-sucre en fouettant.",
      "Remettre sur feu moyen et cuire en remuant constamment jusqu'à épaississement.",
      "Hors du feu, incorporer le beurre. Verser l'appareil dans le fond de tarte.",
      "Préchauffer le four à 180°C. Enfourner 40 à 45 minutes jusqu'à ce que le dessus soit doré et légèrement marbré.",
      "Laisser refroidir complètement avant de démouler. Réfrigérer 2 heures avant de déguster."
    ],
    nutrition: { calories: 360, protein: 9, carbs: 45, fat: 16, fiber: 1 },
    tips: "Le flan parisien doit avoir un dessus légèrement brûlé avec des taches foncées caractéristiques. Ne pas hésiter à le cuire jusqu'à ce qu'il soit bien coloré. Il se conserve 2 jours au réfrigérateur.",
    isCustom: false
  },
  {
    id: "fr-tarte-pommes-normande",
    name: "Tarte aux Pommes à la Normande",
    category: "dessert",
    mealType: ["dejeuner"],
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte sablée maison", qty: 200, unit: "g de farine", optional: false },
      { food: "Pommes golden ou reinette", qty: 4, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 80, unit: "g", optional: false },
      { food: "Sucre en poudre", qty: 80, unit: "g", optional: false },
      { food: "Œufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse très fraîche", qty: 150, unit: "ml", optional: false },
      { food: "Poudre d'amande (amandes blanches fraîches moulues)", qty: 80, unit: "g", optional: false },
      { food: "Gousse de vanille", qty: 1, unit: "pièce", optional: false },
      { food: "Cannelle fraîche moulue", qty: 0.5, unit: "c. à café", optional: true }
    ],
    steps: [
      "Préparer la pâte sablée et foncer un moule de 24 cm. Préchauffer le four à 180°C.",
      "Préparer la crème normande : fouetter le beurre ramolli avec le sucre et les graines de vanille. Incorporer les œufs un à un. Ajouter la poudre d'amande et la crème fraîche.",
      "Éplucher les pommes, enlever le cœur et les couper en lamelles fines.",
      "Étaler la crème normande sur le fond de tarte.",
      "Disposer les lamelles de pommes en rosace sur la crème, en les chevauchant légèrement.",
      "Parsemer d'un peu de sucre. Enfourner 35 à 40 minutes jusqu'à dorure.",
      "À mi-cuisson, badigeonner les pommes de beurre fondu pour les faire briller.",
      "Laisser tiédir avant de servir. Accompagner d'une cuillère de crème fraîche épaisse."
    ],
    nutrition: { calories: 420, protein: 8, carbs: 48, fat: 22, fiber: 3 },
    tips: "La tarte normande se distingue de la tarte aux pommes simple par sa crème aux amandes. Utiliser de la poudre d'amande fraîchement moulue pour un goût optimal. La cannelle fraîche est bien tolérée.",
    isCustom: false
  },
  {
    id: "fr-puree-pommes-de-terre-robuchon",
    name: "Purée de Pommes de Terre Crémeuse au Beurre",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pommes de terre à chair farineuse (BF15 ou Bintje)", qty: 1, unit: "kg", optional: false },
      { food: "Beurre frais de qualité", qty: 150, unit: "g", optional: false },
      { food: "Lait entier chaud", qty: 200, unit: "ml", optional: false },
      { food: "Sel fin", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc fraîchement moulu", qty: 1, unit: "pincée", optional: false },
      { food: "Noix de muscade fraîche râpée", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Éplucher les pommes de terre et les couper en morceaux réguliers. Les cuire dans de l'eau froide salée jusqu'à ébullition, puis 25 minutes à frémissement.",
      "Égoutter les pommes de terre et les remettre dans la casserole sur feu très doux 2 minutes pour les sécher.",
      "Passer les pommes de terre chaudes au moulin à légumes (grille fine) ou au presse-purée. Ne jamais utiliser de mixeur pour éviter la texture gluante.",
      "Incorporer le beurre froid coupé en dés, morceau par morceau, en fouettant vigoureusement avec une spatule en bois.",
      "Verser progressivement le lait chaud tout en continuant à travailler la purée.",
      "Assaisonner de sel, poivre blanc et muscade fraîche.",
      "La purée doit être soyeuse, brillante et tomber du fouet en ruban. Servir immédiatement.",
    ],
    nutrition: { calories: 380, protein: 5, carbs: 42, fat: 22, fiber: 4 },
    tips: "La purée Robuchon est célèbre pour sa proportion de beurre généreuse. La qualité du beurre est déterminante. Ne jamais utiliser de crème aigre ou fermentée pour la purée histamine.",
    isCustom: false
  },
  {
    id: "fr-legumes-vapeur-beurre-herbes",
    name: "Légumes de Printemps à la Vapeur et Beurre aux Herbes",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Haricots verts très fins", qty: 200, unit: "g", optional: false },
      { food: "Asperges vertes", qty: 200, unit: "g", optional: false },
      { food: "Petits pois frais écossés", qty: 150, unit: "g", optional: false },
      { food: "Carottes nouvelles", qty: 4, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 60, unit: "g", optional: false },
      { food: "Persil plat frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Ciboulette fraîche", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Cerfeuil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préparer tous les légumes : équeueter les haricots verts, éplucher les asperges, éplucher et brosser les carottes nouvelles.",
      "Cuire les légumes séparément à la vapeur en respectant les temps : carottes 12 minutes, asperges 8 minutes, haricots verts 7 minutes, petits pois 5 minutes.",
      "Préparer le beurre aux herbes : faire fondre doucement le beurre dans une petite casserole jusqu'à ce qu'il soit mousseux.",
      "Hors du feu, incorporer le persil, la ciboulette et le cerfeuil fraîchement ciselés. Saler et poivrer.",
      "Disposer harmonieusement les légumes vapeur dans un plat de service chaud.",
      "Verser le beurre aux herbes sur les légumes et servir immédiatement."
    ],
    nutrition: { calories: 180, protein: 5, carbs: 14, fat: 12, fiber: 6 },
    tips: "La cuisson à la vapeur préserve les nutriments et les couleurs vives des légumes. Le beurre aux herbes fraîches est la sauce française par excellence pour accompagner les légumes primeurs.",
    isCustom: false
  },
  {
    id: "fr-crepes-classiques-beurre",
    name: "Crêpes Classiques au Beurre Breton",
    category: "plat",
    mealType: ["petitDejeuner", "dejeuner"],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Farine de blé T45", qty: 250, unit: "g", optional: false },
      { food: "Œufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Lait entier frais", qty: 500, unit: "ml", optional: false },
      { food: "Beurre frais fondu", qty: 40, unit: "g", optional: false },
      { food: "Sel fin", qty: 1, unit: "pincée", optional: false },
      { food: "Sucre en poudre", qty: 20, unit: "g", optional: true },
      { food: "Beurre frais salé (pour la cuisson et dégustation)", qty: 50, unit: "g", optional: false }
    ],
    steps: [
      "Mettre la farine dans un saladier et creuser un puits. Casser les œufs au centre et mélanger.",
      "Incorporer progressivement la moitié du lait en fouettant pour éviter les grumeaux.",
      "Ajouter le reste du lait, le beurre fondu tiède, le sel et le sucre. La pâte doit être lisse et fluide.",
      "Laisser reposer la pâte 30 minutes à température ambiante (étape essentielle).",
      "Chauffer une crêpière légèrement beurrée à feu moyen-vif. Verser une louche de pâte et faire pivoter la crêpière pour étaler uniformément.",
      "Cuire 1 minute jusqu'à ce que les bords se décollent. Retourner et cuire 30 secondes.",
      "Empiler les crêpes en les maintenant au chaud dans un torchon propre.",
      "Servir avec du beurre frais, de la confiture maison (si tolérée) ou du miel."
    ],
    nutrition: { calories: 280, protein: 9, carbs: 38, fat: 10, fiber: 1 },
    tips: "La pâte à crêpes doit reposer pour que le gluten se détende et les crêpes soient plus légères. Si des grumeaux persistent, passer la pâte au chinois. Le beurre breton salé est la garniture traditionnelle.",
    isCustom: false
  },
  {
    id: "fr-galettes-sarrasin-classiques",
    name: "Galettes de Sarrasin Bretonnes au Beurre et Œuf",
    category: "plat",
    mealType: ["petitDejeuner", "dejeuner"],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Farine de sarrasin (blé noir)", qty: 250, unit: "g", optional: false },
      { food: "Eau froide", qty: 500, unit: "ml", optional: false },
      { food: "Sel de Guérande", qty: 1, unit: "c. à café", optional: false },
      { food: "Œufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Beurre frais salé", qty: 60, unit: "g", optional: false },
      { food: "Emmental râpé frais du jour (quantité minimale)", qty: 40, unit: "g", optional: true }
    ],
    steps: [
      "Mélanger la farine de sarrasin avec le sel. Incorporer progressivement l'eau froide en fouettant vigoureusement pour obtenir une pâte lisse et sans grumeaux.",
      "Laisser reposer la pâte au minimum 1 heure au réfrigérateur.",
      "Chauffer une crêpière bien chaude. La huiler légèrement avec un morceau de papier absorbant imprégné de beurre.",
      "Verser une louche de pâte et étaler rapidement avec la râteau. La galette doit être fine.",
      "Cuire 2 minutes à feu moyen jusqu'à ce que les bords se soulèvent. Casser un œuf frais au centre.",
      "Parsemer de quelques copeaux de beurre frais. Replier les quatre bords pour former un carré.",
      "Servir immédiatement sur assiette chaude. Accompagner d'une salade verte.",
    ],
    nutrition: { calories: 320, protein: 14, carbs: 36, fat: 14, fiber: 4 },
    tips: "La galette complète est un repas à part entière. Le sarrasin est naturellement sans gluten et très bien toléré. Si l'emmental est utilisé, le choisir très frais du jour, en petite quantité, car les fromages râpés industriels sont plus riches en histamine.",
    isCustom: false
  },
  {
    id: "fr-pain-perdu-beurre-vanille",
    name: "Pain Perdu au Beurre et à la Vanille",
    category: "plat",
    mealType: ["petitDejeuner"],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Pain de mie sans conservateur (du jour ou de la veille)", qty: 6, unit: "tranches épaisses", optional: false },
      { food: "Œufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Lait entier frais", qty: 150, unit: "ml", optional: false },
      { food: "Crème fraîche liquide très fraîche", qty: 50, unit: "ml", optional: false },
      { food: "Sucre en poudre", qty: 30, unit: "g", optional: false },
      { food: "Gousse de vanille", qty: 0.5, unit: "pièce", optional: false },
      { food: "Beurre frais", qty: 40, unit: "g", optional: false }
    ],
    steps: [
      "Gratter les graines de la demi-gousse de vanille. Les mélanger avec les œufs, le lait, la crème et le sucre dans une assiette creuse.",
      "Tremper les tranches de pain de mie dans le mélange pendant 2 minutes de chaque côté, pour qu'elles soient bien imprégnées.",
      "Dans une poêle antiadhésive, faire fondre le beurre à feu moyen.",
      "Déposer les tranches de pain imbibées et cuire 3 à 4 minutes de chaque côté jusqu'à une belle coloration dorée.",
      "Le pain perdu doit être caramélisé en surface et moelleux à cœur.",
      "Saupoudrer de sucre glace et servir immédiatement.",
      "Accompagner d'une compote de pommes maison ou d'un filet de miel."
    ],
    nutrition: { calories: 380, protein: 12, carbs: 46, fat: 16, fiber: 1 },
    tips: "Utiliser du pain de mie sans levure chimique ni conservateur (E282, E281). Un pain fait maison ou de boulangerie artisanale est idéal. Ne jamais utiliser de pain de la veille fermenté avec de la levure de bière.",
    isCustom: false
  },
  {
    id: "fr-soupe-oignon-gratinee-adaptee",
    name: "Soupe à l'Oignon Gratinée (Sans Gruyère Affiné)",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 60,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Oignons", qty: 1, unit: "kg", optional: false },
      { food: "Beurre frais", qty: 50, unit: "g", optional: false },
      { food: "Bouillon de bœuf maison très clair", qty: 1.2, unit: "litre", optional: false },
      { food: "Pain de campagne (du jour)", qty: 4, unit: "tranches épaisses", optional: false },
      { food: "Mozzarella fraîche bien égouttée", qty: 200, unit: "g", optional: false },
      { food: "Farine", qty: 20, unit: "g", optional: false },
      { food: "Thym frais", qty: 3, unit: "branches", optional: false },
      { food: "Laurier frais", qty: 2, unit: "feuilles", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Éplucher et émincer finement tous les oignons en rondelles.",
      "Dans une grande casserole à fond épais, faire fondre le beurre. Y faire suer les oignons à feu très doux pendant 30 à 40 minutes, en remuant régulièrement, jusqu'à caramélisation dorée.",
      "Singer les oignons avec la farine et cuire 2 minutes.",
      "Verser le bouillon de bœuf chaud. Ajouter le thym et le laurier. Saler et poivrer.",
      "Faire mijoter 20 minutes à feu doux.",
      "Faire griller les tranches de pain au four. Préchauffer le gril du four.",
      "Verser la soupe dans des bols allant au four. Déposer une tranche de pain grillé sur chaque bol.",
      "Recouvrir de mozzarella fraîche émiettée. Passer sous le gril 5 minutes jusqu'à dorure. Servir immédiatement."
    ],
    nutrition: { calories: 340, protein: 16, carbs: 38, fat: 14, fiber: 5 },
    tips: "La soupe à l'oignon gratinée française utilise traditionnellement du gruyère ou comté affiné. La mozzarella fraîche très bien égouttée gratine parfaitement et reste tolérée en alimentation pauvre en histamine.",
    isCustom: false
  },
  {
    id: "classic-mousse-vanille-legere",
    name: "Mousse à la Vanille Légère aux Blancs d'Œufs",
    category: "dessert",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Crème fraîche liquide entière très fraîche (bien froide)", qty: 300, unit: "ml", optional: false },
      { food: "Blancs d'œufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Sucre glace", qty: 60, unit: "g", optional: false },
      { food: "Gousses de vanille", qty: 2, unit: "pièces", optional: false },
      { food: "Sucre en poudre", qty: 20, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Fendre les gousses de vanille et gratter les graines. Mélanger les graines avec la crème fraîche froide. Réfrigérer 30 minutes pour infuser.",
      "Monter la crème bien froide en chantilly ferme. Incorporer le sucre glace en continuant à fouetter.",
      "Dans un autre bol bien propre et froid, monter les blancs d'œufs en neige ferme avec la pincée de sel, puis incorporer le sucre en poudre pour former une meringue souple.",
      "Incorporer délicatement les blancs montés à la chantilly vanillée en soulevant la masse de bas en haut pour ne pas les casser.",
      "Répartir dans des verrines ou coupes à dessert.",
      "Réfrigérer au minimum 2 heures avant de servir.",
      "Décorer d'une pointe de crème chantilly et de quelques graines de vanille au moment du service."
    ],
    nutrition: { calories: 280, protein: 5, carbs: 20, fat: 20, fiber: 0 },
    tips: "Cette mousse légère remplace la mousse au chocolat (interdite). La vanille Bourbon de Madagascar est la plus aromatique. La mousse se conserve 24 heures au réfrigérateur, mais est meilleure fraîchement préparée.",
    isCustom: false
  },
  {
    id: "fr-poireaux-vinaigrette-herbes",
    name: "Poireaux Tièdes en Vinaigrette d'Herbes (Sans Vinaigre)",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poireaux fins", qty: 8, unit: "pièces", optional: false },
      { food: "Huile d'olive extra-vierge de première pression", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Persil plat frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Ciboulette fraîche", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Cerfeuil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Estragon frais", qty: 2, unit: "branches", optional: false },
      { food: "Sel", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Poivre noir fraîchement moulu", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Nettoyer soigneusement les poireaux. Garder 5 cm de vert tendre. Les couper en deux dans la longueur.",
      "Cuire les poireaux à la vapeur ou dans de l'eau bouillante salée pendant 15 à 18 minutes, jusqu'à ce qu'ils soient tendres mais encore légèrement fermes.",
      "Égoutter délicatement et laisser tiédir sur un linge propre.",
      "Préparer la vinaigrette aux herbes : hacher finement le persil, la ciboulette, le cerfeuil et l'estragon.",
      "Mélanger les herbes avec l'huile d'olive. Saler et poivrer. Cette huile aux herbes remplace la vinaigrette classique.",
      "Disposer les poireaux tièdes dans un plat de service. Napper généreusement d'huile aux herbes.",
      "Servir tiède ou à température ambiante."
    ],
    nutrition: { calories: 160, protein: 3, carbs: 10, fat: 12, fiber: 4 },
    tips: "Les poireaux vinaigrette sont une entrée bistro emblématique. Sans vinaigre ni moutarde, l'huile aux herbes fraîches remplace avantageusement la sauce. L'estragon frais apporte une légère note anisée.",
    isCustom: false
  },
  {
    id: "fr-artichauts-beurre-fondu",
    name: "Artichauts Cuits au Beurre Fondu aux Herbes",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 45,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Artichauts bretons frais", qty: 2, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 80, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Persil plat frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Estragon frais", qty: 2, unit: "branches", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Casser les queues des artichauts en tirant vers le bas pour retirer les fils. Couper le bout des feuilles avec des ciseaux.",
      "Faire bouillir un grand volume d'eau salée. Plonger les artichauts et cuire 40 à 45 minutes selon leur taille.",
      "Vérifier la cuisson en tirant une feuille du bas : elle doit se détacher facilement.",
      "Égoutter les artichauts tête en bas pendant 5 minutes.",
      "Préparer le beurre fondu aux herbes : faire fondre doucement le beurre jusqu'à ce qu'il soit clarifié mais pas noisette. Ajouter les herbes fraîches ciselées. Saler et poivrer.",
      "Servir les artichauts chauds avec le beurre aux herbes dans une petite coupelle.",
      "Manger feuille par feuille en trempant dans le beurre. Gratter la chair avec les dents."
    ],
    nutrition: { calories: 280, protein: 5, carbs: 14, fat: 22, fiber: 6 },
    tips: "L'artichaut est naturellement riche en fibres prébiotiques et très bien toléré. Le beurre fondu aux herbes fraîches remplace la classique vinaigrette ou la mayonnaise, interdites en alimentation pauvre en histamine.",
    isCustom: false
  },
  {
    id: "bistro-riz-pilaf-beurre-herbes",
    name: "Riz Pilaf au Beurre et Herbes Fraîches",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 20,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz long grain basmati", qty: 300, unit: "g", optional: false },
      { food: "Beurre frais", qty: 40, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Bouillon de légumes ou de poulet maison", qty: 600, unit: "ml", optional: false },
      { food: "Thym frais", qty: 2, unit: "branches", optional: false },
      { food: "Laurier frais", qty: 1, unit: "feuille", optional: false },
      { food: "Persil plat frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C. Émincer finement l'oignon.",
      "Dans une casserole allant au four, faire fondre la moitié du beurre à feu moyen. Y faire suer l'oignon sans le colorer, 3 minutes.",
      "Ajouter le riz et l'enrober de beurre en remuant 2 minutes jusqu'à ce qu'il devienne translucide.",
      "Verser le bouillon chaud en une fois (2 fois le volume de riz). Ajouter le thym et le laurier. Saler.",
      "Porter à ébullition, couvrir hermétiquement et enfourner 17 minutes.",
      "À la sortie du four, laisser reposer 5 minutes couvercle fermé.",
      "Aérer le riz avec une fourchette. Incorporer le reste du beurre en petits dés.",
      "Parsemer de persil frais haché et servir."
    ],
    nutrition: { calories: 280, protein: 5, carbs: 48, fat: 8, fiber: 1 },
    tips: "Le riz pilaf est la garniture classique de la blanquette de veau et des fricassées. La cuisson au four garantit un riz parfaitement cuit grain par grain. Utiliser du bouillon maison, jamais des cubes du commerce (souvent riches en additifs).",
    isCustom: false
  }
];
