const RECIPES_BATCH_6 = [
  {
    id: "veg-zucchini-gratin",
    name: "Gratin de courgettes à la ricotta",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Courgettes", qty: 800, unit: "g", optional: false },
      { food: "Ricotta", qty: 250, unit: "g", optional: false },
      { food: "Mozzarella fraîche", qty: 150, unit: "g", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false },
      { food: "Herbes de Provence", qty: 1, unit: "c. à café", optional: true }
    ],
    steps: [
      "Préchauffer le four à 200°C. Laver et couper les courgettes en rondelles de 5 mm.",
      "Faire revenir l'ail émincé dans l'huile d'olive à feu moyen pendant 1 minute, puis ajouter les courgettes et faire sauter 5 minutes.",
      "Dans un plat à gratin légèrement huilé, déposer la moitié des courgettes en couche uniforme.",
      "Répartir la ricotta émiettée par-dessus, saler, poivrer et ajouter les herbes de Provence.",
      "Ajouter le reste des courgettes, puis disposer la mozzarella en tranches sur le dessus.",
      "Enfourner 25 à 30 minutes jusqu'à ce que le dessus soit bien doré. Laisser reposer 5 minutes avant de servir."
    ],
    nutrition: { calories: 310, protein: 16, carbs: 12, fat: 22, fiber: 3 },
    tips: "Choisissez des courgettes petites et fermes pour éviter qu'elles rendent trop d'eau. Égouttez bien la ricotta si elle est trop humide.",
    isCustom: false
  },
  {
    id: "veg-stuffed-peppers",
    name: "Poivrons farcis au quinoa et chèvre frais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poivrons verts ou jaunes", qty: 4, unit: "pièces", optional: false },
      { food: "Quinoa", qty: 200, unit: "g", optional: false },
      { food: "Chèvre frais", qty: 150, unit: "g", optional: false },
      { food: "Pois chiches rincés", qty: 200, unit: "g", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Persil frais", qty: 20, unit: "g", optional: true },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C. Cuire le quinoa dans 400 ml d'eau salée pendant 15 minutes jusqu'à absorption complète.",
      "Couper le chapeau des poivrons et retirer les graines. Badigeonner l'intérieur d'huile d'olive.",
      "Éplucher et râper les carottes. Les mélanger avec le quinoa cuit, les pois chiches et le persil haché.",
      "Émietter le chèvre frais dans la farce, saler et bien mélanger.",
      "Farcir les poivrons généreusement et remettre le chapeau. Disposer dans un plat allant au four avec un fond d'eau.",
      "Cuire 35 à 40 minutes jusqu'à ce que les poivrons soient tendres. Servir chaud."
    ],
    nutrition: { calories: 390, protein: 18, carbs: 48, fat: 14, fiber: 9 },
    tips: "Les poivrons jaunes sont moins amers que les verts. Rincez bien les pois chiches en conserve pour réduire leur teneur en histamine libérée.",
    isCustom: false
  },
  {
    id: "veg-sweet-potato-curry",
    name: "Curry de patate douce et lentilles corail",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Patate douce", qty: 600, unit: "g", optional: false },
      { food: "Lentilles corail", qty: 200, unit: "g", optional: false },
      { food: "Lait de coco", qty: 400, unit: "ml", optional: false },
      { food: "Bouillon de légumes maison", qty: 500, unit: "ml", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Gingembre frais", qty: 2, unit: "cm", optional: false },
      { food: "Curcuma", qty: 1, unit: "c. à café", optional: false },
      { food: "Cumin", qty: 1, unit: "c. à café", optional: false },
      { food: "Huile de coco", qty: 1, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Éplucher et couper la patate douce en cubes de 2 cm. Émincer l'oignon et râper le gingembre.",
      "Faire chauffer l'huile de coco dans une grande casserole. Faire revenir l'oignon 5 minutes jusqu'à transparence.",
      "Ajouter le gingembre, le curcuma et le cumin. Mélanger et cuire 1 minute pour libérer les arômes.",
      "Incorporer les lentilles rincées, les cubes de patate douce, le lait de coco et le bouillon.",
      "Porter à ébullition puis réduire le feu. Couvrir et laisser mijoter 25 minutes en remuant de temps en temps.",
      "Vérifier la cuisson, ajuster l'assaisonnement et servir avec du riz basmati."
    ],
    nutrition: { calories: 420, protein: 16, carbs: 62, fat: 14, fiber: 12 },
    tips: "Les lentilles corail cuisent vite et s'effacent dans la sauce pour l'épaissir naturellement. Préparez votre bouillon maison sans levure pour rester faible en histamine.",
    isCustom: false
  },
  {
    id: "veg-cauliflower-steak",
    name: "Steaks de chou-fleur rôtis au beurre et herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Chou-fleur", qty: 1, unit: "pièce", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Thym frais", qty: 4, unit: "brins", optional: false },
      { food: "Romarin", qty: 2, unit: "brins", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 220°C. Retirer les feuilles extérieures du chou-fleur et couper 2 steaks épais de 2 cm au centre.",
      "Mélanger l'huile d'olive avec l'ail écrasé, le sel et le poivre. Badigeonner les deux faces de chaque steak.",
      "Chauffer une poêle allant au four à feu vif. Saisir les steaks 3 minutes par face jusqu'à coloration.",
      "Ajouter le beurre, le thym et le romarin dans la poêle. Arroser les steaks avec le beurre fondu.",
      "Transférer la poêle au four et cuire 15 minutes en arrosant à mi-cuisson.",
      "Servir immédiatement avec une purée de pommes de terre ou un gratin de légumes."
    ],
    nutrition: { calories: 260, protein: 7, carbs: 18, fat: 18, fiber: 6 },
    tips: "Gardez les chutes de chou-fleur pour faire une soupe. Le beurre noisette apporte une saveur incomparable, mais veillez à ne pas le brûler.",
    isCustom: false
  },
  {
    id: "veg-leek-tart",
    name: "Tarte aux poireaux et fromage blanc",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte brisée", qty: 1, unit: "rouleau", optional: false },
      { food: "Poireaux", qty: 600, unit: "g", optional: false },
      { food: "Fromage blanc", qty: 300, unit: "g", optional: false },
      { food: "Oeufs", qty: 3, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse", qty: 100, unit: "ml", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C. Foncer un moule à tarte avec la pâte brisée et piquer le fond à la fourchette.",
      "Laver et émincer les poireaux en rondelles. Les faire fondre dans le beurre à feu doux 10 minutes avec une pincée de sel.",
      "Dans un saladier, battre les oeufs avec le fromage blanc et la crème fraîche. Ajouter la muscade, saler.",
      "Répartir les poireaux refroidis sur le fond de tarte. Verser l'appareil par-dessus uniformément.",
      "Enfourner 35 à 40 minutes jusqu'à ce que la tarte soit bien dorée et ferme au centre.",
      "Laisser tiédir 10 minutes avant de démouler et de couper. Servir tiède avec une salade verte."
    ],
    nutrition: { calories: 340, protein: 14, carbs: 28, fat: 19, fiber: 3 },
    tips: "Les oeufs peuvent augmenter légèrement le score d'histamine. Consommez la tarte fraîche le jour même pour limiter la formation d'histamine.",
    isCustom: false
  },
  {
    id: "veggie-quinoa-bowl",
    name: "Buddha bowl quinoa, pois chiches et légumes rôtis",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Quinoa", qty: 180, unit: "g", optional: false },
      { food: "Pois chiches rincés", qty: 240, unit: "g", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Patate douce", qty: 200, unit: "g", optional: false },
      { food: "Brocoli", qty: 200, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Curcuma", qty: 1, unit: "c. à café", optional: false },
      { food: "Paprika doux", qty: 1, unit: "c. à café", optional: false },
      { food: "Tahini", qty: 2, unit: "c. à soupe", optional: true }
    ],
    steps: [
      "Préchauffer le four à 200°C. Cuire le quinoa dans 360 ml d'eau salée pendant 15 minutes.",
      "Couper carottes et patate douce en cubes. Les mélanger avec les pois chiches, l'huile, le curcuma et le paprika.",
      "Étaler sur une plaque de cuisson et rôtir 25 minutes en retournant à mi-cuisson.",
      "Blanchir les sommités de brocoli 3 minutes dans l'eau bouillante, puis égoutter.",
      "Assembler les bols : base de quinoa, légumes rôtis, brocoli vapeur.",
      "Arroser d'un filet d'huile d'olive ou de tahini dilué dans l'eau. Servir tiède."
    ],
    nutrition: { calories: 520, protein: 22, carbs: 74, fat: 16, fiber: 14 },
    tips: "Rincez toujours les pois chiches en conserve sous l'eau froide pendant 1 minute pour réduire leur teneur en histamine libérée.",
    isCustom: false
  },
  {
    id: "veggie-millet-bowl",
    name: "Bol de millet aux haricots blancs et légumes d'hiver",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Millet", qty: 160, unit: "g", optional: false },
      { food: "Haricots blancs rincés", qty: 240, unit: "g", optional: false },
      { food: "Courge butternut", qty: 300, unit: "g", optional: false },
      { food: "Fenouil", qty: 1, unit: "bulbe", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Cumin", qty: 1, unit: "c. à café", optional: false },
      { food: "Persil", qty: 15, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Faire griller le millet à sec dans une casserole 2 minutes, puis ajouter 320 ml d'eau bouillante salée. Couvrir et cuire 20 minutes.",
      "Éplucher et couper la courge en cubes. Émincer le fenouil et l'oignon.",
      "Faire chauffer l'huile dans une poêle et faire revenir l'oignon 3 minutes. Ajouter le fenouil et cuire encore 3 minutes.",
      "Incorporer la courge et le cumin, couvrir et cuire 15 minutes à feu moyen jusqu'à tendreté.",
      "Ajouter les haricots blancs rincés, mélanger et chauffer 3 minutes. Ajuster l'assaisonnement.",
      "Servir le millet en base avec les légumes par-dessus. Parsemer de persil haché."
    ],
    nutrition: { calories: 460, protein: 18, carbs: 70, fat: 12, fiber: 16 },
    tips: "Le millet grillé à sec développe un arôme de noisette agréable. C'est une céréale très bien tolérée par les personnes sensibles à l'histamine.",
    isCustom: false
  },
  {
    id: "veggie-lentil-bowl",
    name: "Bol de lentilles vertes, carottes et feta fraîche",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Lentilles vertes", qty: 200, unit: "g", optional: false },
      { food: "Carottes", qty: 3, unit: "pièces", optional: false },
      { food: "Feta fraîche", qty: 100, unit: "g", optional: false },
      { food: "Chou vert", qty: 100, unit: "g", optional: false },
      { food: "Oignon rouge", qty: 1, unit: "pièce", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Coriandre fraîche", qty: 10, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Rincer les lentilles vertes. Les cuire dans 3 fois leur volume d'eau salée pendant 20 à 25 minutes jusqu'à tendreté.",
      "Éplucher et couper les carottes en bâtonnets. Les rôtir 20 minutes au four à 200°C avec 1 c. à soupe d'huile.",
      "Émincer l'oignon rouge et faire revenir à feu doux 5 minutes dans le reste de l'huile.",
      "Émincer finement le chou et le masser 2 minutes avec une pincée de sel pour l'attendrir.",
      "Égoutter les lentilles. Assembler les bols : lentilles, chou massé, carottes rôties, oignon.",
      "Émietter la feta fraîche par-dessus. Parsemer de coriandre et arroser d'huile d'olive."
    ],
    nutrition: { calories: 480, protein: 24, carbs: 58, fat: 18, fiber: 18 },
    tips: "Choisissez de la feta fraîche en saumure légère. Évitez la feta affinée qui contient plus d'histamine. Rincez-la sous l'eau avant utilisation.",
    isCustom: false
  },
  {
    id: "plant-buckwheat-bowl",
    name: "Bol de sarrasin, légumes sautés et halloumi grillé",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Sarrasin (grains)", qty: 160, unit: "g", optional: false },
      { food: "Halloumi frais", qty: 200, unit: "g", optional: false },
      { food: "Haricots verts", qty: 200, unit: "g", optional: false },
      { food: "Courgettes", qty: 2, unit: "pièces", optional: false },
      { food: "Poivron jaune", qty: 1, unit: "pièce", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Aneth frais", qty: 10, unit: "g", optional: true }
    ],
    steps: [
      "Rincer le sarrasin. Le cuire dans 320 ml d'eau salée portée à ébullition. Couvrir et cuire 12 à 15 minutes à feu doux.",
      "Couper le halloumi en tranches de 1 cm. Griller à la poêle sèche 2 minutes par face jusqu'à coloration dorée.",
      "Équeuter les haricots verts et les blanchir 4 minutes. Égoutter et réserver.",
      "Couper courgettes et poivron en morceaux. Faire sauter avec l'ail émincé dans l'huile 8 minutes à feu vif.",
      "Incorporer les haricots verts aux légumes sautés. Assaisonner.",
      "Assembler les bols avec le sarrasin en base, les légumes et le halloumi grillé. Parsemer d'aneth."
    ],
    nutrition: { calories: 540, protein: 28, carbs: 52, fat: 24, fiber: 8 },
    tips: "Le halloumi frais non affiné est bien toléré. Cherchez-le en épicerie fine ou dans les magasins spécialisés moyen-orientaux. Évitez le halloumi sous vide vieilli.",
    isCustom: false
  },
  {
    id: "veg-frittata-zucchini",
    name: "Frittata courgettes et mozzarella fraîche",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Oeufs", qty: 8, unit: "pièces", optional: false },
      { food: "Courgettes", qty: 400, unit: "g", optional: false },
      { food: "Mozzarella fraîche", qty: 150, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Basilic frais", qty: 10, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C. Émincer l'oignon et couper les courgettes en rondelles fines.",
      "Dans une poêle allant au four, faire revenir l'oignon dans l'huile 3 minutes, puis ajouter les courgettes 5 minutes.",
      "Battre les oeufs en omelette avec sel et poivre. Verser sur les légumes dans la poêle.",
      "Déchirer la mozzarella et la répartir sur la surface de la frittata.",
      "Faire cuire 3 minutes sur le feu puis transférer au four 10 à 12 minutes jusqu'à ce que la frittata soit ferme.",
      "Sortir du four, laisser reposer 5 minutes. Parsemer de basilic et servir coupée en parts."
    ],
    nutrition: { calories: 280, protein: 22, carbs: 6, fat: 19, fiber: 2 },
    tips: "La frittata doit être consommée immédiatement après cuisson. Ne réchauffez pas les oeufs cuits le lendemain, le taux d'histamine augmente rapidement.",
    isCustom: false
  },
  {
    id: "veg-quiche-brocoli",
    name: "Quiche brocoli et chèvre frais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte brisée", qty: 1, unit: "rouleau", optional: false },
      { food: "Brocoli", qty: 400, unit: "g", optional: false },
      { food: "Chèvre frais", qty: 200, unit: "g", optional: false },
      { food: "Oeufs", qty: 4, unit: "pièces", optional: false },
      { food: "Crème fraîche légère", qty: 200, unit: "ml", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Beurre", qty: 15, unit: "g", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Préchauffer le four à 180°C. Foncer un moule à tarte avec la pâte brisée. Piquer le fond et précuire 10 minutes à blanc.",
      "Couper le brocoli en petites sommités et blanchir 3 minutes. Égoutter et bien sécher.",
      "Émincer l'oignon et le faire revenir dans le beurre 5 minutes jusqu'à transparence.",
      "Battre les oeufs avec la crème fraîche, la muscade et le sel. Incorporer l'oignon cuit.",
      "Répartir le brocoli et le chèvre émietté sur le fond de tarte. Verser l'appareil à oeufs.",
      "Cuire 30 à 35 minutes jusqu'à ce que la quiche soit bien dorée et ferme. Servir tiède."
    ],
    nutrition: { calories: 360, protein: 16, carbs: 26, fat: 22, fiber: 3 },
    tips: "Séchez bien le brocoli blanchi pour éviter de détremper la pâte. Le chèvre frais en bûche jeune non affiné est mieux toléré que les fromages affinés.",
    isCustom: false
  },
  {
    id: "veg-egg-asparagus",
    name: "Oeufs cocotte aux asperges et crème fraîche",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Oeufs", qty: 4, unit: "pièces", optional: false },
      { food: "Asperges vertes", qty: 300, unit: "g", optional: false },
      { food: "Crème fraîche épaisse", qty: 100, unit: "ml", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 10, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C avec un bain-marie. Beurrer 2 ramequins.",
      "Casser et retirer la partie dure des asperges. Les couper en tronçons de 3 cm et les blanchir 3 minutes.",
      "Répartir les asperges dans les ramequins beurrés. Verser 2 c. à soupe de crème fraîche sur les asperges.",
      "Casser délicatement 2 oeufs par ramequin sans crever les jaunes. Saler et poivrer.",
      "Placer les ramequins dans le bain-marie et cuire au four 10 à 12 minutes. Le blanc doit être pris mais le jaune encore coulant.",
      "Servir immédiatement parsemé de ciboulette ciselée avec des mouillettes de pain grillé."
    ],
    nutrition: { calories: 240, protein: 14, carbs: 6, fat: 18, fiber: 3 },
    tips: "La cuisson en bain-marie permet une cuisson douce et homogène. Consommez immédiatement à la sortie du four pour limiter la production d'histamine dans les oeufs.",
    isCustom: false
  },
  {
    id: "veg-omelette-herbs",
    name: "Omelette aux fines herbes et fromage blanc",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Oeufs", qty: 3, unit: "pièces", optional: false },
      { food: "Fromage blanc", qty: 60, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 10, unit: "g", optional: false },
      { food: "Persil frais", qty: 5, unit: "g", optional: false },
      { food: "Estragon frais", qty: 5, unit: "g", optional: true },
      { food: "Beurre", qty: 15, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Ciseler finement la ciboulette, le persil et l'estragon. Mélanger avec le fromage blanc, le sel et le poivre.",
      "Casser les oeufs dans un bol, battre avec une fourchette jusqu'à obtenir un mélange homogène. Saler légèrement.",
      "Faire fondre le beurre dans une poêle antiadhésive à feu moyen-vif jusqu'à ce qu'il mousse.",
      "Verser les oeufs battus d'un coup. À l'aide d'une spatule, ramener les bords vers le centre en inclinant la poêle.",
      "Quand l'omelette est encore baveuse au centre, déposer la garniture au fromage blanc sur une moitié.",
      "Replier l'omelette en deux et faire glisser dans l'assiette. Servir sans attendre."
    ],
    nutrition: { calories: 310, protein: 24, carbs: 4, fat: 22, fiber: 0 },
    tips: "Préparez et mangez l'omelette immédiatement. Les oeufs refroidis et réchauffés développent des taux d'histamine élevés. La fraîcheur des herbes est essentielle.",
    isCustom: false
  },
  {
    id: "veg-pasta-cream-leek",
    name: "Pâtes à la crème de poireaux et mascarpone",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pâtes tagliatelles ou penne", qty: 400, unit: "g", optional: false },
      { food: "Poireaux", qty: 400, unit: "g", optional: false },
      { food: "Mascarpone", qty: 200, unit: "g", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Bouillon de légumes maison", qty: 150, unit: "ml", optional: false },
      { food: "Parmesan fraîchement râpé", qty: 50, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Faire cuire les pâtes al dente selon les instructions du paquet. Réserver 100 ml d'eau de cuisson.",
      "Laver et émincer les poireaux en fines rondelles. Faire fondre dans le beurre à feu doux 8 minutes.",
      "Ajouter le bouillon de légumes aux poireaux fondus et laisser réduire 3 minutes.",
      "Incorporer le mascarpone, remuer jusqu'à obtenir une sauce lisse et crémeuse. Assaisonner.",
      "Égoutter les pâtes et les ajouter à la sauce. Mélanger en ajoutant un peu d'eau de cuisson si nécessaire.",
      "Servir immédiatement avec le parmesan râpé et un tour de moulin à poivre."
    ],
    nutrition: { calories: 580, protein: 18, carbs: 72, fat: 26, fiber: 5 },
    tips: "Utilisez un bouillon de légumes maison ou un bouillon en poudre sans levure de bière ni extraits fermentés pour rester bas en histamine.",
    isCustom: false
  },
  {
    id: "veg-pasta-pesto-zucchini",
    name: "Pâtes au pesto de courgette et basilic frais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Spaghetti", qty: 400, unit: "g", optional: false },
      { food: "Courgettes", qty: 300, unit: "g", optional: false },
      { food: "Basilic frais", qty: 40, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 80, unit: "ml", optional: false },
      { food: "Ricotta", qty: 150, unit: "g", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Graines de courge", qty: 40, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Cuire les pâtes al dente. Réserver 150 ml d'eau de cuisson avant d'égoutter.",
      "Couper une courgette en petits dés et la faire sauter dans 1 c. à soupe d'huile 5 minutes.",
      "Couper l'autre courgette grossièrement. La mixer avec le basilic, l'ail, l'huile d'olive restante et la ricotta jusqu'à obtenir une sauce lisse.",
      "Assaisonner le pesto de courgette avec du sel. Ajouter de l'eau de cuisson pour ajuster la consistance.",
      "Mélanger les pâtes égouttées avec le pesto et les dés de courgette sautés.",
      "Servir aussitôt avec les graines de courge grillées à sec et quelques feuilles de basilic frais."
    ],
    nutrition: { calories: 540, protein: 18, carbs: 68, fat: 24, fiber: 5 },
    tips: "Ce pesto sans pignons ni parmesan affiné est idéal pour l'intolérance à l'histamine. La ricotta remplace avantageusement le fromage affiné.",
    isCustom: false
  },
  {
    id: "veg-pasta-butter-sage",
    name: "Pâtes au beurre sauge et ricotta fraîche",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Tagliatelles fraîches", qty: 300, unit: "g", optional: false },
      { food: "Beurre", qty: 60, unit: "g", optional: false },
      { food: "Sauge fraîche", qty: 10, unit: "feuilles", optional: false },
      { food: "Ricotta", qty: 200, unit: "g", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre noir", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Faire cuire les pâtes fraîches dans une grande casserole d'eau bouillante salée 2 à 3 minutes. Réserver 100 ml d'eau de cuisson.",
      "Pendant ce temps, faire fondre le beurre à feu moyen dans une grande poêle. Ajouter la gousse d'ail et les feuilles de sauge entières.",
      "Laisser le beurre devenir légèrement noisette en remuant environ 2 minutes. Retirer l'ail.",
      "Ajouter les pâtes égouttées directement dans la poêle et mélanger pour bien les enrober.",
      "Incorporer la ricotta à la cuillère et un peu d'eau de cuisson pour créer une sauce crémeuse.",
      "Poivrer généreusement, ajuster le sel et servir immédiatement."
    ],
    nutrition: { calories: 620, protein: 22, carbs: 64, fat: 32, fiber: 3 },
    tips: "Choisissez des pâtes fraîches artisanales sans conservateurs. Le beurre noisette à la sauge est une sauce classique italienne naturellement pauvre en histamine.",
    isCustom: false
  },
  {
    id: "veg-pasta-cauliflower",
    name: "Pâtes à la crème de chou-fleur et gruyère",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Penne", qty: 400, unit: "g", optional: false },
      { food: "Chou-fleur", qty: 500, unit: "g", optional: false },
      { food: "Gruyère râpé frais", qty: 80, unit: "g", optional: false },
      { food: "Crème fraîche", qty: 150, unit: "ml", optional: false },
      { food: "Beurre", qty: 25, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Bouillon de légumes", qty: 300, unit: "ml", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Cuire les pâtes al dente. Égoutter et réserver.",
      "Couper le chou-fleur en petites sommités. Émincer l'oignon.",
      "Faire revenir l'oignon dans le beurre 5 minutes. Ajouter le chou-fleur et le bouillon.",
      "Cuire à couvert 15 minutes jusqu'à ce que le chou-fleur soit très tendre. Mixer finement avec la crème fraîche.",
      "Assaisonner la crème de chou-fleur avec la muscade, le sel et le poivre.",
      "Mélanger les pâtes avec la sauce. Parsemer de gruyère râpé et servir aussitôt."
    ],
    nutrition: { calories: 560, protein: 22, carbs: 74, fat: 20, fiber: 6 },
    tips: "Cette sauce veloutée est idéale pour remplacer les sauces tomates. Le gruyère doit être râpé frais le jour même pour limiter la production d'histamine.",
    isCustom: false
  },
  {
    id: "veg-soup-carrot-ginger",
    name: "Soupe veloutée de carottes au gingembre",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Carottes", qty: 700, unit: "g", optional: false },
      { food: "Patate douce", qty: 200, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Gingembre frais", qty: 3, unit: "cm", optional: false },
      { food: "Lait de coco", qty: 200, unit: "ml", optional: false },
      { food: "Bouillon de légumes maison", qty: 800, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Éplucher et couper les carottes, la patate douce et l'oignon en morceaux grossiers.",
      "Faire revenir l'oignon dans l'huile d'olive 3 minutes dans une grande casserole.",
      "Ajouter les carottes, la patate douce et le gingembre râpé. Remuer 2 minutes.",
      "Verser le bouillon de légumes et porter à ébullition. Réduire le feu et cuire 25 minutes.",
      "Mixer finement la soupe au mixeur plongeant. Incorporer le lait de coco et réchauffer sans faire bouillir.",
      "Assaisonner, rectifier l'épaisseur avec un peu de bouillon si nécessaire. Servir avec des graines de courge."
    ],
    nutrition: { calories: 210, protein: 4, carbs: 32, fat: 9, fiber: 7 },
    tips: "Le gingembre frais est naturellement anti-histaminique. Préparez le bouillon vous-même pour éviter les extraits de levure souvent présents dans les bouillons du commerce.",
    isCustom: false
  },
  {
    id: "veg-soup-leek-potato",
    name: "Velouté de poireaux et pommes de terre à la crème",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poireaux", qty: 500, unit: "g", optional: false },
      { food: "Pommes de terre", qty: 400, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Crème fraîche", qty: 100, unit: "ml", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Bouillon de légumes maison", qty: 1, unit: "L", optional: false },
      { food: "Ciboulette", qty: 10, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Laver soigneusement les poireaux et les émincer. Éplucher et couper les pommes de terre en dés.",
      "Faire fondre le beurre dans une grande casserole. Faire suer l'oignon émincé et les poireaux 8 minutes à feu doux.",
      "Ajouter les pommes de terre et le bouillon de légumes. Porter à ébullition.",
      "Réduire le feu et cuire 20 minutes à couvert jusqu'à ce que les pommes de terre soient tendres.",
      "Mixer finement. Incorporer la crème fraîche, réchauffer sans bouillir et ajuster l'assaisonnement.",
      "Servir avec une noisette de beurre, la ciboulette ciselée et du pain frais."
    ],
    nutrition: { calories: 230, protein: 5, carbs: 34, fat: 9, fiber: 5 },
    tips: "Cette soupe classique est naturellement faible en histamine. Elle se congèle bien sans la crème fraîche que vous ajouterez après décongélation.",
    isCustom: false
  },
  {
    id: "veg-soup-butternut",
    name: "Soupe de courge butternut et pomme",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Courge butternut", qty: 900, unit: "g", optional: false },
      { food: "Pomme Golden", qty: 1, unit: "pièce", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Crème de coco", qty: 100, unit: "ml", optional: false },
      { food: "Bouillon de légumes maison", qty: 800, unit: "ml", optional: false },
      { food: "Cannelle", qty: 1, unit: "pincée", optional: true },
      { food: "Huile d'olive", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Éplucher et couper la courge en cubes. Éplucher et couper la pomme en morceaux en retirant le coeur.",
      "Faire revenir l'oignon émincé dans l'huile 3 minutes dans une grande casserole.",
      "Ajouter la courge, la pomme et la cannelle. Mélanger et cuire 2 minutes.",
      "Verser le bouillon, porter à ébullition puis réduire le feu. Couvrir et cuire 30 minutes.",
      "Mixer finement jusqu'à obtenir un velouté lisse. Incorporer la crème de coco.",
      "Réchauffer sans bouillir, assaisonner et servir avec un filet de crème de coco et des graines de courge."
    ],
    nutrition: { calories: 195, protein: 4, carbs: 34, fat: 6, fiber: 6 },
    tips: "La pomme apporte une légère acidité naturelle sans avoir recours au citron. Choisissez une Golden bien mûre pour plus de douceur.",
    isCustom: false
  },
  {
    id: "veg-soup-minestrone",
    name: "Minestrone de légumes au bouillon léger",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Carottes", qty: 3, unit: "pièces", optional: false },
      { food: "Courgettes", qty: 2, unit: "pièces", optional: false },
      { food: "Haricots verts", qty: 150, unit: "g", optional: false },
      { food: "Pommes de terre", qty: 2, unit: "pièces", optional: false },
      { food: "Pois chiches rincés", qty: 200, unit: "g", optional: false },
      { food: "Orzo", qty: 100, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Bouillon de légumes maison", qty: 1500, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Éplucher et couper en petits dés les carottes, courgettes et pommes de terre. Équeuter les haricots verts.",
      "Faire revenir l'oignon et l'ail émincés dans l'huile d'olive 5 minutes dans une grande marmite.",
      "Ajouter les carottes et pommes de terre. Verser le bouillon chaud et porter à ébullition.",
      "Cuire 15 minutes puis ajouter les courgettes, haricots verts et pois chiches rincés.",
      "Cuire encore 10 minutes. Ajouter les pâtes et cuire le temps indiqué sur le paquet.",
      "Ajuster l'assaisonnement et servir avec un filet d'huile d'olive et du pain frais."
    ],
    nutrition: { calories: 260, protein: 10, carbs: 44, fat: 6, fiber: 9 },
    tips: "Ce minestrone sans tomates reste savoureux. Préparez-le en grande quantité et congelez en portions individuelles que vous consommerez fraîchement réchauffées.",
    isCustom: false
  },
  {
    id: "veg-rice-pilaf",
    name: "Riz pilaf aux légumes et curcuma",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz basmati", qty: 300, unit: "g", optional: false },
      { food: "Petits pois surgelés", qty: 200, unit: "g", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Bouillon de légumes maison", qty: 600, unit: "ml", optional: false },
      { food: "Curcuma", qty: 1, unit: "c. à café", optional: false },
      { food: "Feuilles de laurier", qty: 2, unit: "pièces", optional: true }
    ],
    steps: [
      "Rincer le riz à l'eau froide jusqu'à ce que l'eau soit claire. Égoutter.",
      "Émincer l'oignon et couper les carottes en brunoise fine. Faire revenir dans le beurre 5 minutes.",
      "Ajouter le riz et le curcuma. Nacrer le riz en remuant 2 minutes dans le beurre.",
      "Verser le bouillon chaud et ajouter les feuilles de laurier. Porter à ébullition, couvrir.",
      "Cuire à feu très doux 15 minutes sans soulever le couvercle. Ajouter les petits pois les 5 dernières minutes.",
      "Retirer le laurier, égrainer le riz à la fourchette et servir immédiatement."
    ],
    nutrition: { calories: 360, protein: 8, carbs: 68, fat: 7, fiber: 5 },
    tips: "Le riz pilaf se conserve mal une fois cuit car il fige. Cuisinez-le en quantité adaptée et consommez-le frais pour une meilleure digestion et moins d'histamine.",
    isCustom: false
  },
  {
    id: "veg-rice-asparagus-cream",
    name: "Risotto d'asperges vertes à la crème fraîche",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Riz arborio", qty: 320, unit: "g", optional: false },
      { food: "Asperges vertes", qty: 500, unit: "g", optional: false },
      { food: "Bouillon de légumes maison chaud", qty: 1200, unit: "ml", optional: false },
      { food: "Crème fraîche épaisse", qty: 100, unit: "ml", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Gruyère fraîchement râpé", qty: 40, unit: "g", optional: true }
    ],
    steps: [
      "Casser les asperges pour ôter la partie dure. Couper les pointes de 5 cm et les tronçons séparément. Blanchir les pointes 2 minutes.",
      "Faire suer l'oignon émincé dans la moitié du beurre 5 minutes. Ajouter les tronçons d'asperges et cuire 3 minutes.",
      "Ajouter le riz et le nacrer 2 minutes en remuant bien.",
      "Incorporer le bouillon chaud louche par louche, en remuant constamment et en attendant absorption avant d'en rajouter, environ 20 minutes.",
      "Hors du feu, incorporer le reste du beurre et la crème fraîche. Couvrir et laisser reposer 2 minutes.",
      "Ajouter les pointes d'asperges blanchies, le gruyère râpé. Assaisonner et servir immédiatement."
    ],
    nutrition: { calories: 480, protein: 14, carbs: 72, fat: 16, fiber: 5 },
    tips: "Le risotto doit être servi très frais à la préparation. Ne le réchauffez pas le lendemain. Un bon bouillon maison sans exhausteurs de goût est indispensable.",
    isCustom: false
  },
  {
    id: "veg-rice-coconut-vegetables",
    name: "Riz au lait de coco et légumes sautés",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz jasmin", qty: 300, unit: "g", optional: false },
      { food: "Lait de coco", qty: 400, unit: "ml", optional: false },
      { food: "Bok choy", qty: 300, unit: "g", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Petits pois", qty: 150, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 2, unit: "cm", optional: false },
      { food: "Curcuma", qty: 1, unit: "c. à café", optional: false },
      { food: "Huile de coco", qty: 1, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Rincer le riz. Le cuire dans 300 ml d'eau mélangée à 200 ml de lait de coco pendant 15 minutes. Laisser reposer couvert.",
      "Éplucher et émincer les carottes en julienne. Couper le bok choy en quartiers.",
      "Faire chauffer l'huile de coco dans un wok. Faire revenir le gingembre râpé et le curcuma 1 minute.",
      "Ajouter les carottes et faire sauter 4 minutes. Incorporer les petits pois et le bok choy.",
      "Verser le reste du lait de coco et cuire 5 minutes à feu vif en remuant. Assaisonner.",
      "Servir le riz dans des bols avec les légumes au lait de coco par-dessus."
    ],
    nutrition: { calories: 440, protein: 9, carbs: 68, fat: 16, fiber: 6 },
    tips: "Le bok choy est excellent pour les sensibles à l'histamine. Le lait de coco en conserve doit être consommé immédiatement après ouverture pour éviter la formation d'histamine.",
    isCustom: false
  },
  {
    id: "veg-salad-quinoa-roasted",
    name: "Salade de quinoa aux légumes rôtis et feta fraîche",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Quinoa", qty: 200, unit: "g", optional: false },
      { food: "Courgettes", qty: 2, unit: "pièces", optional: false },
      { food: "Poivrons jaunes", qty: 2, unit: "pièces", optional: false },
      { food: "Feta fraîche", qty: 150, unit: "g", optional: false },
      { food: "Menthe fraîche", qty: 15, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Oignon rouge", qty: 1, unit: "pièce", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 200°C. Cuire le quinoa dans 400 ml d'eau salée 15 minutes. Laisser refroidir.",
      "Couper les courgettes et poivrons en cubes. Mélanger avec 2 c. à soupe d'huile, saler.",
      "Rôtir les légumes 25 minutes au four en retournant à mi-cuisson. Laisser refroidir à température ambiante.",
      "Émincer finement l'oignon rouge si utilisé et ciseler la menthe.",
      "Assembler la salade : quinoa, légumes rôtis refroidis, oignon rouge, menthe.",
      "Émietter la feta fraîche par-dessus, arroser avec le reste d'huile d'olive et servir à température ambiante."
    ],
    nutrition: { calories: 380, protein: 16, carbs: 44, fat: 18, fiber: 7 },
    tips: "Cette salade est meilleure à température ambiante que froide. Ne la préparez pas la veille car la feta produit de l'histamine en contact prolongé avec les légumes acides.",
    isCustom: false
  },
  {
    id: "veg-salad-chickpea-herb",
    name: "Salade de pois chiches, herbes fraîches et concombre",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pois chiches rincés", qty: 480, unit: "g", optional: false },
      { food: "Concombre", qty: 1, unit: "pièce", optional: false },
      { food: "Poivron vert", qty: 1, unit: "pièce", optional: false },
      { food: "Persil frais", qty: 30, unit: "g", optional: false },
      { food: "Menthe fraîche", qty: 20, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Rincer soigneusement les pois chiches sous l'eau froide et les égoutter dans une passoire fine pendant 5 minutes.",
      "Couper le concombre en demi-lunes et le poivron en petits dés.",
      "Hacher finement le persil et la menthe. Écraser l'ail avec le plat d'un couteau et l'émincer finement.",
      "Mélanger les pois chiches, le concombre, le poivron, les herbes et l'ail dans un saladier.",
      "Assaisonner avec l'huile d'olive, le sel et un peu de poivre. Bien mélanger.",
      "Servir immédiatement ou laisser reposer 15 minutes à température ambiante pour que les saveurs se développent."
    ],
    nutrition: { calories: 320, protein: 14, carbs: 38, fat: 14, fiber: 12 },
    tips: "Le rinçage abondant des pois chiches en conserve réduit leur histamine de manière significative. Consommez cette salade le jour même.",
    isCustom: false
  },
  {
    id: "plant-salad-lentil-fennel",
    name: "Salade tiède de lentilles beluga et fenouil",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Lentilles beluga noires", qty: 250, unit: "g", optional: false },
      { food: "Fenouil", qty: 2, unit: "bulbes", optional: false },
      { food: "Chèvre frais", qty: 120, unit: "g", optional: false },
      { food: "Céleri branche", qty: 2, unit: "tiges", optional: false },
      { food: "Aneth frais", qty: 15, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Moutarde douce sans vinaigre", qty: 1, unit: "c. à café", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Rincer les lentilles et les cuire dans 3 fois leur volume d'eau non salée pendant 20 minutes. Saler en fin de cuisson. Égoutter.",
      "Émincer finement le fenouil et le céleri en biais. Conserver quelques frondes de fenouil pour la décoration.",
      "Préparer la vinaigrette : mélanger l'huile d'olive, la moutarde douce, le sel et le poivre.",
      "Mélanger les lentilles encore tièdes avec le fenouil, le céleri et la vinaigrette.",
      "Ciseler l'aneth frais et l'incorporer à la salade.",
      "Disposer dans les assiettes et émietter le chèvre frais par-dessus. Décorer avec les frondes de fenouil."
    ],
    nutrition: { calories: 370, protein: 20, carbs: 40, fat: 15, fiber: 14 },
    tips: "Les lentilles beluga tiennent mieux à la cuisson que les lentilles classiques et ne s'écrasent pas. Elles sont aussi légèrement moins susceptibles de libérer de l'histamine.",
    isCustom: false
  },
  {
    id: "veg-cheese-polenta",
    name: "Polenta crémeuse au mascarpone et légumes sautés",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Polenta", qty: 200, unit: "g", optional: false },
      { food: "Mascarpone", qty: 150, unit: "g", optional: false },
      { food: "Lait entier", qty: 500, unit: "ml", optional: false },
      { food: "Eau", qty: 500, unit: "ml", optional: false },
      { food: "Champignons de Paris frais", qty: 300, unit: "g", optional: false },
      { food: "Asperges", qty: 200, unit: "g", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Porter à ébullition le mélange lait et eau salé. Verser la polenta en pluie en fouettant constamment.",
      "Cuire la polenta à feu doux en remuant 15 à 20 minutes jusqu'à ce qu'elle se détache des parois.",
      "Incorporer le mascarpone et 20 g de beurre hors du feu. Assaisonner.",
      "Émincer les champignons et couper les asperges en tronçons. Faire sauter dans le reste du beurre avec l'ail 8 minutes.",
      "Assaisonner les légumes sautés avec sel et poivre.",
      "Servir la polenta crémeuse dans les assiettes avec les légumes sautés par-dessus."
    ],
    nutrition: { calories: 440, protein: 14, carbs: 48, fat: 22, fiber: 4 },
    tips: "Les champignons de Paris frais sont bien tolérés. Évitez les champignons séchés ou en conserve qui ont des taux d'histamine bien plus élevés.",
    isCustom: false
  },
  {
    id: "veg-cheese-halloumi-veg",
    name: "Halloumi grillé, légumes rôtis et sauce yaourt menthe",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Halloumi frais", qty: 250, unit: "g", optional: false },
      { food: "Poivrons jaunes", qty: 2, unit: "pièces", optional: false },
      { food: "Courgettes", qty: 2, unit: "pièces", optional: false },
      { food: "Oignon rouge", qty: 1, unit: "pièce", optional: false },
      { food: "Yaourt nature frais", qty: 150, unit: "g", optional: false },
      { food: "Menthe fraîche", qty: 10, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 200°C. Couper poivrons, courgettes et oignon rouge en morceaux. Mélanger avec 2 c. à soupe d'huile et du sel.",
      "Rôtir les légumes 25 minutes en retournant à mi-cuisson.",
      "Préparer la sauce : mélanger le yaourt avec la menthe ciselée, 1 c. à soupe d'huile et une pincée de sel.",
      "Couper le halloumi en tranches de 1 cm. Chauffer une poêle à feu vif sans matière grasse.",
      "Griller le halloumi 2 minutes par face jusqu'à coloration dorée.",
      "Dresser les assiettes avec les légumes rôtis, le halloumi grillé et la sauce yaourt à la menthe."
    ],
    nutrition: { calories: 480, protein: 28, carbs: 22, fat: 32, fiber: 5 },
    tips: "Le yaourt frais nature est bien toléré s'il est consommé le jour d'ouverture. Évitez les yaourts aromatisés qui contiennent souvent des arômes et conservateurs.",
    isCustom: false
  },
  {
    id: "veg-cheese-ricotta-pancake",
    name: "Pancakes salés à la ricotta et aux herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Ricotta", qty: 250, unit: "g", optional: false },
      { food: "Oeufs", qty: 2, unit: "pièces", optional: false },
      { food: "Farine d'épeautre", qty: 60, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 15, unit: "g", optional: false },
      { food: "Persil frais", qty: 10, unit: "g", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Laitue ou frisée", qty: 100, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Dans un saladier, mélanger la ricotta avec les oeufs battus jusqu'à obtenir une préparation homogène.",
      "Incorporer la farine tamisée, la ciboulette et le persil hachés. Assaisonner avec sel et poivre.",
      "Laisser reposer la pâte 5 minutes. La consistance doit être épaisse comme une purée.",
      "Faire fondre le beurre dans une poêle antiadhésive à feu moyen. Déposer des cuillerées de pâte.",
      "Cuire 3 minutes par face jusqu'à coloration dorée. La pâte doit être ferme au toucher.",
      "Servir les pancakes chauds accompagnés de la salade verte assaisonnée d'huile d'olive."
    ],
    nutrition: { calories: 360, protein: 20, carbs: 28, fat: 20, fiber: 3 },
    tips: "Ces pancakes salés doivent être consommés immédiatement. La ricotta fraîche ouverte le jour même est idéale. L'épeautre est une alternative à la farine de blé bien tolérée.",
    isCustom: false
  },
  {
    id: "veggie-petit-dej-oatmeal",
    name: "Porridge d'avoine à la pomme et cannelle",
    category: "petit-dej",
    mealType: ["petit-dejeuner"],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Flocons d'avoine", qty: 160, unit: "g", optional: false },
      { food: "Lait entier", qty: 400, unit: "ml", optional: false },
      { food: "Pomme Golden", qty: 1, unit: "pièce", optional: false },
      { food: "Cannelle", qty: 1, unit: "c. à café", optional: false },
      { food: "Miel d'acacia", qty: 2, unit: "c. à café", optional: true },
      { food: "Beurre", qty: 5, unit: "g", optional: true },
      { food: "Graines de courge", qty: 20, unit: "g", optional: true }
    ],
    steps: [
      "Verser les flocons d'avoine dans une casserole avec le lait et une pincée de sel.",
      "Porter à feu moyen en remuant régulièrement. Laisser épaissir 5 à 7 minutes.",
      "Pendant ce temps, éplucher et râper ou couper la pomme en petits dés.",
      "Incorporer la pomme et la cannelle dans le porridge. Remuer et cuire encore 2 minutes.",
      "Verser dans les bols, napper de miel si désiré et ajouter une noisette de beurre.",
      "Parsemer de graines de courge pour le croquant. Servir immédiatement."
    ],
    nutrition: { calories: 380, protein: 12, carbs: 62, fat: 10, fiber: 7 },
    tips: "L'avoine est naturellement sans histamine. Choisissez des flocons d'avoine simples sans malt ajouté. Ce petit-déjeuner est idéal pour bien commencer la journée.",
    isCustom: false
  },
  {
    id: "plant-dessert-panna-cotta",
    name: "Panna cotta à la vanille et coulis de poire",
    category: "dessert",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Crème fraîche liquide entière", qty: 500, unit: "ml", optional: false },
      { food: "Sucre", qty: 50, unit: "g", optional: false },
      { food: "Gélatine en feuilles", qty: 3, unit: "feuilles", optional: false },
      { food: "Gousse de vanille", qty: 1, unit: "pièce", optional: false },
      { food: "Poires mûres", qty: 3, unit: "pièces", optional: false },
      { food: "Sucre vanillé", qty: 1, unit: "sachet", optional: true }
    ],
    steps: [
      "Faire ramollir les feuilles de gélatine dans de l'eau froide pendant 5 minutes.",
      "Chauffer la crème avec le sucre et la gousse de vanille fendue et grattée. Porter à frémissement sans bouillir.",
      "Hors du feu, incorporer les feuilles de gélatine bien essorées. Remuer jusqu'à dissolution complète.",
      "Verser dans 4 ramequins et laisser refroidir à température ambiante, puis réfrigérer au moins 3 heures.",
      "Éplucher les poires, les couper en morceaux et les cuire 10 minutes avec le sucre vanillé et un peu d'eau. Mixer.",
      "Au moment de servir, démouler les panna cotta et napper du coulis de poire tiède."
    ],
    nutrition: { calories: 420, protein: 4, carbs: 32, fat: 32, fiber: 2 },
    tips: "Consommez la panna cotta dans les 24 heures suivant la préparation. La poire est un fruit bien toléré par les personnes sensibles à l'histamine.",
    isCustom: false
  },
  {
    id: "veggie-collation-rice-cakes",
    name: "Galettes de riz au fromage blanc et concombre",
    category: "collation",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Galettes de riz soufflé nature", qty: 4, unit: "pièces", optional: false },
      { food: "Fromage blanc", qty: 150, unit: "g", optional: false },
      { food: "Concombre", qty: 0.5, unit: "pièce", optional: false },
      { food: "Ciboulette fraîche", qty: 10, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Huile d'olive", qty: 1, unit: "c. à café", optional: true }
    ],
    steps: [
      "Préparer la garniture : mélanger le fromage blanc avec la ciboulette ciselée, le sel et le poivre.",
      "Laver le concombre et le couper en tranches fines ou en petits dés.",
      "Étaler généreusement la préparation au fromage blanc sur chaque galette de riz.",
      "Disposer les tranches de concombre par-dessus.",
      "Arroser d'un filet d'huile d'olive si désiré et servir immédiatement.",
      "Consommer dans les 10 minutes pour que les galettes restent croustillantes."
    ],
    nutrition: { calories: 140, protein: 8, carbs: 20, fat: 3, fiber: 1 },
    tips: "Les galettes de riz sont une excellente collation neutre en histamine. Choisissez-les nature sans sel ajouté ni arômes. Le fromage blanc frais est très bien toléré.",
    isCustom: false
  }
];
