const RECIPES_BATCH_4 = [
  {
    id: "quick-poulet-beurre-herbes",
    name: "Escalopes de Poulet au Beurre et Fines Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Escalopes de poulet frais", qty: 300, unit: "g", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Persil frais haché", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Ciboulette fraîche", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Aplatir légèrement les escalopes de poulet entre deux feuilles de film alimentaire.",
      "Écraser l'ail et hacher finement le persil et la ciboulette.",
      "Faire fondre le beurre à feu moyen-vif dans une grande poêle.",
      "Saisir les escalopes 4 à 5 minutes de chaque côté jusqu'à ce qu'elles soient bien dorées et cuites à cœur.",
      "Ajouter l'ail écrasé dans la poêle en fin de cuisson et cuire 30 secondes.",
      "Retirer du feu, parsemer de persil et de ciboulette, saler et poivrer.",
      "Servir immédiatement avec les sucs de cuisson versés par-dessus."
    ],
    nutrition: { calories: 320, protein: 38, carbs: 1, fat: 18, fiber: 0 },
    tips: "Aplatir les escalopes assure une cuisson rapide et uniforme. Utilisez du poulet sorti du réfrigérateur 10 minutes avant cuisson pour éviter qu'il soit dur.",
    isCustom: false
  },
  {
    id: "quick-poulet-creme-champignons",
    name: "Émincé de Poulet à la Crème et Champignons",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blanc de poulet frais en lamelles", qty: 280, unit: "g", optional: false },
      { food: "Champignons de Paris frais", qty: 150, unit: "g", optional: false },
      { food: "Crème fraîche épaisse", qty: 100, unit: "ml", optional: false },
      { food: "Oignon", qty: 1, unit: "petit", optional: false },
      { food: "Huile d'olive", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Thym frais", qty: 2, unit: "brins", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Émincer l'oignon et nettoyer puis trancher les champignons.",
      "Couper le blanc de poulet en lamelles fines de 1 cm.",
      "Faire chauffer l'huile d'olive dans une poêle à feu vif.",
      "Faire revenir l'oignon 2 minutes, puis ajouter les lamelles de poulet.",
      "Cuire le poulet 5 minutes en remuant régulièrement jusqu'à coloration.",
      "Ajouter les champignons et cuire 3 minutes supplémentaires.",
      "Baisser le feu, verser la crème fraîche et le thym, mélanger et chauffer 2 minutes sans faire bouillir.",
      "Rectifier l'assaisonnement et servir aussitôt."
    ],
    nutrition: { calories: 380, protein: 40, carbs: 6, fat: 22, fiber: 1 },
    tips: "Coupez le poulet en lamelles très fines pour une cuisson express. Les champignons de Paris sont les seuls champignons recommandés dans le régime anti-histamine.",
    isCustom: false
  },
  {
    id: "express-poulet-courgette-sauté",
    name: "Sauté de Poulet aux Courgettes et Ail",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blanc de poulet frais", qty: 300, unit: "g", optional: false },
      { food: "Courgettes", qty: 2, unit: "moyennes", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Basilic frais", qty: 5, unit: "feuilles", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Couper le poulet en dés de 2 cm et les courgettes en rondelles de 5 mm.",
      "Émincer finement l'ail.",
      "Chauffer l'huile d'olive dans un wok ou une grande poêle à feu très vif.",
      "Faire sauter le poulet 5 minutes en remuant constamment jusqu'à ce qu'il soit doré.",
      "Ajouter les courgettes et l'ail, cuire encore 5 à 6 minutes en remuant.",
      "Les courgettes doivent rester légèrement croquantes.",
      "Saler, poivrer et garnir de basilic frais déchiré avant de servir."
    ],
    nutrition: { calories: 300, protein: 38, carbs: 7, fat: 13, fiber: 2 },
    tips: "Le wok très chaud est la clé d'un sauté rapide. Ne jamais couvrir pour éviter la vapeur qui ramollit les légumes.",
    isCustom: false
  },
  {
    id: "rapide-poulet-moutarde-douce",
    name: "Poulet Sauté à la Moutarde Douce",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Escalopes de poulet frais", qty: 320, unit: "g", optional: false },
      { food: "Crème liquide", qty: 80, unit: "ml", optional: false },
      { food: "Moutarde douce de Dijon", qty: 1, unit: "c. à café", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Échalote", qty: 1, unit: "pièce", optional: false },
      { food: "Persil plat frais", qty: 2, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Émincer finement l'échalote. Couper les escalopes en morceaux.",
      "Faire fondre le beurre dans une poêle à feu moyen.",
      "Faire revenir l'échalote 2 minutes jusqu'à transparence.",
      "Augmenter le feu et faire dorer le poulet 6 à 7 minutes.",
      "Baisser le feu, mélanger la crème avec la moutarde douce et verser dans la poêle.",
      "Laisser mijoter 3 minutes à feu doux en remuant.",
      "Parsemer de persil haché et servir immédiatement."
    ],
    nutrition: { calories: 350, protein: 39, carbs: 3, fat: 20, fiber: 0 },
    tips: "Attention : utilisez de la moutarde douce en petite quantité. La moutarde forte peut être problématique pour certaines personnes histaminiques.",
    isCustom: false
  },
  {
    id: "fast-poulet-paprika-doux",
    name: "Poulet au Paprika Doux et Crème",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 7,
    cookTime: 13,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blanc de poulet frais en dés", qty: 300, unit: "g", optional: false },
      { food: "Paprika doux", qty: 1, unit: "c. à café", optional: false },
      { food: "Crème fraîche", qty: 100, unit: "ml", optional: false },
      { food: "Oignon", qty: 1, unit: "moyen", optional: false },
      { food: "Huile d'olive", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 15, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper l'oignon en petits dés.",
      "Dans une poêle, faire chauffer l'huile et le beurre.",
      "Faire revenir l'oignon 3 minutes à feu moyen.",
      "Ajouter les dés de poulet et les faire dorer 5 minutes en remuant.",
      "Saupoudrer de paprika doux et mélanger pour bien enrober.",
      "Verser la crème fraîche, mélanger et laisser mijoter 4 à 5 minutes.",
      "Saler et servir chaud, accompagné de riz ou de pâtes."
    ],
    nutrition: { calories: 370, protein: 38, carbs: 5, fat: 22, fiber: 1 },
    tips: "Le paprika doux est parfaitement toléré dans le régime anti-histamine. Évitez le paprika fumé ou fort qui peut être irritant.",
    isCustom: false
  },
  {
    id: "quick-poulet-asperges-beurre",
    name: "Suprêmes de Poulet aux Asperges au Beurre",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Escalopes de poulet frais", qty: 300, unit: "g", optional: false },
      { food: "Asperges vertes", qty: 200, unit: "g", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: true },
      { food: "Estragon frais", qty: 1, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Casser les asperges à la base pour enlever la partie fibreuse et les couper en tronçons de 4 cm.",
      "Aplatir légèrement les escalopes.",
      "Faire fondre la moitié du beurre dans une poêle à feu vif.",
      "Faire dorer les escalopes 4 à 5 minutes de chaque côté.",
      "Retirer et réserver au chaud.",
      "Dans la même poêle, ajouter le reste du beurre et faire sauter les asperges 5 minutes.",
      "Ajouter l'ail émincé 1 minute en fin de cuisson.",
      "Remettre le poulet dans la poêle, parsemer d'estragon et servir."
    ],
    nutrition: { calories: 330, protein: 39, carbs: 4, fat: 17, fiber: 2 },
    tips: "Les asperges vertes fraîches cuisent très vite. Vérifiez la cuisson en piquant avec une pointe de couteau : elles doivent rester légèrement fermes.",
    isCustom: false
  },
  {
    id: "express-poulet-brocoli-sésame",
    name: "Poulet Sauté au Brocoli et Graines de Sésame",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blanc de poulet frais en lamelles", qty: 280, unit: "g", optional: false },
      { food: "Brocoli en fleurettes", qty: 200, unit: "g", optional: false },
      { food: "Graines de sésame", qty: 1, unit: "c. à soupe", optional: true },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Gingembre frais râpé", qty: 1, unit: "c. à café", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper le brocoli en petites fleurettes et le poulet en fines lamelles.",
      "Émincer l'ail et râper le gingembre frais.",
      "Faire chauffer l'huile dans un wok à feu très vif.",
      "Faire sauter le poulet 4 minutes en remuant.",
      "Ajouter le brocoli, l'ail et le gingembre, cuire 5 à 6 minutes.",
      "Le brocoli doit être cuit mais encore légèrement croquant.",
      "Parsemer de graines de sésame, saler et servir immédiatement."
    ],
    nutrition: { calories: 310, protein: 40, carbs: 8, fat: 13, fiber: 3 },
    tips: "Pour gagner du temps, utilisez des fleurettes de brocoli surgelées déjà portionnées. Le gingembre frais est toléré en petite quantité.",
    isCustom: false
  },
  {
    id: "rapide-poulet-haricots-verts",
    name: "Poulet Poêlé aux Haricots Verts et Amandes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 7,
    cookTime: 13,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Escalopes de poulet frais", qty: 300, unit: "g", optional: false },
      { food: "Haricots verts surgelés", qty: 200, unit: "g", optional: false },
      { food: "Amandes effilées", qty: 20, unit: "g", optional: true },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Échalote", qty: 1, unit: "pièce", optional: false },
      { food: "Persil frais", qty: 2, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Faire cuire les haricots verts surgelés au micro-ondes 5 minutes ou les blanchir 4 minutes dans l'eau bouillante.",
      "Émincer l'échalote. Couper les escalopes en lanières.",
      "Faire dorer les amandes effilées à sec dans la poêle 1 minute, réserver.",
      "Faire fondre le beurre, faire revenir l'échalote 2 minutes.",
      "Faire sauter les lanières de poulet 6 minutes à feu vif.",
      "Ajouter les haricots verts égouttés, mélanger et réchauffer 2 minutes.",
      "Parsemer d'amandes et de persil, saler et servir."
    ],
    nutrition: { calories: 345, protein: 40, carbs: 9, fat: 16, fiber: 4 },
    tips: "Les haricots verts surgelés permettent de gagner un temps précieux en semaine. Les amandes effilées sont bien tolérées contrairement aux noix et aux cacahuètes.",
    isCustom: false
  },
  {
    id: "quick-sole-beurre-citron-vert",
    name: "Filets de Sole Meunière au Beurre Noisette",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Filets de sole frais", qty: 300, unit: "g", optional: false },
      { food: "Farine", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 50, unit: "g", optional: false },
      { food: "Persil plat frais haché", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Sécher les filets de sole avec du papier absorbant.",
      "Fariner légèrement les deux faces des filets, secouer l'excédent.",
      "Faire fondre le beurre dans une grande poêle à feu moyen-vif.",
      "Quand le beurre mousse, déposer les filets côté peau.",
      "Cuire 2 à 3 minutes de chaque côté jusqu'à dorure.",
      "Retirer les filets et les déposer dans les assiettes.",
      "Laisser le beurre brunir légèrement (beurre noisette), ajouter le persil.",
      "Verser le beurre noisette au persil sur les filets et servir immédiatement."
    ],
    nutrition: { calories: 280, protein: 32, carbs: 8, fat: 13, fiber: 0 },
    tips: "La sole fraîche cuit en quelques minutes seulement. Le beurre noisette se fait en 30 secondes : surveillez attentivement pour ne pas le brûler.",
    isCustom: false
  },
  {
    id: "express-tilapia-vapeur-herbes",
    name: "Tilapia Vapeur aux Herbes Fraîches",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Filets de tilapia frais", qty: 320, unit: "g", optional: false },
      { food: "Persil frais", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Ciboulette fraîche", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: true },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préparer le cuiseur vapeur ou poser un panier vapeur sur une casserole d'eau frémissante.",
      "Hacher finement le persil, la ciboulette et l'ail.",
      "Mélanger les herbes avec l'huile d'olive et le sel.",
      "Badigeonner généreusement les filets de tilapia du mélange herbes-huile.",
      "Déposer les filets dans le panier vapeur.",
      "Cuire à la vapeur 10 à 12 minutes selon l'épaisseur.",
      "Le poisson est cuit quand il s'effeuille facilement à la fourchette.",
      "Servir immédiatement avec un filet d'huile d'olive supplémentaire."
    ],
    nutrition: { calories: 240, protein: 35, carbs: 1, fat: 10, fiber: 0 },
    tips: "La cuisson vapeur préserve toutes les qualités nutritionnelles du poisson et libère moins d'histamine que la friture. Idéal pour le régime anti-histamine.",
    isCustom: false
  },
  {
    id: "rapide-cabillaud-papillote",
    name: "Dos de Cabillaud en Papillote aux Légumes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Dos de cabillaud frais", qty: 320, unit: "g", optional: false },
      { food: "Courgette", qty: 1, unit: "petite", optional: false },
      { food: "Carottes", qty: 2, unit: "moyennes", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Thym frais", qty: 2, unit: "brins", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Huile d'olive", qty: 1, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Préchauffer le four à 200°C.",
      "Couper la courgette en rondelles fines et les carottes en julienne.",
      "Découper deux grandes feuilles de papier aluminium.",
      "Déposer les légumes au centre de chaque feuille.",
      "Poser un morceau de cabillaud sur les légumes.",
      "Ajouter une noix de beurre, un filet d'huile, le thym et le sel.",
      "Fermer hermétiquement les papillotes en repliant les bords.",
      "Cuire 15 minutes au four. Le poisson doit s'effeuiller facilement.",
      "Ouvrir délicatement les papillotes (attention à la vapeur) et servir."
    ],
    nutrition: { calories: 260, protein: 34, carbs: 9, fat: 10, fiber: 2 },
    tips: "Préparez les papillotes le matin et conservez-les au réfrigérateur : il suffira de les enfourner au retour du travail.",
    isCustom: false
  },
  {
    id: "fast-poisson-crème-aneth",
    name: "Filets de Poisson à la Crème d'Aneth",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Filets de sole ou tilapia frais", qty: 300, unit: "g", optional: false },
      { food: "Crème fraîche épaisse", qty: 100, unit: "ml", optional: false },
      { food: "Aneth frais haché", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Échalote", qty: 1, unit: "pièce", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Hacher finement l'échalote et l'aneth frais.",
      "Faire fondre le beurre dans une poêle à feu moyen.",
      "Faire revenir l'échalote 2 minutes.",
      "Déposer les filets de poisson et cuire 3 minutes de chaque côté.",
      "Retirer le poisson et réserver au chaud.",
      "Verser la crème fraîche dans la poêle, incorporer l'aneth.",
      "Chauffer 1 à 2 minutes à feu doux, saler.",
      "Napper le poisson de la sauce à l'aneth et servir."
    ],
    nutrition: { calories: 290, protein: 33, carbs: 3, fat: 16, fiber: 0 },
    tips: "L'aneth est une herbe parfaitement adaptée au régime anti-histamine et se marie idéalement avec les poissons à chair blanche.",
    isCustom: false
  },
  {
    id: "quick-cabillaud-beurre-câpres",
    name: "Cabillaud Poêlé au Beurre Persillé",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Filets de cabillaud frais", qty: 320, unit: "g", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Persil plat frais", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false },
      { food: "Farine", qty: 2, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Sécher les filets de cabillaud avec du papier absorbant.",
      "Fariner légèrement les filets si désiré.",
      "Émincer finement l'ail et hacher le persil.",
      "Faire fondre le beurre dans une poêle à feu moyen-vif.",
      "Déposer les filets et cuire 3 à 4 minutes de chaque côté.",
      "Ajouter l'ail 1 minute avant la fin de cuisson.",
      "Parsemer de persil haché, saler et servir immédiatement."
    ],
    nutrition: { calories: 250, protein: 33, carbs: 4, fat: 12, fiber: 0 },
    tips: "Le cabillaud frais ne doit jamais être trop cuit au risque de devenir sec. Vérifiez la cuisson en effleurant : il doit s'effeuiller légèrement.",
    isCustom: false
  },
  {
    id: "express-omelette-fines-herbes",
    name: "Omelette Baveuse aux Fines Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Œufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Persil frais haché", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Estragon frais haché", qty: 1, unit: "c. à café", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Battre les œufs en omelette avec le sel et le poivre.",
      "Ciseler finement la ciboulette, hacher le persil et l'estragon.",
      "Incorporer les herbes fraîches aux œufs battus.",
      "Faire fondre le beurre dans une poêle antiadhésive à feu moyen-vif.",
      "Quand le beurre mousse, verser les œufs d'un coup.",
      "Remuer rapidement avec une spatule en faisant des petits cercles.",
      "Quand les bords commencent à prendre mais que le centre est encore baveux, plier l'omelette en deux.",
      "Faire glisser dans l'assiette immédiatement."
    ],
    nutrition: { calories: 220, protein: 18, carbs: 1, fat: 16, fiber: 0 },
    tips: "L'omelette baveuse est prête en moins de 5 minutes. Les œufs frais sont la base du régime anti-histamine : consommez-les toujours fraîchement cuits.",
    isCustom: false
  },
  {
    id: "rapide-omelette-champignons-mozzarella",
    name: "Omelette aux Champignons et Mozzarella Fraîche",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 7,
    cookTime: 8,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Œufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Champignons de Paris frais", qty: 100, unit: "g", optional: false },
      { food: "Mozzarella fraîche", qty: 80, unit: "g", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 2, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Trancher les champignons et couper la mozzarella en petits dés.",
      "Faire revenir les champignons dans la moitié du beurre 3 minutes à feu vif. Réserver.",
      "Battre les œufs avec le sel et la ciboulette ciselée.",
      "Faire fondre le reste du beurre dans une poêle antiadhésive.",
      "Verser les œufs et faire cuire en remuant légèrement.",
      "Quand les bords prennent, déposer les champignons et la mozzarella sur une moitié.",
      "Plier l'omelette, couvrir 1 minute pour faire fondre la mozzarella.",
      "Servir immédiatement."
    ],
    nutrition: { calories: 280, protein: 22, carbs: 3, fat: 20, fiber: 1 },
    tips: "La mozzarella fraîche (dans sa saumure) est bien tolérée dans le régime anti-histamine, contrairement aux fromages affinés. Consommez-la le jour de l'ouverture.",
    isCustom: false
  },
  {
    id: "quick-œufs-brouillés-crème",
    name: "Œufs Brouillés Crémeux aux Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 3,
    cookTime: 7,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Œufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Ciboulette fraîche ciselée", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Pain de mie frais", qty: 2, unit: "tranches", optional: true }
    ],
    steps: [
      "Battre les œufs avec la crème fraîche et le sel.",
      "Faire fondre le beurre dans une petite casserole à fond épais à feu très doux.",
      "Verser le mélange d'œufs et remuer constamment avec une spatule souple.",
      "Maintenir le feu très doux et ne jamais cesser de remuer.",
      "Quand les œufs commencent à épaissir en petits morceaux crémeux, retirer du feu.",
      "Continuer à remuer hors du feu encore 30 secondes (la chaleur résiduelle suffit).",
      "Parsemer de ciboulette et servir immédiatement sur des toasts."
    ],
    nutrition: { calories: 230, protein: 16, carbs: 2, fat: 18, fiber: 0 },
    tips: "La clé des œufs brouillés crémeux : feu très doux et patience. Ils ne doivent jamais bouillir. Retirez toujours du feu une à deux secondes avant d'être à la consistance voulue.",
    isCustom: false
  },
  {
    id: "fast-œufs-pochés-épinards-remplacés",
    name: "Œufs Pochés sur Lit de Petits Pois à la Crème",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Œufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Petits pois surgelés", qty: 200, unit: "g", optional: false },
      { food: "Crème fraîche", qty: 80, unit: "ml", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Menthe fraîche", qty: 3, unit: "feuilles", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Faire cuire les petits pois surgelés dans l'eau bouillante salée 5 minutes.",
      "Égoutter et mixer grossièrement avec le beurre, la crème et la menthe.",
      "Saler la purée de petits pois et maintenir au chaud.",
      "Faire chauffer une casserole d'eau frémissante (ne pas faire bouillir).",
      "Casser chaque œuf dans une tasse, puis le faire glisser doucement dans l'eau.",
      "Pocher les œufs 3 minutes pour un jaune coulant.",
      "Répartir la purée de petits pois dans les assiettes.",
      "Déposer les œufs pochés égouttés sur la purée et servir immédiatement."
    ],
    nutrition: { calories: 290, protein: 18, carbs: 15, fat: 18, fiber: 5 },
    tips: "Pour un poché parfait : l'eau doit être frémissante et non bouillante. Ajoutez un trait de vinaigre blanc dans l'eau pour aider la coagulation du blanc.",
    isCustom: false
  },
  {
    id: "express-omelette-ricotta-courgette",
    name: "Omelette Roulée à la Ricotta et Courgette",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 8,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Œufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Ricotta fraîche", qty: 100, unit: "g", optional: false },
      { food: "Courgette", qty: 1, unit: "petite", optional: false },
      { food: "Beurre", qty: 15, unit: "g", optional: false },
      { food: "Basilic frais", qty: 5, unit: "feuilles", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Râper finement la courgette et la presser dans un torchon pour enlever l'excédent d'eau.",
      "Mélanger la ricotta avec la courgette râpée, le basilic ciselé et une pincée de sel.",
      "Battre les œufs avec le sel.",
      "Faire fondre le beurre dans une poêle antiadhésive à feu moyen.",
      "Verser les œufs et cuire en laissant prendre sans remuer.",
      "Quand le dessus est encore légèrement tremblant, étaler la garniture ricotta-courgette sur toute la surface.",
      "Rouler délicatement l'omelette sur elle-même.",
      "Couper en deux et servir immédiatement."
    ],
    nutrition: { calories: 265, protein: 19, carbs: 4, fat: 19, fiber: 1 },
    tips: "La ricotta fraîche est parfaitement tolérée. Pressez bien la courgette râpée pour éviter que l'omelette ne soit détrempée.",
    isCustom: false
  },
  {
    id: "quick-tagliatelles-beurre-sauge",
    name: "Tagliatelles au Beurre de Sauge",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 2,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Tagliatelles fraîches ou sèches", qty: 200, unit: "g", optional: false },
      { food: "Beurre", qty: 60, unit: "g", optional: false },
      { food: "Sauge fraîche", qty: 8, unit: "feuilles", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Faire bouillir une grande casserole d'eau salée.",
      "Cuire les tagliatelles selon les instructions du paquet (7 à 10 min pour les sèches, 2 à 3 min pour les fraîches).",
      "Dans une poêle, faire fondre le beurre à feu moyen.",
      "Ajouter les feuilles de sauge entières et l'ail écrasé.",
      "Laisser les feuilles de sauge croustiller 2 à 3 minutes jusqu'à ce que le beurre devienne légèrement noisette.",
      "Égoutter les pâtes en réservant une tasse d'eau de cuisson.",
      "Verser les pâtes dans le beurre de sauge, mélanger en ajoutant un peu d'eau de cuisson si nécessaire.",
      "Servir immédiatement avec du poivre blanc."
    ],
    nutrition: { calories: 420, protein: 10, carbs: 55, fat: 18, fiber: 2 },
    tips: "Ce plat ultra-simple nécessite des ingrédients de grande qualité. Utilisez un bon beurre pour un résultat optimal. Les pâtes fraîches réduisent encore le temps de cuisson.",
    isCustom: false
  },
  {
    id: "rapide-pâtes-crème-ricotta-basilic",
    name: "Penne à la Crème de Ricotta et Basilic",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 3,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Penne", qty: 180, unit: "g", optional: false },
      { food: "Ricotta fraîche", qty: 150, unit: "g", optional: false },
      { food: "Crème fraîche", qty: 50, unit: "ml", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false },
      { food: "Basilic frais", qty: 10, unit: "feuilles", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Cuire les penne dans une grande casserole d'eau bouillante salée selon le paquet.",
      "Pendant ce temps, mixer la ricotta avec la crème, l'ail et le basilic.",
      "Saler le mélange et ajouter l'huile d'olive.",
      "Égoutter les pâtes en réservant 2 cuillères d'eau de cuisson.",
      "Remettre les pâtes dans la casserole hors du feu.",
      "Ajouter la crème de ricotta et l'eau de cuisson.",
      "Mélanger rapidement pour enrober toutes les pâtes.",
      "Garnir de feuilles de basilic frais entières et servir."
    ],
    nutrition: { calories: 450, protein: 16, carbs: 58, fat: 18, fiber: 3 },
    tips: "La ricotta ne doit jamais être chauffée directement pour éviter qu'elle ne grumelle. Ajoutez-la toujours hors du feu sur les pâtes chaudes.",
    isCustom: false
  },
  {
    id: "fast-spaghetti-beurre-herbes-œuf",
    name: "Spaghetti Carbonara Sans Fromage Affiné",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 3,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Spaghetti", qty: 180, unit: "g", optional: false },
      { food: "Œufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: true },
      { food: "Persil frais haché", qty: 2, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Cuire les spaghetti dans une grande casserole d'eau bouillante salée.",
      "Battre les œufs avec la crème fraîche, le sel et le poivre dans un bol.",
      "Dans une poêle, faire fondre le beurre et faire revenir l'ail 1 minute.",
      "Égoutter les spaghetti en réservant une tasse d'eau de cuisson chaude.",
      "Retirer la poêle du feu et ajouter les spaghetti.",
      "Verser le mélange œufs-crème sur les pâtes et mélanger très rapidement.",
      "Ajouter un peu d'eau de cuisson si la sauce est trop épaisse.",
      "Parsemer de persil et servir immédiatement."
    ],
    nutrition: { calories: 480, protein: 20, carbs: 62, fat: 16, fiber: 3 },
    tips: "Retirez impérativement la poêle du feu avant d'ajouter le mélange œufs-crème pour éviter la coagulation. La chaleur résiduelle des pâtes suffit à cuire la sauce.",
    isCustom: false
  },
  {
    id: "express-farfalle-courgette-ricotta",
    name: "Farfalle à la Courgette Poêlée et Ricotta",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Farfalle", qty: 180, unit: "g", optional: false },
      { food: "Courgettes", qty: 2, unit: "petites", optional: false },
      { food: "Ricotta fraîche", qty: 120, unit: "g", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Menthe fraîche", qty: 5, unit: "feuilles", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Cuire les farfalle selon le paquet dans l'eau bouillante salée.",
      "Couper les courgettes en dés de 1 cm.",
      "Dans une grande poêle, chauffer l'huile d'olive à feu vif.",
      "Faire sauter les dés de courgette avec l'ail émincé 7 à 8 minutes.",
      "Égoutter les pâtes en gardant 3 cuillères d'eau de cuisson.",
      "Ajouter les pâtes dans la poêle avec les courgettes.",
      "Incorporer la ricotta et l'eau de cuisson, mélanger délicatement.",
      "Parsemer de menthe fraîche ciselée et servir."
    ],
    nutrition: { calories: 430, protein: 14, carbs: 60, fat: 15, fiber: 4 },
    tips: "Faites sauter les courgettes à feu vraiment vif pour qu'elles soient dorées et non molles. La ricotta doit être ajoutée hors du feu.",
    isCustom: false
  },
  {
    id: "quick-riz-poulet-petits-pois",
    name: "Riz Sauté au Poulet et Petits Pois",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz précuit en sachet micro-ondes", qty: 250, unit: "g", optional: false },
      { food: "Blanc de poulet frais en petits dés", qty: 200, unit: "g", optional: false },
      { food: "Petits pois surgelés", qty: 100, unit: "g", optional: false },
      { food: "Œuf frais", qty: 1, unit: "pièce", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Faire chauffer le sachet de riz précuit au micro-ondes selon les instructions (2 minutes).",
      "Faire chauffer l'huile dans un wok ou grande poêle à feu très vif.",
      "Faire sauter les dés de poulet 5 minutes jusqu'à dorure.",
      "Ajouter l'ail émincé et les petits pois surgelés, cuire 3 minutes.",
      "Pousser le tout sur les bords et verser l'œuf au centre.",
      "Brouiller l'œuf rapidement puis mélanger avec le reste.",
      "Ajouter le riz précuit et mélanger 2 minutes à feu vif.",
      "Saler et servir immédiatement."
    ],
    nutrition: { calories: 420, protein: 32, carbs: 48, fat: 10, fiber: 3 },
    tips: "Le riz précuit en sachet est le secret du riz sauté express. Utilisez un riz de la veille si vous en avez : il saute mieux car il est plus sec.",
    isCustom: false
  },
  {
    id: "rapide-couscous-poulet-légumes",
    name: "Couscous Express au Poulet et Légumes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Semoule de couscous fine", qty: 160, unit: "g", optional: false },
      { food: "Blanc de poulet frais en dés", qty: 200, unit: "g", optional: false },
      { food: "Courgette", qty: 1, unit: "petite", optional: false },
      { food: "Carottes", qty: 1, unit: "grande", optional: false },
      { food: "Bouillon de volaille (cube sans glutamate)", qty: 300, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Cumin", qty: 1, unit: "c. à café", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper la courgette et les carottes en petits dés.",
      "Faire chauffer l'huile dans une poêle et faire dorer les dés de poulet 5 minutes.",
      "Ajouter les légumes et le cumin, cuire 5 minutes en remuant.",
      "Pendant ce temps, faire bouillir 300 ml de bouillon.",
      "Verser la semoule dans un saladier, couvrir avec le bouillon bouillant.",
      "Couvrir d'une assiette et laisser gonfler 5 minutes.",
      "Égrainer la semoule avec une fourchette et l'huile d'olive restante.",
      "Mélanger la semoule avec le poulet et les légumes, servir."
    ],
    nutrition: { calories: 460, protein: 34, carbs: 55, fat: 12, fiber: 4 },
    tips: "Le couscous à la semoule fine ne nécessite aucune cuisson : l'eau bouillante suffit. Choisissez un bouillon cube sans glutamate (MSG) pour rester anti-histamine.",
    isCustom: false
  },
  {
    id: "fast-quinoa-légumes-œuf",
    name: "Bowl de Quinoa aux Légumes Rôtis et Œuf Poché",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 18,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Quinoa précuit en sachet", qty: 250, unit: "g", optional: false },
      { food: "Œufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Brocoli en fleurettes", qty: 150, unit: "g", optional: false },
      { food: "Carottes", qty: 1, unit: "grande", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Ail en poudre", qty: 1, unit: "c. à café", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 220°C (grill si possible).",
      "Couper les carottes en bâtonnets et les mélanger avec le brocoli, l'huile, l'ail en poudre et le sel.",
      "Étaler sur une plaque et enfourner 15 minutes.",
      "Faire chauffer le sachet de quinoa au micro-ondes 2 minutes.",
      "Porter une casserole d'eau frémissante, pocher les œufs 3 minutes.",
      "Répartir le quinoa dans deux bols.",
      "Ajouter les légumes rôtis par-dessus.",
      "Déposer un œuf poché sur chaque bol et servir immédiatement."
    ],
    nutrition: { calories: 390, protein: 18, carbs: 45, fat: 15, fiber: 6 },
    tips: "Le quinoa précuit est un gain de temps considérable. Il se trouve en sachet micro-ondes dans tous les supermarchés. Préparez les légumes rôtis le week-end pour encore plus de rapidité.",
    isCustom: false
  },
  {
    id: "express-riz-crevettes-remplacé",
    name: "Riz Pilaf Rapide au Beurre et Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 3,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz basmati", qty: 160, unit: "g", optional: false },
      { food: "Bouillon de légumes (sans glutamate)", qty: 320, unit: "ml", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "petit", optional: false },
      { food: "Persil frais haché", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Ciboulette fraîche", qty: 2, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Émincer finement l'oignon.",
      "Dans une casserole, faire fondre 20 g de beurre à feu moyen.",
      "Faire revenir l'oignon 2 minutes jusqu'à transparence.",
      "Ajouter le riz et nacrer 1 minute en remuant.",
      "Verser le bouillon chaud, porter à ébullition puis baisser à feu doux.",
      "Couvrir et cuire 12 minutes sans soulever le couvercle.",
      "Retirer du feu, laisser reposer 2 minutes couvercle fermé.",
      "Incorporer le reste du beurre, le persil et la ciboulette avec une fourchette."
    ],
    nutrition: { calories: 320, protein: 6, carbs: 55, fat: 8, fiber: 1 },
    tips: "Le riz pilaf au beurre est un accompagnement polyvalent prêt en moins de 20 minutes. Choisissez un bouillon cube certifié sans glutamate (MSG).",
    isCustom: false
  },
  {
    id: "quick-soupe-courgette-crème",
    name: "Velouté Express de Courgettes à la Crème",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Courgettes", qty: 3, unit: "moyennes", optional: false },
      { food: "Crème fraîche", qty: 80, unit: "ml", optional: false },
      { food: "Bouillon de légumes (sans glutamate)", qty: 400, unit: "ml", optional: false },
      { food: "Oignon", qty: 1, unit: "petit", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Basilic frais", qty: 5, unit: "feuilles", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper les courgettes en rondelles et émincer l'oignon.",
      "Faire fondre le beurre dans une casserole.",
      "Faire revenir l'oignon 2 minutes.",
      "Ajouter les courgettes et faire revenir 3 minutes.",
      "Verser le bouillon chaud, couvrir et cuire 10 minutes à feu moyen.",
      "Mixer finement avec un mixeur plongeant.",
      "Incorporer la crème fraîche, rectifier l'assaisonnement.",
      "Garnir de basilic frais et servir avec du pain grillé."
    ],
    nutrition: { calories: 200, protein: 5, carbs: 14, fat: 14, fiber: 3 },
    tips: "Pour un velouté encore plus rapide, utilisez des courgettes surgelées déjà coupées en rondelles. Le temps de cuisson reste identique.",
    isCustom: false
  },
  {
    id: "rapide-soupe-carotte-gingembre",
    name: "Soupe de Carottes au Gingembre Frais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Carottes", qty: 400, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 1, unit: "morceau de 2 cm", optional: false },
      { food: "Bouillon de légumes (sans glutamate)", qty: 500, unit: "ml", optional: false },
      { food: "Crème de coco", qty: 50, unit: "ml", optional: true },
      { food: "Huile d'olive", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Oignon", qty: 1, unit: "petit", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Peler et couper les carottes en rondelles fines. Émincer l'oignon. Râper le gingembre.",
      "Chauffer l'huile dans une casserole et faire revenir l'oignon 2 minutes.",
      "Ajouter les carottes et le gingembre, mélanger 1 minute.",
      "Verser le bouillon chaud et cuire 12 minutes à feu moyen jusqu'à ce que les carottes soient tendres.",
      "Mixer finement avec un mixeur plongeant.",
      "Incorporer la crème de coco si utilisée.",
      "Rectifier l'assaisonnement et servir chaud."
    ],
    nutrition: { calories: 175, protein: 3, carbs: 22, fat: 8, fiber: 5 },
    tips: "Les carottes coupées en rondelles fines cuisent en 12 minutes seulement. Le gingembre frais est préférable au gingembre en poudre pour une meilleure tolérance.",
    isCustom: false
  },
  {
    id: "fast-soupe-poulet-vermicelles",
    name: "Bouillon de Poulet aux Vermicelles et Légumes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blanc de poulet frais en petits morceaux", qty: 150, unit: "g", optional: false },
      { food: "Vermicelles fins", qty: 60, unit: "g", optional: false },
      { food: "Carottes", qty: 1, unit: "grande", optional: false },
      { food: "Bouillon de volaille maison ou cube sans glutamate", qty: 800, unit: "ml", optional: false },
      { food: "Persil frais haché", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper les carottes en petits dés et le poulet en petits morceaux.",
      "Porter le bouillon à ébullition dans une casserole.",
      "Ajouter le poulet et les carottes dès l'ébullition.",
      "Cuire 7 minutes à feu moyen.",
      "Ajouter les vermicelles et cuire encore 3 à 4 minutes.",
      "Rectifier l'assaisonnement.",
      "Servir bien chaud parsemé de persil frais."
    ],
    nutrition: { calories: 230, protein: 22, carbs: 25, fat: 4, fiber: 2 },
    tips: "Ce bouillon réconfortant est idéal les soirs de semaine. Préparez du bouillon maison le week-end et congelez-le en portions pour un accès rapide.",
    isCustom: false
  },
  {
    id: "express-soupe-brocoli-crème",
    name: "Crème de Brocoli Express",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Brocoli en fleurettes (frais ou surgelé)", qty: 350, unit: "g", optional: false },
      { food: "Crème fraîche", qty: 80, unit: "ml", optional: false },
      { food: "Bouillon de légumes (sans glutamate)", qty: 400, unit: "ml", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false },
      { food: "Beurre", qty: 15, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Faire fondre le beurre dans une casserole.",
      "Faire revenir l'ail écrasé 1 minute.",
      "Ajouter le brocoli (frais ou surgelé directement).",
      "Verser le bouillon chaud et cuire 10 minutes à feu moyen.",
      "Mixer finement avec un mixeur plongeant.",
      "Incorporer la crème fraîche et la noix de muscade.",
      "Saler, chauffer 1 minute sans faire bouillir et servir."
    ],
    nutrition: { calories: 185, protein: 7, carbs: 13, fat: 12, fiber: 4 },
    tips: "Le brocoli surgelé est une excellente alternative : il est souvent plus riche en nutriments que le brocoli frais et supprime l'étape de découpe.",
    isCustom: false
  },
  {
    id: "quick-salade-poulet-avocat-remplacé",
    name: "Salade de Poulet Poêlé aux Herbes et Champignons",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blanc de poulet frais", qty: 250, unit: "g", optional: false },
      { food: "Champignons de Paris frais", qty: 100, unit: "g", optional: false },
      { food: "Laitue ou mâche", qty: 100, unit: "g", optional: false },
      { food: "Concombre", qty: 0.5, unit: "pièce", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Ciboulette fraîche", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper le poulet en lamelles et les champignons en tranches.",
      "Faire chauffer 1 cuillère d'huile dans une poêle à feu vif.",
      "Faire sauter le poulet 5 minutes puis les champignons 3 minutes.",
      "Saler et laisser tiédir légèrement.",
      "Préparer la vinaigrette avec l'huile d'olive restante, du sel et la ciboulette.",
      "Laver et essorer la salade. Couper le concombre en rondelles.",
      "Disposer la salade et le concombre dans les assiettes.",
      "Déposer le poulet et les champignons tièdes par-dessus, arroser de vinaigrette."
    ],
    nutrition: { calories: 310, protein: 36, carbs: 5, fat: 16, fiber: 2 },
    tips: "Cette salade tiède est parfaite pour un dîner léger de semaine. Le poulet tiède sur la salade froide crée un contraste agréable de textures et de températures.",
    isCustom: false
  },
  {
    id: "rapide-salade-quinoa-légumes",
    name: "Salade de Quinoa aux Légumes Croquants",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Quinoa précuit en sachet", qty: 250, unit: "g", optional: false },
      { food: "Concombre", qty: 1, unit: "moyen", optional: false },
      { food: "Carottes", qty: 2, unit: "moyennes", optional: false },
      { food: "Petits pois surgelés décongelés", qty: 100, unit: "g", optional: false },
      { food: "Persil frais haché", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Menthe fraîche", qty: 5, unit: "feuilles", optional: true },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Chauffer le sachet de quinoa au micro-ondes 2 minutes, puis laisser refroidir légèrement.",
      "Couper le concombre en petits dés et les carottes en julienne fine.",
      "Décongeler les petits pois en les passant sous l'eau chaude ou au micro-ondes.",
      "Dans un saladier, mélanger le quinoa tiède avec les légumes.",
      "Préparer la vinaigrette : huile d'olive, sel, persil et menthe.",
      "Verser la vinaigrette sur la salade et mélanger.",
      "Laisser reposer 5 minutes pour que les saveurs se mélangent.",
      "Servir à température ambiante."
    ],
    nutrition: { calories: 350, protein: 11, carbs: 42, fat: 14, fiber: 6 },
    tips: "Cette salade se conserve jusqu'au lendemain au réfrigérateur. Idéale à préparer la veille au soir pour le déjeuner du lendemain.",
    isCustom: false
  },
  {
    id: "fast-salade-lentilles-remplacée",
    name: "Salade Tiède de Pommes de Terre aux Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pommes de terre nouvelles", qty: 350, unit: "g", optional: false },
      { food: "Œufs durs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Ciboulette fraîche", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Persil frais haché", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Crème fraîche", qty: 2, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper les pommes de terre en deux et les cuire 12 à 15 minutes dans l'eau bouillante salée.",
      "Pendant ce temps, faire cuire les œufs durs 8 minutes.",
      "Préparer la vinaigrette avec l'huile d'olive, la crème, le sel, la ciboulette et le persil.",
      "Égoutter les pommes de terre et les laisser tiédir 2 minutes.",
      "Peler et couper les œufs durs en quartiers.",
      "Mélanger les pommes de terre tièdes avec la vinaigrette aux herbes.",
      "Disposer les œufs par-dessus et servir tiède."
    ],
    nutrition: { calories: 340, protein: 10, carbs: 35, fat: 18, fiber: 3 },
    tips: "Les pommes de terre nouvelles n'ont pas besoin d'être pelées : leur peau fine est comestible et apporte des fibres supplémentaires.",
    isCustom: false
  },
  {
    id: "quick-collation-toast-cream-cheese",
    name: "Toasts au Cream Cheese et Concombre",
    category: "collation",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 3,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pain complet frais en tranches", qty: 4, unit: "tranches", optional: false },
      { food: "Cream cheese (Philadelphia frais)", qty: 80, unit: "g", optional: false },
      { food: "Concombre", qty: 0.5, unit: "pièce", optional: false },
      { food: "Ciboulette fraîche ciselée", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Aneth frais", qty: 1, unit: "c. à café", optional: true }
    ],
    steps: [
      "Faire griller les tranches de pain au grille-pain jusqu'à dorure.",
      "Pendant ce temps, couper le concombre en fines rondelles.",
      "Mélanger le cream cheese avec la ciboulette et l'aneth.",
      "Saler légèrement.",
      "Tartiner généreusement le cream cheese aux herbes sur les toasts.",
      "Disposer les rondelles de concombre sur le cream cheese.",
      "Parsemer d'un peu de ciboulette supplémentaire et servir immédiatement."
    ],
    nutrition: { calories: 250, protein: 8, carbs: 30, fat: 11, fiber: 3 },
    tips: "Le cream cheese frais est parfaitement toléré dans le régime anti-histamine. Évitez les variétés aromatisées aux épices préparées qui peuvent contenir des additifs.",
    isCustom: false
  },
  {
    id: "express-collation-riz-galettes-beurre",
    name: "Galettes de Riz Soufflé au Beurre d'Amande",
    category: "collation",
    mealType: ["dejeuner", "diner"],
    prepTime: 3,
    cookTime: 0,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Galettes de riz soufflé nature", qty: 4, unit: "pièces", optional: false },
      { food: "Beurre d'amande (purée d'amandes blanches)", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Miel toutes fleurs", qty: 1, unit: "c. à café", optional: true },
      { food: "Cannelle en poudre", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Disposer les galettes de riz sur une assiette.",
      "Tartiner chaque galette d'une bonne couche de beurre d'amande.",
      "Ajouter un léger filet de miel si désiré.",
      "Saupoudrer d'une pincée de cannelle.",
      "Servir immédiatement."
    ],
    nutrition: { calories: 180, protein: 4, carbs: 22, fat: 8, fiber: 2 },
    tips: "La purée d'amandes blanches (non grillées) est bien tolérée dans le régime anti-histamine. Évitez les purées d'amandes complètes ou grillées qui peuvent être problématiques.",
    isCustom: false
  },
  {
    id: "quick-nouilles-riz-poulet-bouillon",
    name: "Soupe de Nouilles de Riz au Poulet",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Nouilles de riz fines", qty: 120, unit: "g", optional: false },
      { food: "Blanc de poulet frais en lamelles", qty: 180, unit: "g", optional: false },
      { food: "Bouillon de volaille (sans glutamate)", qty: 700, unit: "ml", optional: false },
      { food: "Brocoli en petites fleurettes", qty: 100, unit: "g", optional: false },
      { food: "Gingembre frais râpé", qty: 1, unit: "c. à café", optional: true },
      { food: "Coriandre fraîche", qty: 5, unit: "feuilles", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Faire tremper les nouilles de riz dans de l'eau tiède 5 minutes.",
      "Porter le bouillon à ébullition avec le gingembre râpé.",
      "Ajouter les lamelles de poulet et cuire 4 minutes.",
      "Ajouter le brocoli et cuire 3 minutes.",
      "Égoutter les nouilles et les ajouter dans le bouillon.",
      "Cuire encore 1 à 2 minutes, les nouilles doivent être tendres.",
      "Rectifier l'assaisonnement et servir garnies de coriandre fraîche."
    ],
    nutrition: { calories: 320, protein: 28, carbs: 40, fat: 5, fiber: 2 },
    tips: "Les nouilles de riz se réhydratent dans l'eau tiède sans cuisson préalable, ce qui est un énorme gain de temps. La coriandre fraîche est bien tolérée en garniture.",
    isCustom: false
  },
  {
    id: "rapide-turkey-légumes-poêlée",
    name: "Émincé de Dinde aux Petits Légumes Printaniers",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Escalope de dinde fraîche en lamelles", qty: 300, unit: "g", optional: false },
      { food: "Petits pois surgelés", qty: 100, unit: "g", optional: false },
      { food: "Haricots verts surgelés", qty: 100, unit: "g", optional: false },
      { food: "Carottes", qty: 1, unit: "grande", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Estragon frais", qty: 1, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Couper les carottes en petits dés. Décongeler rapidement les légumes surgelés au micro-ondes 3 minutes.",
      "Faire fondre le beurre dans une grande poêle.",
      "Faire sauter les lamelles de dinde 5 à 6 minutes à feu vif.",
      "Ajouter les carottes et cuire 3 minutes.",
      "Incorporer les petits pois et les haricots verts, cuire 2 à 3 minutes.",
      "Parsemer d'estragon frais haché.",
      "Saler et servir immédiatement."
    ],
    nutrition: { calories: 295, protein: 38, carbs: 14, fat: 10, fiber: 5 },
    tips: "La dinde fraîche est une excellente alternative au poulet dans le régime anti-histamine. Choisissez toujours des escalopes fraîches, jamais de dinde préparée ou marinée.",
    isCustom: false
  },
  {
    id: "fast-patate-douce-œufs-épices",
    name: "Hash de Patate Douce et Œufs au Plat",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Patate douce", qty: 300, unit: "g", optional: false },
      { food: "Œufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Oignon", qty: 1, unit: "moyen", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Paprika doux", qty: 1, unit: "c. à café", optional: false },
      { food: "Persil frais haché", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Peler la patate douce et la râper grossièrement ou la couper en petits dés.",
      "Émincer l'oignon.",
      "Chauffer l'huile dans une grande poêle antiadhésive à feu moyen-vif.",
      "Faire revenir l'oignon 2 minutes.",
      "Ajouter la patate douce râpée, le paprika et le sel.",
      "Cuire 8 à 10 minutes en retournant régulièrement jusqu'à dorure.",
      "Faire 4 petits puits dans le hash, casser un œuf dans chacun.",
      "Couvrir et cuire 3 à 4 minutes pour que les blancs soient pris.",
      "Parsemer de persil et servir directement dans la poêle."
    ],
    nutrition: { calories: 360, protein: 16, carbs: 38, fat: 16, fiber: 5 },
    tips: "Râper la patate douce plutôt que de la couper en dés accélère considérablement la cuisson. Ce plat est rassasiant et riche en bêta-carotène.",
    isCustom: false
  },
  {
    id: "quick-chou-fleur-rôti-crème",
    name: "Chou-fleur Rôti à la Crème et Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 8,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Chou-fleur en fleurettes", qty: 400, unit: "g", optional: false },
      { food: "Crème fraîche épaisse", qty: 80, unit: "ml", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Persil frais haché", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Noix de muscade", qty: 1, unit: "pincée", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 220°C.",
      "Couper le chou-fleur en petites fleurettes.",
      "Mélanger avec le beurre fondu, l'ail émincé et le sel.",
      "Étaler sur une plaque de cuisson.",
      "Rôtir 12 à 15 minutes jusqu'à ce que les bords soient dorés et caramélisés.",
      "Pendant ce temps, chauffer la crème avec la muscade et saler.",
      "Verser la crème chaude sur le chou-fleur rôti.",
      "Parsemer de persil et servir immédiatement."
    ],
    nutrition: { calories: 210, protein: 5, carbs: 13, fat: 16, fiber: 4 },
    tips: "La clé du chou-fleur rôti réussi : fleurettes de taille similaire et four très chaud. La caramélisation lui apporte un goût de noisette incroyable.",
    isCustom: false
  },
  {
    id: "express-pâtes-beurre-courgette-œuf",
    name: "Linguine au Beurre, Courgette et Œuf Coulant",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Linguine", qty: 180, unit: "g", optional: false },
      { food: "Courgette", qty: 1, unit: "grande", optional: false },
      { food: "Œufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false },
      { food: "Parmesan ou ricotta salata (facultatif)", qty: 20, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Cuire les linguine dans l'eau bouillante salée selon le paquet.",
      "Couper la courgette en fins rubans à l'aide d'un épluche-légumes ou en julienne.",
      "Dans une poêle, faire fondre le beurre avec l'ail émincé.",
      "Ajouter les rubans de courgette et sauter 3 à 4 minutes.",
      "Faire frire les œufs au plat dans une autre poêle avec un peu de beurre.",
      "Égoutter les pâtes, mélanger avec le beurre et les courgettes.",
      "Répartir dans les assiettes, déposer un œuf au plat sur chaque portion.",
      "Briser le jaune au moment de déguster et mélanger."
    ],
    nutrition: { calories: 490, protein: 16, carbs: 62, fat: 20, fiber: 4 },
    tips: "Le jaune d'œuf coulant mélangé aux pâtes crée une sauce onctueuse naturelle sans avoir besoin de fromage affiné. Un classique de la cuisine express.",
    isCustom: false
  }
];
