const RECIPES_BATCH_8 = [
  {
    id: "pdej-porridge-pomme-cannelle",
    name: "Porridge Pomme Cannelle",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Flocons d'avoine", qty: 160, unit: "g", optional: false },
      { food: "Lait entier", qty: 400, unit: "ml", optional: false },
      { food: "Pomme", qty: 1, unit: "pièce", optional: false },
      { food: "Cannelle moulue", qty: 1, unit: "c. à café", optional: false },
      { food: "Miel", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Beurre frais", qty: 10, unit: "g", optional: true }
    ],
    steps: [
      "Éplucher et râper finement la pomme. Réserver.",
      "Dans une casserole, verser les flocons d'avoine et le lait froid. Mélanger.",
      "Faire chauffer à feu moyen en remuant constamment pendant 7 à 8 minutes jusqu'à ce que le mélange épaississe.",
      "Incorporer la pomme râpée et la cannelle. Cuire encore 2 minutes.",
      "Servir dans deux bols, napper de miel et ajouter le beurre si désiré.",
      "Déguster chaud immédiatement."
    ],
    nutrition: { calories: 340, protein: 10, carbs: 58, fat: 8, fiber: 5 },
    tips: "Utiliser une pomme bien mûre de type Gala ou Golden pour plus de douceur. Râper la pomme au dernier moment pour éviter l'oxydation. La cannelle doit rester modérée car les épices peuvent être irritantes en grande quantité.",
    isCustom: false
  },
  {
    id: "pdej-overnight-oats-poire-vanille",
    name: "Overnight Oats Poire et Vanille",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Flocons d'avoine", qty: 160, unit: "g", optional: false },
      { food: "Lait entier", qty: 300, unit: "ml", optional: false },
      { food: "Crème fraîche liquide", qty: 100, unit: "ml", optional: false },
      { food: "Poire", qty: 2, unit: "pièces", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Sirop d'érable", qty: 3, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "La veille au soir, mélanger les flocons d'avoine avec le lait, la crème et la poudre de vanille.",
      "Ajouter 2 cuillères à soupe de sirop d'érable et bien remuer.",
      "Couvrir et placer au réfrigérateur toute la nuit (minimum 8 heures).",
      "Le matin, peler et couper les poires en petits dés.",
      "Sortir les overnight oats du réfrigérateur, remuer et ajouter un peu de lait si trop épais.",
      "Garnir avec les dés de poire et arroser du sirop d'érable restant."
    ],
    nutrition: { calories: 380, protein: 9, carbs: 62, fat: 11, fiber: 6 },
    tips: "Préparer deux bocaux individuels le soir pour un petit-déjeuner prêt en 2 minutes le matin. La poudre de vanille sans alcool est essentielle pour éviter les réactions. Consommer dans les 24 heures une fois préparé.",
    isCustom: false
  },
  {
    id: "pdej-porridge-riz-lait-coco",
    name: "Porridge de Riz au Lait de Coco",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 5,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz à dessert à grain rond", qty: 120, unit: "g", optional: false },
      { food: "Lait de coco", qty: 300, unit: "ml", optional: false },
      { food: "Lait entier", qty: 200, unit: "ml", optional: false },
      { food: "Sucre en poudre", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Melon", qty: 150, unit: "g", optional: true }
    ],
    steps: [
      "Rincer le riz à l'eau froide.",
      "Dans une casserole, mélanger le lait de coco et le lait entier. Porter à frémissement.",
      "Ajouter le riz rincé et la poudre de vanille.",
      "Cuire à feu doux pendant 18 à 20 minutes en remuant régulièrement jusqu'à ce que le riz soit tendre et crémeux.",
      "Incorporer le sucre en fin de cuisson et ajuster selon les goûts.",
      "Servir chaud dans des bols, garnir de dés de melon frais si désiré."
    ],
    nutrition: { calories: 360, protein: 7, carbs: 65, fat: 9, fiber: 1 },
    tips: "Ce porridge de riz convient aux personnes très sensibles aux flocons d'avoine. Le lait de coco apporte une texture onctueuse naturelle. Consommer immédiatement car le riz au lait épaissit rapidement en refroidissant.",
    isCustom: false
  },
  {
    id: "pdej-overnight-oats-myrtilles",
    name: "Overnight Oats aux Myrtilles",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Flocons d'avoine", qty: 160, unit: "g", optional: false },
      { food: "Lait entier", qty: 350, unit: "ml", optional: false },
      { food: "Myrtilles fraîches", qty: 120, unit: "g", optional: false },
      { food: "Miel", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Graines de chia", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "La veille, mélanger les flocons d'avoine, les graines de chia, la poudre de vanille et le lait dans un grand bol.",
      "Couvrir d'un film alimentaire et réfrigérer toute la nuit.",
      "Le lendemain matin, remuer les overnight oats et ajouter un peu de lait si nécessaire pour obtenir la consistance souhaitée.",
      "Répartir dans deux bols.",
      "Garnir généreusement de myrtilles fraîches et napper de miel.",
      "Consommer immédiatement."
    ],
    nutrition: { calories: 355, protein: 11, carbs: 57, fat: 8, fiber: 8 },
    tips: "Les myrtilles sont mieux tolérées en quantité modérée. Utiliser des myrtilles fraîches plutôt que congelées. Les graines de chia épaississent naturellement la préparation et apportent des oméga-3. Ne pas dépasser 100 g de myrtilles par portion.",
    isCustom: false
  },
  {
    id: "pdej-crepes-sarrasin-beurre",
    name: "Crêpes au Sarrasin Beurre et Miel",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Farine de sarrasin", qty: 150, unit: "g", optional: false },
      { food: "Farine de riz", qty: 50, unit: "g", optional: false },
      { food: "Oeufs", qty: 2, unit: "pièces", optional: false },
      { food: "Lait entier", qty: 400, unit: "ml", optional: false },
      { food: "Beurre frais fondu", qty: 30, unit: "g", optional: false },
      { food: "Miel", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Sel fin", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Dans un grand bol, mélanger les farines et le sel. Faire un puits au centre.",
      "Casser les œufs dans le puits et fouetter en incorporant progressivement la farine.",
      "Ajouter le lait petit à petit en fouettant pour éviter les grumeaux.",
      "Incorporer la moitié du beurre fondu dans la pâte. Bien mélanger.",
      "Laisser reposer la pâte 15 minutes à température ambiante.",
      "Chauffer une poêle à crêpes, graisser légèrement avec un peu de beurre.",
      "Verser une louche de pâte, incliner la poêle pour bien répartir. Cuire 1 à 2 minutes de chaque côté.",
      "Servir chaud avec le reste du beurre fondu et le miel."
    ],
    nutrition: { calories: 290, protein: 9, carbs: 44, fat: 9, fiber: 3 },
    tips: "Le mélange sarrasin et farine de riz donne une texture légère tout en restant sans gluten. Ne pas utiliser de levure dans cette recette. Les crêpes peuvent être préparées à l'avance et réchauffées à la poêle au moment de servir.",
    isCustom: false
  },
  {
    id: "pdej-galettes-avoine-pomme",
    name: "Galettes d'Avoine à la Pomme",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Flocons d'avoine", qty: 120, unit: "g", optional: false },
      { food: "Farine de riz", qty: 60, unit: "g", optional: false },
      { food: "Pomme", qty: 1, unit: "pièce", optional: false },
      { food: "Oeuf", qty: 1, unit: "pièce", optional: false },
      { food: "Lait entier", qty: 150, unit: "ml", optional: false },
      { food: "Sucre de coco", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Cannelle", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Beurre frais", qty: 20, unit: "g", optional: false }
    ],
    steps: [
      "Éplucher la pomme et la râper grossièrement.",
      "Dans un bol, mélanger les flocons d'avoine, la farine de riz, le sucre de coco et la cannelle.",
      "Dans un autre bol, battre l'œuf avec le lait.",
      "Verser le mélange liquide sur les ingrédients secs. Ajouter la pomme râpée. Bien mélanger.",
      "Laisser reposer 5 minutes pour que les flocons absorbent le liquide.",
      "Faire fondre le beurre dans une poêle à feu moyen.",
      "Verser des petites quantités de pâte et aplatir légèrement. Cuire 3 minutes par face jusqu'à dorure.",
      "Servir chaud avec un filet de miel."
    ],
    nutrition: { calories: 310, protein: 9, carbs: 50, fat: 9, fiber: 4 },
    tips: "Ces galettes font un petit-déjeuner rassasiant grâce aux flocons d'avoine. Presser légèrement la pomme râpée entre les doigts pour enlever l'excès d'eau avant de l'ajouter à la pâte. Se conservent 24 heures au réfrigérateur.",
    isCustom: false
  },
  {
    id: "pdej-crepes-epeautre-ricotta",
    name: "Crêpes à l'Épeautre Ricotta et Poire",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 15,
    cookTime: 20,
    servings: 3,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Farine d'épeautre", qty: 200, unit: "g", optional: false },
      { food: "Oeufs", qty: 2, unit: "pièces", optional: false },
      { food: "Lait entier", qty: 400, unit: "ml", optional: false },
      { food: "Beurre frais fondu", qty: 25, unit: "g", optional: false },
      { food: "Ricotta fraîche", qty: 200, unit: "g", optional: false },
      { food: "Poire", qty: 2, unit: "pièces", optional: false },
      { food: "Miel", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préparer la pâte à crêpes : mélanger la farine d'épeautre, les œufs et incorporer progressivement le lait en fouettant.",
      "Ajouter le beurre fondu. Laisser reposer 15 minutes.",
      "Pendant ce temps, préparer la garniture : mélanger la ricotta avec la poudre de vanille et une cuillère à soupe de miel.",
      "Peler les poires et les couper en fines lamelles.",
      "Cuire les crêpes dans une poêle légèrement beurrée, 2 minutes de chaque côté.",
      "Garnir chaque crêpe de ricotta vanillée et de lamelles de poire.",
      "Plier ou rouler et arroser du reste de miel."
    ],
    nutrition: { calories: 395, protein: 14, carbs: 55, fat: 13, fiber: 4 },
    tips: "La farine d'épeautre est souvent bien tolérée par les personnes sensibles au gluten ordinaire. La ricotta fraîche est l'un des fromages les mieux tolérés car peu fermenté. Acheter la ricotta le jour même pour garantir sa fraîcheur.",
    isCustom: false
  },
  {
    id: "pdej-oeufs-cocotte-creme",
    name: "Œufs Cocotte à la Crème Fraîche",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Oeufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Beurre frais", qty: 10, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel fin", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C (thermostat 6).",
      "Beurrer généreusement 2 ramequins individuels allant au four.",
      "Déposer une cuillère à soupe de crème fraîche au fond de chaque ramequin.",
      "Casser délicatement 2 œufs dans chaque ramequin sans percer les jaunes.",
      "Recouvrir chaque ramequin d'une deuxième cuillère de crème fraîche.",
      "Assaisonner de sel et de poivre blanc.",
      "Placer les ramequins dans un plat rempli d'eau chaude (bain-marie). Enfourner 12 à 15 minutes.",
      "Le blanc doit être pris et le jaune encore coulant. Parsemer de ciboulette fraîche ciselée avant de servir."
    ],
    nutrition: { calories: 220, protein: 14, carbs: 1, fat: 18, fiber: 0 },
    tips: "Les œufs très frais sont essentiels. Utiliser du poivre blanc à la place du noir car il est légèrement moins irritant. La cuisson en bain-marie permet une cuisson douce et homogène. Servir avec du pain sans levure de boulanger.",
    isCustom: false
  },
  {
    id: "pdej-oeufs-brouilles-beurre",
    name: "Œufs Brouillés au Beurre Persillé",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Oeufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 30, unit: "g", optional: false },
      { food: "Crème fraîche liquide", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Persil frais", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Sel fin", qty: 1, unit: "pincée", optional: false },
      { food: "Ciboulette fraîche", qty: 1, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Battre les œufs dans un bol avec la crème fraîche. Saler légèrement.",
      "Dans une petite casserole à fond épais, faire fondre le beurre à feu très doux.",
      "Verser les œufs battus dans la casserole.",
      "Remuer continuellement avec une spatule en silicone, en faisant des allers-retours dans la casserole.",
      "Retirer du feu de temps en temps pour contrôler la cuisson. Les œufs doivent rester crémeux et fondants.",
      "Dès que les œufs commencent à prendre (environ 6 à 8 minutes), retirer du feu.",
      "Incorporer le persil et la ciboulette ciselés. Servir immédiatement sur une tartine de pain frais."
    ],
    nutrition: { calories: 240, protein: 14, carbs: 1, fat: 20, fiber: 0 },
    tips: "La clé des œufs brouillés parfaits est une cuisson très lente à feu doux. Retirer la casserole du feu avant que les œufs soient totalement pris car la chaleur résiduelle continue la cuisson. Utiliser uniquement des herbes fraîches, pas déshydratées.",
    isCustom: false
  },
  {
    id: "pdej-omelette-fines-herbes",
    name: "Omelette aux Fines Herbes",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Oeufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Beurre frais", qty: 15, unit: "g", optional: false },
      { food: "Persil frais ciselé", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Ciboulette ciselée", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Sel fin", qty: 1, unit: "pincée", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false },
      { food: "Eau froide", qty: 1, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Casser les œufs dans un bol, ajouter une cuillère à soupe d'eau froide, le sel et le poivre.",
      "Battre vigoureusement à la fourchette jusqu'à obtenir un mélange homogène et légèrement mousseux.",
      "Faire chauffer une poêle anti-adhésive à feu vif. Ajouter le beurre.",
      "Dès que le beurre mousse, verser les œufs en une seule fois.",
      "Remuer rapidement avec une fourchette tout en faisant des cercles, en ramenant les bords vers le centre.",
      "Lorsque l'omelette commence à prendre mais reste encore baveuse, parsemer les herbes fraîches.",
      "Plier l'omelette en deux et la faire glisser sur l'assiette. Servir immédiatement."
    ],
    nutrition: { calories: 230, protein: 18, carbs: 1, fat: 17, fiber: 0 },
    tips: "L'eau froide dans les œufs battus crée de la vapeur à la cuisson et rend l'omelette plus légère. La cuisson doit être rapide, pas plus de 2 minutes. Les œufs très frais sont indispensables pour les personnes à histamine élevée.",
    isCustom: false
  },
  {
    id: "pdej-smoothie-bowl-mangue-peche",
    name: "Smoothie Bowl Mangue et Pêche",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Mangue fraîche", qty: 200, unit: "g", optional: false },
      { food: "Pêche fraîche", qty: 2, unit: "pièces", optional: false },
      { food: "Lait de coco", qty: 100, unit: "ml", optional: false },
      { food: "Flocons d'avoine", qty: 40, unit: "g", optional: false },
      { food: "Miel", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Graines de chia", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Noix de coco râpée", qty: 2, unit: "c. à soupe", optional: true }
    ],
    steps: [
      "Peler et dénoyauter les pêches. Couper en morceaux.",
      "Peler la mangue et couper la chair en dés.",
      "Réserver quelques morceaux de chaque fruit pour la garniture.",
      "Dans un blender, mixer la mangue, la pêche et le lait de coco jusqu'à obtenir une consistance épaisse et crémeuse.",
      "Verser dans deux bols.",
      "Garnir avec les fruits réservés, les flocons d'avoine, les graines de chia et la noix de coco râpée.",
      "Arroser de miel et servir immédiatement."
    ],
    nutrition: { calories: 280, protein: 5, carbs: 52, fat: 7, fiber: 6 },
    tips: "Utiliser des fruits très frais et bien mûrs. La mangue est à consommer avec modération (environ 100 g par personne) car certaines personnes y sont sensibles. Ce smoothie bowl est à consommer dès préparation pour éviter l'oxydation.",
    isCustom: false
  },
  {
    id: "pdej-smoothie-bowl-melon-poire",
    name: "Smoothie Bowl Melon et Poire",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Melon Cantaloup", qty: 300, unit: "g", optional: false },
      { food: "Poire bien mûre", qty: 2, unit: "pièces", optional: false },
      { food: "Lait entier", qty: 100, unit: "ml", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Flocons d'avoine", qty: 40, unit: "g", optional: false },
      { food: "Miel", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Graines de lin moulues", qty: 1, unit: "c. à soupe", optional: true }
    ],
    steps: [
      "Éplucher et épépiner le melon. Couper en morceaux. Réserver quelques billes de melon pour la garniture.",
      "Peler les poires et les couper en dés. Réserver quelques tranches pour la garniture.",
      "Mixer le melon et les poires avec le lait et la poudre de vanille jusqu'à obtenir une consistance lisse et épaisse.",
      "Si le mélange est trop liquide, ajouter plus de melon ou placer au congélateur 10 minutes.",
      "Verser dans deux bols.",
      "Garnir avec les fruits réservés, les flocons d'avoine et les graines de lin.",
      "Napper de miel. Servir immédiatement."
    ],
    nutrition: { calories: 255, protein: 6, carbs: 50, fat: 4, fiber: 5 },
    tips: "Le melon et la poire sont deux des fruits les mieux tolérés en cas d'histamine. Veiller à utiliser un melon bien mûr mais pas trop avancé. Le smoothie bowl est à consommer immédiatement après préparation.",
    isCustom: false
  },
  {
    id: "pdej-pancakes-farine-riz",
    name: "Pancakes Moelleux à la Farine de Riz",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Farine de riz", qty: 200, unit: "g", optional: false },
      { food: "Oeufs", qty: 2, unit: "pièces", optional: false },
      { food: "Lait entier", qty: 250, unit: "ml", optional: false },
      { food: "Beurre frais fondu", qty: 30, unit: "g", optional: false },
      { food: "Sucre en poudre", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Levure chimique", qty: 2, unit: "c. à café", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Sel fin", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Dans un bol, mélanger la farine de riz, le sucre, la levure chimique, le sel et la poudre de vanille.",
      "Dans un autre bol, battre les œufs avec le lait et le beurre fondu.",
      "Verser les ingrédients liquides sur les ingrédients secs et mélanger jusqu'à homogénéité.",
      "Laisser reposer la pâte 5 minutes.",
      "Chauffer une poêle anti-adhésive à feu moyen. Graisser légèrement avec un peu de beurre.",
      "Verser environ 3 cuillères à soupe de pâte par pancake. Cuire jusqu'à formation de bulles en surface (environ 2 minutes).",
      "Retourner et cuire encore 1 à 2 minutes. Répéter avec le reste de pâte.",
      "Servir chaud avec du sirop d'érable ou du miel."
    ],
    nutrition: { calories: 330, protein: 9, carbs: 52, fat: 10, fiber: 1 },
    tips: "La levure chimique sans bicarbonate de soude et acide citrique est la plus sûre. La farine de riz donne des pancakes légers et sans gluten. Ne pas trop mélanger la pâte pour éviter des pancakes caoutchouteux.",
    isCustom: false
  },
  {
    id: "pdej-gaufres-epeautre-vanille",
    name: "Gaufres à l'Épeautre et Vanille",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Farine d'épeautre", qty: 250, unit: "g", optional: false },
      { food: "Oeufs", qty: 2, unit: "pièces", optional: false },
      { food: "Lait entier", qty: 300, unit: "ml", optional: false },
      { food: "Beurre frais fondu", qty: 60, unit: "g", optional: false },
      { food: "Sucre en poudre", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Levure chimique", qty: 2, unit: "c. à café", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Séparer les blancs des jaunes d'œufs.",
      "Mélanger la farine, la levure chimique, le sucre, le sel et la poudre de vanille.",
      "Incorporer les jaunes d'œufs, puis le lait et le beurre fondu. Mélanger jusqu'à obtenir une pâte lisse.",
      "Monter les blancs en neige ferme.",
      "Incorporer délicatement les blancs en neige à la pâte à l'aide d'une spatule.",
      "Préchauffer le gaufrier et le huiler légèrement.",
      "Verser la pâte et cuire selon les instructions du gaufrier (environ 4 à 5 minutes).",
      "Servir avec du sirop d'érable et des tranches de pomme fraîche."
    ],
    nutrition: { calories: 385, protein: 12, carbs: 52, fat: 15, fiber: 3 },
    tips: "Les blancs en neige sont le secret de gaufres légères sans bicarbonate de soude. Cuire les gaufres à bonne température pour une surface croustillante. Consommer immédiatement pour profiter du croustillant.",
    isCustom: false
  },
  {
    id: "pdej-granola-maison-avoine",
    name: "Granola Maison à l'Avoine et au Miel",
    category: "petit-dej",
    mealType: ["petit-dej"],
    prepTime: 10,
    cookTime: 25,
    servings: 8,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Flocons d'avoine", qty: 300, unit: "g", optional: false },
      { food: "Graines de courge", qty: 60, unit: "g", optional: false },
      { food: "Graines de tournesol", qty: 60, unit: "g", optional: false },
      { food: "Noix de coco râpée", qty: 50, unit: "g", optional: false },
      { food: "Miel", qty: 80, unit: "ml", optional: false },
      { food: "Huile de coco", qty: 40, unit: "ml", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffer le four à 160°C.",
      "Dans un grand bol, mélanger les flocons d'avoine, les graines de courge, les graines de tournesol et la noix de coco.",
      "Dans une petite casserole, faire chauffer doucement le miel et l'huile de coco jusqu'à liquéfaction.",
      "Ajouter la poudre de vanille et la cannelle au mélange chaud.",
      "Verser le mélange liquide sur les ingrédients secs. Bien enrober.",
      "Étaler uniformément sur une plaque de cuisson recouverte de papier sulfurisé.",
      "Enfourner 20 à 25 minutes en remuant à mi-cuisson, jusqu'à dorure.",
      "Laisser refroidir complètement avant de stocker dans un bocal hermétique."
    ],
    nutrition: { calories: 295, protein: 8, carbs: 38, fat: 13, fiber: 5 },
    tips: "Le granola maison se conserve 2 semaines dans un bocal hermétique à température ambiante. Ne pas ajouter de fruits secs ou noix qui sont problématiques pour l'histamine. Servir avec du lait frais ou de la crème fraîche. La cannelle doit rester en petite quantité.",
    isCustom: false
  },
  {
    id: "dessert-tarte-pommes-classique",
    name: "Tarte aux Pommes Classique",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 30,
    cookTime: 35,
    servings: 8,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte brisée fraîche", qty: 250, unit: "g", optional: false },
      { food: "Pommes Golden", qty: 5, unit: "pièces", optional: false },
      { food: "Sucre en poudre", qty: 60, unit: "g", optional: false },
      { food: "Beurre frais", qty: 30, unit: "g", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Compote de pommes maison", qty: 150, unit: "g", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C.",
      "Étaler la pâte brisée et foncer un moule à tarte de 26 cm de diamètre.",
      "Piquer le fond avec une fourchette. Étaler la compote de pommes en couche fine.",
      "Éplucher, épépiner et couper les pommes en quartiers fins réguliers.",
      "Disposer les quartiers en rosace sur la compote, en les faisant se chevaucher légèrement.",
      "Saupoudrer de sucre, de poudre de vanille et d'une pincée de cannelle.",
      "Répartir de petits morceaux de beurre sur les pommes.",
      "Enfourner 35 minutes jusqu'à ce que les pommes soient dorées et la pâte bien cuite.",
      "Laisser tiédir avant de démouler et servir."
    ],
    nutrition: { calories: 265, protein: 3, carbs: 42, fat: 10, fiber: 3 },
    tips: "La compote de pommes maison comme fond évite l'humidité. Utiliser des pommes Golden pour leur douceur ou des Reinettes pour un léger acidulé. La tarte est meilleure le jour même mais peut se conserver 24 heures à température ambiante.",
    isCustom: false
  },
  {
    id: "dessert-tarte-poires-amandes",
    name: "Tarte Bourdaloue Poires à la Crème d'Avoine",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 25,
    cookTime: 40,
    servings: 8,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte sablée fraîche", qty: 250, unit: "g", optional: false },
      { food: "Poires Conférence", qty: 4, unit: "pièces", optional: false },
      { food: "Flocons d'avoine fins", qty: 100, unit: "g", optional: false },
      { food: "Beurre frais ramolli", qty: 80, unit: "g", optional: false },
      { food: "Sucre en poudre", qty: 80, unit: "g", optional: false },
      { food: "Oeufs", qty: 2, unit: "pièces", optional: false },
      { food: "Crème fraîche liquide", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffer le four à 175°C.",
      "Foncer un moule à tarte avec la pâte sablée. Réserver au frais.",
      "Préparer la crème d'avoine : mixer les flocons d'avoine finement en poudre.",
      "Fouetter le beurre ramolli avec le sucre jusqu'à blanchiment. Incorporer les œufs un à un.",
      "Ajouter la poudre d'avoine, la crème fraîche et la poudre de vanille. Mélanger.",
      "Étaler la crème d'avoine sur le fond de tarte.",
      "Peler et couper les poires en deux, retirer les pépins. Les déposer face bombée sur la crème.",
      "Enfourner 35 à 40 minutes jusqu'à dorure.",
      "Servir tiède ou à température ambiante."
    ],
    nutrition: { calories: 335, protein: 6, carbs: 42, fat: 16, fiber: 4 },
    tips: "La crème d'avoine remplace la frangipane aux amandes qui n'est pas toujours bien tolérée. Choisir des poires Conférence légèrement fermes qui ne se désintègrent pas à la cuisson. Cette tarte se conserve 2 jours au réfrigérateur.",
    isCustom: false
  },
  {
    id: "dessert-tarte-peches-fraiche",
    name: "Tarte aux Pêches et Crème Fraîche",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 20,
    cookTime: 30,
    servings: 6,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte brisée fraîche", qty: 250, unit: "g", optional: false },
      { food: "Pêches fraîches mûres", qty: 5, unit: "pièces", optional: false },
      { food: "Crème fraîche épaisse", qty: 200, unit: "g", optional: false },
      { food: "Oeufs", qty: 2, unit: "pièces", optional: false },
      { food: "Sucre en poudre", qty: 60, unit: "g", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Farine de riz", qty: 2, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C.",
      "Foncer un moule à tarte avec la pâte. Piquer le fond.",
      "Précuire le fond de tarte à blanc 10 minutes avec des billes de cuisson.",
      "Préparer l'appareil à flan : fouetter les œufs avec le sucre, la crème fraîche, la farine de riz et la poudre de vanille.",
      "Ébouillanter les pêches 30 secondes, peler et trancher en quartiers.",
      "Disposer les quartiers de pêches sur le fond précuit.",
      "Verser l'appareil à flan sur les pêches.",
      "Enfourner 25 à 30 minutes jusqu'à ce que le flan soit pris et légèrement doré."
    ],
    nutrition: { calories: 290, protein: 6, carbs: 38, fat: 13, fiber: 2 },
    tips: "Les pêches fraîches sont idéales pour cette tarte. Ne jamais utiliser des pêches en conserve car le sirop de conservation augmente l'histamine. Consommer la tarte le jour même pour profiter des pêches fraîches à leur meilleur.",
    isCustom: false
  },
  {
    id: "dessert-creme-caramel-vanille",
    name: "Crème Caramel à la Vanille",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Lait entier", qty: 500, unit: "ml", optional: false },
      { food: "Oeufs entiers", qty: 3, unit: "pièces", optional: false },
      { food: "Jaunes d'oeufs", qty: 2, unit: "pièces", optional: false },
      { food: "Sucre en poudre", qty: 150, unit: "g", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Eau", qty: 3, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Préchauffer le four à 160°C.",
      "Préparer le caramel : faire chauffer 100 g de sucre avec l'eau dans une casserole à feu moyen sans remuer jusqu'à obtenir une couleur ambrée.",
      "Verser rapidement le caramel au fond de 6 ramequins. Laisser durcir.",
      "Chauffer le lait avec la poudre de vanille jusqu'à frémissement.",
      "Fouetter les œufs entiers, les jaunes et les 50 g de sucre restants sans faire mousser.",
      "Verser le lait chaud sur les œufs en filet, en remuant doucement.",
      "Filtrer et répartir dans les ramequins caramelisés.",
      "Cuire au bain-marie au four 35 à 40 minutes. La crème doit être tremblotante au centre.",
      "Laisser refroidir, puis réfrigérer au moins 3 heures. Démouler au moment de servir."
    ],
    nutrition: { calories: 195, protein: 7, carbs: 30, fat: 6, fiber: 0 },
    tips: "Le caramel doit être réalisé rapidement sans brûler. Consommer dans les 24 heures. Les œufs très frais sont essentiels. Ne pas utiliser d'extrait de vanille avec alcool, uniquement la poudre de vanille pure.",
    isCustom: false
  },
  {
    id: "dessert-panna-cotta-vanille-coulis-pomme",
    name: "Panna Cotta Vanille et Coulis de Pomme",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Crème fraîche liquide entière", qty: 400, unit: "ml", optional: false },
      { food: "Lait entier", qty: 200, unit: "ml", optional: false },
      { food: "Sucre en poudre", qty: 50, unit: "g", optional: false },
      { food: "Agar-agar", qty: 2, unit: "g", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Pommes Golden", qty: 3, unit: "pièces", optional: false },
      { food: "Miel", qty: 2, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Mélanger la crème, le lait, le sucre et la poudre de vanille dans une casserole.",
      "Saupoudrer l'agar-agar et fouetter à froid. Porter à ébullition en remuant.",
      "Maintenir l'ébullition 2 minutes sans cesser de remuer.",
      "Verser dans 4 verrines ou moules. Laisser refroidir puis réfrigérer 3 heures minimum.",
      "Préparer le coulis : peler et couper les pommes en morceaux. Cuire avec le miel et 3 cuillères à soupe d'eau pendant 10 minutes.",
      "Mixer le coulis de pommes et passer au tamis fin. Laisser refroidir.",
      "Au moment de servir, démouler les panna cotta et napper du coulis de pomme tiède."
    ],
    nutrition: { calories: 340, protein: 4, carbs: 28, fat: 24, fiber: 1 },
    tips: "L'agar-agar est d'origine végétale, contrairement à la gélatine d'origine animale, et est souvent mieux toléré. La panna cotta se conserve 2 jours au réfrigérateur. Le coulis de pomme maison se substitue avantageusement aux coulis de fruits rouges.",
    isCustom: false
  },
  {
    id: "dessert-gateau-pommes-riz",
    name: "Gâteau Moelleux à la Pomme et Farine de Riz",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 20,
    cookTime: 40,
    servings: 8,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Farine de riz", qty: 200, unit: "g", optional: false },
      { food: "Pommes", qty: 3, unit: "pièces", optional: false },
      { food: "Oeufs", qty: 3, unit: "pièces", optional: false },
      { food: "Beurre frais fondu", qty: 100, unit: "g", optional: false },
      { food: "Sucre en poudre", qty: 120, unit: "g", optional: false },
      { food: "Levure chimique", qty: 2, unit: "c. à café", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Lait entier", qty: 100, unit: "ml", optional: false }
    ],
    steps: [
      "Préchauffer le four à 175°C. Beurrer et fariner un moule à cake ou un moule rond.",
      "Éplucher deux pommes et les couper en dés. Couper la troisième en fines lamelles pour le dessus.",
      "Fouetter les œufs et le sucre jusqu'à blanchiment et doublement de volume (5 minutes).",
      "Incorporer le beurre fondu refroidi et le lait.",
      "Tamiser la farine de riz, la levure et la poudre de vanille sur le mélange. Incorporer délicatement.",
      "Ajouter les dés de pomme à la pâte. Verser dans le moule.",
      "Disposer les lamelles de pomme en rosace sur le dessus.",
      "Enfourner 35 à 40 minutes. Vérifier la cuisson avec un couteau : la lame doit ressortir sèche."
    ],
    nutrition: { calories: 295, protein: 6, carbs: 46, fat: 11, fiber: 2 },
    tips: "La farine de riz donne un gâteau naturellement sans gluten et à texture légèrement différente du blé. Il est important de bien fouetter les œufs et le sucre pour intégrer de l'air dans la pâte, compensant l'absence de gluten.",
    isCustom: false
  },
  {
    id: "dessert-cake-poire-epeautre",
    name: "Cake Fondant aux Poires et Épeautre",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 20,
    cookTime: 45,
    servings: 8,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Farine d'épeautre", qty: 220, unit: "g", optional: false },
      { food: "Poires bien mûres", qty: 3, unit: "pièces", optional: false },
      { food: "Oeufs", qty: 3, unit: "pièces", optional: false },
      { food: "Beurre frais fondu", qty: 100, unit: "g", optional: false },
      { food: "Sucre de coco", qty: 110, unit: "g", optional: false },
      { food: "Levure chimique", qty: 2, unit: "c. à café", optional: false },
      { food: "Crème fraîche liquide", qty: 80, unit: "ml", optional: false },
      { food: "Cardamome moulue", qty: 0.25, unit: "c. à café", optional: true }
    ],
    steps: [
      "Préchauffer le four à 175°C. Chemiser un moule à cake de papier sulfurisé.",
      "Peler deux poires et les couper en petits dés. Couper la troisième en lamelles fines.",
      "Battre les œufs avec le sucre de coco jusqu'à obtenir un mélange mousseux.",
      "Incorporer le beurre fondu refroidi et la crème fraîche.",
      "Ajouter la farine d'épeautre, la levure et la cardamome. Mélanger juste assez.",
      "Incorporer les dés de poires à la pâte.",
      "Verser dans le moule et disposer les lamelles de poire sur le dessus.",
      "Cuire 40 à 45 minutes. Laisser refroidir 10 minutes avant de démouler."
    ],
    nutrition: { calories: 305, protein: 7, carbs: 43, fat: 12, fiber: 3 },
    tips: "La cardamome doit être utilisée très modérément. La farine d'épeautre est souvent bien tolérée comparée à la farine de blé classique. Ce cake est meilleur le lendemain car les saveurs se développent. Se conserve 3 jours sous film alimentaire.",
    isCustom: false
  },
  {
    id: "dessert-sorbet-pomme-maison",
    name: "Sorbet Pomme Maison",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 15,
    cookTime: 5,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pommes Golden", qty: 6, unit: "pièces", optional: false },
      { food: "Sucre en poudre", qty: 80, unit: "g", optional: false },
      { food: "Eau", qty: 200, unit: "ml", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Jus de pomme non pasteurisé frais", qty: 100, unit: "ml", optional: false }
    ],
    steps: [
      "Préparer un sirop : porter l'eau et le sucre à ébullition, remuer jusqu'à dissolution. Laisser refroidir.",
      "Éplucher, évider et couper les pommes en morceaux.",
      "Faire compoter les pommes avec 2 cuillères à soupe d'eau 5 minutes. Égoutter et laisser refroidir.",
      "Mixer les pommes compotées avec le sirop froid, le jus de pomme et la poudre de vanille jusqu'à obtenir une purée lisse.",
      "Filtrer au tamis fin pour une texture lisse.",
      "Verser dans une sorbetière et turbiner selon les instructions du fabricant.",
      "Sans sorbetière : verser dans un bac, placer au congélateur 4 heures en remuant toutes les 30 minutes.",
      "Sortir 10 minutes avant de servir pour ramollir légèrement."
    ],
    nutrition: { calories: 130, protein: 0, carbs: 32, fat: 0, fiber: 2 },
    tips: "Ce sorbet se conserve 2 semaines au congélateur dans une boîte hermétique. Le jus de pomme frais (pas pasteurisé en bouteille longue conservation) est préférable pour l'histamine. Ajouter une cuillère à café de gingembre râpé pour varier, en quantité minimale.",
    isCustom: false
  },
  {
    id: "dessert-glace-vanille-maison",
    name: "Glace Vanille Maison à la Crème",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 20,
    cookTime: 15,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Crème fraîche liquide entière", qty: 400, unit: "ml", optional: false },
      { food: "Lait entier", qty: 200, unit: "ml", optional: false },
      { food: "Jaunes d'oeufs", qty: 4, unit: "pièces", optional: false },
      { food: "Sucre en poudre", qty: 100, unit: "g", optional: false },
      { food: "Poudre de vanille", qty: 1.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Chauffer le lait et 200 ml de crème avec la poudre de vanille jusqu'à frémissement.",
      "Fouetter les jaunes avec le sucre jusqu'à blanchiment.",
      "Verser le lait chaud sur les jaunes en filet, sans cesser de remuer.",
      "Remettre sur feu doux et cuire à 83°C en remuant (crème anglaise). La crème doit napper la cuillère.",
      "Retirer du feu, filtrer, laisser refroidir complètement.",
      "Monter les 200 ml de crème restants en chantilly souple.",
      "Incorporer délicatement la chantilly à la crème anglaise froide.",
      "Turbiner en sorbetière ou placer au congélateur 6 heures en fouettant toutes les heures.",
      "Sortir 15 minutes avant de servir."
    ],
    nutrition: { calories: 320, protein: 5, carbs: 22, fat: 24, fiber: 0 },
    tips: "La poudre de vanille pure sans alcool est essentielle. Utiliser des œufs très frais et consommer dans les 10 jours. La méthode sans sorbetière donne de bons résultats si on est régulier dans le brassage. Conserver dans un contenant hermétique.",
    isCustom: false
  },
  {
    id: "dessert-cookies-avoine-pomme",
    name: "Cookies Avoine et Pomme",
    category: "dessert",
    mealType: ["dessert", "collation"],
    prepTime: 15,
    cookTime: 15,
    servings: 16,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Flocons d'avoine", qty: 180, unit: "g", optional: false },
      { food: "Farine d'épeautre", qty: 80, unit: "g", optional: false },
      { food: "Pomme", qty: 1, unit: "pièce", optional: false },
      { food: "Beurre frais ramolli", qty: 100, unit: "g", optional: false },
      { food: "Sucre de coco", qty: 80, unit: "g", optional: false },
      { food: "Oeuf", qty: 1, unit: "pièce", optional: false },
      { food: "Cannelle", qty: 1, unit: "c. à café", optional: false },
      { food: "Levure chimique", qty: 1, unit: "c. à café", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffer le four à 175°C. Tapisser une plaque de papier sulfurisé.",
      "Éplucher la pomme et la râper finement. Presser dans un torchon pour enlever l'excès d'eau.",
      "Fouetter le beurre ramolli et le sucre de coco jusqu'à consistance crémeuse.",
      "Incorporer l'œuf et battre encore 1 minute.",
      "Ajouter la pomme râpée, la cannelle, la poudre de vanille.",
      "Incorporer les flocons d'avoine, la farine et la levure. Mélanger jusqu'à homogénéité.",
      "Former des boules de pâte (environ 30 g chacune), les déposer sur la plaque et les aplatir légèrement.",
      "Cuire 12 à 15 minutes jusqu'à dorure des bords. Laisser refroidir sur une grille."
    ],
    nutrition: { calories: 135, protein: 3, carbs: 18, fat: 6, fiber: 2 },
    tips: "Ces cookies se conservent 5 jours dans une boîte hermétique. La pomme râpée apporte de l'humidité naturelle. Pour varier, remplacer la pomme par de la poire. La cannelle peut être réduite ou omise selon la tolérance individuelle.",
    isCustom: false
  },
  {
    id: "dessert-sables-coco-vanille",
    name: "Sablés à la Noix de Coco et Vanille",
    category: "dessert",
    mealType: ["dessert", "collation"],
    prepTime: 20,
    cookTime: 12,
    servings: 24,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Farine d'épeautre", qty: 200, unit: "g", optional: false },
      { food: "Noix de coco râpée", qty: 80, unit: "g", optional: false },
      { food: "Beurre frais froid en dés", qty: 120, unit: "g", optional: false },
      { food: "Sucre en poudre", qty: 80, unit: "g", optional: false },
      { food: "Jaune d'oeuf", qty: 1, unit: "pièce", optional: false },
      { food: "Poudre de vanille", qty: 1, unit: "c. à café", optional: false },
      { food: "Sel fin", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 170°C.",
      "Mélanger la farine, la noix de coco, le sucre, la poudre de vanille et le sel.",
      "Incorporer le beurre froid en dés du bout des doigts jusqu'à obtenir une texture sableuse.",
      "Ajouter le jaune d'œuf et malaxer rapidement pour former une boule de pâte.",
      "Envelopper dans du film alimentaire et réfrigérer 30 minutes.",
      "Abaisser la pâte entre deux feuilles de papier sulfurisé sur 5 mm d'épaisseur.",
      "Découper avec un emporte-pièce et déposer sur une plaque.",
      "Cuire 10 à 12 minutes jusqu'à légère dorure des bords. Refroidir sur grille."
    ],
    nutrition: { calories: 95, protein: 2, carbs: 11, fat: 5, fiber: 1 },
    tips: "La pâte sablée peut être préparée la veille et conservée au réfrigérateur. Ces sablés se conservent 2 semaines dans une boîte hermétique. La noix de coco râpée est généralement bien tolérée. Ne pas trop manipuler la pâte pour garder la texture sablée.",
    isCustom: false
  },
  {
    id: "dessert-mousse-vanille-mascarpone",
    name: "Mousse Légère Vanille et Mascarpone",
    category: "dessert",
    mealType: ["dessert"],
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Mascarpone très frais", qty: 250, unit: "g", optional: false },
      { food: "Crème fraîche liquide entière très froide", qty: 200, unit: "ml", optional: false },
      { food: "Sucre en poudre", qty: 60, unit: "g", optional: false },
      { food: "Poudre de vanille", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Blancs d'oeufs très frais", qty: 2, unit: "pièces", optional: false },
      { food: "Sel fin", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Fouetter le mascarpone avec la poudre de vanille et la moitié du sucre jusqu'à consistance lisse.",
      "Monter la crème fraîche très froide en chantilly ferme.",
      "Incorporer délicatement la chantilly au mascarpone.",
      "Monter les blancs en neige ferme avec une pincée de sel.",
      "Serrer les blancs avec le reste du sucre en fin de montage.",
      "Incorporer délicatement les blancs en neige au mélange mascarpone-chantilly en trois fois.",
      "Répartir dans 4 coupes ou verrines.",
      "Réfrigérer au moins 2 heures avant de servir."
    ],
    nutrition: { calories: 370, protein: 6, carbs: 18, fat: 30, fiber: 0 },
    tips: "Utiliser du mascarpone acheté le jour même et très froid. Cette mousse ne contient pas de gélatine et se tient grâce aux blancs en neige. À consommer dans les 24 heures. La poudre de vanille pure donne un arôme intense.",
    isCustom: false
  },
  {
    id: "collation-energy-balls-avoine-miel",
    name: "Energy Balls Avoine et Miel",
    category: "collation",
    mealType: ["collation"],
    prepTime: 15,
    cookTime: 0,
    servings: 12,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Flocons d'avoine", qty: 150, unit: "g", optional: false },
      { food: "Miel", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Beurre de coco", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Graines de courge", qty: 40, unit: "g", optional: false },
      { food: "Noix de coco râpée", qty: 40, unit: "g", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Cannelle", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Dans un grand bol, mélanger les flocons d'avoine, les graines de courge et la noix de coco râpée.",
      "Dans une petite casserole, chauffer doucement le miel et le beurre de coco jusqu'à liquéfaction.",
      "Ajouter la poudre de vanille et la cannelle au mélange chaud.",
      "Verser sur les ingrédients secs et mélanger vigoureusement.",
      "Placer le bol au réfrigérateur 20 minutes pour faciliter le façonnage.",
      "Prendre des petites portions de pâte (~20 g) et former des boules entre les paumes.",
      "Rouler dans la noix de coco râpée ou les flocons d'avoine.",
      "Conserver au réfrigérateur dans une boîte hermétique."
    ],
    nutrition: { calories: 110, protein: 3, carbs: 14, fat: 5, fiber: 2 },
    tips: "Ces energy balls se conservent 1 semaine au réfrigérateur. Le beurre de coco apporte de l'onctuosité sans huile végétale. Elles peuvent être congelées pour 1 mois. Sortir 15 minutes avant consommation pour les déguster à température ambiante.",
    isCustom: false
  },
  {
    id: "collation-energy-balls-avoine-poire",
    name: "Energy Balls Avoine Poire et Cardamome",
    category: "collation",
    mealType: ["collation"],
    prepTime: 20,
    cookTime: 5,
    servings: 14,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Flocons d'avoine", qty: 160, unit: "g", optional: false },
      { food: "Poire séchée maison (déshydratée)", qty: 50, unit: "g", optional: false },
      { food: "Miel", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Huile de coco", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Noix de coco râpée", qty: 50, unit: "g", optional: false },
      { food: "Graines de chia", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Cardamome moulue", qty: 0.25, unit: "c. à café", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Réduire les flocons d'avoine en poudre grossière au mixeur (garder de la texture).",
      "Hacher finement la poire déshydratée maison.",
      "Faire chauffer doucement le miel et l'huile de coco.",
      "Mélanger tous les ingrédients secs : flocons, noix de coco, graines de chia, cardamome, vanille.",
      "Ajouter la poire hachée et le mélange miel-huile de coco. Bien mélanger.",
      "Si la pâte est trop sèche, ajouter un peu de miel. Si trop molle, placer 15 minutes au congélateur.",
      "Former des boules et rouler dans la noix de coco râpée.",
      "Conserver au réfrigérateur dans une boîte hermétique pendant 5 jours."
    ],
    nutrition: { calories: 105, protein: 2, carbs: 15, fat: 5, fiber: 2 },
    tips: "La poire déshydratée doit être préparée maison en tranchant finement des poires fraîches et en les faisant sécher au four à 60°C pendant 4 heures. Les poires séchées du commerce peuvent contenir des conservateurs. La cardamome est à doser très modérément.",
    isCustom: false
  },
  {
    id: "collation-energy-balls-sarrasin-coco",
    name: "Energy Balls Sarrasin Grillé et Coco",
    category: "collation",
    mealType: ["collation"],
    prepTime: 15,
    cookTime: 5,
    servings: 12,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Flocons d'avoine", qty: 100, unit: "g", optional: false },
      { food: "Graines de sarrasin grillées (kasha)", qty: 60, unit: "g", optional: false },
      { food: "Noix de coco râpée", qty: 80, unit: "g", optional: false },
      { food: "Miel", qty: 5, unit: "c. à soupe", optional: false },
      { food: "Beurre de coco", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Poudre de vanille", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Si vous utilisez des graines de sarrasin crues, les faire griller à sec dans une poêle 3 à 4 minutes jusqu'à ce qu'elles soient dorées et craquantes. Laisser refroidir.",
      "Mélanger les flocons d'avoine, les graines de sarrasin grillées et 60 g de noix de coco râpée dans un bol.",
      "Faire chauffer doucement le miel et le beurre de coco dans une casserole.",
      "Ajouter la poudre de vanille au mélange chaud.",
      "Verser sur les ingrédients secs et mélanger.",
      "Laisser reposer 10 minutes à température ambiante pour que les flocons absorbent le liquide.",
      "Former des boules de la taille d'une balle de golf.",
      "Rouler dans les 20 g de noix de coco râpée restants. Réfrigérer 30 minutes."
    ],
    nutrition: { calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 2 },
    tips: "Le sarrasin grillé (kasha) apporte un arôme noisette agréable et naturel, sans l'allergène de la vraie noisette. Ces energy balls sont sans gluten. Se conservent 1 semaine au réfrigérateur ou 1 mois au congélateur.",
    isCustom: false
  },
  {
    id: "collation-dip-ricotta-herbes",
    name: "Dip Ricotta aux Fines Herbes",
    category: "collation",
    mealType: ["collation"],
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Ricotta fraîche", qty: 250, unit: "g", optional: false },
      { food: "Ciboulette fraîche ciselée", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Persil frais ciselé", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Huile d'olive fraîche", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel fin", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre blanc moulu", qty: 1, unit: "pincée", optional: false },
      { food: "Céleri", qty: 2, unit: "branches", optional: true }
    ],
    steps: [
      "Égoutter la ricotta si elle est trop humide en la plaçant dans une passoire 15 minutes.",
      "Dans un bol, travailler la ricotta à la fourchette pour la rendre lisse et crémeuse.",
      "Ajouter la ciboulette et le persil ciselés finement.",
      "Incorporer l'huile d'olive, le sel et le poivre blanc.",
      "Bien mélanger et ajuster l'assaisonnement.",
      "Réfrigérer au moins 30 minutes avant de servir pour que les saveurs se développent.",
      "Servir avec des bâtonnets de céleri, de concombre, de carottes fraîches ou des crackers de riz."
    ],
    nutrition: { calories: 145, protein: 8, carbs: 3, fat: 11, fiber: 0 },
    tips: "La ricotta doit être achetée le jour même ou au maximum la veille. C'est l'un des fromages les moins fermentés. Utiliser uniquement des herbes fraîches pour ce dip. Se conserve 2 jours au réfrigérateur dans un contenant hermétique.",
    isCustom: false
  },
  {
    id: "collation-houmous-feves",
    name: "Tartinade de Fèves Fraîches à l'Huile d'Olive",
    category: "collation",
    mealType: ["collation"],
    prepTime: 20,
    cookTime: 10,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Fèves fraîches décortiquées", qty: 400, unit: "g", optional: false },
      { food: "Huile d'olive fraîche de première pression", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Ail frais", qty: 1, unit: "gousse", optional: false },
      { food: "Sel fin", qty: 1, unit: "c. à café", optional: false },
      { food: "Cumin moulu", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Persil frais", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Eau froide", qty: 3, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Cuire les fèves fraîches décortiquées dans l'eau bouillante salée 8 à 10 minutes.",
      "Égoutter et passer immédiatement sous l'eau froide pour stopper la cuisson.",
      "Retirer la seconde peau des fèves en les pressant entre les doigts (facultatif mais améliore la texture).",
      "Mixer les fèves avec l'ail pressé, le sel, le cumin et 2 cuillères à soupe d'huile d'olive.",
      "Ajouter l'eau froide progressivement pour obtenir une consistance crémeuse.",
      "Goûter et ajuster l'assaisonnement.",
      "Verser dans un bol, arroser du reste d'huile d'olive et parsemer de persil ciselé.",
      "Servir avec des crackers de riz ou des légumes crus."
    ],
    nutrition: { calories: 125, protein: 6, carbs: 12, fat: 6, fiber: 5 },
    tips: "Utiliser uniquement des fèves fraîches de saison, jamais en conserve. L'ail peut être omis ou utilisé en très petite quantité selon la tolérance. Cette tartinade remplace avantageusement le houmous classique aux pois chiches pour certaines personnes.",
    isCustom: false
  },
  {
    id: "collation-galettes-riz-ricotta",
    name: "Galettes de Riz Soufflées Garniture Ricotta et Pomme",
    category: "collation",
    mealType: ["collation"],
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Galettes de riz soufflé nature", qty: 4, unit: "pièces", optional: false },
      { food: "Ricotta fraîche", qty: 100, unit: "g", optional: false },
      { food: "Pomme", qty: 1, unit: "pièce", optional: false },
      { food: "Miel", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Poudre de cannelle", qty: 1, unit: "pincée", optional: true }
    ],
    steps: [
      "Étaler une fine couche de ricotta fraîche sur chaque galette de riz.",
      "Éplucher et couper la pomme en fines lamelles.",
      "Disposer les lamelles de pomme sur la ricotta.",
      "Arroser d'un filet de miel.",
      "Saupoudrer d'une pincée de cannelle si désiré.",
      "Servir immédiatement."
    ],
    nutrition: { calories: 155, protein: 6, carbs: 27, fat: 3, fiber: 1 },
    tips: "Les galettes de riz nature (sans sel ou légèrement salées) sont un excellent vecteur pour les collations histamine. Garnir juste avant de consommer pour éviter que les galettes ramollissent. Choisir une ricotta achetée le jour même.",
    isCustom: false
  },
  {
    id: "collation-crudites-dip-creme",
    name: "Assiette de Crudités et Dip à la Crème Fraîche",
    category: "collation",
    mealType: ["collation"],
    prepTime: 15,
    cookTime: 0,
    servings: 3,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Carottes", qty: 3, unit: "pièces", optional: false },
      { food: "Concombre", qty: 1, unit: "pièce", optional: false },
      { food: "Céleri", qty: 3, unit: "branches", optional: false },
      { food: "Crème fraîche épaisse", qty: 150, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel fin", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Poivre blanc", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Éplucher et couper les carottes en bâtonnets réguliers d'environ 8 cm.",
      "Laver et couper le concombre en bâtonnets, retirer les graines si désiré.",
      "Laver et couper le céleri en bâtonnets.",
      "Préparer le dip : mélanger la crème fraîche épaisse avec la ciboulette ciselée, le sel et le poivre blanc.",
      "Réfrigérer le dip 15 minutes pour qu'il prenne.",
      "Dresser les légumes dans une assiette ou un verre.",
      "Servir avec le dip à la crème fraîche."
    ],
    nutrition: { calories: 130, protein: 2, carbs: 10, fat: 9, fiber: 3 },
    tips: "Les légumes crus sont parmi les aliments les mieux tolérés en cas d'intolérance à l'histamine. La crème fraîche fraîche est préférable à la crème aigre ou à la crème fermentée. Préparer les crudités juste avant de servir pour qu'elles restent croquantes.",
    isCustom: false
  },
  {
    id: "collation-smoothie-melon-poire",
    name: "Smoothie Melon, Poire et Lait de Coco",
    category: "collation",
    mealType: ["collation"],
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Melon Cantaloupe", qty: 250, unit: "g", optional: false },
      { food: "Poire bien mûre", qty: 2, unit: "pièces", optional: false },
      { food: "Lait de coco", qty: 150, unit: "ml", optional: false },
      { food: "Miel", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Poudre de vanille", qty: 0.25, unit: "c. à café", optional: false },
      { food: "Glaçons", qty: 4, unit: "pièces", optional: true }
    ],
    steps: [
      "Peler et épépiner le melon. Couper en morceaux.",
      "Peler et épépiner les poires. Couper en quartiers.",
      "Mettre tous les ingrédients dans le blender : melon, poires, lait de coco, miel et poudre de vanille.",
      "Ajouter les glaçons si désiré pour un smoothie plus frais.",
      "Mixer à haute vitesse pendant 1 minute jusqu'à obtenir un mélange parfaitement lisse.",
      "Goûter et ajuster le sucre selon les goûts.",
      "Verser dans des verres et consommer immédiatement."
    ],
    nutrition: { calories: 195, protein: 2, carbs: 36, fat: 6, fiber: 4 },
    tips: "Ce smoothie est à consommer immédiatement après préparation. Les fruits ne doivent pas être trop mûrs pour rester dans une tolérance optimale. Le melon et la poire sont parmi les fruits les mieux tolérés. Ne pas préparer à l'avance car l'oxydation peut augmenter l'histamine.",
    isCustom: false
  }
];
