const RECIPES_BATCH_5 = [
  {
    id: "batch-bouillon-poulet-legumes",
    name: "Bouillon de poulet aux légumes racines",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poulet entier frais", qty: 1200, unit: "g", optional: false },
      { food: "Carottes", qty: 300, unit: "g", optional: false },
      { food: "Poireaux", qty: 200, unit: "g", optional: false },
      { food: "Céleri branche", qty: 100, unit: "g", optional: false },
      { food: "Oignon", qty: 150, unit: "g", optional: false },
      { food: "Thym frais", qty: 5, unit: "g", optional: false },
      { food: "Laurier", qty: 2, unit: "feuilles", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false },
      { food: "Eau froide", qty: 2500, unit: "ml", optional: false }
    ],
    steps: [
      "Rincer le poulet à l'eau froide et le placer dans une grande marmite. Couvrir d'eau froide et porter à ébullition.",
      "Écumer soigneusement la mousse qui remonte en surface pendant les 10 premières minutes.",
      "Éplucher et couper grossièrement les carottes, poireaux, céleri et oignon. Les ajouter au bouillon avec le thym et le laurier.",
      "Réduire le feu, couvrir partiellement et laisser mijoter 75 minutes à frémissement doux.",
      "Retirer le poulet, effilocher la chair et filtrer le bouillon. Saler selon le goût.",
      "Laisser refroidir rapidement en posant la marmite dans un bain de glace avant de congeler."
    ],
    nutrition: { calories: 180, protein: 22, carbs: 8, fat: 6, fiber: 2 },
    tips: "Congeler le bouillon en portions de 500 ml dans des sachets plats ou des bocaux. La chair effilochée se conserve séparément jusqu'à 3 mois au congélateur. Dégraisser le bouillon froid avant congélation.",
    isCustom: false
  },
  {
    id: "batch-bouillon-boeuf-os",
    name: "Bouillon de bœuf aux os à moelle",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 180,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Os à moelle de bœuf frais", qty: 800, unit: "g", optional: false },
      { food: "Bœuf plat de côtes frais", qty: 400, unit: "g", optional: false },
      { food: "Carottes", qty: 250, unit: "g", optional: false },
      { food: "Oignon", qty: 200, unit: "g", optional: false },
      { food: "Céleri branche", qty: 120, unit: "g", optional: false },
      { food: "Persil frais", qty: 20, unit: "g", optional: false },
      { food: "Thym", qty: 4, unit: "g", optional: false },
      { food: "Laurier", qty: 2, unit: "feuilles", optional: false },
      { food: "Sel", qty: 10, unit: "g", optional: false },
      { food: "Eau froide", qty: 3000, unit: "ml", optional: false }
    ],
    steps: [
      "Blanchir les os 5 minutes dans de l'eau bouillante, les rincer sous l'eau froide pour éliminer les impuretés.",
      "Placer les os et la viande dans une grande marmite, couvrir d'eau froide et porter lentement à ébullition.",
      "Écumer régulièrement. Ajouter les légumes grossièrement coupés, les herbes et le sel.",
      "Réduire le feu au minimum et laisser mijoter à couvert pendant 3 heures.",
      "Filtrer le bouillon à travers une passoire fine, effilocher la viande séparément.",
      "Refroidir rapidement dans un bain de glace, dégraisser une fois froid et congeler en portions."
    ],
    nutrition: { calories: 120, protein: 18, carbs: 5, fat: 4, fiber: 1 },
    tips: "Congeler en cubes de glace pour de petites portions ou en pots de 500 ml. Se conserve 4 mois au congélateur. Utiliser comme base de sauce ou de soupe. Dégraisser toujours après refroidissement complet.",
    isCustom: false
  },
  {
    id: "batch-soupe-courgette-basilic",
    name: "Soupe veloutée de courgettes au basilic",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 25,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Courgettes fraîches", qty: 1200, unit: "g", optional: false },
      { food: "Pommes de terre", qty: 300, unit: "g", optional: false },
      { food: "Oignon", qty: 150, unit: "g", optional: false },
      { food: "Bouillon de poulet maison", qty: 1000, unit: "ml", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Basilic frais", qty: 20, unit: "g", optional: false },
      { food: "Crème fraîche", qty: 80, unit: "ml", optional: true },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Éplucher et émincer l'oignon. Faire fondre le beurre dans une grande casserole et faire revenir l'oignon 5 minutes sans coloration.",
      "Couper les courgettes en rondelles et les pommes de terre en cubes. Les ajouter à la casserole.",
      "Verser le bouillon chaud, saler et porter à ébullition. Cuire 20 minutes à feu moyen.",
      "Hors du feu, ajouter les feuilles de basilic frais et mixer finement jusqu'à obtention d'un velouté lisse.",
      "Ajuster l'assaisonnement. Ajouter la crème si désiré pour plus d'onctuosité.",
      "Laisser refroidir complètement avant de répartir en portions et de congeler."
    ],
    nutrition: { calories: 160, protein: 6, carbs: 22, fat: 6, fiber: 4 },
    tips: "Se congèle très bien en portions individuelles de 300 ml. Durée de conservation : 3 mois. Ajouter la crème fraîche au moment du réchauffage pour une meilleure texture. Étiqueter avec la date de préparation.",
    isCustom: false
  },
  {
    id: "batch-soupe-lentilles-curcuma",
    name: "Soupe de lentilles corail au curcuma",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 35,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Lentilles corail sèches", qty: 400, unit: "g", optional: false },
      { food: "Carottes", qty: 250, unit: "g", optional: false },
      { food: "Oignon", qty: 180, unit: "g", optional: false },
      { food: "Ail frais", qty: 3, unit: "gousses", optional: false },
      { food: "Curcuma en poudre", qty: 5, unit: "g", optional: false },
      { food: "Cumin en poudre", qty: 3, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 30, unit: "ml", optional: false },
      { food: "Bouillon de légumes maison", qty: 1500, unit: "ml", optional: false },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Rincer les lentilles corail à l'eau froide. Éplucher et émincer l'oignon et l'ail, couper les carottes en rondelles.",
      "Faire chauffer l'huile d'olive dans une grande casserole. Faire revenir l'oignon et l'ail 3 minutes, ajouter le curcuma et le cumin, mélanger 1 minute.",
      "Ajouter les carottes et les lentilles, bien mélanger pour enrober des épices.",
      "Verser le bouillon, porter à ébullition puis réduire à feu doux. Cuire 30 minutes en remuant régulièrement.",
      "Mixer partiellement ou totalement selon la texture souhaitée. Ajuster sel et épices.",
      "Refroidir rapidement et répartir en portions de 400 ml pour la congélation."
    ],
    nutrition: { calories: 250, protein: 14, carbs: 38, fat: 5, fiber: 8 },
    tips: "Excellente soupe à congeler en portions pour 3 mois. La texture s'améliore après congélation. Décongeler au réfrigérateur la veille ou directement dans une casserole à feu doux. Ajouter un filet d'huile d'olive au service.",
    isCustom: false
  },
  {
    id: "batch-soupe-potiron-gingembre",
    name: "Velouté de potiron au gingembre frais",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 30,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Potiron frais", qty: 1500, unit: "g", optional: false },
      { food: "Oignon", qty: 200, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 20, unit: "g", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Bouillon de poulet maison", qty: 1200, unit: "ml", optional: false },
      { food: "Crème fraîche", qty: 100, unit: "ml", optional: true },
      { food: "Graines de courge", qty: 30, unit: "g", optional: true },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Éplucher le potiron, retirer les graines et le couper en gros cubes. Émincer l'oignon et râper le gingembre frais.",
      "Faire fondre le beurre dans une grande marmite et faire revenir l'oignon 5 minutes. Ajouter le gingembre et cuire 1 minute supplémentaire.",
      "Ajouter les cubes de potiron, mélanger et verser le bouillon chaud. Saler.",
      "Porter à ébullition, couvrir et cuire à feu moyen 25 minutes jusqu'à ce que le potiron soit très tendre.",
      "Mixer finement jusqu'à obtention d'un velouté lisse. Ajouter la crème, mélanger et rectifier l'assaisonnement.",
      "Refroidir complètement avant de congeler en portions individuelles de 350 ml."
    ],
    nutrition: { calories: 175, protein: 5, carbs: 24, fat: 7, fiber: 4 },
    tips: "Congeler sans la crème pour une meilleure conservation (3 mois). Ajouter la crème fraîche au réchauffage. Les graines de courge toastées ajoutent du croquant au service. Étiqueter avec la date.",
    isCustom: false
  },
  {
    id: "batch-soupe-minestrone-legumes",
    name: "Minestrone de légumes frais aux herbes",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Haricots verts frais", qty: 300, unit: "g", optional: false },
      { food: "Courgettes", qty: 300, unit: "g", optional: false },
      { food: "Carottes", qty: 200, unit: "g", optional: false },
      { food: "Céleri branche", qty: 150, unit: "g", optional: false },
      { food: "Oignon", qty: 150, unit: "g", optional: false },
      { food: "Haricots blancs cuits", qty: 400, unit: "g", optional: false },
      { food: "Bouillon de légumes maison", qty: 2000, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 40, unit: "ml", optional: false },
      { food: "Basilic et persil frais", qty: 30, unit: "g", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Éplucher et couper en petits cubes tous les légumes. Émincer l'oignon finement.",
      "Faire chauffer l'huile d'olive dans une grande marmite, faire revenir l'oignon et le céleri 5 minutes.",
      "Ajouter les carottes, courgettes et haricots verts coupés. Mélanger et cuire 5 minutes.",
      "Verser le bouillon chaud, porter à ébullition et cuire 25 minutes. Ajouter les haricots blancs.",
      "Cuire encore 10 minutes. Saler et ajouter les herbes fraîches hors du feu.",
      "Laisser refroidir avant de congeler en portions de 400 ml."
    ],
    nutrition: { calories: 210, protein: 9, carbs: 30, fat: 6, fiber: 8 },
    tips: "Congeler en portions de 400 ml pour 3 mois. Ajouter des pâtes cuites séparément au moment du service pour éviter qu'elles ne ramollissent. Les herbes fraîches s'ajoutent uniquement au service. Idéal pour des repas rapides.",
    isCustom: false
  },
  {
    id: "batch-blanquette-veau",
    name: "Blanquette de veau à l'ancienne",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 90,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Veau épaule fraîche", qty: 1200, unit: "g", optional: false },
      { food: "Carottes", qty: 300, unit: "g", optional: false },
      { food: "Oignons", qty: 200, unit: "g", optional: false },
      { food: "Champignons de Paris frais", qty: 300, unit: "g", optional: false },
      { food: "Beurre", qty: 60, unit: "g", optional: false },
      { food: "Farine", qty: 50, unit: "g", optional: false },
      { food: "Crème fraîche épaisse", qty: 200, unit: "ml", optional: false },
      { food: "Bouillon de veau maison", qty: 800, unit: "ml", optional: false },
      { food: "Thym et laurier", qty: 5, unit: "g", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Couper le veau en gros cubes de 5 cm. Blanchir 5 minutes dans l'eau bouillante salée, égoutter et rincer.",
      "Faire fondre 40 g de beurre dans une cocotte. Faire revenir oignons émincés 3 minutes, ajouter le veau et les carottes en rondelles.",
      "Saupoudrer de farine, mélanger et cuire 2 minutes. Verser le bouillon chaud, ajouter thym et laurier. Porter à ébullition.",
      "Couvrir et laisser mijoter 70 minutes à feu doux jusqu'à ce que le veau soit très tendre.",
      "Dans une poêle, faire sauter les champignons émincés dans 20 g de beurre. Les ajouter à la blanquette.",
      "Incorporer la crème fraîche hors du feu, rectifier l'assaisonnement. Refroidir avant de conditionner."
    ],
    nutrition: { calories: 420, protein: 38, carbs: 12, fat: 24, fiber: 2 },
    tips: "Se congèle parfaitement en portions de 300 g pour 3 mois. Décongeler lentement au réfrigérateur. Réchauffer doucement à feu doux sans faire bouillir pour préserver la sauce crémeuse. Servir avec du riz blanc.",
    isCustom: false
  },
  {
    id: "batch-pot-au-feu-classique",
    name: "Pot-au-feu de bœuf aux légumes d'hiver",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 180,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Bœuf gîte ou paleron frais", qty: 1500, unit: "g", optional: false },
      { food: "Os à moelle frais", qty: 400, unit: "g", optional: true },
      { food: "Carottes", qty: 400, unit: "g", optional: false },
      { food: "Poireaux", qty: 300, unit: "g", optional: false },
      { food: "Navets", qty: 300, unit: "g", optional: false },
      { food: "Pommes de terre", qty: 400, unit: "g", optional: false },
      { food: "Oignon piqué de clous de girofle", qty: 1, unit: "pièce", optional: false },
      { food: "Bouquet garni (thym, laurier, persil)", qty: 10, unit: "g", optional: false },
      { food: "Sel gris", qty: 15, unit: "g", optional: false },
      { food: "Eau froide", qty: 3000, unit: "ml", optional: false }
    ],
    steps: [
      "Ficeler la viande pour maintenir sa forme. Placer dans une grande marmite avec l'eau froide, porter lentement à ébullition en écumant.",
      "Ajouter l'oignon piqué de clous de girofle, le bouquet garni et le sel. Réduire le feu et mijoter 1 heure.",
      "Ajouter carottes, navets et poireaux ficelés en bottes. Continuer la cuisson 1 heure.",
      "Ajouter les pommes de terre et les os à moelle les 30 dernières minutes de cuisson.",
      "Vérifier la tendreté de la viande. Retirer la viande et les légumes. Filtrer le bouillon.",
      "Trancher la viande refroidie, conditionner séparément viande, légumes et bouillon avant congélation."
    ],
    nutrition: { calories: 380, protein: 42, carbs: 22, fat: 12, fiber: 4 },
    tips: "Congeler la viande, les légumes et le bouillon séparément en portions pour 3 mois. Le bouillon dégraissé se congèle en cubes de glace. Les pommes de terre ne se congèlent pas bien, à préparer frais. Réchauffer doucement dans le bouillon.",
    isCustom: false
  },
  {
    id: "batch-poulet-roti-herbes",
    name: "Cuisses de poulet rôties aux herbes de Provence",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 55,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Cuisses de poulet fraîches", qty: 1500, unit: "g", optional: false },
      { food: "Herbes de Provence", qty: 10, unit: "g", optional: false },
      { food: "Ail frais", qty: 6, unit: "gousses", optional: false },
      { food: "Huile d'olive", qty: 50, unit: "ml", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Thym frais", qty: 10, unit: "g", optional: false },
      { food: "Romarin frais", qty: 5, unit: "g", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Préchauffer le four à 200°C. Sécher les cuisses de poulet avec du papier absorbant.",
      "Mélanger l'huile d'olive, les herbes de Provence et le sel. Badigeonner généreusement les cuisses.",
      "Disposer les cuisses dans un grand plat à rôtir. Ajouter les gousses d'ail en chemise, le thym et le romarin.",
      "Parsemer de noisettes de beurre et enfourner 50 minutes en arrosant deux fois en cours de cuisson.",
      "Vérifier la cuisson (jus clair quand on pique la cuisse). Laisser reposer 10 minutes hors du four.",
      "Effilocher ou laisser entier selon l'usage prévu. Refroidir rapidement avant de conditionner."
    ],
    nutrition: { calories: 390, protein: 35, carbs: 2, fat: 27, fiber: 0 },
    tips: "Congeler les cuisses entières ou effilochées en portions pour 3 mois. La chair effilochée est pratique pour garnir des soupes ou des salades. Conserver le jus de cuisson dégraissé comme sauce. Décongeler au réfrigérateur 12 heures avant utilisation.",
    isCustom: false
  },
  {
    id: "batch-agneau-mijote-legumes",
    name: "Épaule d'agneau mijotée aux légumes du soleil",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Épaule d'agneau fraîche désossée", qty: 1200, unit: "g", optional: false },
      { food: "Courgettes", qty: 300, unit: "g", optional: false },
      { food: "Poivrons rouges frais", qty: 300, unit: "g", optional: false },
      { food: "Oignons", qty: 250, unit: "g", optional: false },
      { food: "Ail frais", qty: 4, unit: "gousses", optional: false },
      { food: "Carottes", qty: 200, unit: "g", optional: false },
      { food: "Curcuma", qty: 5, unit: "g", optional: false },
      { food: "Cumin", qty: 5, unit: "g", optional: false },
      { food: "Coriandre fraîche", qty: 20, unit: "g", optional: false },
      { food: "Bouillon de légumes maison", qty: 500, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 40, unit: "ml", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Couper l'agneau en cubes de 4 cm. Dans une cocotte, faire chauffer l'huile à feu vif et saisir la viande en plusieurs fois jusqu'à coloration. Réserver.",
      "Faire revenir les oignons émincés et l'ail dans la même cocotte 5 minutes. Ajouter le curcuma et le cumin, mélanger 1 minute.",
      "Remettre l'agneau, ajouter les carottes en rondelles. Verser le bouillon et porter à ébullition.",
      "Couvrir et cuire à feu doux 80 minutes. Ajouter les courgettes et les poivrons coupés en cubes.",
      "Cuire encore 25 minutes jusqu'à ce que tous les légumes soient tendres. Rectifier l'assaisonnement.",
      "Parsemer de coriandre fraîche. Refroidir rapidement avant de conditionner en portions."
    ],
    nutrition: { calories: 380, protein: 34, carbs: 12, fat: 22, fiber: 3 },
    tips: "Congeler en portions de 300 g pour 3 mois. La sauce se fige en refroidissant, c'est normal. Servir avec du couscous ou du riz. Décongeler lentement au réfrigérateur et réchauffer doucement en ajoutant un peu d'eau si nécessaire.",
    isCustom: false
  },
  {
    id: "batch-riz-blanc-congel",
    name: "Riz blanc en batch pour congélation",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 20,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz basmati", qty: 600, unit: "g", optional: false },
      { food: "Eau", qty: 1200, unit: "ml", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false }
    ],
    steps: [
      "Rincer le riz plusieurs fois à l'eau froide jusqu'à ce que l'eau soit claire pour enlever l'excès d'amidon.",
      "Porter l'eau à ébullition avec le sel et un filet d'huile d'olive dans une grande casserole.",
      "Ajouter le riz, mélanger une fois et couvrir hermétiquement. Réduire le feu au minimum.",
      "Cuire exactement 15 minutes sans soulever le couvercle, puis retirer du feu et laisser reposer 5 minutes.",
      "Égrainer le riz à la fourchette pour aérer les grains. Étaler sur une plaque pour refroidir rapidement.",
      "Répartir en portions de 150 g dans des sacs de congélation plats. Congeler à plat pour faciliter le stockage."
    ],
    nutrition: { calories: 280, protein: 5, carbs: 60, fat: 2, fiber: 1 },
    tips: "Se congèle parfaitement jusqu'à 3 mois. Décongeler au micro-ondes en ajoutant 1 cuillère à soupe d'eau par portion (3 minutes à puissance moyenne). Ou laisser décongeler au réfrigérateur et réchauffer à la poêle avec un peu de beurre.",
    isCustom: false
  },
  {
    id: "batch-quinoa-cuit",
    name: "Quinoa cuit en grande quantité",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 20,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Quinoa blanc ou tricolore", qty: 500, unit: "g", optional: false },
      { food: "Bouillon de légumes maison", qty: 1000, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Sel", qty: 5, unit: "g", optional: false }
    ],
    steps: [
      "Rincer abondamment le quinoa dans une passoire fine sous l'eau froide pour enlever la saponine amère.",
      "Faire toaster le quinoa à sec dans une casserole 2 minutes en remuant pour développer les arômes.",
      "Ajouter le bouillon et l'huile, porter à ébullition. Réduire le feu, couvrir.",
      "Cuire 12 à 15 minutes jusqu'à absorption totale du liquide. Les germes blancs doivent être visibles.",
      "Retirer du feu, laisser reposer 5 minutes couvert puis égrainer à la fourchette.",
      "Refroidir rapidement sur une plaque et conditionner en portions de 150 g pour la congélation."
    ],
    nutrition: { calories: 240, protein: 9, carbs: 42, fat: 4, fiber: 3 },
    tips: "Se conserve 3 mois au congélateur en portions individuelles. Le quinoa cuit se réchauffe très bien au micro-ondes ou à la casserole avec un peu de bouillon. Utiliser comme base de bowl, accompagnement ou ajout dans les soupes.",
    isCustom: false
  },
  {
    id: "batch-pates-portionnees",
    name: "Pâtes cuites al dente en portions congelées",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 12,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Penne ou farfalle", qty: 600, unit: "g", optional: false },
      { food: "Eau", qty: 4000, unit: "ml", optional: false },
      { food: "Sel", qty: 20, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 30, unit: "ml", optional: false }
    ],
    steps: [
      "Porter une grande quantité d'eau salée à ébullition vive. La quantité d'eau est importante pour une cuisson uniforme.",
      "Ajouter les pâtes et cuire en retirant 2 minutes avant le temps indiqué sur le paquet (al dente plus ferme).",
      "Égoutter les pâtes en réservant 200 ml d'eau de cuisson.",
      "Rincer rapidement sous l'eau froide pour stopper la cuisson. Égoutter soigneusement.",
      "Huiler légèrement les pâtes avec l'huile d'olive pour éviter qu'elles collent. Mélanger délicatement.",
      "Répartir en portions de 150 g dans des sacs de congélation. Congeler à plat. Conserver l'eau de cuisson séparément."
    ],
    nutrition: { calories: 310, protein: 10, carbs: 58, fat: 5, fiber: 2 },
    tips: "Se conserve 2 mois au congélateur. Plonger directement les pâtes congelées dans de l'eau bouillante 2 minutes ou décongeler au micro-ondes avec un peu d'eau. Cuire légèrement al dente car elles ramollissent au réchauffage.",
    isCustom: false
  },
  {
    id: "batch-polenta-creme",
    name: "Polenta crémeuse en batch",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 30,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Semoule de maïs (polenta)", qty: 400, unit: "g", optional: false },
      { food: "Eau ou bouillon de légumes", qty: 2000, unit: "ml", optional: false },
      { food: "Beurre", qty: 60, unit: "g", optional: false },
      { food: "Ricotta fraîche", qty: 150, unit: "g", optional: true },
      { food: "Sel", qty: 10, unit: "g", optional: false }
    ],
    steps: [
      "Porter l'eau salée ou le bouillon à ébullition dans une grande casserole à fond épais.",
      "Verser la semoule en pluie fine en fouettant constamment pour éviter les grumeaux.",
      "Réduire le feu au minimum. Cuire 25 à 30 minutes en remuant souvent avec une cuillère en bois.",
      "Quand la polenta se détache des parois, incorporer le beurre et la ricotta si utilisée.",
      "Pour la congélation : verser dans des moules à cake chemisés ou des bacs à glaçons. Laisser refroidir.",
      "Démouler une fois froid, couper en tranches ou portions et emballer sous vide ou film alimentaire."
    ],
    nutrition: { calories: 290, protein: 7, carbs: 48, fat: 8, fiber: 2 },
    tips: "Congeler en tranches individuelles ou en blocs pour 2 mois. Réchauffer à la poêle avec un peu de beurre pour la gratifier, ou dans du lait pour retrouver la consistance crémeuse. Peut aussi se couper en tranches et se griller.",
    isCustom: false
  },
  {
    id: "batch-riz-pilaf-epices",
    name: "Riz pilaf aux épices douces",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 25,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz long grain", qty: 600, unit: "g", optional: false },
      { food: "Oignon", qty: 150, unit: "g", optional: false },
      { food: "Beurre", qty: 50, unit: "g", optional: false },
      { food: "Bouillon de légumes maison", qty: 1200, unit: "ml", optional: false },
      { food: "Curcuma", qty: 4, unit: "g", optional: false },
      { food: "Cumin", qty: 3, unit: "g", optional: false },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Rincer le riz et le laisser égoutter. Émincer finement l'oignon.",
      "Faire fondre le beurre dans une grande casserole à fond épais. Faire revenir l'oignon jusqu'à ce qu'il soit transparent, environ 5 minutes.",
      "Ajouter le riz et mélanger pour bien l'enrober de beurre. Faire nacrer 2 à 3 minutes à feu moyen.",
      "Ajouter le curcuma et le cumin, mélanger. Verser le bouillon chaud et saler.",
      "Porter à ébullition, couvrir hermétiquement, réduire le feu au minimum et cuire 18 minutes.",
      "Retirer du feu, laisser reposer 5 minutes sans soulever le couvercle. Égrainer et refroidir avant congélation."
    ],
    nutrition: { calories: 295, protein: 6, carbs: 58, fat: 5, fiber: 1 },
    tips: "Congeler en portions de 200 g dans des sachets plats pour 3 mois. La couleur dorée du curcuma est très appétissante au service. Décongeler au micro-ondes avec une cuillère d'eau. Accompagne parfaitement le poulet et l'agneau.",
    isCustom: false
  },
  {
    id: "batch-legumes-roles-four",
    name: "Légumes rôtis au four en grande quantité",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 45,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Courgettes", qty: 400, unit: "g", optional: false },
      { food: "Poivrons rouges et jaunes frais", qty: 400, unit: "g", optional: false },
      { food: "Champignons de Paris", qty: 300, unit: "g", optional: false },
      { food: "Carottes", qty: 300, unit: "g", optional: false },
      { food: "Oignons rouges", qty: 200, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 60, unit: "ml", optional: false },
      { food: "Thym et romarin frais", qty: 15, unit: "g", optional: false },
      { food: "Ail frais", qty: 4, unit: "gousses", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Préchauffer le four à 220°C. Couper tous les légumes en morceaux de taille uniforme (3-4 cm).",
      "Répartir les légumes sur deux grandes plaques de cuisson en évitant de trop les superposer.",
      "Arroser d'huile d'olive, ajouter l'ail en chemise, le thym et le romarin. Saler et mélanger.",
      "Enfourner 40 à 45 minutes en retournant à mi-cuisson jusqu'à ce que les légumes soient dorés et légèrement caramélisés.",
      "Laisser refroidir complètement sur les plaques pour éviter la condensation lors de la congélation.",
      "Répartir en portions de 200 g dans des sachets de congélation en expulsant l'air au maximum."
    ],
    nutrition: { calories: 160, protein: 4, carbs: 18, fat: 9, fiber: 5 },
    tips: "Se congèle pour 3 mois. Réchauffer directement au four à 180°C pendant 15 minutes ou à la poêle. Éviter le micro-ondes qui ramollit les légumes. Idéal en accompagnement, dans des wraps ou mélangé à des pâtes.",
    isCustom: false
  },
  {
    id: "batch-betteraves-carottes-roties",
    name: "Betteraves rôties et carottes glacées au four",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 60,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Betteraves crues fraîches", qty: 600, unit: "g", optional: false },
      { food: "Carottes", qty: 500, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 50, unit: "ml", optional: false },
      { food: "Miel", qty: 30, unit: "g", optional: false },
      { food: "Thym frais", qty: 8, unit: "g", optional: false },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Préchauffer le four à 200°C. Éplucher les betteraves et les carottes. Couper en quartiers ou bâtonnets selon la taille.",
      "Séparer betteraves et carottes sur deux plaques différentes car les betteraves colorent tout.",
      "Arroser d'huile d'olive, ajouter le miel, le thym et le sel. Mélanger pour bien enrober les légumes.",
      "Enfourner les betteraves 50 à 60 minutes et les carottes 35 à 40 minutes jusqu'à tendreté et légère caramélisation.",
      "Laisser refroidir complètement à température ambiante.",
      "Mélanger betteraves et carottes une fois refroidies. Portionner en 200 g et congeler en sachets."
    ],
    nutrition: { calories: 170, protein: 3, carbs: 28, fat: 6, fiber: 5 },
    tips: "Congeler en portions pour 3 mois. Porter des gants pour manipuler les betteraves qui tachent. Réchauffer au four 15 minutes à 180°C pour retrouver le côté rôti. Délicieux avec du chèvre frais au moment du service.",
    isCustom: false
  },
  {
    id: "batch-champignons-ail-persil",
    name: "Champignons sautés en batch à l'ail et persil",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Champignons de Paris frais", qty: 1200, unit: "g", optional: false },
      { food: "Beurre", qty: 60, unit: "g", optional: false },
      { food: "Ail frais", qty: 4, unit: "gousses", optional: false },
      { food: "Persil frais", qty: 30, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 30, unit: "ml", optional: false },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Nettoyer les champignons avec un linge humide sans les laver sous l'eau. Les couper en quartiers.",
      "Dans une très grande poêle ou en plusieurs fournées, chauffer le mélange beurre-huile à feu vif.",
      "Cuire les champignons sans les bouger 3 minutes pour les saisir, puis mélanger. Ils doivent dorer, pas rendre d'eau.",
      "Ajouter l'ail émincé et faire sauter encore 2 minutes.",
      "Hors du feu, ajouter le persil haché, saler. Mélanger et laisser refroidir.",
      "Portionner en 150 g dans des sacs de congélation ou boîtes hermétiques."
    ],
    nutrition: { calories: 120, protein: 4, carbs: 6, fat: 9, fiber: 2 },
    tips: "Se congèle pour 2 mois. Excellente garniture pour omelettes, pâtes, riz ou sur des tranches de pain. Ajouter le persil frais uniquement au service pour plus de fraîcheur. Cuire à feu très vif pour éviter l'excès d'eau.",
    isCustom: false
  },
  {
    id: "batch-ratatouille-sans-tomate",
    name: "Ratatouille provençale sans tomates",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 50,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Courgettes", qty: 600, unit: "g", optional: false },
      { food: "Poivrons rouges et jaunes frais", qty: 500, unit: "g", optional: false },
      { food: "Oignons", qty: 300, unit: "g", optional: false },
      { food: "Ail frais", qty: 5, unit: "gousses", optional: false },
      { food: "Huile d'olive", qty: 80, unit: "ml", optional: false },
      { food: "Thym et romarin frais", qty: 15, unit: "g", optional: false },
      { food: "Basilic frais", qty: 20, unit: "g", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Couper les courgettes en demi-rondelles épaisses. Épépiner et couper les poivrons en lanières. Émincer les oignons.",
      "Faire chauffer l'huile dans une grande cocotte. Faire revenir les oignons 8 minutes jusqu'à légère coloration.",
      "Ajouter les poivrons et cuire 10 minutes à feu moyen. Ajouter l'ail émincé.",
      "Incorporer les courgettes, le thym et le romarin. Saler et mélanger.",
      "Couvrir et cuire à feu doux 30 minutes, en remuant régulièrement jusqu'à ce que les légumes soient fondants.",
      "Ajouter le basilic hors du feu. Refroidir avant de portionner pour la congélation."
    ],
    nutrition: { calories: 145, protein: 3, carbs: 16, fat: 8, fiber: 4 },
    tips: "Congeler en portions de 200 g pour 3 mois. Polyvalente : à utiliser en accompagnement, garniture de tarte, sauce pour pâtes ou sur du riz. Ajouter le basilic frais uniquement au moment du service. Se bonifie en réchauffant.",
    isCustom: false
  },
  {
    id: "batch-lentilles-vertes-cuites",
    name: "Lentilles vertes cuites en batch",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 35,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Lentilles vertes du Puy sèches", qty: 500, unit: "g", optional: false },
      { food: "Carottes", qty: 200, unit: "g", optional: false },
      { food: "Oignon", qty: 150, unit: "g", optional: false },
      { food: "Ail frais", qty: 3, unit: "gousses", optional: false },
      { food: "Bouquet garni", qty: 5, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 30, unit: "ml", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false },
      { food: "Eau froide", qty: 1500, unit: "ml", optional: false }
    ],
    steps: [
      "Trier et rincer les lentilles à l'eau froide. Ne pas les faire tremper pour les lentilles vertes.",
      "Dans une casserole, faire revenir l'oignon émincé dans l'huile 3 minutes. Ajouter l'ail et les carottes en brunoise.",
      "Ajouter les lentilles et le bouquet garni. Couvrir d'eau froide (2 fois le volume de lentilles).",
      "Porter à ébullition, écumer puis réduire le feu. Cuire 30 minutes à feu doux.",
      "Saler en fin de cuisson seulement (le sel précoce durcit les lentilles). Vérifier la tendreté.",
      "Égoutter si trop d'eau, laisser refroidir et portionner en 200 g pour la congélation."
    ],
    nutrition: { calories: 230, protein: 15, carbs: 36, fat: 4, fiber: 8 },
    tips: "Se congèle parfaitement pour 3 mois. Utiliser en vinaigrette (assaisonner tiède), en soupe, en accompagnement ou en galettes. Congeler avec un peu de leur jus de cuisson pour éviter le dessèchement. Polyvalentes et nutritives.",
    isCustom: false
  },
  {
    id: "batch-pois-chiches-epices",
    name: "Pois chiches mijotés aux épices maison",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pois chiches secs (trempés une nuit)", qty: 500, unit: "g", optional: false },
      { food: "Oignons", qty: 250, unit: "g", optional: false },
      { food: "Ail frais", qty: 4, unit: "gousses", optional: false },
      { food: "Curcuma", qty: 5, unit: "g", optional: false },
      { food: "Cumin moulu", qty: 5, unit: "g", optional: false },
      { food: "Coriandre moulue", qty: 4, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 40, unit: "ml", optional: false },
      { food: "Bouillon de légumes maison", qty: 600, unit: "ml", optional: false },
      { food: "Persil frais", qty: 20, unit: "g", optional: true },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Faire tremper les pois chiches 12 heures dans l'eau froide. Égoutter et rincer avant utilisation.",
      "Faire chauffer l'huile dans une grande casserole. Faire dorer les oignons émincés 8 minutes.",
      "Ajouter l'ail et les épices, mélanger 2 minutes à feu moyen pour les torréfier légèrement.",
      "Ajouter les pois chiches égouttés, mélanger pour les enrober. Verser le bouillon.",
      "Porter à ébullition, couvrir et mijoter 35 à 40 minutes jusqu'à tendreté. Ajouter de l'eau si nécessaire.",
      "Saler en fin de cuisson. Écraser légèrement quelques pois chiches pour épaissir la sauce. Refroidir avant congélation."
    ],
    nutrition: { calories: 270, protein: 13, carbs: 38, fat: 7, fiber: 9 },
    tips: "Congeler en portions de 200 g avec leur jus pour 3 mois. Polyvalent : en houmous maison, en soupe, avec du riz, dans des wraps. Peut se préparer avec des pois chiches en boîte rincés pour gagner du temps, cuisson réduite à 15 minutes.",
    isCustom: false
  },
  {
    id: "batch-haricots-blancs-mijoter",
    name: "Haricots blancs mijotés au thym et laurier",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 60,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Haricots blancs secs (cocos ou lingots)", qty: 500, unit: "g", optional: false },
      { food: "Oignon", qty: 200, unit: "g", optional: false },
      { food: "Carottes", qty: 200, unit: "g", optional: false },
      { food: "Ail frais", qty: 3, unit: "gousses", optional: false },
      { food: "Thym frais", qty: 5, unit: "g", optional: false },
      { food: "Laurier", qty: 2, unit: "feuilles", optional: false },
      { food: "Huile d'olive", qty: 30, unit: "ml", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false },
      { food: "Eau froide", qty: 1800, unit: "ml", optional: false }
    ],
    steps: [
      "Faire tremper les haricots blancs une nuit (minimum 8 heures) dans de l'eau froide. Égoutter et rincer.",
      "Faire revenir l'oignon et les carottes en brunoise dans l'huile d'olive 5 minutes.",
      "Ajouter les haricots, l'ail, le thym et le laurier. Couvrir d'eau froide (3 fois le volume).",
      "Porter à ébullition 5 minutes puis réduire le feu. Cuire 50 à 55 minutes à frémissement.",
      "Saler uniquement en fin de cuisson. Les haricots doivent être tendres mais entiers.",
      "Laisser tiédir dans leur jus, portionner en 200 g avec du jus et congeler."
    ],
    nutrition: { calories: 245, protein: 12, carbs: 40, fat: 4, fiber: 10 },
    tips: "Congeler avec leur jus de cuisson en portions de 200 g pour 3 mois. Parfaits en soupe, en salade tiède, en gratin ou en purée. Le jus de cuisson est précieux comme bouillon végétal. Décongeler au réfrigérateur la veille.",
    isCustom: false
  },
  {
    id: "batch-dahl-lentilles-coco",
    name: "Dahl de lentilles corail au lait de coco",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 30,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Lentilles corail sèches", qty: 400, unit: "g", optional: false },
      { food: "Lait de coco", qty: 400, unit: "ml", optional: false },
      { food: "Oignons", qty: 200, unit: "g", optional: false },
      { food: "Ail frais", qty: 3, unit: "gousses", optional: false },
      { food: "Gingembre frais râpé", qty: 15, unit: "g", optional: false },
      { food: "Curcuma", qty: 5, unit: "g", optional: false },
      { food: "Cumin", qty: 4, unit: "g", optional: false },
      { food: "Coriandre moulue", qty: 4, unit: "g", optional: false },
      { food: "Huile de coco ou beurre", qty: 30, unit: "ml", optional: false },
      { food: "Bouillon de légumes maison", qty: 500, unit: "ml", optional: false },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Rincer les lentilles corail. Émincer les oignons, écraser l'ail, râper le gingembre frais.",
      "Dans une grande casserole, faire fondre l'huile de coco. Faire revenir les oignons 5 minutes.",
      "Ajouter l'ail, le gingembre et les épices. Mélanger 2 minutes à feu moyen.",
      "Incorporer les lentilles rincées, verser le lait de coco et le bouillon. Mélanger.",
      "Porter à ébullition, réduire le feu et cuire 20 à 25 minutes en remuant régulièrement jusqu'à épaississement.",
      "Rectifier sel et épices. Laisser refroidir avant de portionner et congeler."
    ],
    nutrition: { calories: 320, protein: 14, carbs: 40, fat: 12, fiber: 7 },
    tips: "Congeler en portions de 250 g pour 3 mois. Servir avec du riz basmati. Ajouter de la coriandre fraîche au service uniquement. Légèrement épais à la congélation, diluer avec un peu d'eau au réchauffage. Plat complet très nutritif.",
    isCustom: false
  },
  {
    id: "prep-poulet-effiloche-massif",
    name: "Blanc de poulet poché et effiloché en grande quantité",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blancs de poulet frais", qty: 1500, unit: "g", optional: false },
      { food: "Bouillon de poulet maison", qty: 800, unit: "ml", optional: false },
      { food: "Thym et laurier", qty: 5, unit: "g", optional: false },
      { food: "Ail frais", qty: 2, unit: "gousses", optional: false },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Verser le bouillon dans une grande sauteuse. Ajouter thym, laurier, ail et sel. Porter à frémissement.",
      "Plonger les blancs de poulet dans le bouillon frémissant. Ils doivent être entièrement couverts.",
      "Cuire à feu doux 20 à 25 minutes jusqu'à ce que la chair soit bien cuite (70°C à cœur).",
      "Retirer les blancs et laisser tiédir 10 minutes. Conserver le bouillon pour d'autres préparations.",
      "Effilocher la chair en fines lamelles à l'aide de deux fourchettes.",
      "Répartir en portions de 150 g dans des sachets de congélation avec 2 cuillères de bouillon pour garder l'humidité."
    ],
    nutrition: { calories: 200, protein: 38, carbs: 1, fat: 4, fiber: 0 },
    tips: "Se congèle 3 mois en portions. Cuisson pochée idéale pour la congélation car plus juteuse. Utiliser dans des soupes, salades, sandwichs, pâtes ou quiches. Décongeler au réfrigérateur 8 heures. Ne jamais recongeler après décongélation.",
    isCustom: false
  },
  {
    id: "prep-boulettes-agneau-four",
    name: "Boulettes d'agneau aux herbes cuites au four",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 25,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Agneau haché frais", qty: 1000, unit: "g", optional: false },
      { food: "Oignon", qty: 150, unit: "g", optional: false },
      { food: "Ail frais", qty: 3, unit: "gousses", optional: false },
      { food: "Persil frais", qty: 25, unit: "g", optional: false },
      { food: "Menthe fraîche", qty: 10, unit: "g", optional: false },
      { food: "Cumin moulu", qty: 5, unit: "g", optional: false },
      { food: "Coriandre moulue", qty: 3, unit: "g", optional: false },
      { food: "Oeuf frais", qty: 1, unit: "pièce", optional: false },
      { food: "Chapelure de pain frais", qty: 40, unit: "g", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false }
    ],
    steps: [
      "Préchauffer le four à 200°C. Râper l'oignon finement, écraser l'ail. Hacher finement persil et menthe.",
      "Dans un grand bol, mélanger la viande hachée, l'oignon, l'ail, les herbes, les épices, l'oeuf et la chapelure.",
      "Pétrir la farce à la main pendant 2 minutes pour bien amalgamer tous les ingrédients.",
      "Former des boulettes de 3 cm de diamètre (environ 30 à 35 boulettes). Les déposer sur une plaque huilée.",
      "Enfourner 20 à 25 minutes jusqu'à coloration dorée en retournant à mi-cuisson.",
      "Laisser refroidir sur une grille avant de congeler en portions de 6 à 8 boulettes."
    ],
    nutrition: { calories: 310, protein: 28, carbs: 8, fat: 18, fiber: 1 },
    tips: "Congeler en portions pour 3 mois. Surgeler d'abord sur plaque puis transférer en sachet pour éviter qu'elles ne collent. Réchauffer au four 15 minutes à 180°C. Servir avec du couscous, du riz ou du yaourt nature. Très pratiques pour les repas rapides.",
    isCustom: false
  },
  {
    id: "prep-steaks-boeuf-maries",
    name: "Steaks de bœuf marinés aux herbes fraîches",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Bavette ou faux-filet de bœuf frais", qty: 800, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 60, unit: "ml", optional: false },
      { food: "Ail frais", qty: 4, unit: "gousses", optional: false },
      { food: "Thym frais", qty: 10, unit: "g", optional: false },
      { food: "Romarin frais", qty: 5, unit: "g", optional: false },
      { food: "Persil frais", qty: 15, unit: "g", optional: false },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Couper la viande en steaks de 150 à 200 g. Écraser l'ail et hacher finement les herbes.",
      "Préparer la marinade en mélangeant huile, ail, thym, romarin, persil et sel.",
      "Badigeonner généreusement chaque steak de marinade sur les deux faces.",
      "Pour congélation crue : emballer chaque steak mariné individuellement dans du film alimentaire puis en sachet.",
      "Pour cuisson immédiate : saisir à la poêle très chaude 2 à 3 minutes par face. Laisser reposer 5 minutes.",
      "Si cuits avant congélation : refroidir rapidement sur grille avant d'emballer."
    ],
    nutrition: { calories: 320, protein: 34, carbs: 1, fat: 20, fiber: 0 },
    tips: "Congeler cru mariné (idéal, 3 mois) ou cuit (2 mois). Décongeler au réfrigérateur pour une meilleure texture. Les steaks crus marinés se cuisent directement à la sortie du réfrigérateur. Ne pas décongeler à température ambiante.",
    isCustom: false
  },
  {
    id: "cook-sauce-bechamel-batch",
    name: "Sauce béchamel en grande quantité",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 20,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Beurre", qty: 100, unit: "g", optional: false },
      { food: "Farine", qty: 100, unit: "g", optional: false },
      { food: "Lait entier frais", qty: 1500, unit: "ml", optional: false },
      { food: "Noix de muscade", qty: 2, unit: "g", optional: false },
      { food: "Sel", qty: 6, unit: "g", optional: false }
    ],
    steps: [
      "Faire fondre le beurre dans une grande casserole à fond épais à feu moyen sans le faire brunir.",
      "Ajouter la farine d'un coup et mélanger vigoureusement avec un fouet pour former un roux lisse.",
      "Cuire le roux 2 minutes en remuant pour éliminer le goût de farine crue.",
      "Verser le lait froid en filet tout en fouettant constamment pour éviter les grumeaux.",
      "Cuire à feu moyen en fouettant sans arrêt jusqu'à épaississement, environ 10 à 12 minutes. Assaisonner de sel et muscade.",
      "Verser dans des pots hermétiques. Recouvrir d'un film alimentaire au contact pour éviter la croûte. Laisser refroidir avant de congeler."
    ],
    nutrition: { calories: 220, protein: 6, carbs: 18, fat: 14, fiber: 0 },
    tips: "Congeler en portions de 250 ml pour 2 mois. Filmer au contact avant congélation. Décongeler au réfrigérateur et réchauffer à feu doux en fouettant. Diluer avec un peu de lait si trop épaisse. Base essentielle pour gratins, lasagnes et crêpes salées.",
    isCustom: false
  },
  {
    id: "cook-coulis-poivrons-doux",
    name: "Coulis de légumes doux façon sauce pour pâtes",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poivrons rouges frais", qty: 800, unit: "g", optional: false },
      { food: "Carottes", qty: 400, unit: "g", optional: false },
      { food: "Oignons", qty: 300, unit: "g", optional: false },
      { food: "Ail frais", qty: 4, unit: "gousses", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 40, unit: "ml", optional: false },
      { food: "Basilic frais", qty: 20, unit: "g", optional: false },
      { food: "Origan séché", qty: 4, unit: "g", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Éplucher et couper grossièrement poivrons, carottes et oignons. Écraser l'ail.",
      "Faire fondre le beurre avec l'huile d'olive dans une grande casserole. Faire revenir l'oignon 8 minutes.",
      "Ajouter carottes et poivrons, mélanger et cuire 5 minutes. Ajouter l'ail et l'origan.",
      "Couvrir d'eau à mi-hauteur et cuire à feu doux 30 minutes jusqu'à ce que les légumes soient très tendres.",
      "Mixer finement et passer au tamis fin pour une texture lisse. Rectifier le sel.",
      "Incorporer le basilic frais ciselé hors du feu. Refroidir et portionner en 200 ml pour congélation."
    ],
    nutrition: { calories: 130, protein: 3, carbs: 18, fat: 6, fiber: 4 },
    tips: "Congeler en portions de 200 ml pour 3 mois. Utiliser comme substitut de sauce tomate pour les pasta, la pizza maison ou les gratins. Se bonifie à la recongélation. Ajouter le basilic uniquement au service pour préserver la fraîcheur des arômes.",
    isCustom: false
  },
  {
    id: "cook-beurre-herbes-congel",
    name: "Beurre composé aux herbes fraîches",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Beurre doux", qty: 200, unit: "g", optional: false },
      { food: "Persil frais", qty: 40, unit: "g", optional: false },
      { food: "Ciboulette fraîche", qty: 20, unit: "g", optional: false },
      { food: "Estragon frais", qty: 10, unit: "g", optional: false },
      { food: "Cerfeuil frais", qty: 10, unit: "g", optional: false },
      { food: "Ail frais", qty: 2, unit: "gousses", optional: true },
      { food: "Sel", qty: 4, unit: "g", optional: false }
    ],
    steps: [
      "Sortir le beurre 30 minutes à température ambiante pour le ramollir.",
      "Laver et sécher soigneusement toutes les herbes. Les hacher très finement au couteau.",
      "Écraser l'ail si utilisé, réduire en purée fine.",
      "Dans un bol, malaxer le beurre mou avec toutes les herbes hachées, l'ail et le sel.",
      "Façonner en boudin dans du film alimentaire en roulant fermement. Nouer les extrémités.",
      "Réfrigérer 2 heures ou congeler directement. Couper en tranches au moment de l'utilisation."
    ],
    nutrition: { calories: 180, protein: 1, carbs: 0, fat: 20, fiber: 0 },
    tips: "Se conserve 3 mois au congélateur en boudin. Couper des tranches de 1 cm directement congelées sur les viandes chaudes, les pâtes ou les légumes. Peut aussi être coulé en petits cercles de silicone pour des portions individuelles. Très pratique au quotidien.",
    isCustom: false
  },
  {
    id: "congel-gratin-dauphinois-portions",
    name: "Gratin dauphinois en barquettes individuelles",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 60,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Pommes de terre à gratin", qty: 1500, unit: "g", optional: false },
      { food: "Crème fraîche liquide entière", qty: 500, unit: "ml", optional: false },
      { food: "Lait entier frais", qty: 300, unit: "ml", optional: false },
      { food: "Ail frais", qty: 3, unit: "gousses", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Mozzarella fraîche", qty: 150, unit: "g", optional: true },
      { food: "Noix de muscade", qty: 3, unit: "g", optional: false },
      { food: "Sel", qty: 8, unit: "g", optional: false }
    ],
    steps: [
      "Préchauffer le four à 180°C. Éplucher et couper les pommes de terre en rondelles fines de 3 mm à la mandoline.",
      "Frotter un plat à gratin beurré avec les gousses d'ail coupées. Faire chauffer crème et lait avec l'ail émincé.",
      "Disposer les rondelles en couches imbriquées. Saler légèrement et saupoudrer de muscade entre chaque couche.",
      "Verser le mélange crème-lait chaud sur les pommes de terre. Le liquide doit affleurer.",
      "Couvrir de papier alu et enfourner 45 minutes, retirer le papier et cuire encore 15 minutes pour gratiner.",
      "Laisser refroidir complètement avant de découper en portions individuelles et d'emballer pour congélation."
    ],
    nutrition: { calories: 380, protein: 8, carbs: 40, fat: 22, fiber: 3 },
    tips: "Congeler en portions individuelles bien emballées pour 2 mois. Réchauffer au four à 160°C pendant 25 minutes couvert de papier alu, puis 10 minutes à découvert pour retrouver le croustillant. Éviter le micro-ondes qui rend les pommes de terre caoutchouteuses.",
    isCustom: false
  },
  {
    id: "congel-curry-poulet-coco",
    name: "Curry de poulet au lait de coco",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 5,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Cuisses ou blancs de poulet frais", qty: 1000, unit: "g", optional: false },
      { food: "Lait de coco", qty: 400, unit: "ml", optional: false },
      { food: "Oignons", qty: 200, unit: "g", optional: false },
      { food: "Ail frais", qty: 3, unit: "gousses", optional: false },
      { food: "Gingembre frais", qty: 15, unit: "g", optional: false },
      { food: "Curcuma", qty: 5, unit: "g", optional: false },
      { food: "Cumin et coriandre moulus", qty: 6, unit: "g", optional: false },
      { food: "Pommes de terre", qty: 400, unit: "g", optional: false },
      { food: "Petits pois frais ou surgelés", qty: 200, unit: "g", optional: true },
      { food: "Huile de coco", qty: 30, unit: "ml", optional: false },
      { food: "Sel", qty: 7, unit: "g", optional: false }
    ],
    steps: [
      "Couper le poulet en morceaux de 4 cm. Émincer oignons, écraser l'ail, râper le gingembre.",
      "Faire chauffer l'huile de coco dans une grande casserole. Dorer le poulet sur toutes les faces. Réserver.",
      "Dans la même casserole, faire revenir oignons 5 minutes. Ajouter ail, gingembre et épices, mélanger 2 minutes.",
      "Remettre le poulet, ajouter les pommes de terre en cubes et verser le lait de coco. Porter à ébullition.",
      "Réduire le feu, couvrir et cuire 25 minutes. Ajouter les petits pois les 5 dernières minutes.",
      "Rectifier l'assaisonnement. Refroidir rapidement avant de portionner et congeler."
    ],
    nutrition: { calories: 420, protein: 32, carbs: 28, fat: 20, fiber: 4 },
    tips: "Congeler en portions de 300 g sans riz pour 3 mois. Préparer le riz frais au service. Décongeler au réfrigérateur 12 heures. Réchauffer doucement en casserole en ajoutant un peu d'eau. Plat complet et très parfumé.",
    isCustom: false
  }
];
