const RECIPES_BATCH_1 = [
  {
    id: "bowl-poulet-riz-jasmin-legumes",
    name: "Bol de Poulet au Riz Jasmin et Légumes Croquants",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Poulet frais (blanc)", qty: 300, unit: "g", optional: false },
      { food: "Riz jasmin", qty: 180, unit: "g", optional: false },
      { food: "Courgette", qty: 1, unit: "pièce", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Bok choy", qty: 2, unit: "pièce", optional: false },
      { food: "Gingembre frais", qty: 5, unit: "g", optional: true },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Huile de sésame", qty: 10, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Coriandre fraîche", qty: 10, unit: "g", optional: true }
    ],
    steps: [
      "Rincer le riz jasmin à l'eau froide jusqu'à ce que l'eau soit claire. Cuire dans 360 ml d'eau salée, porter à ébullition puis réduire à feu doux, couvrir et cuire 15 minutes. Laisser reposer 5 minutes.",
      "Couper le poulet en lanières de 2 cm. Émincer l'ail et râper finement le gingembre.",
      "Éplucher les carottes et les couper en julienne. Couper la courgette en demi-lunes. Séparer les feuilles de bok choy du trognon.",
      "Chauffer l'huile d'olive dans un wok à feu vif. Faire revenir l'ail et le gingembre 30 secondes, puis ajouter le poulet et cuire 5 à 7 minutes jusqu'à coloration dorée.",
      "Ajouter les carottes et cuire 3 minutes, puis incorporer la courgette et le bok choy. Sauter 3 à 4 minutes en remuant constamment.",
      "Répartir le riz dans deux bols, disposer le mélange poulet-légumes par-dessus. Arroser d'un filet d'huile de sésame et garnir de coriandre fraîche.",
      "Servir immédiatement pendant que c'est chaud."
    ],
    nutrition: { calories: 480, protein: 38, carbs: 52, fat: 12, fiber: 4 },
    tips: "Utiliser uniquement du gingembre frais en petite quantité. Le gingembre séché ou en poudre est plus concentré et peut être plus irritant. Éviter de conserver ce plat plus de 24h car les restes de poulet cuit augmentent le taux d'histamine.",
    isCustom: false
  },
  {
    id: "bowl-dinde-riz-brun-concombre",
    name: "Bol Japonais à la Dinde et Concombre sur Riz Brun",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Escalope de dinde fraîche", qty: 320, unit: "g", optional: false },
      { food: "Riz brun", qty: 160, unit: "g", optional: false },
      { food: "Concombre", qty: 1, unit: "pièce", optional: false },
      { food: "Carotte", qty: 1, unit: "pièce", optional: false },
      { food: "Oignon vert (ciboulette)", qty: 3, unit: "tige", optional: true },
      { food: "Coconut aminos", qty: 30, unit: "ml", optional: false },
      { food: "Huile de sésame", qty: 10, unit: "ml", optional: false },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false },
      { food: "Graines de sésame", qty: 10, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Cuire le riz brun selon les instructions du paquet (environ 30 minutes). Maintenir au chaud.",
      "Couper la dinde en fines tranches. Dans un bol, mélanger les coconut aminos avec l'ail émincé et laisser mariner 10 minutes.",
      "Éplucher le concombre et le couper en demi-rondelles. Râper la carotte. Émincer finement les oignons verts.",
      "Chauffer l'huile d'olive dans un wok à feu vif. Égoutter la dinde de sa marinade et faire sauter 5 à 6 minutes jusqu'à cuisson complète. Réserver.",
      "Déglacer le wok avec la marinade restante et laisser réduire 1 minute.",
      "Répartir le riz dans deux bols. Disposer la dinde, le concombre et la carotte. Arroser de sauce réduite et d'huile de sésame.",
      "Garnir d'oignons verts et de graines de sésame. Servir aussitôt."
    ],
    nutrition: { calories: 460, protein: 42, carbs: 44, fat: 11, fiber: 3 },
    tips: "Les coconut aminos remplacent parfaitement la sauce soja et sont bien tolérés par la plupart des personnes sensibles à l'histamine. Utiliser les oignons verts en petite quantité car ils peuvent être légèrement histaminiques.",
    isCustom: false
  },
  {
    id: "noodle-poulet-nouilles-riz-gingembre",
    name: "Nouilles de Riz au Poulet et Gingembre Style Thaï",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Nouilles de riz larges", qty: 200, unit: "g", optional: false },
      { food: "Poulet frais (blanc)", qty: 280, unit: "g", optional: false },
      { food: "Poivron jaune", qty: 1, unit: "pièce", optional: false },
      { food: "Carotte", qty: 1, unit: "pièce", optional: false },
      { food: "Bok choy", qty: 2, unit: "pièce", optional: false },
      { food: "Gingembre frais", qty: 8, unit: "g", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Coconut aminos", qty: 40, unit: "ml", optional: false },
      { food: "Huile de coco", qty: 20, unit: "ml", optional: false },
      { food: "Basilic thaï frais", qty: 15, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Faire tremper les nouilles de riz dans de l'eau tiède pendant 20 minutes jusqu'à ce qu'elles soient souples, puis égoutter.",
      "Couper le poulet en fines lanières. Émincer l'ail et râper le gingembre. Couper le poivron en lanières, les carottes en julienne fine.",
      "Chauffer l'huile de coco dans un grand wok à feu très vif. Faire sauter l'ail et le gingembre 30 secondes en remuant constamment.",
      "Ajouter le poulet et cuire 5 minutes jusqu'à ce qu'il soit doré. Ajouter les carottes et le poivron, cuire 3 minutes.",
      "Incorporer le bok choy haché et les nouilles égouttées. Verser les coconut aminos et mélanger vigoureusement 2 à 3 minutes.",
      "Vérifier la cuisson des nouilles - elles doivent être al dente. Rectifier l'assaisonnement en sel.",
      "Servir dans des bols profonds, garnir de feuilles de basilic thaï frais."
    ],
    nutrition: { calories: 510, protein: 36, carbs: 62, fat: 11, fiber: 4 },
    tips: "Le poivron jaune est mieux toléré que le rouge qui est plus riche en histamine. Choisir des nouilles de riz pur sans additifs ni colorants. Consommer immédiatement après la cuisson.",
    isCustom: false
  },
  {
    id: "viet-pho-poulet-maison",
    name: "Pho de Poulet Maison Style Vietnamien",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 3,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Poulet frais entier ou morceaux", qty: 600, unit: "g", optional: false },
      { food: "Nouilles de riz vermicelles", qty: 200, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 20, unit: "g", optional: false },
      { food: "Ail", qty: 4, unit: "gousse", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Bok choy", qty: 3, unit: "pièce", optional: false },
      { food: "Oignon vert", qty: 4, unit: "tige", optional: true },
      { food: "Basilic frais", qty: 20, unit: "g", optional: true },
      { food: "Menthe fraîche", qty: 10, unit: "g", optional: true },
      { food: "Sel", qty: 2, unit: "c. à café", optional: false },
      { food: "Eau", qty: 1500, unit: "ml", optional: false }
    ],
    steps: [
      "Blanchir le poulet : plonger les morceaux dans de l'eau bouillante 3 minutes, égoutter et rincer à l'eau froide. Cette étape élimine les impuretés et réduit l'histamine.",
      "Dans une grande casserole, porter 1500 ml d'eau à ébullition. Ajouter le poulet, le gingembre coupé en tranches épaisses, l'ail écrasé et les carottes coupées en morceaux. Saler.",
      "Laisser mijoter à feu doux pendant 35 minutes. Écumer régulièrement pour un bouillon clair. Ne pas faire bouillir à gros bouillons.",
      "Sortir le poulet, laisser tiédir, effiler la chair et réserver. Filtrer le bouillon au chinois fin pour le clarifier.",
      "Cuire les vermicelles de riz selon les instructions (généralement 3 à 5 minutes dans de l'eau bouillante), égoutter et rincer à l'eau froide.",
      "Chauffer à nouveau le bouillon. Répartir les vermicelles dans des bols profonds, ajouter le poulet effilé et le bok choy coupé. Verser le bouillon chaud par-dessus.",
      "Garnir d'oignons verts émincés, de feuilles de basilic et de menthe fraîche. Servir immédiatement."
    ],
    nutrition: { calories: 380, protein: 34, carbs: 44, fat: 7, fiber: 3 },
    tips: "Pour un bouillon à faible teneur en histamine, ne pas laisser mijoter plus de 45 minutes. Plus le bouillon mijote longtemps, plus il libère des amines biogènes. Consommer immédiatement ou congeler le bouillon rapidement.",
    isCustom: false
  },
  {
    id: "viet-rouleaux-printemps-poulet",
    name: "Rouleaux de Printemps Vietnamiens au Poulet Frais",
    category: "collation",
    mealType: ["dejeuner", "collation"],
    prepTime: 30,
    cookTime: 15,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Galettes de riz (papier de riz)", qty: 8, unit: "pièce", optional: false },
      { food: "Poulet frais (blanc)", qty: 200, unit: "g", optional: false },
      { food: "Vermicelles de riz", qty: 80, unit: "g", optional: false },
      { food: "Carotte", qty: 1, unit: "pièce", optional: false },
      { food: "Concombre", qty: 0.5, unit: "pièce", optional: false },
      { food: "Salade iceberg", qty: 4, unit: "feuille", optional: false },
      { food: "Menthe fraîche", qty: 15, unit: "g", optional: true },
      { food: "Coriandre fraîche", qty: 10, unit: "g", optional: true },
      { food: "Coconut aminos", qty: 30, unit: "ml", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false }
    ],
    steps: [
      "Pocher le poulet dans de l'eau bouillante salée pendant 12 minutes. Laisser refroidir complètement et couper en fines lanières.",
      "Cuire les vermicelles de riz 3 minutes dans l'eau bouillante, égoutter, rincer à l'eau froide et couper grossièrement.",
      "Éplucher la carotte et la couper en fine julienne. Couper le concombre en fins bâtonnets. Laver et sécher les feuilles de salade.",
      "Préparer une sauce en mélangeant les coconut aminos avec l'ail finement émincé.",
      "Tremper une galette de riz dans de l'eau tiède pendant 15 à 20 secondes jusqu'à ce qu'elle soit souple. Placer sur un plan de travail propre.",
      "Garnir avec une feuille de salade, quelques vermicelles, des lanières de carotte, de concombre, de poulet, de menthe et de coriandre. Replier les côtés et rouler fermement.",
      "Répéter jusqu'à épuisement des ingrédients. Servir avec la sauce coconut aminos."
    ],
    nutrition: { calories: 290, protein: 24, carbs: 38, fat: 4, fiber: 2 },
    tips: "Préparer et consommer les rouleaux immédiatement après la confection car le riz ramollit rapidement. La sauce coconut aminos remplace la sauce nuoc-mâm traditionnelle qui est très riche en histamine.",
    isCustom: false
  },
  {
    id: "wok-boeuf-haricots-verts-thaï",
    name: "Wok de Poulet aux Poivrons Jaunes Style Thaï",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Poulet frais (cuisse désossée)", qty: 350, unit: "g", optional: false },
      { food: "Poivron jaune", qty: 2, unit: "pièce", optional: false },
      { food: "Poivron vert", qty: 1, unit: "pièce", optional: false },
      { food: "Bok choy", qty: 2, unit: "pièce", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 10, unit: "g", optional: false },
      { food: "Lait de coco", qty: 100, unit: "ml", optional: false },
      { food: "Coconut aminos", qty: 30, unit: "ml", optional: false },
      { food: "Huile de coco", qty: 20, unit: "ml", optional: false },
      { food: "Basilic thaï frais", qty: 20, unit: "g", optional: true },
      { food: "Riz blanc cuit", qty: 300, unit: "g", optional: false }
    ],
    steps: [
      "Couper le poulet en morceaux de 3 cm. Émincer l'ail, râper le gingembre. Couper les poivrons en lamelles et le bok choy en gros tronçons.",
      "Chauffer l'huile de coco dans un wok à feu très vif jusqu'à ce qu'elle fume légèrement.",
      "Faire revenir l'ail et le gingembre 30 secondes. Ajouter le poulet et saisir à feu vif 5 à 6 minutes jusqu'à coloration.",
      "Ajouter les poivrons et cuire 3 minutes en remuant. Incorporer le bok choy et cuire 2 minutes.",
      "Verser le lait de coco et les coconut aminos, mélanger et laisser réduire 2 à 3 minutes à feu moyen.",
      "Vérifier la cuisson du poulet et rectifier l'assaisonnement.",
      "Servir sur le riz chaud, garnir de feuilles de basilic thaï frais."
    ],
    nutrition: { calories: 520, protein: 40, carbs: 45, fat: 18, fiber: 4 },
    tips: "Les poivrons jaunes et verts sont mieux tolérés que les rouges. Le lait de coco apporte une onctuosité et remplace avantageusement la crème dans les plats à l'asiatique. Score histamine 2 en raison des poivrons.",
    isCustom: false
  },
  {
    id: "japan-donburi-poulet-teriyaki-coco",
    name: "Donburi de Poulet Teriyaki à la Noix de Coco",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Poulet frais (blanc)", qty: 300, unit: "g", optional: false },
      { food: "Riz japonais (rond)", qty: 200, unit: "g", optional: false },
      { food: "Coconut aminos", qty: 50, unit: "ml", optional: false },
      { food: "Miel pur", qty: 15, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 5, unit: "g", optional: true },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Huile de sésame", qty: 10, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false },
      { food: "Graines de sésame", qty: 10, unit: "g", optional: true },
      { food: "Oignon vert", qty: 3, unit: "tige", optional: true },
      { food: "Concombre", qty: 0.5, unit: "pièce", optional: false }
    ],
    steps: [
      "Rincer le riz japonais plusieurs fois jusqu'à eau claire. Cuire avec 240 ml d'eau, porter à ébullition, couvrir et cuire 12 minutes à feu doux. Laisser reposer 10 minutes.",
      "Préparer la sauce teriyaki : mélanger les coconut aminos, le miel, l'ail émincé et le gingembre râpé.",
      "Couper le poulet en escalopes de 1 cm d'épaisseur. Faire mariner 10 minutes dans la moitié de la sauce.",
      "Chauffer l'huile d'olive dans une poêle à feu moyen-vif. Faire cuire le poulet 4 à 5 minutes par face jusqu'à belle caramélisation.",
      "Verser la sauce restante sur le poulet et laisser réduire 2 minutes pour obtenir un glaçage brillant.",
      "Couper le concombre en fines rondelles. Émincer les oignons verts.",
      "Répartir le riz dans deux bols, disposer les tranches de poulet glacées, le concombre et garnir de graines de sésame, d'huile de sésame et d'oignons verts."
    ],
    nutrition: { calories: 490, protein: 38, carbs: 54, fat: 13, fiber: 2 },
    tips: "La sauce teriyaki classique contient de la sauce soja, remplacée ici par les coconut aminos. Le miel aide à obtenir la caramélisation caractéristique du teriyaki sans utiliser d'ingrédients problématiques.",
    isCustom: false
  },
  {
    id: "thai-soupe-coco-poulet-galanga",
    name: "Soupe Tom Kha de Poulet au Lait de Coco",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 25,
    servings: 3,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Poulet frais (blanc)", qty: 350, unit: "g", optional: false },
      { food: "Lait de coco entier", qty: 400, unit: "ml", optional: false },
      { food: "Bouillon de légumes maison", qty: 400, unit: "ml", optional: false },
      { food: "Champignons de Paris frais", qty: 150, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 20, unit: "g", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Citronnelle (partie blanche)", qty: 2, unit: "tige", optional: false },
      { food: "Coriandre fraîche", qty: 15, unit: "g", optional: true },
      { food: "Oignon vert", qty: 3, unit: "tige", optional: true },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Huile de coco", qty: 10, unit: "ml", optional: false }
    ],
    steps: [
      "Couper le poulet en morceaux de 3 cm. Frapper les tiges de citronnelle pour libérer les arômes et les couper en tronçons de 5 cm. Trancher le gingembre. Émincer l'ail.",
      "Dans une casserole, chauffer l'huile de coco et faire revenir l'ail 1 minute. Ajouter le poulet et saisir légèrement.",
      "Verser le bouillon de légumes, ajouter la citronnelle et le gingembre. Porter à ébullition et cuire 10 minutes.",
      "Ajouter les champignons de Paris nettoyés et coupés en quartiers. Cuire 5 minutes.",
      "Incorporer le lait de coco, réduire le feu et laisser frémir doucement 5 minutes sans faire bouillir. Saler.",
      "Retirer les morceaux de citronnelle et de gingembre qui sont uniquement aromatiques.",
      "Servir dans des bols, garnir de coriandre fraîche et d'oignons verts émincés."
    ],
    nutrition: { calories: 420, protein: 32, carbs: 12, fat: 28, fiber: 2 },
    tips: "La soupe Tom Kha originale contient du galanga, du citron et de la sauce de poisson, tous déconseillés. Cette version conserve les saveurs authentiques grâce à la citronnelle et au lait de coco. Ne pas faire bouillir le lait de coco pour éviter qu'il ne tourne.",
    isCustom: false
  },
  {
    id: "bowl-poisson-blanc-riz-thaï",
    name: "Bol de Poisson Blanc au Riz Thaï et Herbes Fraîches",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Filet de cabillaud frais", qty: 300, unit: "g", optional: false },
      { food: "Riz thaï (jasmin)", qty: 180, unit: "g", optional: false },
      { food: "Lait de coco", qty: 200, unit: "ml", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Courgette", qty: 1, unit: "pièce", optional: false },
      { food: "Gingembre frais", qty: 8, unit: "g", optional: true },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Coriandre fraîche", qty: 15, unit: "g", optional: true },
      { food: "Menthe fraîche", qty: 10, unit: "g", optional: true },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Cuire le riz jasmin dans 360 ml d'eau salée : porter à ébullition, couvrir et cuire 15 minutes à feu très doux.",
      "Éplucher et couper les carottes en rondelles fines, la courgette en demi-lunes. Émincer l'ail et râper le gingembre.",
      "Faire revenir l'ail et le gingembre dans l'huile d'olive 30 secondes. Ajouter les légumes et cuire 5 minutes.",
      "Verser le lait de coco sur les légumes, porter à frémissement. Ajouter le cabillaud coupé en gros dés.",
      "Couvrir et pocher le poisson dans le lait de coco 5 à 7 minutes jusqu'à ce qu'il s'effiloche facilement.",
      "Rectifier l'assaisonnement en sel.",
      "Servir le riz dans des bols, déposer les légumes et le poisson poché, napper de sauce au lait de coco. Garnir de coriandre et de menthe fraîches."
    ],
    nutrition: { calories: 470, protein: 34, carbs: 52, fat: 14, fiber: 4 },
    tips: "Le cabillaud est un poisson blanc très frais à choisir impérativement le jour même ou le lendemain de la pêche. Le tilapia ou la sole peuvent aussi être utilisés. Ne jamais utiliser de poisson en conserve ou légèrement avarié.",
    isCustom: false
  },
  {
    id: "japan-gyudon-bol-dinde-riz",
    name: "Gyudon de Dinde Adapté sur Riz Japonais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Escalope de dinde fraîche", qty: 350, unit: "g", optional: false },
      { food: "Riz japonais (rond)", qty: 200, unit: "g", optional: false },
      { food: "Oignon blanc", qty: 1, unit: "pièce", optional: false },
      { food: "Coconut aminos", qty: 60, unit: "ml", optional: false },
      { food: "Miel", qty: 20, unit: "g", optional: false },
      { food: "Eau", qty: 100, unit: "ml", optional: false },
      { food: "Gingembre frais", qty: 5, unit: "g", optional: true },
      { food: "Huile de sésame", qty: 10, unit: "ml", optional: false },
      { food: "Graines de sésame", qty: 8, unit: "g", optional: true },
      { food: "Oignon vert", qty: 2, unit: "tige", optional: true }
    ],
    steps: [
      "Rincer le riz japonais plusieurs fois. Cuire avec 240 ml d'eau : porter à ébullition, couvrir et cuire 12 minutes à feu minimal. Laisser reposer 10 minutes couvert.",
      "Couper la dinde en très fines lanières. Émincer l'oignon en demi-lunes.",
      "Dans une casserole, mélanger les coconut aminos, le miel, l'eau et le gingembre râpé. Porter à ébullition.",
      "Ajouter les oignons émincés dans la sauce et cuire 5 minutes jusqu'à translucidité.",
      "Ajouter les lanières de dinde et cuire à feu moyen 8 à 10 minutes en remuant doucement, jusqu'à cuisson complète et absorption partielle de la sauce.",
      "Répartir le riz dans deux bols. Verser la préparation dinde-oignons avec la sauce par-dessus.",
      "Arroser d'huile de sésame et garnir de graines de sésame et d'oignons verts émincés."
    ],
    nutrition: { calories: 505, protein: 44, carbs: 56, fat: 10, fiber: 2 },
    tips: "Le gyudon traditionnel est fait avec du boeuf et de la sauce soja. Cette adaptation utilise la dinde (moins histaminique que le boeuf) et les coconut aminos. Couper la dinde en lanières très fines pour une cuisson rapide et uniforme.",
    isCustom: false
  },
  {
    id: "wok-crevettes-legumes-coco",
    name: "Wok de Crevettes Fraîches aux Légumes et Coco",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Crevettes fraîches crues (décortiquées)", qty: 300, unit: "g", optional: false },
      { food: "Bok choy", qty: 3, unit: "pièce", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Poivron vert", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 8, unit: "g", optional: true },
      { food: "Lait de coco", qty: 150, unit: "ml", optional: false },
      { food: "Coconut aminos", qty: 30, unit: "ml", optional: false },
      { food: "Huile de coco", qty: 15, unit: "ml", optional: false },
      { food: "Coriandre fraîche", qty: 15, unit: "g", optional: true },
      { food: "Riz basmati cuit", qty: 300, unit: "g", optional: false }
    ],
    steps: [
      "Rincer les crevettes fraîches à l'eau froide et les sécher avec du papier absorbant. Couper les légumes : carrotes en bâtonnets, bok choy en tronçons, poivron en lanières.",
      "Chauffer l'huile de coco dans un wok à feu très vif. Faire revenir l'ail émincé et le gingembre râpé 20 secondes.",
      "Ajouter les crevettes et cuire 2 à 3 minutes jusqu'à ce qu'elles deviennent roses. Ne pas surcuire. Retirer et réserver.",
      "Dans le même wok, faire sauter les carottes 3 minutes, puis ajouter le poivron et le bok choy. Cuire 2 minutes.",
      "Verser le lait de coco et les coconut aminos. Mélanger et laisser réduire 2 minutes.",
      "Remettre les crevettes dans le wok, mélanger délicatement et réchauffer 1 minute.",
      "Servir sur le riz basmati chaud, garnir de coriandre fraîche."
    ],
    nutrition: { calories: 440, protein: 32, carbs: 44, fat: 16, fiber: 4 },
    tips: "Les crevettes doivent être achetées et consommées le jour même. Les crevettes fraîches crues libèrent moins d'histamine que les cuites ou congelées. Éviter les crevettes précuites ou en saumure. Score histamine 2 en raison du poivron et des crevettes.",
    isCustom: false
  },
  {
    id: "noodle-sole-vermicelles-bouillon",
    name: "Vermicelles de Riz à la Sole et Bouillon Clair",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Filet de sole frais", qty: 280, unit: "g", optional: false },
      { food: "Vermicelles de riz", qty: 150, unit: "g", optional: false },
      { food: "Bouillon de poulet maison (non concentré)", qty: 800, unit: "ml", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Bok choy", qty: 2, unit: "pièce", optional: false },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Huile d'olive", qty: 10, unit: "ml", optional: false }
    ],
    steps: [
      "Préparer le bouillon de poulet maison (cuit moins de 45 minutes) ou utiliser un bouillon maison préalablement réalisé et congelé.",
      "Cuire les vermicelles de riz selon les instructions (3 à 5 minutes). Égoutter et rincer à l'eau froide.",
      "Porter le bouillon à frémissement dans une casserole. Ajouter l'ail émincé et les carottes en rondelles fines. Cuire 8 minutes.",
      "Ajouter le bok choy coupé en tronçons et cuire 3 minutes.",
      "Couper la sole en morceaux de 4 cm. Déposer délicatement dans le bouillon frémissant et pocher 3 à 4 minutes jusqu'à ce que la chair soit opaque et s'effiloche facilement.",
      "Répartir les vermicelles dans des bols profonds. Verser le bouillon avec les légumes et les morceaux de sole.",
      "Assaisonner de sel et servir immédiatement."
    ],
    nutrition: { calories: 320, protein: 30, carbs: 38, fat: 6, fiber: 3 },
    tips: "Cette soupe est une des options les plus sûres avec un score histamine de 0. La sole est un poisson blanc très pauvre en histamine. Préparer et consommer immédiatement. Ne jamais réutiliser le bouillon de cuisson du poisson le lendemain.",
    isCustom: false
  },
  {
    id: "asian-riz-frit-poulet-oeuf",
    name: "Riz Frit Asiatique au Poulet et à l'Oeuf",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 2,
    ingredients: [
      { food: "Riz blanc cuit (refroidi)", qty: 400, unit: "g", optional: false },
      { food: "Poulet frais (blanc)", qty: 200, unit: "g", optional: false },
      { food: "Oeufs frais", qty: 2, unit: "pièce", optional: false },
      { food: "Carotte", qty: 1, unit: "pièce", optional: false },
      { food: "Chou chinois (napa)", qty: 100, unit: "g", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 5, unit: "g", optional: true },
      { food: "Coconut aminos", qty: 30, unit: "ml", optional: false },
      { food: "Huile de sésame", qty: 10, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Oignon vert", qty: 3, unit: "tige", optional: true }
    ],
    steps: [
      "Utiliser du riz cuit refroidi de préférence (idéalement préparé la veille et conservé au réfrigérateur). Couper le poulet en tout petits dés. Émincer l'ail et râper le gingembre.",
      "Chauffer l'huile d'olive dans un grand wok à feu très vif. Saisir le poulet 4 à 5 minutes jusqu'à cuisson complète. Réserver.",
      "Dans le même wok, faire revenir l'ail et le gingembre 30 secondes. Ajouter les carottes en brunoise et le chou chinois émincé. Cuire 3 minutes.",
      "Pousser les légumes sur le côté, ajouter une noisette d'huile et brouiller les oeufs directement dans le wok.",
      "Ajouter le riz froid et mélanger vigoureusement à feu très vif pendant 3 à 4 minutes pour bien séparer les grains.",
      "Incorporer le poulet cuit, verser les coconut aminos et l'huile de sésame. Mélanger 1 à 2 minutes.",
      "Servir immédiatement, garnir d'oignons verts émincés."
    ],
    nutrition: { calories: 530, protein: 38, carbs: 58, fat: 16, fiber: 3 },
    tips: "Le riz frit est meilleur avec du riz refroidi qui s'égraine bien. Les oeufs sont classés score 2 dans les plats combinés. Consommer immédiatement après la cuisson.",
    isCustom: false
  },
  {
    id: "viet-bun-bo-dinde-adapte",
    name: "Bún Bò de Dinde Adapté aux Herbes Fraîches",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 30,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Escalope de dinde fraîche", qty: 300, unit: "g", optional: false },
      { food: "Vermicelles de riz", qty: 180, unit: "g", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Concombre", qty: 1, unit: "pièce", optional: false },
      { food: "Salade verte", qty: 4, unit: "feuille", optional: false },
      { food: "Menthe fraîche", qty: 20, unit: "g", optional: true },
      { food: "Coriandre fraîche", qty: 15, unit: "g", optional: true },
      { food: "Basilic frais", qty: 10, unit: "g", optional: true },
      { food: "Coconut aminos", qty: 40, unit: "ml", optional: false },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 5, unit: "g", optional: true },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false }
    ],
    steps: [
      "Cuire les vermicelles de riz dans l'eau bouillante 3 à 5 minutes. Égoutter, rincer à l'eau froide et réserver.",
      "Mariner la dinde coupée en lamelles dans les coconut aminos, l'ail émincé et le gingembre râpé pendant 15 minutes.",
      "Préparer les garnitures : éplucher et râper les carottes, couper le concombre en fins bâtonnets, laver les feuilles de salade et les herbes.",
      "Chauffer l'huile d'olive dans une poêle à feu vif. Faire sauter les lamières de dinde égouttées 5 à 6 minutes jusqu'à légère caramélisation.",
      "Déglacer avec la marinade restante et laisser réduire 1 minute.",
      "Dans deux bols profonds, disposer les vermicelles, la salade, les carottes, le concombre et la dinde cuite.",
      "Garnir généralement d'herbes fraîches (menthe, coriandre, basilic). Arroser du jus de cuisson de la dinde."
    ],
    nutrition: { calories: 420, protein: 40, carbs: 46, fat: 8, fiber: 4 },
    tips: "Le bún bò traditionnel contient de la sauce de poisson et du citron vert, remplacés ici par les coconut aminos. Les herbes fraîches sont essentielles à ce plat - les utiliser en quantité modérée.",
    isCustom: false
  },
  {
    id: "japan-onigiri-poulet-sesame",
    name: "Onigiri de Poulet au Sésame Style Japonais",
    category: "collation",
    mealType: ["collation", "dejeuner"],
    prepTime: 30,
    cookTime: 20,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Riz japonais (rond)", qty: 300, unit: "g", optional: false },
      { food: "Poulet frais (blanc)", qty: 150, unit: "g", optional: false },
      { food: "Coconut aminos", qty: 20, unit: "ml", optional: false },
      { food: "Miel", qty: 10, unit: "g", optional: false },
      { food: "Graines de sésame", qty: 15, unit: "g", optional: false },
      { food: "Huile de sésame", qty: 5, unit: "ml", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Eau", qty: 360, unit: "ml", optional: false }
    ],
    steps: [
      "Rincer le riz japonais jusqu'à eau claire. Cuire avec 360 ml d'eau légèrement salée, porter à ébullition, couvrir et cuire 12 minutes. Laisser reposer 10 minutes.",
      "Pocher le poulet dans l'eau bouillante salée 12 minutes. Laisser tiédir et effilocher finement.",
      "Assaisonner le poulet effiloche avec les coconut aminos, le miel, l'ail émincé et l'huile de sésame.",
      "Laisser tiédir le riz jusqu'à ce qu'il soit manipulable mais encore légèrement chaud.",
      "Se mouiller les mains avec de l'eau salée. Prendre une portion de riz (environ 80 g), former une coupelle, déposer une cuillère de farce au poulet au centre.",
      "Refermer le riz autour de la farce et former un triangle ou une boule. Presser fermement.",
      "Rouler dans les graines de sésame. Répéter pour former 4 à 6 onigiri. Servir immédiatement ou dans les 2 heures."
    ],
    nutrition: { calories: 310, protein: 18, carbs: 48, fat: 6, fiber: 1 },
    tips: "Les onigiri traditionnels sont parfois garnis d'umeboshi (prune salée fermentée) ou de thon en conserve, tous deux contre-indiqués. Cette version au poulet frais est parfaitement adaptée. À consommer dans les 2 heures.",
    isCustom: false
  },
  {
    id: "wok-cabillaud-bok-choy-gingembre",
    name: "Wok de Cabillaud au Bok Choy et Gingembre Frais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Filet de cabillaud frais", qty: 350, unit: "g", optional: false },
      { food: "Bok choy", qty: 4, unit: "pièce", optional: false },
      { food: "Gingembre frais", qty: 12, unit: "g", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Coconut aminos", qty: 30, unit: "ml", optional: false },
      { food: "Huile de sésame", qty: 10, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Oignon vert", qty: 3, unit: "tige", optional: true },
      { food: "Fécule de pomme de terre", qty: 15, unit: "g", optional: false },
      { food: "Eau", qty: 60, unit: "ml", optional: false },
      { food: "Riz basmati cuit", qty: 300, unit: "g", optional: false }
    ],
    steps: [
      "Couper le cabillaud en pavés de 4 cm. Enrober légèrement de fécule de pomme de terre. Séparer les feuilles de bok choy des tiges. Émincer l'ail, trancher finement le gingembre.",
      "Chauffer l'huile d'olive dans un wok à feu très vif. Faire dorer les pavés de cabillaud 2 minutes par face. Réserver délicatement.",
      "Dans le même wok, faire revenir l'ail et le gingembre 30 secondes. Ajouter les tiges de bok choy, cuire 2 minutes.",
      "Ajouter les feuilles de bok choy et cuire encore 2 minutes.",
      "Mélanger les coconut aminos avec l'eau et verser dans le wok. Laisser réduire 1 minute pour former une sauce légère.",
      "Remettre délicatement le cabillaud sur les légumes, arroser d'huile de sésame et chauffer 1 minute.",
      "Servir sur le riz basmati, garnir d'oignons verts. Éviter de trop mélanger pour ne pas casser le poisson."
    ],
    nutrition: { calories: 430, protein: 38, carbs: 46, fat: 11, fiber: 3 },
    tips: "La fécule de pomme de terre crée une légère croûte protectrice qui maintient le poisson intact lors de la cuisson au wok. Le cabillaud doit être d'une fraîcheur absolue. La fécule de maïs peut être substituée.",
    isCustom: false
  },
  {
    id: "thai-poulet-basil-holy-riz",
    name: "Poulet Sauté au Basilic Thaï sur Riz (Pad Krapao Adapté)",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Poulet haché frais", qty: 350, unit: "g", optional: false },
      { food: "Basilic thaï frais", qty: 30, unit: "g", optional: false },
      { food: "Poivron vert", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 4, unit: "gousse", optional: false },
      { food: "Coconut aminos", qty: 40, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Miel", qty: 10, unit: "g", optional: false },
      { food: "Riz jasmin cuit", qty: 300, unit: "g", optional: false },
      { food: "Oeufs frais", qty: 2, unit: "pièce", optional: true },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Hacher grossièrement l'ail. Couper le poivron en petits dés. Effeuiller le basilic.",
      "Chauffer l'huile dans un wok à feu très vif. Faire revenir l'ail 30 secondes jusqu'à ce qu'il soit légèrement doré.",
      "Ajouter le poulet haché et cuire à feu vif en l'égrainant avec une spatule, environ 5 à 6 minutes.",
      "Ajouter le poivron vert, cuire 2 minutes. Verser les coconut aminos et le miel, mélanger.",
      "Incorporer le basilic thaï hors du feu ou en toute fin de cuisson (30 secondes) pour préserver les arômes.",
      "Si désiré, faire frire un oeuf dans une poêle séparée avec un peu d'huile, côté ensoleillé.",
      "Servir le poulet sur le riz jasmin, surmonter d'un oeuf au plat si désiré."
    ],
    nutrition: { calories: 490, protein: 42, carbs: 46, fat: 14, fiber: 3 },
    tips: "Le Pad Krapao traditionnel contient de la sauce huître et de la sauce soja, remplacées ici par les coconut aminos. Les oeufs frais du jour sont mieux tolérés. Score histamine 2 dû aux poivrons et oeufs.",
    isCustom: false
  },
  {
    id: "noodle-vermicelles-haricots-mungo-poulet",
    name: "Nouilles de Haricots Mungo au Poulet et Légumes Croquants",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 15,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Nouilles de haricots mungo (vermicelles de soja)", qty: 150, unit: "g", optional: false },
      { food: "Poulet frais (blanc)", qty: 250, unit: "g", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Chou chinois (napa)", qty: 150, unit: "g", optional: false },
      { food: "Champignons de Paris frais", qty: 100, unit: "g", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 8, unit: "g", optional: true },
      { food: "Coconut aminos", qty: 35, unit: "ml", optional: false },
      { food: "Huile de sésame", qty: 10, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Oignon vert", qty: 3, unit: "tige", optional: true }
    ],
    steps: [
      "Faire tremper les nouilles de haricots mungo dans de l'eau tiède pendant 15 minutes. Égoutter.",
      "Couper le poulet en dés. Émincer l'ail et râper le gingembre. Couper les carottes en julienne, émincer le chou chinois, trancher les champignons.",
      "Chauffer l'huile d'olive dans un wok à feu vif. Faire sauter l'ail et le gingembre 30 secondes.",
      "Ajouter le poulet et cuire 5 minutes. Ajouter les carottes, cuire 2 minutes, puis les champignons et le chou chinois.",
      "Incorporer les nouilles égouttées, verser les coconut aminos. Mélanger vigoureusement à feu vif 3 minutes.",
      "Les nouilles de haricots mungo doivent être translucides et tendres mais encore légèrement fermes.",
      "Arroser d'huile de sésame, garnir d'oignons verts émincés et servir immédiatement."
    ],
    nutrition: { calories: 440, protein: 34, carbs: 50, fat: 12, fiber: 4 },
    tips: "Les nouilles de haricots mungo (glass noodles) sont naturellement sans gluten et bien tolérées. Les champignons de Paris sont acceptés en quantité modérée (score 2 à éviter si très sensible). Ne pas utiliser de shiitake.",
    isCustom: false
  },
  {
    id: "korea-bibimbap-adapte-poulet",
    name: "Bibimbap Adapté au Poulet et Légumes Colorés",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 25,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 2,
    ingredients: [
      { food: "Riz à sushi ou riz japonais", qty: 200, unit: "g", optional: false },
      { food: "Poulet frais (blanc)", qty: 250, unit: "g", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Courgette", qty: 1, unit: "pièce", optional: false },
      { food: "Chou chinois (napa)", qty: 100, unit: "g", optional: false },
      { food: "Champignons de Paris frais", qty: 100, unit: "g", optional: false },
      { food: "Oeufs frais", qty: 2, unit: "pièce", optional: false },
      { food: "Coconut aminos", qty: 40, unit: "ml", optional: false },
      { food: "Huile de sésame", qty: 15, unit: "ml", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Graines de sésame", qty: 10, unit: "g", optional: true },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false }
    ],
    steps: [
      "Cuire le riz selon les instructions. Préparer chaque composant séparément pour conserver les saveurs.",
      "Faire sauter les carottes râpées dans un peu d'huile avec l'ail, 3 minutes. Réserver.",
      "Faire sauter la courgette en julienne 3 minutes. Réserver. Faire sauter les champignons tranchés 4 minutes avec un peu d'ail. Réserver.",
      "Émincer le chou chinois et le faire revenir 2 minutes. Réserver.",
      "Couper le poulet en lamières et faire sauter dans les coconut aminos et l'ail 5 à 6 minutes.",
      "Faire cuire les oeufs au plat (jaune encore coulant de préférence) dans l'huile d'olive.",
      "Répartir le riz dans des bols. Disposer en quartiers les légumes, le poulet. Poser l'oeuf au centre. Arroser d'huile de sésame, parsemer de graines de sésame. Mélanger avant de manger."
    ],
    nutrition: { calories: 560, protein: 42, carbs: 58, fat: 18, fiber: 5 },
    tips: "Le bibimbap traditionnel contient du gochujang (pâte de piment fermentée). Cette version adaptée conserve l'esprit du plat sans les ingrédients histaminiques. Mélanger vigoureusement avant de manger pour combiner toutes les saveurs.",
    isCustom: false
  },
  {
    id: "asian-soupe-miso-adapte-legumes",
    name: "Bouillon Clair Asiatique aux Légumes et Tofu Frais",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 20,
    servings: 3,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Tofu frais (non fermenté)", qty: 200, unit: "g", optional: false },
      { food: "Bok choy", qty: 3, unit: "pièce", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Chou chinois (napa)", qty: 150, unit: "g", optional: false },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Eau", qty: 1200, unit: "ml", optional: false },
      { food: "Sel", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Huile de sésame", qty: 5, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 10, unit: "ml", optional: false }
    ],
    steps: [
      "Porter l'eau à ébullition dans une casserole. Ajouter l'ail émincé.",
      "Éplucher les carottes et les couper en rondelles fines. Les ajouter au bouillon et cuire 8 minutes.",
      "Ajouter le chou chinois émincé et le bok choy coupé en tronçons. Cuire 5 minutes.",
      "Couper le tofu en cubes de 2 cm. L'ajouter délicatement dans le bouillon.",
      "Saler et laisser frémir doucement 3 à 4 minutes. Ne pas faire bouillir fort pour ne pas écraser le tofu.",
      "Vérifier l'assaisonnement et ajouter un filet d'huile de sésame juste avant de servir.",
      "Servir dans des bols profonds, avec un filet d'huile d'olive si désiré."
    ],
    nutrition: { calories: 180, protein: 10, carbs: 14, fat: 8, fiber: 3 },
    tips: "Utiliser uniquement du tofu frais non fermenté, non pressé et non fumé. Le tofu fermenté ou séché est contre-indiqué. Ce bouillon minimaliste est excellent en cas de crise histaminique. Score histamine 0.",
    isCustom: false
  },
  {
    id: "bowl-tilapia-riz-coco-herbes",
    name: "Bol de Tilapia au Riz de Coco et Herbes Fraîches",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Filet de tilapia frais", qty: 300, unit: "g", optional: false },
      { food: "Riz basmati", qty: 180, unit: "g", optional: false },
      { food: "Lait de coco", qty: 200, unit: "ml", optional: false },
      { food: "Eau", qty: 160, unit: "ml", optional: false },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false },
      { food: "Coriandre fraîche", qty: 15, unit: "g", optional: true },
      { food: "Menthe fraîche", qty: 10, unit: "g", optional: true },
      { food: "Concombre", qty: 1, unit: "pièce", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préparer le riz au lait de coco : mélanger le riz basmati rincé avec 200 ml de lait de coco et 160 ml d'eau. Porter à ébullition, couvrir et cuire 15 minutes à feu très doux. Laisser reposer 5 minutes.",
      "Couper le concombre en brunoise ou en fins bâtonnets. Émincer l'ail.",
      "Faire fondre le beurre dans une poêle à feu moyen. Faire revenir l'ail 30 secondes.",
      "Ajouter les filets de tilapia, saler, et cuire 3 à 4 minutes par face. Le poisson est cuit quand la chair est opaque et s'effiloche légèrement.",
      "Le riz au lait de coco doit être onctueux et légèrement parfumé.",
      "Répartir le riz dans des bols. Déposer le tilapia par-dessus.",
      "Garnir de concombre frais, de coriandre et de menthe hachées. Servir immédiatement."
    ],
    nutrition: { calories: 490, protein: 36, carbs: 52, fat: 16, fiber: 2 },
    tips: "Le riz cuit au lait de coco est une excellente base pour les plats de poisson. Le tilapia est un poisson blanc doux et très peu histaminique quand il est frais. Score histamine 0 - idéal en période de réintroduction.",
    isCustom: false
  },
  {
    id: "wok-dinde-champignons-chou",
    name: "Wok de Dinde aux Champignons de Paris et Chou Chinois",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Escalope de dinde fraîche", qty: 320, unit: "g", optional: false },
      { food: "Champignons de Paris frais", qty: 200, unit: "g", optional: false },
      { food: "Chou chinois (napa)", qty: 200, unit: "g", optional: false },
      { food: "Carotte", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 8, unit: "g", optional: true },
      { food: "Coconut aminos", qty: 35, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Fécule de pomme de terre", qty: 10, unit: "g", optional: false },
      { food: "Eau", qty: 50, unit: "ml", optional: false },
      { food: "Riz blanc cuit", qty: 300, unit: "g", optional: false }
    ],
    steps: [
      "Couper la dinde en fines lamelles. Enrober légèrement de fécule de pomme de terre. Nettoyer et trancher les champignons. Émincer le chou chinois, couper les carottes en julienne.",
      "Chauffer l'huile d'olive dans un wok à feu très vif. Saisir la dinde en petites quantités pour éviter qu'elle ne cuise à l'étouffée, 4 minutes. Réserver.",
      "Dans le même wok, faire revenir l'ail émincé et le gingembre râpé 30 secondes.",
      "Ajouter les carottes et cuire 3 minutes. Ajouter les champignons et cuire 3 minutes jusqu'à ce qu'ils rendent leur eau.",
      "Incorporer le chou chinois, mélanger et cuire 2 minutes.",
      "Mélanger les coconut aminos avec l'eau, verser dans le wok. Remettre la dinde.",
      "Mélanger et cuire 1 à 2 minutes. Servir sur le riz chaud."
    ],
    nutrition: { calories: 450, protein: 42, carbs: 46, fat: 10, fiber: 4 },
    tips: "Les champignons de Paris doivent être très frais (achetés le jour même ou au maximum la veille). Éviter les champignons en conserve ou préemballés depuis plusieurs jours. Ne jamais utiliser de shiitake ou morilles qui sont plus histaminiques.",
    isCustom: false
  },
  {
    id: "asian-soupe-legumes-racines-gingembre",
    name: "Soupe Asiatique aux Racines et Patate Douce",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 3,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Patate douce", qty: 300, unit: "g", optional: false },
      { food: "Carotte", qty: 3, unit: "pièce", optional: false },
      { food: "Bok choy", qty: 3, unit: "pièce", optional: false },
      { food: "Gingembre frais", qty: 15, unit: "g", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Lait de coco", qty: 200, unit: "ml", optional: false },
      { food: "Eau", qty: 800, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false },
      { food: "Sel", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Coriandre fraîche", qty: 10, unit: "g", optional: true }
    ],
    steps: [
      "Éplucher et couper la patate douce en cubes de 2 cm. Éplucher et couper les carottes en rondelles.",
      "Chauffer l'huile d'olive dans une casserole. Faire revenir l'ail émincé et le gingembre tranché 1 minute.",
      "Ajouter les cubes de patate douce et les carottes. Faire revenir 3 minutes.",
      "Verser l'eau, saler et porter à ébullition. Cuire 15 minutes à feu moyen.",
      "Ajouter le bok choy coupé en tronçons et cuire 5 minutes de plus.",
      "Incorporer le lait de coco, laisser frémir 5 minutes. Ne pas faire bouillir.",
      "Servir dans des bols, garnir de coriandre fraîche. La soupe peut être mixée partiellement pour une texture veloutée."
    ],
    nutrition: { calories: 240, protein: 4, carbs: 36, fat: 10, fiber: 5 },
    tips: "La patate douce est un excellent choix dans le régime anti-histamine car elle est naturellement anti-inflammatoire. La soupe peut être conservée au congélateur. Réchauffer doucement sans faire rebouillir.",
    isCustom: false
  },
  {
    id: "japan-ochazuke-poulet-riz-bouillon",
    name: "Ochazuke de Poulet sur Riz Japonais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz japonais cuit chaud", qty: 400, unit: "g", optional: false },
      { food: "Poulet frais (blanc)", qty: 200, unit: "g", optional: false },
      { food: "Bouillon de poulet maison clair", qty: 600, unit: "ml", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Graines de sésame", qty: 8, unit: "g", optional: true },
      { food: "Oignon vert", qty: 2, unit: "tige", optional: true }
    ],
    steps: [
      "Préparer un bouillon de poulet léger maison : faire cuire les os ou morceaux de poulet 30 minutes maximum dans l'eau avec de l'ail. Filtrer.",
      "Pocher le blanc de poulet dans le bouillon 12 minutes. Retirer, laisser tiédir et couper en fines tranches.",
      "Répartir le riz japonais chaud dans deux bols profonds.",
      "Porter le bouillon clair à frémissement et le verser chaud sur le riz.",
      "Disposer les tranches de poulet sur le riz dans le bouillon.",
      "Parsemer de graines de sésame et d'oignons verts émincés si désiré.",
      "Servir immédiatement, en mélangeant légèrement le riz et le bouillon avant de manger."
    ],
    nutrition: { calories: 380, protein: 30, carbs: 52, fat: 6, fiber: 1 },
    tips: "L'ochazuke est un plat japonais réconfortant à base de riz dans le bouillon. Cette version simple est idéale lors des phases de restriction histamine. Score histamine 0 avec seulement les ingrédients de base.",
    isCustom: false
  },
  {
    id: "bowl-sole-patate-douce-gingembre",
    name: "Bol de Sole Pochée, Patate Douce Rôtie et Gingembre",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Filet de sole frais", qty: 280, unit: "g", optional: false },
      { food: "Patate douce", qty: 400, unit: "g", optional: false },
      { food: "Riz basmati", qty: 160, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 10, unit: "g", optional: true },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Beurre", qty: 15, unit: "g", optional: false },
      { food: "Coriandre fraîche", qty: 10, unit: "g", optional: true },
      { food: "Eau", qty: 400, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffer le four à 200°C. Éplucher et couper la patate douce en cubes de 2 cm. Enrober d'huile d'olive et de sel. Rôtir 25 minutes jusqu'à tendreté.",
      "Cuire le riz basmati rincé dans 320 ml d'eau salée, 15 minutes à feu doux couvert.",
      "Préparer un court-bouillon léger : porter 400 ml d'eau à frémissement avec l'ail, le gingembre tranché et du sel.",
      "Y pocher les filets de sole 4 à 5 minutes. Retirer délicatement avec une écumoire.",
      "Filtrer le bouillon de pochage et faire fondre le beurre dedans pour obtenir une sauce légère.",
      "Répartir le riz dans des bols. Déposer la patate douce rôtie et les filets de sole.",
      "Verser un peu de sauce au beurre, garnir de coriandre fraîche et servir."
    ],
    nutrition: { calories: 450, protein: 30, carbs: 58, fat: 12, fiber: 5 },
    tips: "La patate douce rôtie apporte de la couleur et une douceur naturelle. La sole est un poisson très délicat qui cuit rapidement. Surveiller la cuisson : trop cuite, elle devient caoutchouteuse. Consommer immédiatement.",
    isCustom: false
  },
  {
    id: "wok-riz-frit-legumes-coco",
    name: "Riz Frit Végétarien au Lait de Coco et Légumes Asiatiques",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Riz blanc cuit (refroidi)", qty: 400, unit: "g", optional: false },
      { food: "Lait de coco", qty: 80, unit: "ml", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Courgette", qty: 1, unit: "pièce", optional: false },
      { food: "Bok choy", qty: 2, unit: "pièce", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 5, unit: "g", optional: true },
      { food: "Coconut aminos", qty: 25, unit: "ml", optional: false },
      { food: "Huile de coco", qty: 15, unit: "ml", optional: false },
      { food: "Graines de sésame", qty: 8, unit: "g", optional: true }
    ],
    steps: [
      "S'assurer que le riz est bien refroidi (idéalement préparé le jour d'avant et conservé au frigo). Des grains froids évitent le riz gluant.",
      "Couper les légumes en petits dés ou julienne fine : carottes, courgette, bok choy.",
      "Chauffer l'huile de coco dans un grand wok à feu très vif. Faire revenir l'ail et le gingembre 30 secondes.",
      "Ajouter les carottes, cuire 2 minutes. Ajouter la courgette et le bok choy, cuire 2 minutes.",
      "Pousser les légumes sur les côtés, ajouter le riz froid au centre et l'écraser avec la spatule pour séparer les grains. Mélanger avec les légumes.",
      "Verser les coconut aminos et le lait de coco. Remuer à feu très vif 2 à 3 minutes.",
      "Servir en accompagnement, parsemer de graines de sésame."
    ],
    nutrition: { calories: 310, protein: 6, carbs: 54, fat: 9, fiber: 3 },
    tips: "Ce riz frit végétarien est un excellent accompagnement. Le lait de coco lui confère une douceur et un côté crémeux caractéristique. Utiliser un riz refroidi est indispensable pour un riz frit réussi.",
    isCustom: false
  },
  {
    id: "asian-riz-cuit-vapeur-gingembre",
    name: "Riz Collant à la Vapeur au Gingembre et Sésame",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 25,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Riz gluant (riz collant)", qty: 300, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 10, unit: "g", optional: false },
      { food: "Huile de sésame", qty: 15, unit: "ml", optional: false },
      { food: "Graines de sésame", qty: 15, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Oignon vert", qty: 3, unit: "tige", optional: true }
    ],
    steps: [
      "Rincer le riz gluant et le faire tremper dans de l'eau froide pendant minimum 2 heures, idéalement une nuit.",
      "Égoutter et rincer à nouveau le riz.",
      "Disposer le riz dans un panier vapeur tapissé d'une feuille de papier sulfurisé percée de trous. Parsemer de gingembre râpé et de sel.",
      "Cuire à la vapeur pendant 20 à 25 minutes jusqu'à ce que le riz soit translucide et collant.",
      "Transférer dans un bol, arroser d'huile de sésame et mélanger délicatement.",
      "Garnir de graines de sésame dorées à sec et d'oignons verts émincés.",
      "Servir chaud en accompagnement de plats asiatiques."
    ],
    nutrition: { calories: 280, protein: 5, carbs: 54, fat: 5, fiber: 1 },
    tips: "Le riz gluant nécessite un long trempage avant cuisson. La cuisson vapeur est essentielle pour obtenir la texture caractéristique. Ce riz se mange à la main en petites boulettes dans la tradition asiatique.",
    isCustom: false
  },
  {
    id: "thai-poulet-coco-patate-douce-curry",
    name: "Curry Vert de Poulet à la Patate Douce et Lait de Coco",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 30,
    servings: 3,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Poulet frais (cuisse désossée)", qty: 400, unit: "g", optional: false },
      { food: "Patate douce", qty: 300, unit: "g", optional: false },
      { food: "Lait de coco entier", qty: 400, unit: "ml", optional: false },
      { food: "Bok choy", qty: 2, unit: "pièce", optional: false },
      { food: "Ail", qty: 4, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 15, unit: "g", optional: false },
      { food: "Citronnelle (partie blanche)", qty: 2, unit: "tige", optional: false },
      { food: "Coriandre fraîche", qty: 20, unit: "g", optional: true },
      { food: "Huile de coco", qty: 20, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Riz jasmin cuit", qty: 400, unit: "g", optional: false }
    ],
    steps: [
      "Éplucher et couper la patate douce en cubes de 3 cm. Couper le poulet en morceaux. Frapper la citronnelle et couper en tronçons.",
      "Préparer une base aromatique : mixer (ou piler) l'ail, le gingembre et la moitié de la coriandre en une pâte.",
      "Chauffer l'huile de coco dans une cocotte. Faire revenir la pâte aromatique et la citronnelle 2 minutes.",
      "Ajouter le poulet et faire dorer 5 minutes en remuant.",
      "Incorporer la patate douce, mélanger et verser le lait de coco. Saler et porter à frémissement.",
      "Couvrir et cuire à feu doux 20 minutes jusqu'à ce que la patate douce soit tendre.",
      "Ajouter le bok choy les 5 dernières minutes. Servir sur le riz avec la coriandre fraîche restante."
    ],
    nutrition: { calories: 550, protein: 35, carbs: 58, fat: 20, fiber: 6 },
    tips: "Ce curry maison évite les pâtes de curry commerciales qui contiennent souvent de la sauce de poisson, de la citronnelle déshydratée ou des additifs. La citronnelle et le gingembre frais apportent les arômes typiques sans histamine.",
    isCustom: false
  },
  {
    id: "korea-japchae-adapte-poulet",
    name: "Japchae de Poulet aux Vermicelles de Patate Douce",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 20,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 2,
    ingredients: [
      { food: "Vermicelles de patate douce (dangmyeon)", qty: 150, unit: "g", optional: false },
      { food: "Poulet frais (blanc)", qty: 250, unit: "g", optional: false },
      { food: "Carotte", qty: 1, unit: "pièce", optional: false },
      { food: "Courgette", qty: 1, unit: "pièce", optional: false },
      { food: "Champignons de Paris frais", qty: 100, unit: "g", optional: false },
      { food: "Oeuf frais", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Coconut aminos", qty: 40, unit: "ml", optional: false },
      { food: "Miel", qty: 15, unit: "g", optional: false },
      { food: "Huile de sésame", qty: 15, unit: "ml", optional: false },
      { food: "Graines de sésame", qty: 10, unit: "g", optional: true },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false }
    ],
    steps: [
      "Faire bouillir les vermicelles de patate douce 6 à 8 minutes jusqu'à ce qu'ils soient translucides et tendres. Égoutter, rincer et couper avec des ciseaux en morceaux de 15 cm.",
      "Mélanger les coconut aminos, le miel et l'ail émincé pour faire la sauce. Assaisonner les vermicelles avec 2/3 de la sauce et l'huile de sésame.",
      "Couper le poulet en lanières. Faire sauter dans l'huile d'olive 5 minutes. Réserver.",
      "Faire sauter chaque légume séparément : carottes en julienne (3 min), courgette en julienne (2 min), champignons tranchés (3 min). Assaisonner chacun légèrement.",
      "Faire brouiller l'oeuf en une fine omelette, rouler et couper en lamelles.",
      "Dans un grand wok, mélanger les vermicelles avec tous les légumes et le poulet. Verser la sauce restante.",
      "Garnir de graines de sésame et de lamelles d'omelette. Servir tiède."
    ],
    nutrition: { calories: 520, protein: 36, carbs: 64, fat: 14, fiber: 4 },
    tips: "Le japchae coréen utilise traditionnellement de la sauce soja. Les vermicelles de patate douce sont naturellement sans gluten et bien tolérés. Score histamine 2 dû aux champignons et à l'oeuf.",
    isCustom: false
  },
  {
    id: "asian-accomp-bok-choy-ail",
    name: "Bok Choy Sauté à l'Ail et Huile de Sésame",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Bok choy", qty: 6, unit: "pièce", optional: false },
      { food: "Ail", qty: 4, unit: "gousse", optional: false },
      { food: "Huile de sésame", qty: 10, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Laver soigneusement les bok choy en séparant les feuilles. Couper les plus gros en deux dans la longueur.",
      "Émincer finement l'ail.",
      "Chauffer l'huile d'olive dans une poêle ou wok à feu vif.",
      "Faire dorer l'ail 30 secondes en remuant constamment pour éviter qu'il ne brûle.",
      "Ajouter les bok choy, les tiges d'abord, et faire sauter à feu vif 3 à 4 minutes jusqu'à ce qu'ils soient légèrement dorés mais encore croquants.",
      "Ajouter les feuilles et cuire encore 1 à 2 minutes.",
      "Arroser d'huile de sésame, saler et servir immédiatement."
    ],
    nutrition: { calories: 90, protein: 3, carbs: 6, fat: 7, fiber: 2 },
    tips: "Le bok choy est un légume excellent dans le régime anti-histamine. Très rapide à préparer, il conserve son croquant si la cuisson est courte. Score histamine 0 - parfait pour accompagner n'importe quel plat de la liste.",
    isCustom: false
  },
  {
    id: "noodle-rice-noodle-sole-bouillon",
    name: "Nouilles de Riz à la Sole dans un Bouillon Parfumé",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Nouilles de riz plates", qty: 200, unit: "g", optional: false },
      { food: "Filet de sole frais", qty: 250, unit: "g", optional: false },
      { food: "Gingembre frais", qty: 15, unit: "g", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Bok choy", qty: 2, unit: "pièce", optional: false },
      { food: "Citronnelle (partie blanche)", qty: 1, unit: "tige", optional: true },
      { food: "Eau", qty: 800, unit: "ml", optional: false },
      { food: "Sel", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Huile d'olive", qty: 10, unit: "ml", optional: false },
      { food: "Menthe fraîche", qty: 10, unit: "g", optional: true }
    ],
    steps: [
      "Préparer le bouillon : faire chauffer l'huile d'olive, faire revenir l'ail et le gingembre tranché 1 minute. Ajouter la citronnelle frappée.",
      "Verser l'eau et porter à ébullition. Ajouter les carottes en rondelles et cuire 10 minutes. Saler.",
      "Tremper les nouilles de riz dans de l'eau tiède 10 minutes ou cuire selon les instructions. Égoutter.",
      "Ajouter le bok choy dans le bouillon et cuire 3 minutes.",
      "Couper la sole en gros morceaux. Pocher doucement dans le bouillon 4 minutes.",
      "Répartir les nouilles dans des bols. Verser le bouillon chaud avec les légumes et la sole.",
      "Garnir de menthe fraîche. Retirer la citronnelle avant de servir."
    ],
    nutrition: { calories: 370, protein: 28, carbs: 52, fat: 6, fiber: 4 },
    tips: "La citronnelle parfume délicatement le bouillon. Ne pas la manger mais retirer les tronçons avant de servir. Ce plat léger est idéal si vous souhaitez quelque chose de nourrissant mais facilement digestible.",
    isCustom: false
  },
  {
    id: "asian-poulet-chou-napa-braise",
    name: "Poulet Braisé au Chou Napa et Bouillon de Coco",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 35,
    servings: 3,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Poulet frais (morceaux avec os)", qty: 600, unit: "g", optional: false },
      { food: "Chou chinois (napa)", qty: 300, unit: "g", optional: false },
      { food: "Lait de coco", qty: 300, unit: "ml", optional: false },
      { food: "Eau", qty: 300, unit: "ml", optional: false },
      { food: "Gingembre frais", qty: 15, unit: "g", optional: false },
      { food: "Ail", qty: 4, unit: "gousse", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Coconut aminos", qty: 30, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Riz blanc cuit", qty: 400, unit: "g", optional: false }
    ],
    steps: [
      "Faire dorer les morceaux de poulet dans l'huile d'olive à feu vif, 3 minutes par face. Réserver.",
      "Dans la même cocotte, faire revenir l'ail émincé et le gingembre en fines rondelles 1 minute.",
      "Remettre le poulet, ajouter les carottes coupées en morceaux.",
      "Verser le lait de coco, l'eau et les coconut aminos. Porter à frémissement.",
      "Couvrir et laisser braiser à feu doux 25 à 30 minutes.",
      "Ajouter le chou napa coupé en gros morceaux les 10 dernières minutes de cuisson.",
      "Servir le poulet braisé sur le riz avec le bouillon au coco et les légumes."
    ],
    nutrition: { calories: 520, protein: 42, carbs: 46, fat: 20, fiber: 4 },
    tips: "Braiser le poulet avec os donne un bouillon plus riche. Cependant, ne pas dépasser 35 minutes de braisage pour maintenir un taux d'histamine bas dans le bouillon. Consommer le jour même.",
    isCustom: false
  },
  {
    id: "bowl-dinde-legumes-grilles-sesame",
    name: "Bol de Dinde Rôtie, Légumes Grillés et Sauce Sésame",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Escalope de dinde fraîche", qty: 320, unit: "g", optional: false },
      { food: "Courgette", qty: 2, unit: "pièce", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Patate douce", qty: 200, unit: "g", optional: false },
      { food: "Riz jasmin cuit", qty: 300, unit: "g", optional: false },
      { food: "Tahini (purée de sésame)", qty: 30, unit: "g", optional: false },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 5, unit: "g", optional: true },
      { food: "Huile d'olive", qty: 25, unit: "ml", optional: false },
      { food: "Eau tiède", qty: 30, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false }
    ],
    steps: [
      "Préchauffer le four à 210°C. Couper les légumes (courgette, carotte, patate douce) en morceaux de taille uniforme. Enrober d'huile d'olive et de sel. Rôtir 20 à 25 minutes.",
      "Assaisonner la dinde avec sel et un peu d'ail émincé. Faire cuire dans une poêle avec de l'huile d'olive, 5 à 6 minutes par face jusqu'à cuisson complète.",
      "Préparer la sauce sésame : mélanger le tahini avec l'eau tiède, l'ail émincé finement et le gingembre râpé. Délayer jusqu'à consistance de sauce coulante.",
      "Laisser reposer la dinde 3 minutes avant de couper en tranches.",
      "Répartir le riz dans des bols.",
      "Disposer les légumes rôtis et les tranches de dinde sur le riz.",
      "Arroser généreusement de sauce au sésame et servir immédiatement."
    ],
    nutrition: { calories: 540, protein: 44, carbs: 54, fat: 16, fiber: 6 },
    tips: "Le tahini (purée de sésame) est une excellente source de calcium et de graisses saines. Choisir un tahini pur sans additifs ni conservateurs. La sauce peut être préparée à l'avance et conservée 2 jours au réfrigérateur.",
    isCustom: false
  },
  {
    id: "wok-cabillaud-coco-curry-doux",
    name: "Cabillaud Sauté au Curry Doux et Lait de Coco",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Filet de cabillaud frais", qty: 320, unit: "g", optional: false },
      { food: "Lait de coco entier", qty: 250, unit: "ml", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Courgette", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 10, unit: "g", optional: false },
      { food: "Poudre de curcuma", qty: 5, unit: "g", optional: false },
      { food: "Huile de coco", qty: 15, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Coriandre fraîche", qty: 10, unit: "g", optional: true },
      { food: "Riz basmati cuit", qty: 300, unit: "g", optional: false }
    ],
    steps: [
      "Couper le cabillaud en gros cubes. Éplucher et couper les légumes en brunoise ou en rondelles.",
      "Chauffer l'huile de coco dans un wok à feu moyen. Faire revenir l'ail émincé et le gingembre râpé 1 minute.",
      "Ajouter le curcuma et faire revenir 30 secondes pour le torréfier légèrement.",
      "Ajouter les carottes, cuire 3 minutes. Incorporer la courgette et cuire 2 minutes.",
      "Verser le lait de coco, saler et porter à frémissement.",
      "Déposer délicatement le cabillaud dans la sauce. Couvrir et pocher 5 à 6 minutes à feu doux.",
      "Servir sur le riz basmati, garnir de coriandre fraîche."
    ],
    nutrition: { calories: 450, protein: 34, carbs: 46, fat: 16, fiber: 4 },
    tips: "Le curcuma est un anti-inflammatoire naturel excellent pour les personnes sensibles à l'histamine. Il colore joliment la sauce. Choisir un curcuma pur sans mélanges d'épices qui pourraient contenir des irritants.",
    isCustom: false
  },
  {
    id: "asian-chou-napa-salade-tiede",
    name: "Salade Tiède de Chou Napa à la Vinaigrette Asiatique",
    category: "accompagnement",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 10,
    servings: 3,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Chou chinois (napa)", qty: 400, unit: "g", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Ail", qty: 2, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 8, unit: "g", optional: true },
      { food: "Coconut aminos", qty: 25, unit: "ml", optional: false },
      { food: "Huile de sésame", qty: 15, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 15, unit: "ml", optional: false },
      { food: "Graines de sésame", qty: 10, unit: "g", optional: false },
      { food: "Oignon vert", qty: 3, unit: "tige", optional: true }
    ],
    steps: [
      "Émincer finement le chou napa en lanières. Râper les carottes ou les couper en fine julienne.",
      "Chauffer l'huile d'olive dans un wok à feu vif. Faire revenir l'ail émincé et le gingembre râpé 30 secondes.",
      "Ajouter le chou napa et les carottes. Faire sauter 3 à 4 minutes en remuant : les légumes doivent être chauds mais encore croquants.",
      "Retirer du feu. Arroser de coconut aminos et d'huile de sésame. Mélanger.",
      "Transférer dans un plat de service.",
      "Garnir de graines de sésame et d'oignons verts émincés.",
      "Servir tiède en accompagnement."
    ],
    nutrition: { calories: 110, protein: 3, carbs: 10, fat: 7, fiber: 3 },
    tips: "Cette salade tiède est rapide à préparer et très polyvalente. Elle peut accompagner tout plat de riz ou de nouilles. Le chou napa est riche en vitamine C et excellent pour la digestion. Consommer rapidement.",
    isCustom: false
  },
  {
    id: "japan-ramen-poulet-clair",
    name: "Ramen de Poulet au Bouillon Clair Style Japonais",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 45,
    servings: 2,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Nouilles ramen (riz ou sans gluten)", qty: 180, unit: "g", optional: false },
      { food: "Poulet frais (carcasse ou morceaux)", qty: 500, unit: "g", optional: false },
      { food: "Bok choy", qty: 3, unit: "pièce", optional: false },
      { food: "Carotte", qty: 2, unit: "pièce", optional: false },
      { food: "Gingembre frais", qty: 15, unit: "g", optional: false },
      { food: "Ail", qty: 4, unit: "gousse", optional: false },
      { food: "Coconut aminos", qty: 20, unit: "ml", optional: false },
      { food: "Huile de sésame", qty: 8, unit: "ml", optional: false },
      { food: "Eau", qty: 1200, unit: "ml", optional: false },
      { food: "Sel", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Oignon vert", qty: 3, unit: "tige", optional: true }
    ],
    steps: [
      "Blanchir le poulet 3 minutes dans l'eau bouillante, égoutter et rincer à l'eau froide. Cela garantit un bouillon clair et moins histaminique.",
      "Porter 1200 ml d'eau à ébullition avec le poulet blanchi, l'ail écrasé, le gingembre tranché. Laisser frémir 35 minutes maximum à feu doux. Écumer régulièrement.",
      "Retirer le poulet. Laisser tiédir, effilocher la chair et réserver. Filtrer le bouillon au chinois.",
      "Ajouter les coconut aminos au bouillon filtré. Rectifier le sel.",
      "Cuire les nouilles selon les instructions. Égoutter.",
      "Blanchir le bok choy 2 minutes dans de l'eau bouillante salée. Égoutter.",
      "Répartir les nouilles dans des bols. Disposer le poulet effiloche et le bok choy. Verser le bouillon très chaud. Arroser d'huile de sésame, garnir d'oignons verts."
    ],
    nutrition: { calories: 460, protein: 42, carbs: 48, fat: 10, fiber: 3 },
    tips: "Le bouillon de ramen ne doit pas mijoter plus de 40-45 minutes pour rester pauvre en histamine. Pour un ramen très sûr, ne pas dépasser 35 minutes. Utiliser des nouilles de riz sans gluten si nécessaire.",
    isCustom: false
  },
  {
    id: "viet-com-tam-dinde-grilee",
    name: "Com Tâm de Dinde Grillée aux Herbes Vietnamiennes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Escalope de dinde fraîche", qty: 350, unit: "g", optional: false },
      { food: "Riz cassé ou riz blanc", qty: 200, unit: "g", optional: false },
      { food: "Concombre", qty: 1, unit: "pièce", optional: false },
      { food: "Carotte", qty: 1, unit: "pièce", optional: false },
      { food: "Coconut aminos", qty: 40, unit: "ml", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 5, unit: "g", optional: true },
      { food: "Miel", qty: 15, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Menthe fraîche", qty: 15, unit: "g", optional: true },
      { food: "Coriandre fraîche", qty: 10, unit: "g", optional: true }
    ],
    steps: [
      "Préparer la marinade : mélanger les coconut aminos, le miel, l'ail émincé et le gingembre râpé.",
      "Aplatir légèrement les escalopes de dinde. Les mettre à mariner 15 à 30 minutes.",
      "Cuire le riz cassé selon les instructions (similaire au riz blanc).",
      "Égoutter la dinde de sa marinade. Faire chauffer l'huile d'olive dans une poêle grillée ou normale. Cuire 5 à 6 minutes par face jusqu'à caramélisation.",
      "Verser la marinade restante dans la poêle et laisser caraméliser 1 minute.",
      "Couper le concombre en fines rondelles. Râper la carotte.",
      "Servir le riz dans des assiettes, poser la dinde grillée tranchée, les légumes frais et les herbes fraîches."
    ],
    nutrition: { calories: 480, protein: 44, carbs: 48, fat: 12, fiber: 3 },
    tips: "Le com tâm (riz cassé) est un plat de rue vietnamien populaire. Le riz cassé a une texture légèrement différente mais peut être remplacé par du riz blanc ordinaire. La marinade sans nuoc-mâm conserve bien les saveurs.",
    isCustom: false
  },
  {
    id: "bowl-riz-courgette-grilee-poulet",
    name: "Bol de Riz au Poulet Citronné (sans citron) et Courgette Grillée",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poulet frais (blanc)", qty: 300, unit: "g", optional: false },
      { food: "Riz basmati", qty: 180, unit: "g", optional: false },
      { food: "Courgette", qty: 2, unit: "pièce", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Beurre", qty: 25, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 20, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Herbes fraîches (basilic ou menthe)", qty: 15, unit: "g", optional: true }
    ],
    steps: [
      "Cuire le riz basmati rincé dans 360 ml d'eau salée, 15 minutes à feu doux couvert.",
      "Couper les courgettes en rondelles de 1 cm. Faire chauffer une poêle grill ou une poêle ordinaire à feu vif.",
      "Griller les courgettes avec un filet d'huile d'olive, 2 à 3 minutes par face jusqu'à légères traces de cuisson. Saler et réserver.",
      "Couper le poulet en escalopes fines. Faire fondre le beurre dans une poêle à feu moyen-vif.",
      "Ajouter l'ail émincé et faire dorer 30 secondes. Ajouter le poulet et cuire 5 minutes par face.",
      "Arroser le poulet avec le beurre à l'ail fondu pendant la cuisson pour bien l'enrober.",
      "Répartir le riz, disposer les courgettes et le poulet. Garnir d'herbes fraîches."
    ],
    nutrition: { calories: 460, protein: 38, carbs: 50, fat: 13, fiber: 3 },
    tips: "Ce bol de base avec un score histamine 0 est idéal en période de crise. Le beurre et l'ail apportent des saveurs riches sans histamine. Le basilic frais peut être remplacé par de la menthe ou omis selon la tolérance.",
    isCustom: false
  },
  {
    id: "wok-tilapia-poivron-jaune-coco",
    name: "Wok de Tilapia au Poivron Jaune et Sauce Coco",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 18,
    servings: 2,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Filet de tilapia frais", qty: 300, unit: "g", optional: false },
      { food: "Poivron jaune", qty: 2, unit: "pièce", optional: false },
      { food: "Lait de coco", qty: 200, unit: "ml", optional: false },
      { food: "Bok choy", qty: 2, unit: "pièce", optional: false },
      { food: "Ail", qty: 3, unit: "gousse", optional: false },
      { food: "Gingembre frais", qty: 8, unit: "g", optional: true },
      { food: "Fécule de pomme de terre", qty: 15, unit: "g", optional: false },
      { food: "Huile de coco", qty: 20, unit: "ml", optional: false },
      { food: "Coconut aminos", qty: 20, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Riz blanc cuit", qty: 300, unit: "g", optional: false }
    ],
    steps: [
      "Couper le tilapia en morceaux de 4 cm. Enrober légèrement de fécule de pomme de terre et de sel. Couper les poivrons en cubes, le bok choy en tronçons.",
      "Chauffer l'huile de coco dans un wok à feu très vif. Faire dorer rapidement le tilapia enrobé de fécule, 2 minutes par côté. Retirer et réserver.",
      "Dans le même wok, faire revenir l'ail émincé et le gingembre râpé 30 secondes.",
      "Ajouter les poivrons jaunes et faire sauter 3 minutes.",
      "Ajouter le bok choy, cuire 2 minutes.",
      "Verser le lait de coco et les coconut aminos. Laisser frémir 3 minutes pour réduire légèrement.",
      "Remettre délicatement le tilapia dans la sauce. Réchauffer 1 minute sans mélanger pour ne pas casser le poisson. Servir sur le riz."
    ],
    nutrition: { calories: 440, protein: 34, carbs: 44, fat: 16, fiber: 3 },
    tips: "La fécule de pomme de terre protège le poisson à la cuisson et épaissit légèrement la sauce. Le poivron jaune est mieux toléré que le rouge. Score histamine 2 dû aux poivrons.",
    isCustom: false
  }
];
