const RECIPES_BATCH_2 = [
  {
    id: "grec-moussaka-courgette",
    name: "Moussaka de Courgettes à la Grecque",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 45,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Agneau haché frais", qty: 500, unit: "g", optional: false },
      { food: "Courgettes", qty: 4, unit: "pièces", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Cannelle moulue", qty: 1, unit: "c. à café", optional: false },
      { food: "Cumin moulu", qty: 0.5, unit: "c. à café", optional: true },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Farine", qty: 30, unit: "g", optional: false },
      { food: "Lait entier", qty: 400, unit: "ml", optional: false },
      { food: "Ricotta", qty: 200, unit: "g", optional: false },
      { food: "Persil frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffez le four à 180°C. Coupez les courgettes en tranches d'environ 5 mm d'épaisseur dans le sens de la longueur.",
      "Faites griller les tranches de courgettes dans une poêle avec un filet d'huile d'olive, 3 minutes de chaque côté, jusqu'à ce qu'elles soient légèrement dorées. Réservez.",
      "Dans une grande poêle, faites revenir l'oignon émincé dans 2 cuillères à soupe d'huile d'olive pendant 5 minutes à feu moyen.",
      "Ajoutez l'ail écrasé et l'agneau haché. Faites cuire en remuant pendant 8 à 10 minutes jusqu'à ce que la viande soit bien dorée.",
      "Assaisonnez avec la cannelle, le cumin, le sel et le poivre. Ajoutez le persil haché. Mélangez bien et retirez du feu.",
      "Préparez la béchamel : faites fondre le beurre dans une casserole, ajoutez la farine et fouettez 1 minute. Versez le lait progressivement en fouettant sans cesse jusqu'à épaississement.",
      "Retirez la béchamel du feu, incorporez la ricotta et assaisonnez de sel et poivre.",
      "Dans un plat à gratin, déposez une couche de courgettes, puis la moitié de la viande, encore une couche de courgettes, le reste de la viande, et terminez par les courgettes restantes.",
      "Nappez généreusement de béchamel à la ricotta. Enfournez 30 minutes jusqu'à ce que le dessus soit bien doré.",
      "Laissez reposer 10 minutes avant de servir pour que le plat se tienne bien."
    ],
    nutrition: { calories: 520, protein: 38, carbs: 18, fat: 34, fiber: 3 },
    tips: "Remplacez l'aubergine traditionnelle par des courgettes pour éviter les histamines. Préparez et consommez ce plat le jour même pour minimiser la formation d'histamine dans la viande.",
    isCustom: false
  },
  {
    id: "grec-souvlaki-poulet",
    name: "Souvlaki de Poulet aux Herbes Fraîches",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blancs de poulet frais", qty: 600, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Origan séché", qty: 1, unit: "c. à café", optional: false },
      { food: "Thym frais", qty: 4, unit: "branches", optional: false },
      { food: "Romarin frais", qty: 2, unit: "branches", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Concombre frais", qty: 1, unit: "pièce", optional: false },
      { food: "Yaourt nature (frais, non fermenté longtemps)", qty: 200, unit: "g", optional: true },
      { food: "Menthe fraîche", qty: 10, unit: "feuilles", optional: false },
      { food: "Pain pita", qty: 4, unit: "pièces", optional: false }
    ],
    steps: [
      "Coupez le poulet en cubes de 3 cm. Dans un saladier, mélangez l'huile d'olive, l'ail émincé, l'origan, les feuilles de thym, le romarin haché, le sel et le poivre.",
      "Ajoutez les cubes de poulet dans la marinade, mélangez bien pour les enrober. Laissez mariner 30 minutes minimum au réfrigérateur.",
      "Enfilez les morceaux de poulet sur des brochettes en bois préalablement trempées dans l'eau.",
      "Faites cuire les brochettes sur un gril chaud ou une plancha pendant 12 à 15 minutes en les retournant régulièrement, jusqu'à cuisson complète.",
      "Pendant la cuisson, préparez la sauce tzatziki : râpez le concombre, pressez-le dans un torchon pour enlever l'excès d'eau, mélangez avec le yaourt et la menthe ciselée. Salez légèrement.",
      "Faites chauffer les pains pita quelques secondes de chaque côté sur le gril.",
      "Servez les brochettes dans les pitas avec la sauce tzatziki fraîche et quelques feuilles de menthe."
    ],
    nutrition: { calories: 420, protein: 42, carbs: 32, fat: 14, fiber: 2 },
    tips: "Utilisez du poulet ultra-frais et faites-le mariner au réfrigérateur, jamais à température ambiante. Le yaourt doit être frais du jour pour rester à faible teneur en histamine.",
    isCustom: false
  },
  {
    id: "grec-spanakopita-sans-epinard",
    name: "Feuilleté Grec aux Herbes et Feta Fraîche",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 35,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Pâte filo", qty: 8, unit: "feuilles", optional: false },
      { food: "Feta fraîche", qty: 300, unit: "g", optional: false },
      { food: "Ricotta", qty: 200, unit: "g", optional: false },
      { food: "Persil frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Menthe fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Coriandre fraîche", qty: 0.5, unit: "bouquet", optional: true },
      { food: "Oignon vert", qty: 4, unit: "tiges", optional: false },
      { food: "Oeufs frais", qty: 2, unit: "pièces", optional: false },
      { food: "Huile d'olive", qty: 5, unit: "c. à soupe", optional: false },
      { food: "Beurre fondu", qty: 50, unit: "g", optional: false },
      { food: "Sel", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffez le four à 180°C. Beurrez un plat rectangulaire de 30x20 cm.",
      "Émietez la feta dans un grand saladier. Ajoutez la ricotta et mélangez.",
      "Hachez finement le persil, la menthe, la coriandre et les oignons verts. Incorporez-les au mélange de fromages.",
      "Battez les oeufs et ajoutez-les à la garniture. Assaisonnez de sel (modérément, la feta est déjà salée) et de poivre.",
      "Mélangez le beurre fondu et l'huile d'olive dans un bol.",
      "Étalez 4 feuilles de filo dans le plat en les badigeonnant de mélange beurre-huile entre chaque feuille. Laissez dépasser les bords.",
      "Versez toute la garniture aux herbes et fromages sur la pâte. Étalez uniformément.",
      "Repliez les bords de pâte sur la garniture, puis posez les 4 feuilles restantes par-dessus, en badigeonnant chaque feuille de beurre-huile.",
      "Avec un couteau, marquez des losanges ou des carrés sur le dessus sans couper complètement.",
      "Enfournez 30 à 35 minutes jusqu'à ce que la pâte soit bien dorée et croustillante. Servez chaud ou tiède."
    ],
    nutrition: { calories: 380, protein: 16, carbs: 28, fat: 24, fiber: 1 },
    tips: "Adaptez la spanakopita en remplaçant les épinards (riches en histamine) par un mélange d'herbes fraîches. La feta doit être fraîche, achetée en bloc et conservée dans sa saumure, pas pré-emballée depuis longtemps.",
    isCustom: false
  },
  {
    id: "grec-gigot-agneau-citronné",
    name: "Gigot d'Agneau Rôti aux Herbes Méditerranéennes",
    category: "plat",
    mealType: ["diner"],
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Gigot d'agneau frais", qty: 1.5, unit: "kg", optional: false },
      { food: "Ail", qty: 6, unit: "gousses", optional: false },
      { food: "Romarin frais", qty: 4, unit: "branches", optional: false },
      { food: "Thym frais", qty: 4, unit: "branches", optional: false },
      { food: "Origan séché", qty: 2, unit: "c. à café", optional: false },
      { food: "Huile d'olive", qty: 5, unit: "c. à soupe", optional: false },
      { food: "Pommes de terre", qty: 800, unit: "g", optional: false },
      { food: "Carottes", qty: 3, unit: "pièces", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Bouillon de légumes maison (sans levure)", qty: 200, unit: "ml", optional: false },
      { food: "Sel", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Sortez le gigot du réfrigérateur 30 minutes avant la cuisson. Préchauffez le four à 200°C.",
      "Avec un couteau pointu, faites de petites incisions profondes dans la chair du gigot. Glissez dans chaque incision un demi-gousse d'ail et un brin de romarin ou thym.",
      "Mélangez l'huile d'olive avec l'origan, le sel et le poivre. Badigeonnez généreusement tout le gigot de ce mélange.",
      "Épluchez et coupez les pommes de terre en quartiers, les carottes en rondelles épaisses et les oignons en quartiers.",
      "Disposez les légumes dans un grand plat à rôtir. Arrosez d'un filet d'huile d'olive, salez et poivrez.",
      "Posez le gigot sur les légumes. Versez le bouillon dans le fond du plat.",
      "Enfournez à 200°C pendant 20 minutes pour saisir, puis baissez à 170°C pour le reste de la cuisson.",
      "Comptez environ 15 minutes par 500g pour une cuisson rosée, ou 20 minutes par 500g pour bien cuit. Arrosez toutes les 30 minutes avec les jus de cuisson.",
      "Laissez reposer le gigot 15 minutes, recouvert de papier aluminium, avant de découper et servir avec les légumes rôtis."
    ],
    nutrition: { calories: 580, protein: 52, carbs: 28, fat: 28, fiber: 4 },
    tips: "L'agneau doit être ultra-frais, acheté le jour même ou la veille au maximum. Ne laissez jamais la viande mariner à température ambiante. Le bouillon maison sans levure ni additifs est essentiel pour les personnes sensibles à l'histamine.",
    isCustom: false
  },
  {
    id: "grec-poulet-citron-origan",
    name: "Poulet Grillé à l'Origan et Huile d'Olive",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Cuisses de poulet fraîches (avec os)", qty: 4, unit: "pièces", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 4, unit: "gousses", optional: false },
      { food: "Origan frais ou séché", qty: 2, unit: "c. à café", optional: false },
      { food: "Thym frais", qty: 3, unit: "branches", optional: false },
      { food: "Romarin frais", qty: 2, unit: "branches", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Pommes de terre nouvelles", qty: 600, unit: "g", optional: false },
      { food: "Poivron jaune", qty: 1, unit: "pièce", optional: false }
    ],
    steps: [
      "Préchauffez le four à 200°C. Entaillez la peau des cuisses de poulet avec un couteau pour que les saveurs pénètrent mieux.",
      "Mélangez l'huile d'olive, l'ail émincé, l'origan, les feuilles de thym, le romarin ciselé, le sel et le poivre dans un bol.",
      "Badigeonnez généreusement les cuisses de poulet avec cette marinade aux herbes.",
      "Lavez les pommes de terre nouvelles et coupez-les en deux si elles sont grosses. Émincez le poivron jaune en lanières.",
      "Disposez les pommes de terre et le poivron dans un plat à rôtir, arrosez d'un filet d'huile d'olive, salez et poivrez.",
      "Posez les cuisses de poulet par-dessus les légumes, peau vers le haut.",
      "Enfournez 30 à 35 minutes jusqu'à ce que le poulet soit bien doré et que les pommes de terre soient tendres.",
      "En fin de cuisson, passez sous le gril 3 à 5 minutes pour bien dorer la peau. Servez immédiatement."
    ],
    nutrition: { calories: 490, protein: 38, carbs: 32, fat: 22, fiber: 3 },
    tips: "Choisissez un poulet fermier de qualité, le plus frais possible. La cuisson au four est préférable à la friture pour minimiser la formation de composés pouvant aggraver l'intolérance à l'histamine.",
    isCustom: false
  },
  {
    id: "liban-tabbouleh-quinoa",
    name: "Taboulé au Quinoa et Herbes Fraîches",
    category: "salade",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Quinoa", qty: 200, unit: "g", optional: false },
      { food: "Persil frais", qty: 2, unit: "bouquets", optional: false },
      { food: "Menthe fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Concombre", qty: 1, unit: "pièce", optional: false },
      { food: "Oignon vert", qty: 5, unit: "tiges", optional: false },
      { food: "Poivron vert", qty: 1, unit: "pièce", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Rincez le quinoa à l'eau froide dans une passoire fine. Faites-le cuire dans 400 ml d'eau salée pendant 12 à 15 minutes jusqu'à absorption complète de l'eau.",
      "Étalez le quinoa cuit sur une plaque et laissez-le refroidir complètement à température ambiante, puis réfrigérez-le.",
      "Hachez très finement le persil (feuilles et tiges fines) et la menthe. Dans un taboulé authentique, les herbes doivent être en très grande quantité par rapport aux autres ingrédients.",
      "Coupez le concombre en très petits dés, le poivron vert en petits dés et émincez finement les oignons verts.",
      "Dans un grand saladier, mélangez le quinoa froid avec toutes les herbes hachées, le concombre, le poivron et les oignons verts.",
      "Arrosez d'huile d'olive, salez et poivrez. Mélangez délicatement.",
      "Réfrigérez 30 minutes avant de servir pour que les saveurs se mélangent. Servez frais."
    ],
    nutrition: { calories: 280, protein: 9, carbs: 38, fat: 11, fiber: 5 },
    tips: "Le taboulé traditionnel contient de la tomate et du jus de citron, tous deux riches en histamine. Cette version utilise le poivron vert pour la fraîcheur et le croquant. Le quinoa remplace le boulgour pour plus de protéines. À consommer le jour même.",
    isCustom: false
  },
  {
    id: "liban-hummus-maison",
    name: "Houmous Maison Onctueux",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Pois chiches en boîte (rincés abondamment)", qty: 400, unit: "g", optional: false },
      { food: "Tahini (pâte de sésame)", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Cumin moulu", qty: 0.5, unit: "c. à café", optional: true },
      { food: "Sel", qty: 0.75, unit: "c. à café", optional: false },
      { food: "Eau froide", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Paprika doux", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Persil frais", qty: 5, unit: "tiges", optional: false }
    ],
    steps: [
      "Rincez les pois chiches en boîte très abondamment sous l'eau froide pendant 2 minutes minimum pour éliminer le maximum de liquide de conservation.",
      "Pour une texture plus lisse, retirez la peau fine de quelques pois chiches entre vos doigts (étape optionnelle mais recommandée).",
      "Dans le bol d'un mixeur, placez les pois chiches, le tahini, l'ail, 2 cuillères à soupe d'huile d'olive, le cumin et le sel.",
      "Mixez pendant 2 minutes, en ajoutant l'eau froide cuillère par cuillère jusqu'à obtenir une texture crémeuse et lisse.",
      "Goûtez et rectifiez l'assaisonnement en sel si nécessaire.",
      "Versez l'houmous dans un plat de service creux. Faites un léger creux au centre avec le dos d'une cuillère.",
      "Arrosez du reste d'huile d'olive, saupoudrez de paprika doux et décorez de quelques feuilles de persil. Servez avec du pain pita ou des crudités."
    ],
    nutrition: { calories: 210, protein: 8, carbs: 22, fat: 11, fiber: 6 },
    tips: "Les pois chiches en boîte doivent être rincés très abondamment pour réduire la teneur en histamine. Si possible, faites cuire des pois chiches secs vous-même et utilisez-les immédiatement après cuisson. Le tahini est modérément riche en histamine, utilisez-le avec modération si vous êtes très sensible.",
    isCustom: false
  },
  {
    id: "liban-fattoush-sans-tomate",
    name: "Fattoush Libanais sans Tomate",
    category: "salade",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pain pita", qty: 2, unit: "pièces", optional: false },
      { food: "Concombre", qty: 2, unit: "pièces", optional: false },
      { food: "Poivron vert", qty: 1, unit: "pièce", optional: false },
      { food: "Poivron jaune", qty: 1, unit: "pièce", optional: false },
      { food: "Oignon rouge", qty: 0.5, unit: "pièce", optional: false },
      { food: "Persil frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Menthe fraîche", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Laitue romaine", qty: 1, unit: "petite", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Sumac", qty: 1, unit: "c. à café", optional: true },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffez le four à 180°C. Coupez les pitas en petits morceaux et étalez-les sur une plaque. Arrosez d'un filet d'huile d'olive et enfournez 8 à 10 minutes jusqu'à ce qu'ils soient dorés et croustillants.",
      "Coupez le concombre en demi-lunes, les poivrons en petits dés et l'oignon rouge en fines lamelles.",
      "Ciselez grossièrement la laitue romaine. Hachez le persil et la menthe.",
      "Dans un grand saladier, mélangez tous les légumes, la laitue et les herbes.",
      "Préparez la vinaigrette : fouettez l'huile d'olive avec le sel, le poivre et le sumac si utilisé.",
      "Ajoutez les croûtons de pita au dernier moment, versez la vinaigrette et mélangez rapidement.",
      "Servez immédiatement pour que les pitas restent croustillants."
    ],
    nutrition: { calories: 230, protein: 5, carbs: 28, fat: 12, fiber: 4 },
    tips: "Le fattoush traditionnel contient de la tomate et de la grenade avec du jus de citron. Cette version est adaptée en supprimant ces ingrédients riches en histamine. Le sumac apporte une légère acidité tolérée par certains, à omettre si vous êtes très sensible.",
    isCustom: false
  },
  {
    id: "liban-poulet-safran-riz",
    name: "Poulet au Safran et Riz Pilaf Libanais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Poulet entier découpé en morceaux frais", qty: 1.2, unit: "kg", optional: false },
      { food: "Riz basmati", qty: 300, unit: "g", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Safran", qty: 0.5, unit: "g", optional: false },
      { food: "Cannelle moulue", qty: 1, unit: "c. à café", optional: false },
      { food: "Cumin moulu", qty: 1, unit: "c. à café", optional: true },
      { food: "Cardamome moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Bouillon de poulet maison (sans levure)", qty: 600, unit: "ml", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Faites infuser le safran dans 3 cuillères à soupe d'eau chaude pendant 10 minutes.",
      "Dans une grande cocotte, faites dorer les morceaux de poulet dans le mélange beurre-huile à feu vif, environ 5 minutes de chaque côté. Réservez.",
      "Dans la même cocotte, faites revenir les oignons émincés à feu moyen pendant 8 minutes jusqu'à dorure. Ajoutez l'ail et faites cuire 1 minute.",
      "Remettez le poulet dans la cocotte. Ajoutez la cannelle, le cumin, la cardamome et l'infusion de safran. Mélangez bien.",
      "Versez le bouillon maison, couvrez et laissez mijoter à feu doux 25 minutes.",
      "Pendant ce temps, rincez le riz basmati à l'eau froide jusqu'à ce que l'eau soit claire.",
      "Retirez le poulet de la cocotte. Dans le bouillon restant, faites cuire le riz : portez à ébullition, couvrez et cuisez à feu très doux 15 minutes.",
      "Servez le riz dans un grand plat, disposez les morceaux de poulet par-dessus et garnissez de persil haché."
    ],
    nutrition: { calories: 540, protein: 44, carbs: 52, fat: 16, fiber: 2 },
    tips: "Le safran doit être de bonne qualité et infusé dans de l'eau chaude, jamais dans de l'alcool. Préparez votre propre bouillon de poulet maison sans cubes (qui contiennent souvent de la levure et des additifs pouvant déclencher une réaction).",
    isCustom: false
  },
  {
    id: "liban-kebbe-cuit",
    name: "Kebbé Cuit au Four aux Épices Douces",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 30,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Agneau haché frais (très maigre)", qty: 500, unit: "g", optional: false },
      { food: "Boulgour fin", qty: 150, unit: "g", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Cannelle moulue", qty: 1, unit: "c. à café", optional: false },
      { food: "Cumin moulu", qty: 0.5, unit: "c. à café", optional: true },
      { food: "Noix de muscade fraîchement râpée", qty: 0.25, unit: "c. à café", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Pignons de pin", qty: 50, unit: "g", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false }
    ],
    steps: [
      "Versez de l'eau bouillante sur le boulgour, couvrez et laissez gonfler 15 minutes. Égouttez et pressez pour enlever l'excès d'eau.",
      "Dans un mixeur, mixez la moitié de l'oignon (haché grossièrement) avec l'agneau haché, le boulgour, la cannelle, le cumin, la muscade, le sel et le poivre jusqu'à obtenir une pâte homogène.",
      "Faites revenir l'autre moitié de l'oignon émincé dans le beurre jusqu'à dorure. Ajoutez les pignons et faites-les dorer. Réservez pour la garniture.",
      "Préchauffez le four à 190°C. Huilez généreusement un plat rectangulaire.",
      "Étalez la moitié de la pâte de kebbé en une couche uniforme dans le plat. Répartissez la garniture oignon-pignons par-dessus.",
      "Étalez le reste de la pâte sur la garniture en une couche régulière. Lissez avec les mains humides.",
      "Avec un couteau, tracez des losanges sur le dessus. Arrosez d'huile d'olive.",
      "Enfournez 25 à 30 minutes jusqu'à ce que le dessus soit bien doré. Laissez reposer 5 minutes avant de servir."
    ],
    nutrition: { calories: 460, protein: 34, carbs: 32, fat: 22, fiber: 4 },
    tips: "Le kebbé doit être préparé avec de l'agneau du jour, le plus frais possible. Les pignons de pin sont généralement bien tolérés contrairement aux noix et aux noix de cajou. Servez immédiatement à la sortie du four.",
    isCustom: false
  },
  {
    id: "liban-soupe-lentilles",
    name: "Soupe de Lentilles Libanaise aux Épices",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Lentilles rouges corail", qty: 250, unit: "g", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Cumin moulu", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Curcuma moulu", qty: 1, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Gingembre frais", qty: 1, unit: "c. à café", optional: true },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Bouillon de légumes maison (sans levure)", qty: 1.2, unit: "litre", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Rincez les lentilles rouges à l'eau froide jusqu'à ce que l'eau soit claire. Égouttez.",
      "Émincez finement les oignons. Épluchez et coupez les carottes en dés. Émincez l'ail.",
      "Dans une grande casserole, faites chauffer l'huile d'olive à feu moyen. Faites revenir les oignons 7 à 8 minutes jusqu'à dorure.",
      "Ajoutez l'ail, le cumin, le curcuma, la cannelle et le gingembre râpé. Faites revenir 1 minute en remuant.",
      "Ajoutez les carottes, les lentilles rincées et le bouillon maison. Portez à ébullition.",
      "Réduisez le feu, couvrez et laissez mijoter 20 à 25 minutes jusqu'à ce que les lentilles soient très tendres.",
      "Mixez partiellement ou complètement la soupe selon la texture désirée (veloutée ou avec morceaux).",
      "Rectifiez l'assaisonnement. Servez dans des bols avec un filet d'huile d'olive et du persil haché."
    ],
    nutrition: { calories: 280, protein: 14, carbs: 42, fat: 8, fiber: 12 },
    tips: "Les lentilles font partie des légumineuses pouvant libérer de l'histamine chez certaines personnes. Consommez cette soupe fraîchement préparée et ne la réchauffez pas (la congeler puis réchauffer une seule fois est possible). Si très sensible, réduisez la quantité de lentilles.",
    isCustom: false
  },
  {
    id: "liban-mujaddara",
    name: "Mujaddara : Riz aux Lentilles et Oignons Caramélisés",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Lentilles vertes du Puy", qty: 200, unit: "g", optional: false },
      { food: "Riz à grain long", qty: 200, unit: "g", optional: false },
      { food: "Oignons", qty: 4, unit: "grandes pièces", optional: false },
      { food: "Huile d'olive", qty: 5, unit: "c. à soupe", optional: false },
      { food: "Cumin moulu", qty: 1, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Curcuma", qty: 0.5, unit: "c. à café", optional: true },
      { food: "Bouillon de légumes maison (sans levure)", qty: 800, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Yaourt nature frais", qty: 200, unit: "g", optional: true }
    ],
    steps: [
      "Rincez les lentilles et faites-les cuire dans le bouillon pendant 20 minutes. Elles doivent être mi-cuites. Égouttez en conservant le bouillon.",
      "Rincez le riz à l'eau froide jusqu'à ce que l'eau soit claire.",
      "Émincez finement les oignons en demi-lunes. Faites-les cuire dans l'huile d'olive à feu moyen-doux pendant 25 à 30 minutes en remuant souvent, jusqu'à ce qu'ils soient dorés et bien caramélisés. Réservez la moitié pour la garniture.",
      "Avec les oignons restants dans la casserole, ajoutez le cumin, la cannelle et le curcuma. Mélangez 1 minute.",
      "Ajoutez les lentilles mi-cuites et le riz rincé. Versez 600 ml du bouillon de cuisson des lentilles. Salez.",
      "Portez à ébullition, couvrez et cuisez à feu très doux 20 minutes jusqu'à absorption complète du liquide.",
      "Retirez du feu, couvrez d'un torchon plié puis du couvercle et laissez reposer 10 minutes.",
      "Servez dans un plat, garni des oignons caramélisés réservés. Accompagnez de yaourt frais nature si désiré."
    ],
    nutrition: { calories: 390, protein: 15, carbs: 62, fat: 9, fiber: 10 },
    tips: "La cuisson longue et douce des oignons est le secret de ce plat. Les lentilles et le riz doivent être consommés frais, le lendemain ne convient pas pour les personnes très sensibles à l'histamine. Le yaourt doit être du jour.",
    isCustom: false
  },
  {
    id: "maroc-tagine-agneau-courgettes",
    name: "Tajine d'Agneau aux Courgettes et Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 75,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Épaule d'agneau fraîche coupée en cubes", qty: 700, unit: "g", optional: false },
      { food: "Courgettes", qty: 3, unit: "pièces", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Ail", qty: 4, unit: "gousses", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Cumin moulu", qty: 1, unit: "c. à café", optional: false },
      { food: "Curcuma moulu", qty: 1, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Gingembre frais râpé", qty: 1, unit: "c. à café", optional: false },
      { food: "Paprika doux", qty: 1, unit: "c. à café", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Coriandre fraîche", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Bouillon de légumes maison (sans levure)", qty: 300, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Dans une cocotte ou un tajine, faites chauffer l'huile d'olive à feu moyen-vif. Faites dorer les cubes d'agneau sur toutes leurs faces, environ 5 minutes. Réservez.",
      "Dans le même récipient, faites revenir les oignons émincés 5 minutes. Ajoutez l'ail émincé et le gingembre râpé, cuisez 1 minute.",
      "Ajoutez le cumin, le curcuma, la cannelle et le paprika. Mélangez bien pendant 1 minute pour torréfier les épices.",
      "Remettez l'agneau dans la cocotte. Ajoutez les carottes coupées en rondelles épaisses et le bouillon maison.",
      "Couvrez et laissez mijoter à feu doux pendant 45 minutes.",
      "Coupez les courgettes en gros tronçons. Ajoutez-les dans la cocotte et poursuivez la cuisson 20 minutes.",
      "Rectifiez l'assaisonnement. Ajoutez la coriandre et le persil hachés juste avant de servir.",
      "Servez dans le tajine ou dans des bols profonds, accompagné de couscous ou de riz."
    ],
    nutrition: { calories: 510, protein: 42, carbs: 18, fat: 28, fiber: 5 },
    tips: "Un tajine authentique est cuit lentement à feu très doux. Dans le contexte de l'intolérance à l'histamine, l'agneau doit impérativement être frais du jour. Ne conservez pas les restes plus de 24 heures au réfrigérateur.",
    isCustom: false
  },
  {
    id: "maroc-couscous-legumes",
    name: "Couscous Royal aux Légumes d'Été",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 30,
    cookTime: 50,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Couscous à grains moyens", qty: 400, unit: "g", optional: false },
      { food: "Poulet frais (morceaux)", qty: 600, unit: "g", optional: false },
      { food: "Courgettes", qty: 3, unit: "pièces", optional: false },
      { food: "Carottes", qty: 3, unit: "pièces", optional: false },
      { food: "Courge butternut", qty: 400, unit: "g", optional: false },
      { food: "Navets", qty: 2, unit: "pièces", optional: false },
      { food: "Pois chiches en boîte (bien rincés)", qty: 240, unit: "g", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Ras el hanout (sans additifs)", qty: 2, unit: "c. à café", optional: false },
      { food: "Curcuma", qty: 1, unit: "c. à café", optional: false },
      { food: "Bouillon de poulet maison (sans levure)", qty: 800, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Coriandre fraîche", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Dans une grande cocotte, faites dorer les morceaux de poulet dans l'huile d'olive à feu vif. Réservez.",
      "Faites revenir les oignons émincés 5 minutes. Ajoutez le ras el hanout et le curcuma, cuisez 1 minute.",
      "Remettez le poulet, ajoutez les carottes et navets coupés en morceaux et le bouillon. Portez à ébullition, couvrez et mijotez 20 minutes.",
      "Ajoutez la courge butternut en cubes et les courgettes en tronçons. Ajoutez les pois chiches bien rincés. Poursuivez la cuisson 20 minutes.",
      "Préparez le couscous : versez-le dans un grand saladier, ajoutez 1 cuillère à café de sel et un filet d'huile d'olive. Versez 400 ml d'eau bouillante, couvrez et laissez gonfler 5 minutes.",
      "Égrainez le couscous à la fourchette, ajoutez le beurre en parcelles et mélangez.",
      "Disposez le couscous dans un grand plat creux. Déposez les légumes et la viande par-dessus.",
      "Arrosez de bouillon de cuisson et garnissez de coriandre hachée. Servez le reste du bouillon à part."
    ],
    nutrition: { calories: 580, protein: 38, carbs: 68, fat: 16, fiber: 9 },
    tips: "Le ras el hanout maison est préférable car certains mélanges commerciaux contiennent des épices fermentées ou des additifs. Vérifiez les ingrédients : il doit contenir uniquement des épices sèches naturelles.",
    isCustom: false
  },
  {
    id: "maroc-harira-sans-tomate",
    name: "Harira Marocaine sans Tomate",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 50,
    servings: 6,
    difficulty: "moyen",
    histamineScore: 2,
    ingredients: [
      { food: "Agneau haché frais", qty: 250, unit: "g", optional: false },
      { food: "Lentilles corail", qty: 100, unit: "g", optional: false },
      { food: "Pois chiches en boîte (bien rincés)", qty: 240, unit: "g", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Céleri", qty: 3, unit: "tiges", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Curcuma", qty: 1, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Gingembre frais râpé", qty: 1, unit: "c. à café", optional: false },
      { food: "Cumin moulu", qty: 1, unit: "c. à café", optional: false },
      { food: "Farine", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Bouillon de légumes maison (sans levure)", qty: 1.5, unit: "litre", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Coriandre fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Dans une grande cocotte, faites revenir l'oignon émincé dans l'huile d'olive 5 minutes. Ajoutez l'agneau haché et faites-le dorer en remuant.",
      "Ajoutez le curcuma, la cannelle, le gingembre et le cumin. Mélangez bien.",
      "Ajoutez les carottes en dés, le céleri en tronçons, les lentilles rincées et les pois chiches égouttés et rincés.",
      "Versez le bouillon maison et portez à ébullition. Réduisez le feu, couvrez et laissez mijoter 30 minutes.",
      "Délayez la farine dans un peu d'eau froide pour faire une liaison. Versez dans la soupe en remuant pour épaissir.",
      "Poursuivez la cuisson 10 minutes à feu doux en remuant régulièrement.",
      "Ajoutez la coriandre et le persil hachés, rectifiez le sel.",
      "Servez bien chaud dans des bols profonds. Traditionnellement servie avec des dattes fraîches et du pain."
    ],
    nutrition: { calories: 320, protein: 20, carbs: 38, fat: 10, fiber: 10 },
    tips: "La harira traditionnelle contient de la tomate et parfois du céleri qui peut être légèrement histaminogène. Cette version adaptée est bien tolérée par la plupart des personnes avec une intolérance légère à modérée. À consommer le jour même.",
    isCustom: false
  },
  {
    id: "maroc-poulet-preserved-citron",
    name: "Poulet aux Épices Douces et Olives Vertes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 55,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Poulet entier découpé frais", qty: 1.2, unit: "kg", optional: false },
      { food: "Oignon", qty: 3, unit: "pièces", optional: false },
      { food: "Ail", qty: 4, unit: "gousses", optional: false },
      { food: "Curcuma", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Gingembre frais râpé", qty: 2, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 1, unit: "c. à café", optional: false },
      { food: "Paprika doux", qty: 1, unit: "c. à café", optional: false },
      { food: "Olives vertes (non marinées au vinaigre)", qty: 100, unit: "g", optional: true },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Bouillon de poulet maison (sans levure)", qty: 300, unit: "ml", optional: false },
      { food: "Coriandre fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Mélangez le curcuma, le gingembre, la cannelle, le paprika et le sel avec 2 cuillères à soupe d'huile d'olive pour former une pâte d'épices.",
      "Badigeonnez généreusement les morceaux de poulet de cette pâte. Laissez mariner 30 minutes au réfrigérateur.",
      "Dans une cocotte, faites chauffer le reste de l'huile et faites dorer les morceaux de poulet 5 minutes de chaque côté. Réservez.",
      "Faites revenir les oignons émincés dans la même cocotte pendant 8 minutes. Ajoutez l'ail et cuisez 1 minute.",
      "Remettez le poulet dans la cocotte. Ajoutez le bouillon maison et la moitié des herbes hachées.",
      "Couvrez et laissez mijoter à feu doux 40 minutes.",
      "Si vous utilisez les olives vertes (rincées à l'eau froide), ajoutez-les les 10 dernières minutes.",
      "Garnissez du reste des herbes fraîches avant de servir avec du couscous ou du pain."
    ],
    nutrition: { calories: 470, protein: 42, carbs: 10, fat: 28, fiber: 2 },
    tips: "Remplacez le citron confit traditionnel (très riche en histamine car fermenté) par du zeste de poivron jaune pour une légère touche acidulée. Les olives en saumure sont à rincer abondamment ou à éviter selon votre niveau de sensibilité.",
    isCustom: false
  },
  {
    id: "turc-menemen-sans-tomate",
    name: "Menemen Turc aux Poivrons sans Tomates",
    category: "plat",
    mealType: ["dejeuner"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Oeufs frais", qty: 4, unit: "pièces", optional: false },
      { food: "Poivron vert", qty: 2, unit: "pièces", optional: false },
      { food: "Poivron jaune", qty: 1, unit: "pièce", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Paprika doux", qty: 1, unit: "c. à café", optional: false },
      { food: "Cumin moulu", qty: 0.5, unit: "c. à café", optional: true },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 10, unit: "g", optional: false },
      { food: "Persil frais", qty: 0.25, unit: "bouquet", optional: false },
      { food: "Sel", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Pain turc ou pita", qty: 2, unit: "pièces", optional: false }
    ],
    steps: [
      "Émincez finement l'oignon. Coupez les poivrons en petits dés. Émincez l'ail.",
      "Dans une poêle large (idéalement en fonte), faites chauffer l'huile d'olive et le beurre à feu moyen.",
      "Faites revenir l'oignon 5 minutes jusqu'à translucidité. Ajoutez l'ail et les poivrons.",
      "Faites cuire les poivrons 8 minutes en remuant, jusqu'à ce qu'ils soient tendres. Ajoutez le paprika et le cumin, mélangez.",
      "Battez légèrement les oeufs avec le sel dans un bol. Versez sur les poivrons.",
      "Mélangez doucement en raclant le fond de la poêle avec une spatule, comme pour des oeufs brouillés. Stoppez la cuisson quand les oeufs sont encore légèrement coulants.",
      "Garnissez de persil haché et servez immédiatement dans la poêle avec du pain chaud."
    ],
    nutrition: { calories: 380, protein: 18, carbs: 30, fat: 22, fiber: 3 },
    tips: "Le menemen traditionnel contient des tomates, remplacées ici par plus de poivrons pour maintenir le moelleux du plat. Les oeufs doivent être ultra-frais (date du jour ou J-1). Consommez immédiatement, ne réchauffez pas.",
    isCustom: false
  },
  {
    id: "turc-dolma-courgette",
    name: "Dolmas de Courgettes Farcies au Riz et Herbes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 35,
    cookTime: 40,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Courgettes rondes ou longues", qty: 6, unit: "pièces", optional: false },
      { food: "Riz à grain court", qty: 150, unit: "g", optional: false },
      { food: "Agneau haché frais", qty: 250, unit: "g", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Menthe fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Cumin moulu", qty: 0.5, unit: "c. à café", optional: true },
      { food: "Cannelle moulue", qty: 0.25, unit: "c. à café", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Bouillon de légumes maison (sans levure)", qty: 400, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Yaourt frais nature", qty: 150, unit: "g", optional: true }
    ],
    steps: [
      "Lavez les courgettes. Pour les courgettes rondes, coupez le chapeau et évidez-les avec une cuillère en laissant 1 cm de chair. Pour les courgettes longues, coupez-les en tronçons de 8 cm et évidez-les.",
      "Hachez finement la chair retirée des courgettes. Émincez l'oignon.",
      "Faites revenir l'oignon dans l'huile d'olive 5 minutes. Ajoutez l'agneau haché et la chair de courgette, cuisez 5 minutes.",
      "Ajoutez le riz rincé, la menthe et le persil hachés, le cumin, la cannelle et le sel. Mélangez bien.",
      "Farcissez les courgettes avec ce mélange en laissant un peu de place pour que le riz gonfle.",
      "Disposez les courgettes farcies debout dans une casserole large ou un tajine. Versez le bouillon à mi-hauteur.",
      "Couvrez et faites cuire à feu doux 35 à 40 minutes jusqu'à ce que le riz soit cuit et les courgettes tendres.",
      "Servez chaud avec du yaourt frais nature en accompagnement si désiré."
    ],
    nutrition: { calories: 380, protein: 22, carbs: 38, fat: 14, fiber: 4 },
    tips: "Les dolmas traditionnels utilisent des feuilles de vigne (marinées, donc riches en histamine). Cette version avec des courgettes est parfaitement adaptée. La farce au riz cru va absorber le bouillon pendant la cuisson.",
    isCustom: false
  },
  {
    id: "turc-pilaf-poulet-safran",
    name: "Pilaf de Poulet au Safran et Amandes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 35,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Riz basmati", qty: 300, unit: "g", optional: false },
      { food: "Blancs de poulet frais", qty: 400, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Safran", qty: 0.5, unit: "g", optional: false },
      { food: "Cannelle moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Cardamome moulue", qty: 0.25, unit: "c. à café", optional: false },
      { food: "Amandes effilées", qty: 50, unit: "g", optional: false },
      { food: "Raisins secs dorés (quantité modérée)", qty: 30, unit: "g", optional: true },
      { food: "Beurre", qty: 40, unit: "g", optional: false },
      { food: "Bouillon de poulet maison (sans levure)", qty: 600, unit: "ml", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Persil frais", qty: 0.25, unit: "bouquet", optional: false }
    ],
    steps: [
      "Faites infuser le safran dans 3 cuillères à soupe de bouillon chaud pendant 10 minutes.",
      "Rincez le riz basmati à l'eau froide plusieurs fois jusqu'à eau claire. Égouttez.",
      "Coupez le poulet en dés de 2 cm. Dans une grande casserole, faites-les dorer dans la moitié du beurre 5 minutes. Réservez.",
      "Dans la même casserole, faites fondre le reste du beurre. Faites revenir l'oignon émincé 5 minutes puis l'ail 1 minute.",
      "Ajoutez le riz et mélangez pour l'enrober de beurre. Faites-le revenir 2 minutes.",
      "Versez le bouillon chaud, l'infusion de safran, la cannelle, la cardamome et le sel. Ajoutez le poulet.",
      "Portez à ébullition, couvrez avec un couvercle hermétique et cuisez à feu très doux 18 minutes.",
      "Retirez du feu, glissez un torchon plié sous le couvercle et laissez reposer 10 minutes.",
      "Pendant ce temps, faites dorer les amandes effilées à sec dans une poêle.",
      "Servez le pilaf dans un plat, garni des amandes et du persil haché."
    ],
    nutrition: { calories: 520, protein: 36, carbs: 58, fat: 16, fiber: 2 },
    tips: "Les raisins secs sont optionnels car ils peuvent contenir des sulfites (conservateurs). Si vous les utilisez, choisissez des raisins secs sans sulfites ajoutés (SO2). Les amandes sont généralement bien tolérées contrairement aux noix.",
    isCustom: false
  },
  {
    id: "turc-corba-potiron",
    name: "Soupe de Potiron Épicée à la Turque",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Potiron ou courge butternut", qty: 800, unit: "g", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Gingembre frais râpé", qty: 1, unit: "c. à café", optional: false },
      { food: "Curcuma moulu", qty: 1, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Cardamome moulue", qty: 0.25, unit: "c. à café", optional: true },
      { food: "Paprika doux", qty: 1, unit: "c. à café", optional: false },
      { food: "Beurre", qty: 30, unit: "g", optional: false },
      { food: "Crème fraîche liquide (fraîche)", qty: 100, unit: "ml", optional: true },
      { food: "Bouillon de légumes maison (sans levure)", qty: 900, unit: "ml", optional: false },
      { food: "Graines de courge", qty: 2, unit: "c. à soupe", optional: true },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Épluchez le potiron et coupez-le en gros cubes. Émincez les oignons.",
      "Dans une grande casserole, faites fondre le beurre à feu moyen. Faites revenir les oignons 5 minutes.",
      "Ajoutez l'ail émincé, le gingembre, le curcuma, la cannelle, la cardamome et le paprika. Remuez 1 minute pour faire revenir les épices.",
      "Ajoutez les cubes de potiron et mélangez bien pour les enrober des épices.",
      "Versez le bouillon maison, salez et portez à ébullition. Réduisez le feu, couvrez et laissez cuire 25 minutes jusqu'à ce que le potiron soit très tendre.",
      "Mixez la soupe au mixeur plongeant jusqu'à obtenir une texture parfaitement lisse.",
      "Ajoutez la crème fraîche si désiré, mélangez et réchauffez doucement sans bouillir.",
      "Servez dans des bols, arrosez d'un filet de crème, saupoudrez de paprika et de graines de courge grillées."
    ],
    nutrition: { calories: 195, protein: 5, carbs: 28, fat: 8, fiber: 5 },
    tips: "La crème fraîche légèrement fermentée peut être un déclencheur pour les très sensibles. Remplacez-la par du lait entier ou de la crème de coco fraîche si nécessaire. Le potiron est un légume excellent pour les personnes intolérantes à l'histamine.",
    isCustom: false
  },
  {
    id: "ital-risotto-asperges",
    name: "Risotto aux Asperges et Chèvre Frais",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 1,
    ingredients: [
      { food: "Riz arborio ou carnaroli", qty: 320, unit: "g", optional: false },
      { food: "Asperges fraîches", qty: 400, unit: "g", optional: false },
      { food: "Chèvre frais (bûche fraîche)", qty: 120, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Bouillon de légumes maison chaud (sans levure)", qty: 1.2, unit: "litre", optional: false },
      { food: "Beurre", qty: 50, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Thym frais", qty: 3, unit: "branches", optional: false },
      { food: "Basilic frais", qty: 10, unit: "feuilles", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Cassez les asperges à la base pour enlever la partie dure. Coupez les pointes (5 cm) et le reste en tronçons de 2 cm.",
      "Faites blanchir les pointes d'asperges 3 minutes dans de l'eau bouillante salée. Égouttez et réservez. Faites de même avec les tronçons.",
      "Maintenez le bouillon chaud dans une casserole à feu doux.",
      "Dans une grande casserole, faites fondre la moitié du beurre avec l'huile d'olive à feu moyen. Faites revenir l'oignon émincé 5 minutes.",
      "Ajoutez l'ail et le riz. Faites revenir 2 minutes en remuant jusqu'à ce que le riz soit nacré.",
      "Ajoutez les tronçons d'asperges et commencez à ajouter le bouillon chaud, louche par louche, en remuant constamment. Attendez que chaque louche soit absorbée avant d'en ajouter une autre.",
      "Continuez ainsi pendant environ 18 à 20 minutes. Le riz doit être al dente.",
      "Hors du feu, incorporez le reste du beurre et le chèvre frais émietté. Mélangez vigoureusement pour une texture crémeuse.",
      "Incorporez les feuilles de basilic et les pointes d'asperges. Rectifiez le sel. Servez immédiatement."
    ],
    nutrition: { calories: 490, protein: 14, carbs: 72, fat: 16, fiber: 4 },
    tips: "Le risotto doit être préparé et servi immédiatement. Le chèvre frais (bûche fraîche non affinée) est bien toléré contrairement aux fromages affinés. N'utilisez jamais de parmesan dans un plat histamine-friendly.",
    isCustom: false
  },
  {
    id: "ital-pasta-pesto-herbes",
    name: "Pâtes au Pesto d'Herbes Fraîches sans Parmesan",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pâtes sèches (spaghetti ou penne)", qty: 400, unit: "g", optional: false },
      { food: "Basilic frais", qty: 2, unit: "bouquets", optional: false },
      { food: "Persil frais", qty: 1, unit: "bouquet", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Pignons de pin", qty: 50, unit: "g", optional: false },
      { food: "Ricotta fraîche", qty: 100, unit: "g", optional: false },
      { food: "Huile d'olive extra vierge", qty: 6, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Faites griller légèrement les pignons de pin à sec dans une poêle 2 à 3 minutes. Laissez refroidir.",
      "Dans un mixeur ou un mortier, placez les feuilles de basilic, le persil, l'ail, les pignons refroidis, le sel et le poivre.",
      "Mixez en ajoutant l'huile d'olive progressivement jusqu'à obtenir une texture de pesto légèrement grumeleuse ou lisse selon votre préférence.",
      "Incorporez la ricotta fraîche et mixez brièvement pour homogénéiser.",
      "Faites cuire les pâtes al dente dans une grande quantité d'eau bouillante salée selon les instructions de l'emballage.",
      "Réservez une tasse d'eau de cuisson avant d'égoutter les pâtes.",
      "Dans le saladier de service, mélangez le pesto avec 2 à 3 cuillères à soupe d'eau de cuisson.",
      "Ajoutez les pâtes égouttées et mélangez rapidement pour bien les enrober. Servez immédiatement."
    ],
    nutrition: { calories: 520, protein: 16, carbs: 68, fat: 22, fiber: 3 },
    tips: "La ricotta remplace le parmesan (très affiné, très riche en histamine) en apportant une texture crémeuse. Préparez le pesto au moment du repas, car l'oxydation augmente la teneur en histamine. Ne réchauffez pas les restes.",
    isCustom: false
  },
  {
    id: "ital-risotto-poulet-citron-herbes",
    name: "Risotto Crémeux au Poulet et Herbes Citronnées",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 35,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Riz carnaroli ou arborio", qty: 300, unit: "g", optional: false },
      { food: "Blancs de poulet frais", qty: 400, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Bouillon de poulet maison chaud (sans levure)", qty: 1.2, unit: "litre", optional: false },
      { food: "Beurre", qty: 60, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Basilic frais", qty: 15, unit: "feuilles", optional: false },
      { food: "Thym frais", qty: 3, unit: "branches", optional: false },
      { food: "Persil frais", qty: 0.25, unit: "bouquet", optional: false },
      { food: "Mozzarella fraîche", qty: 125, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Coupez les blancs de poulet en petits dés. Maintenez le bouillon chaud à feu doux.",
      "Dans une grande poêle, faites dorer les dés de poulet dans l'huile d'olive 5 minutes. Réservez.",
      "Dans une casserole large, faites fondre la moitié du beurre. Faites revenir l'oignon émincé 5 minutes.",
      "Ajoutez l'ail et le riz, faites-les revenir 2 minutes en remuant.",
      "Commencez l'ajout du bouillon chaud louche par louche en remuant constamment, en attendant l'absorption complète entre chaque ajout.",
      "À mi-cuisson (environ 10 minutes), incorporez les morceaux de poulet et le thym effeuillé.",
      "Continuez le risotto 8 à 10 minutes supplémentaires. Le riz doit être al dente.",
      "Hors du feu, incorporez le reste du beurre et la mozzarella fraîche déchirée en petits morceaux. Mélangez vivement.",
      "Parsemez de basilic et de persil hachés. Poivrez généreusement. Servez sans attendre."
    ],
    nutrition: { calories: 560, protein: 38, carbs: 62, fat: 18, fiber: 2 },
    tips: "La mozzarella fraîche (dans son eau, à utiliser le jour d'achat) est bien tolérée. Si vous ne trouvez pas de mozzarella très fraîche, la ricotta en quantité similaire est une excellente alternative.",
    isCustom: false
  },
  {
    id: "ital-pasta-beurre-sauge",
    name: "Pasta Burro e Salvia : Pâtes Beurre et Sauge",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Pâtes fraîches (tagliatelles ou pappardelles)", qty: 300, unit: "g", optional: false },
      { food: "Beurre", qty: 80, unit: "g", optional: false },
      { food: "Sauge fraîche", qty: 15, unit: "feuilles", optional: false },
      { food: "Ail", qty: 2, unit: "gousses", optional: false },
      { food: "Ricotta fraîche", qty: 80, unit: "g", optional: true },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Faites bouillir une grande casserole d'eau salée.",
      "Dans une grande poêle, faites fondre le beurre à feu moyen. Ajoutez les gousses d'ail entières légèrement aplaties.",
      "Quand le beurre commence à mousser et à légèrement brunir (beurre noisette), ajoutez les feuilles de sauge entières. Faites-les frire 1 minute jusqu'à ce qu'elles soient croustillantes. Retirez l'ail.",
      "Faites cuire les pâtes fraîches 2 à 3 minutes dans l'eau bouillante. Égouttez en réservant une tasse d'eau de cuisson.",
      "Ajoutez les pâtes dans la poêle au beurre de sauge. Mélangez sur feu doux en ajoutant un peu d'eau de cuisson si nécessaire.",
      "Incorporez la ricotta fraîche si désiré pour une sauce crémeuse. Poivrez généreusement.",
      "Servez immédiatement dans des assiettes chaudes."
    ],
    nutrition: { calories: 640, protein: 16, carbs: 72, fat: 34, fiber: 3 },
    tips: "Ce plat minimaliste met en valeur des ingrédients parfaitement adaptés à l'intolérance à l'histamine. Les pâtes fraîches du commerce sont généralement à base d'oeufs frais et de farine, vérifiez qu'elles ne contiennent pas d'additifs ou de conservateurs.",
    isCustom: false
  },
  {
    id: "med-mezze-baba-courgette",
    name: "Baba Ganoush de Courgettes Grillées",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Courgettes", qty: 4, unit: "grosses pièces", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Tahini (pâte de sésame)", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Cumin moulu", qty: 0.5, unit: "c. à café", optional: true },
      { food: "Sel", qty: 0.75, unit: "c. à café", optional: false },
      { food: "Persil frais", qty: 0.25, unit: "bouquet", optional: false },
      { food: "Paprika doux", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Pain pita", qty: 4, unit: "pièces", optional: false }
    ],
    steps: [
      "Préchauffez le four à 220°C ou allumez le gril. Coupez les courgettes en deux dans le sens de la longueur.",
      "Badigeonnez les courgettes d'huile d'olive et enfournez-les côté coupé vers le bas pendant 15 à 20 minutes jusqu'à ce qu'elles soient très tendres et légèrement caramélisées.",
      "Laissez refroidir légèrement, puis grattez la chair dans un saladier.",
      "Ajoutez l'ail écrasé, le tahini, 2 cuillères à soupe d'huile d'olive, le cumin et le sel.",
      "Mixez ou écrasez à la fourchette selon la texture désirée (lisse ou rustique).",
      "Goûtez et rectifiez l'assaisonnement.",
      "Versez dans un plat, arrosez du reste d'huile d'olive, saupoudrez de paprika et de persil haché.",
      "Faites chauffer les pitas et servez avec le baba ganoush pour tremper."
    ],
    nutrition: { calories: 210, protein: 6, carbs: 28, fat: 10, fiber: 3 },
    tips: "Ce baba ganoush remplace l'aubergine traditionnelle (riche en histamine) par des courgettes grillées. La texture sera plus légère mais tout aussi savoureuse. Le tahini est utilisé en petite quantité pour rester dans les limites conseillées.",
    isCustom: false
  },
  {
    id: "med-mezze-poivrons-marines",
    name: "Mezze de Poivrons Rôtis à l'Huile d'Olive",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Poivrons jaunes", qty: 4, unit: "pièces", optional: false },
      { food: "Poivrons verts", qty: 2, unit: "pièces", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Huile d'olive extra vierge", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Thym frais", qty: 3, unit: "branches", optional: false },
      { food: "Origan frais", qty: 2, unit: "branches", optional: false },
      { food: "Sel", qty: 0.75, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préchauffez le four à 220°C. Placez les poivrons entiers sur une plaque et enfournez 20 à 25 minutes en les retournant à mi-cuisson jusqu'à ce que la peau soit cloquée et noircie.",
      "Transférez immédiatement les poivrons dans un saladier et couvrez hermétiquement avec du film alimentaire. Laissez reposer 10 minutes pour faciliter l'épluchage.",
      "Pelez les poivrons en retirant la peau brûlée, puis épépinez-les. Récupérez le jus de cuisson.",
      "Coupez les poivrons en lanières et disposez-les dans un plat de service.",
      "Arrosez de l'huile d'olive et du jus de cuisson récupéré. Ajoutez l'ail tranché finement.",
      "Parsemez de feuilles de thym et d'origan. Assaisonnez de sel et poivre.",
      "Laissez mariner à température ambiante 30 minutes avant de servir, ou réfrigérez et consommez dans les 2 heures."
    ],
    nutrition: { calories: 130, protein: 2, carbs: 14, fat: 8, fiber: 4 },
    tips: "Les poivrons rôtis sont un classique des mezze. Évitez les poivrons rouges car ils contiennent plus d'histamine que les jaunes et verts. Consommez rapidement après préparation, ne conservez pas plus de quelques heures.",
    isCustom: false
  },
  {
    id: "med-mezze-labneh",
    name: "Labneh Maison aux Herbes Fraîches",
    category: "entree",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "facile",
    histamineScore: 1,
    ingredients: [
      { food: "Yaourt grec nature très frais", qty: 500, unit: "g", optional: false },
      { food: "Sel fin", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Menthe fraîche", qty: 10, unit: "feuilles", optional: false },
      { food: "Thym frais", qty: 3, unit: "branches", optional: false },
      { food: "Ail", qty: 1, unit: "gousse", optional: true },
      { food: "Huile d'olive", qty: 3, unit: "c. à soupe", optional: false },
      { food: "Paprika doux", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Pain pita ou pain libanais", qty: 4, unit: "pièces", optional: false }
    ],
    steps: [
      "Mélangez le yaourt grec avec le sel dans un saladier.",
      "Déposez le mélange sur un grand carré de mousseline ou d'un torchon propre. Nouez les coins et suspendez au-dessus d'un saladier pour récupérer le petit lait.",
      "Laissez égoutter au réfrigérateur pendant 4 à 8 heures (ou une nuit pour une texture plus ferme).",
      "Récupérez le labneh (fromage frais épaissi). Vous pouvez le laisser en crème onctueuse ou en faire des petites boules avec les mains.",
      "Disposez dans un plat, arrosez généreusement d'huile d'olive.",
      "Garnissez de feuilles de menthe, de thym effeuillé, de paprika et si désiré d'une gousse d'ail finement émincée.",
      "Servez avec du pain pita frais chaud."
    ],
    nutrition: { calories: 185, protein: 10, carbs: 18, fat: 8, fiber: 1 },
    tips: "Le labneh est du yaourt égoutté et légèrement fermenté. Utilisez un yaourt du jour, le plus frais possible, et consommez le labneh dans les 24 heures. Évitez les yaourts pasteurisés avec longue conservation qui sont plus riches en histamine.",
    isCustom: false
  },
  {
    id: "grec-salade-pois-chiches-concombre",
    name: "Salade Grecque de Pois Chiches et Concombre",
    category: "salade",
    mealType: ["dejeuner", "diner"],
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "facile",
    histamineScore: 2,
    ingredients: [
      { food: "Pois chiches en boîte (bien rincés)", qty: 400, unit: "g", optional: false },
      { food: "Concombres", qty: 2, unit: "pièces", optional: false },
      { food: "Feta fraîche", qty: 150, unit: "g", optional: false },
      { food: "Oignon rouge", qty: 0.5, unit: "pièce", optional: false },
      { food: "Menthe fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Origan séché", qty: 1, unit: "c. à café", optional: false },
      { food: "Sel", qty: 0.75, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Égouttez et rincez les pois chiches abondamment sous l'eau froide pendant 2 minutes.",
      "Coupez les concombres en demi-lunes. Émincez l'oignon rouge en très fines rondelles.",
      "Émiettez grossièrement la feta fraîche.",
      "Hachez le persil et la menthe.",
      "Dans un grand saladier, combinez les pois chiches, les concombres, l'oignon rouge, le persil et la menthe.",
      "Préparez la vinaigrette : fouettez l'huile d'olive avec le sel, le poivre et l'origan.",
      "Versez la vinaigrette sur la salade et mélangez délicatement.",
      "Ajoutez la feta émiettée par-dessus. Servez immédiatement ou laissez reposer 15 minutes pour que les saveurs se mélangent."
    ],
    nutrition: { calories: 320, protein: 14, carbs: 30, fat: 17, fiber: 8 },
    tips: "Cette salade combine deux ingrédients modérément histaminogènes (pois chiches et feta). Assurez-vous que la feta est fraîche et non affinée longtemps. Consommez cette salade le jour même.",
    isCustom: false
  },
  {
    id: "maroc-soupe-poulet-vermicelles",
    name: "Chorba de Poulet au Vermicelle et Herbes",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blancs de poulet frais", qty: 400, unit: "g", optional: false },
      { food: "Vermicelles de blé fin", qty: 80, unit: "g", optional: false },
      { food: "Oignon", qty: 2, unit: "pièces", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Carottes", qty: 2, unit: "pièces", optional: false },
      { food: "Céleri", qty: 2, unit: "tiges", optional: false },
      { food: "Curcuma moulu", qty: 1, unit: "c. à café", optional: false },
      { food: "Gingembre frais râpé", qty: 1, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.25, unit: "c. à café", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Eau ou bouillon de légumes maison (sans levure)", qty: 1.5, unit: "litre", optional: false },
      { food: "Coriandre fraîche", qty: 1, unit: "bouquet", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Sel", qty: 1.5, unit: "c. à café", optional: false }
    ],
    steps: [
      "Coupez les blancs de poulet en petits cubes. Épluchez et coupez les carottes en dés. Émincez l'oignon, l'ail et le céleri.",
      "Dans une grande casserole, faites chauffer l'huile d'olive. Faites revenir l'oignon 5 minutes.",
      "Ajoutez l'ail, le gingembre et les épices (curcuma, cannelle). Faites revenir 1 minute.",
      "Ajoutez le poulet et faites-le dorer légèrement 3 minutes.",
      "Ajoutez les carottes et le céleri, versez l'eau ou le bouillon maison. Portez à ébullition.",
      "Réduisez le feu, couvrez et laissez mijoter 25 minutes.",
      "Ajoutez les vermicelles et cuisez encore 5 à 8 minutes jusqu'à ce qu'ils soient tendres.",
      "Incorporez la coriandre et le persil hachés. Rectifiez le sel.",
      "Servez bien chaud dans des bols avec du pain croustillant."
    ],
    nutrition: { calories: 230, protein: 24, carbs: 22, fat: 6, fiber: 3 },
    tips: "La chorba est un excellent plat de réconfort adapté à l'histamine. Préparez et consommez immédiatement. Le céleri peut être légèrement histaminogène pour certaines personnes très sensibles, il peut être omis.",
    isCustom: false
  },
  {
    id: "med-pain-pita-maison",
    name: "Pain Pita Maison Moelleux",
    category: "pain",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 15,
    servings: 8,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Farine de blé T55", qty: 400, unit: "g", optional: false },
      { food: "Levure boulangère sèche (quantité réduite)", qty: 5, unit: "g", optional: false },
      { food: "Eau tiède", qty: 240, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Sucre", qty: 1, unit: "c. à café", optional: false }
    ],
    steps: [
      "Dissolvez la levure et le sucre dans l'eau tiède. Laissez reposer 10 minutes jusqu'à ce que le mélange mousse.",
      "Dans un grand saladier, mélangez la farine et le sel. Faites un puits au centre.",
      "Versez le mélange de levure et l'huile d'olive dans le puits. Mélangez jusqu'à formation d'une boule.",
      "Pétrissez la pâte sur une surface farinée pendant 8 à 10 minutes jusqu'à ce qu'elle soit lisse et élastique.",
      "Placez la pâte dans un saladier légèrement huilé, couvrez d'un torchon humide. Laissez lever 1 heure dans un endroit chaud.",
      "Divisez la pâte en 8 boules égales. Étalez chaque boule en un disque de 5 mm d'épaisseur.",
      "Préchauffez le four à 250°C avec une plaque à l'intérieur. Faites cuire les pitas 5 à 7 minutes directement sur la plaque chaude jusqu'à ce qu'ils gonflent et soient légèrement dorés.",
      "Enveloppez les pitas dans un torchon propre dès la sortie du four pour les garder moelleux."
    ],
    nutrition: { calories: 210, protein: 6, carbs: 40, fat: 4, fiber: 2 },
    tips: "Le pain fait maison est préférable au pain industriel qui peut contenir des additifs. La levure boulangère est utilisée en petite quantité ; si vous êtes très sensible, réduisez encore la quantité ou essayez une version sans levure (pain azyme). Consommez le jour même.",
    isCustom: false
  },
  {
    id: "med-pain-mana-esh",
    name: "Manoushé au Za'atar et Huile d'Olive",
    category: "pain",
    mealType: ["dejeuner"],
    prepTime: 25,
    cookTime: 10,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Farine de blé T55", qty: 300, unit: "g", optional: false },
      { food: "Levure boulangère sèche (quantité réduite)", qty: 4, unit: "g", optional: false },
      { food: "Eau tiède", qty: 180, unit: "ml", optional: false },
      { food: "Huile d'olive", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 0.75, unit: "c. à café", optional: false },
      { food: "Thym séché", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Origan séché", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Graines de sésame", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Huile d'olive (pour la garniture)", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Sel", qty: 0.25, unit: "c. à café", optional: false }
    ],
    steps: [
      "Préparez la pâte : dissolvez la levure dans l'eau tiède avec une pincée de sucre. Laissez reposer 10 minutes.",
      "Mélangez la farine et le sel, faites un puits, versez la levure et l'huile. Pétrissez 8 minutes jusqu'à pâte souple.",
      "Laissez lever 45 minutes à 1 heure couvert d'un torchon dans un endroit chaud.",
      "Préparez le mélange za'atar maison : mélangez le thym, l'origan, les graines de sésame, 4 cuillères d'huile d'olive et le sel.",
      "Préchauffez le four à 240°C avec une plaque.",
      "Divisez la pâte en 4 boules. Étalez chaque boule très finement (3 mm) en disques de 20 cm.",
      "Étalez généreusement le mélange za'atar-huile sur chaque disque.",
      "Enfournez directement sur la plaque chaude 8 à 10 minutes jusqu'à ce que les bords soient dorés et croustillants.",
      "Servez chaud avec du labneh frais, du concombre et de la menthe."
    ],
    nutrition: { calories: 370, protein: 8, carbs: 48, fat: 17, fiber: 3 },
    tips: "Le za'atar commercial peut contenir du sumac (légèrement histaminogène) et d'autres additifs. Préparez votre propre mélange za'atar maison avec du thym, de l'origan et des graines de sésame comme dans cette recette.",
    isCustom: false
  },
  {
    id: "med-dessert-semolina-cake",
    name: "Gâteau de Semoule à la Fleur d'Oranger",
    category: "dessert",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 35,
    servings: 8,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Semoule de blé fine", qty: 200, unit: "g", optional: false },
      { food: "Farine de blé", qty: 100, unit: "g", optional: false },
      { food: "Sucre", qty: 150, unit: "g", optional: false },
      { food: "Beurre fondu", qty: 100, unit: "g", optional: false },
      { food: "Yaourt nature frais", qty: 200, unit: "g", optional: false },
      { food: "Oeufs frais", qty: 3, unit: "pièces", optional: false },
      { food: "Levure chimique (sans aluminium)", qty: 1, unit: "sachet", optional: false },
      { food: "Eau de fleur d'oranger", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Amandes effilées", qty: 50, unit: "g", optional: false },
      { food: "Sel", qty: 1, unit: "pincée", optional: false },
      { food: "Miel doux", qty: 3, unit: "c. à soupe", optional: true }
    ],
    steps: [
      "Préchauffez le four à 175°C. Beurrez et farinez un moule rond de 24 cm.",
      "Dans un grand saladier, fouettez les oeufs avec le sucre jusqu'à ce que le mélange blanchisse et devienne mousseux.",
      "Incorporez le beurre fondu refroidi et le yaourt frais.",
      "Ajoutez l'eau de fleur d'oranger et mélangez.",
      "Incorporez la semoule, la farine, la levure chimique et le sel. Mélangez jusqu'à obtenir une pâte homogène. La pâte sera un peu épaisse.",
      "Versez dans le moule beurré. Lissez la surface. Parsemez d'amandes effilées.",
      "Enfournez 30 à 35 minutes. Vérifiez la cuisson avec la pointe d'un couteau (elle doit ressortir sèche).",
      "Optionnel : à la sortie du four, badigeonnez le gâteau de miel légèrement dilué dans un peu d'eau chaude pour le glacer.",
      "Laissez refroidir avant de démouler et servir."
    ],
    nutrition: { calories: 310, protein: 7, carbs: 44, fat: 12, fiber: 1 },
    tips: "L'eau de fleur d'oranger est généralement bien tolérée. Choisissez une levure chimique sans aluminium. Les oeufs doivent être frais du jour pour les personnes très sensibles. Ce gâteau se conserve 24 heures à température ambiante.",
    isCustom: false
  },
  {
    id: "med-dessert-riz-au-lait-cardamome",
    name: "Riz au Lait à la Cardamome et Eau de Rose",
    category: "dessert",
    mealType: ["dejeuner", "diner"],
    prepTime: 5,
    cookTime: 40,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Riz à grain rond", qty: 100, unit: "g", optional: false },
      { food: "Lait entier frais", qty: 800, unit: "ml", optional: false },
      { food: "Sucre", qty: 60, unit: "g", optional: false },
      { food: "Cardamome moulue", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Cannelle moulue", qty: 0.25, unit: "c. à café", optional: false },
      { food: "Eau de rose", qty: 1, unit: "c. à soupe", optional: false },
      { food: "Amandes effilées grillées", qty: 30, unit: "g", optional: false },
      { food: "Pistaches non salées (fraîches)", qty: 20, unit: "g", optional: true }
    ],
    steps: [
      "Rincez le riz à l'eau froide. Dans une casserole épaisse, portez le lait à ébullition à feu moyen en remuant.",
      "Ajoutez le riz et réduisez le feu au minimum. Cuisez en remuant très souvent pendant 30 à 35 minutes jusqu'à ce que le riz soit très tendre et que le mélange ait bien épaissi.",
      "Ajoutez le sucre, la cardamome et la cannelle. Mélangez bien et cuisez encore 5 minutes.",
      "Retirez du feu, incorporez l'eau de rose.",
      "Versez dans des petits bols ou coupes individuelles.",
      "Laissez refroidir à température ambiante puis réfrigérez 1 heure.",
      "Au moment de servir, garnissez d'amandes effilées grillées et de pistaches concassées."
    ],
    nutrition: { calories: 285, protein: 9, carbs: 44, fat: 8, fiber: 1 },
    tips: "Le riz au lait épicé est un dessert méditerranéen classique parfaitement adapté à l'intolérance à l'histamine. L'eau de rose (ma ward) est aromatique et bien tolérée. Utilisez du lait entier frais, pas de lait UHT longue conservation.",
    isCustom: false
  },
  {
    id: "grec-youvarlakia-soupe",
    name: "Yuvarlakia : Soupe de Boulettes d'Agneau au Riz",
    category: "soupe",
    mealType: ["dejeuner", "diner"],
    prepTime: 25,
    cookTime: 30,
    servings: 4,
    difficulty: "moyen",
    histamineScore: 0,
    ingredients: [
      { food: "Agneau haché frais", qty: 400, unit: "g", optional: false },
      { food: "Riz à grain rond", qty: 60, unit: "g", optional: false },
      { food: "Oignon", qty: 1, unit: "pièce", optional: false },
      { food: "Persil frais", qty: 0.5, unit: "bouquet", optional: false },
      { food: "Menthe fraîche séchée ou fraîche", qty: 1, unit: "c. à café", optional: false },
      { food: "Oeuf frais", qty: 1, unit: "pièce", optional: false },
      { food: "Bouillon de légumes ou poulet maison (sans levure)", qty: 1.2, unit: "litre", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivre noir frais moulu", qty: 0.25, unit: "c. à café", optional: false },
      { food: "Farine", qty: 2, unit: "c. à soupe", optional: false },
      { food: "Beurre", qty: 20, unit: "g", optional: false }
    ],
    steps: [
      "Dans un saladier, mélangez l'agneau haché avec le riz cru (non cuit), l'oignon râpé finement, le persil haché, la menthe, l'oeuf, le sel et le poivre.",
      "Mélangez avec les mains jusqu'à obtenir une préparation homogène.",
      "Façonnez des boulettes de la taille d'une noix (environ 30 pièces). Réfrigérez 15 minutes.",
      "Portez le bouillon maison à ébullition dans une grande casserole.",
      "Ajoutez les boulettes délicatement dans le bouillon bouillant. Réduisez le feu.",
      "Laissez cuire à feu doux 20 à 25 minutes. Les boulettes vont gonfler légèrement grâce au riz.",
      "Préparez une liaison : faites fondre le beurre dans une petite casserole, ajoutez la farine et cuisez 1 minute. Versez quelques louches de bouillon chaud en fouettant, puis reversez dans la soupe.",
      "Mélangez délicatement pour épaissir légèrement. Rectifiez le sel.",
      "Servez chaud garni de persil haché frais."
    ],
    nutrition: { calories: 380, protein: 28, carbs: 24, fat: 18, fiber: 1 },
    tips: "Les boulettes d'agneau doivent être préparées et cuites immédiatement avec de la viande ultra-fraîche. Ne conservez pas cette soupe au réfrigérateur pour la réchauffer, l'histamine se forme rapidement dans les viandes cuites.",
    isCustom: false
  },
  {
    id: "turc-chicken-shish-legumes",
    name: "Chiche Taouk Turc : Brochettes de Poulet Mariné aux Légumes",
    category: "plat",
    mealType: ["dejeuner", "diner"],
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    difficulty: "facile",
    histamineScore: 0,
    ingredients: [
      { food: "Blancs de poulet frais", qty: 600, unit: "g", optional: false },
      { food: "Yaourt nature frais", qty: 100, unit: "g", optional: false },
      { food: "Huile d'olive", qty: 4, unit: "c. à soupe", optional: false },
      { food: "Ail", qty: 3, unit: "gousses", optional: false },
      { food: "Paprika doux", qty: 1.5, unit: "c. à café", optional: false },
      { food: "Cumin moulu", qty: 1, unit: "c. à café", optional: true },
      { food: "Curcuma", qty: 0.5, unit: "c. à café", optional: false },
      { food: "Gingembre frais râpé", qty: 1, unit: "c. à café", optional: false },
      { food: "Poivron jaune", qty: 1, unit: "pièce", optional: false },
      { food: "Poivron vert", qty: 1, unit: "pièce", optional: false },
      { food: "Courgette", qty: 1, unit: "pièce", optional: false },
      { food: "Oignon rouge", qty: 1, unit: "pièce", optional: false },
      { food: "Sel", qty: 1, unit: "c. à café", optional: false },
      { food: "Pain pita ou riz basmati", qty: 4, unit: "pièces", optional: false }
    ],
    steps: [
      "Coupez les blancs de poulet en cubes de 3 cm.",
      "Préparez la marinade : mélangez le yaourt frais, l'huile d'olive, l'ail écrasé, le paprika, le cumin, le curcuma, le gingembre et le sel.",
      "Ajoutez les cubes de poulet dans la marinade et mélangez bien. Couvrez et réfrigérez 30 minutes minimum (pas plus de 2 heures).",
      "Coupez les poivrons en carrés de 3 cm, la courgette en rondelles épaisses et l'oignon en quartiers.",
      "Enfilez en alternance les morceaux de poulet marinés et les légumes sur des brochettes.",
      "Faites cuire sur un gril chaud, une plancha ou sous le gril du four préchauffé à 220°C pendant 15 à 20 minutes, en retournant à mi-cuisson.",
      "Vérifiez que le poulet est bien cuit à coeur (pas de rose).",
      "Servez immédiatement avec des pitas chauds ou du riz basmati, accompagné de yaourt frais et de menthe."
    ],
    nutrition: { calories: 430, protein: 44, carbs: 28, fat: 16, fiber: 3 },
    tips: "Le shish taouk est un grand classique des grillades du Moyen-Orient. La marinade au yaourt attendrit la viande et apporte de la saveur sans nécessiter d'ingrédients histaminogènes. Utilisez un poulet ultra-frais et ne prolongez pas la marinade au-delà de 2 heures.",
    isCustom: false
  }
];
